"""
English word lists for preset vocabulary categories.

Each entry is (english_word, word_type).
These are the seeds used to generate per-language preset files
(e.g. el_en_presets.txt, fr_en_presets.txt, etc.).

Word types: noun, verb, adjective, adverb, phrase, interjection,
            numeral, preposition, conjunction
"""

CATEGORIES = {
    "greetings": {
        "name": "Greetings & phrases",
        "emoji": "👋",
        "words": [
            ("hello",               "interjection"),
            ("hi",                  "interjection"),
            ("goodbye",             "interjection"),
            ("good morning",        "phrase"),
            ("good afternoon",      "phrase"),
            ("good evening",        "phrase"),
            ("good night",          "phrase"),
            ("please",              "interjection"),
            ("thank you",           "interjection"),
            ("you're welcome",      "phrase"),
            ("sorry",               "interjection"),
            ("excuse me",           "phrase"),
            ("yes",                 "interjection"),
            ("no",                  "interjection"),
            ("I don't understand",  "phrase"),
            ("my name is",          "phrase"),
            ("how are you",         "phrase"),
            ("I'm fine",            "phrase"),
            ("nice to meet you",    "phrase"),
            ("see you later",       "phrase"),
            ("see you tomorrow",    "phrase"),
            ("cheers",              "interjection"),
            ("congratulations",     "interjection"),
            ("happy birthday",      "phrase"),
            ("welcome",             "interjection"),
            ("no problem",          "phrase"),
            ("of course",           "phrase"),
            ("here you go",         "phrase"),
        ],
    },

    "numbers_time": {
        "name": "Numbers & time",
        "emoji": "🕐",
        "words": [
            ("one",         "numeral"),
            ("two",         "numeral"),
            ("three",       "numeral"),
            ("four",        "numeral"),
            ("five",        "numeral"),
            ("six",         "numeral"),
            ("seven",       "numeral"),
            ("eight",       "numeral"),
            ("nine",        "numeral"),
            ("ten",         "numeral"),
            ("twenty",      "numeral"),
            ("thirty",      "numeral"),
            ("forty",       "numeral"),
            ("fifty",       "numeral"),
            ("sixty",       "numeral"),
            ("seventy",     "numeral"),
            ("eighty",      "numeral"),
            ("ninety",      "numeral"),
            ("hundred",     "numeral"),
            ("thousand",    "numeral"),
            ("million",     "numeral"),
            ("first",       "adjective"),
            ("second",      "adjective"),
            ("third",       "adjective"),
            ("Monday",      "noun"),
            ("Tuesday",     "noun"),
            ("Wednesday",   "noun"),
            ("Thursday",    "noun"),
            ("Friday",      "noun"),
            ("Saturday",    "noun"),
            ("Sunday",      "noun"),
            ("January",     "noun"),
            ("February",    "noun"),
            ("March",       "noun"),
            ("April",       "noun"),
            ("May",         "noun"),
            ("June",        "noun"),
            ("July",        "noun"),
            ("August",      "noun"),
            ("September",   "noun"),
            ("October",     "noun"),
            ("November",    "noun"),
            ("December",    "noun"),
            ("morning",     "noun"),
            ("afternoon",   "noun"),
            ("evening",     "noun"),
            ("night",       "noun"),
            ("today",       "adverb"),
            ("tomorrow",    "adverb"),
            ("yesterday",   "adverb"),
            ("hour",        "noun"),
            ("minute",      "noun"),
            ("week",        "noun"),
            ("month",       "noun"),
            ("year",        "noun"),
            ("now",         "adverb"),
            ("later",       "adverb"),
        ],
    },

    "colors_shapes": {
        "name": "Colors & shapes",
        "emoji": "🎨",
        "words": [
            ("red",         "adjective"),
            ("blue",        "adjective"),
            ("green",       "adjective"),
            ("yellow",      "adjective"),
            ("orange",      "adjective"),
            ("purple",      "adjective"),
            ("pink",        "adjective"),
            ("brown",       "adjective"),
            ("black",       "adjective"),
            ("white",       "adjective"),
            ("grey",        "adjective"),
            ("dark",        "adjective"),
            ("light",       "adjective"),
            ("bright",      "adjective"),
            ("pale",        "adjective"),
            ("big",         "adjective"),
            ("small",       "adjective"),
            ("long",        "adjective"),
            ("short",       "adjective"),
            ("wide",        "adjective"),
            ("narrow",      "adjective"),
            ("round",       "adjective"),
            ("circle",      "noun"),
            ("square",      "noun"),
            ("triangle",    "noun"),
            ("rectangle",   "noun"),
            ("line",        "noun"),
            ("point",       "noun"),
        ],
    },

    "body_doctor": {
        "name": "Body & Doctor",
        "emoji": "🩺",
        "words": [
            ("head",            "noun"),
            ("eye",             "noun"),
            ("ear",             "noun"),
            ("nose",            "noun"),
            ("mouth",           "noun"),
            ("tooth",           "noun"),
            ("tongue",          "noun"),
            ("neck",            "noun"),
            ("shoulder",        "noun"),
            ("arm",             "noun"),
            ("elbow",           "noun"),
            ("wrist",           "noun"),
            ("hand",            "noun"),
            ("finger",          "noun"),
            ("thumb",           "noun"),
            ("back",            "noun"),
            ("chest",           "noun"),
            ("stomach",         "noun"),
            ("leg",             "noun"),
            ("knee",            "noun"),
            ("ankle",           "noun"),
            ("foot",            "noun"),
            ("toe",             "noun"),
            ("skin",            "noun"),
            ("hair",            "noun"),
            ("heart",           "noun"),
            ("lung",            "noun"),
            ("blood",           "noun"),
            ("bone",            "noun"),
            ("doctor",          "noun"),
            ("nurse",           "noun"),
            ("hospital",        "noun"),
            ("pharmacy",        "noun"),
            ("medicine",        "noun"),
            ("pain",            "noun"),
            ("fever",           "noun"),
            ("ill",             "adjective"),
            ("appointment",     "noun"),
            ("allergy",         "noun"),
            ("symptom",         "noun"),
            ("injection",       "noun"),
            ("prescription",    "noun"),
            ("ambulance",       "noun"),
        ],
    },

    "family": {
        "name": "Family & relationships",
        "emoji": "👨‍👩‍👧",
        "words": [
            ("mother",      "noun"),
            ("father",      "noun"),
            ("parents",     "noun"),
            ("sister",      "noun"),
            ("brother",     "noun"),
            ("son",         "noun"),
            ("daughter",    "noun"),
            ("baby",        "noun"),
            ("child",       "noun"),
            ("grandmother", "noun"),
            ("grandfather", "noun"),
            ("grandparents","noun"),
            ("uncle",       "noun"),
            ("aunt",        "noun"),
            ("cousin",      "noun"),
            ("niece",       "noun"),
            ("nephew",      "noun"),
            ("husband",     "noun"),
            ("wife",        "noun"),
            ("partner",     "noun"),
            ("friend",      "noun"),
            ("colleague",   "noun"),
            ("neighbor",    "noun"),
            ("boyfriend",   "noun"),
            ("girlfriend",  "noun"),
            ("married",     "adjective"),
            ("divorced",    "adjective"),
            ("single",      "adjective"),
            ("family",      "noun"),
        ],
    },

    "city_directions": {
        "name": "City & directions",
        "emoji": "🗺️",
        "words": [
            ("city",            "noun"),
            ("town",            "noun"),
            ("village",         "noun"),
            ("street",          "noun"),
            ("road",            "noun"),
            ("park",            "noun"),
            ("bridge",          "noun"),
            ("left",            "adverb"),
            ("right",           "adverb"),
            ("straight ahead",  "phrase"),
            ("north",           "noun"),
            ("south",           "noun"),
            ("east",            "noun"),
            ("west",            "noun"),
            ("turn",            "verb"),
            ("near",            "adverb"),
            ("far",             "adverb"),
            ("next to",         "phrase"),
            ("opposite",        "preposition"),
            ("between",         "preposition"),
            ("corner",          "noun"),
            ("traffic lights",  "noun"),
            ("roundabout",      "noun"),
            ("church",          "noun"),
            ("museum",          "noun"),
            ("library",         "noun"),
            ("bank",            "noun"),
            ("post office",     "noun"),
            ("school",          "noun"),
            ("station",         "noun"),
            ("market",          "noun"),
            ("bus stop",        "noun"),
            ("port",            "noun"),
        ],
    },

    "travelling": {
        "name": "Travelling",
        "emoji": "✈️",
        "words": [
            ("train",           "noun"),
            ("bus",             "noun"),
            ("plane",           "noun"),
            ("car",             "noun"),
            ("taxi",            "noun"),
            ("ferry",           "noun"),
            ("bicycle",         "noun"),
            ("metro",           "noun"),
            ("airport",         "noun"),
            ("hotel",           "noun"),
            ("hostel",          "noun"),
            ("passport",        "noun"),
            ("visa",            "noun"),
            ("ticket",          "noun"),
            ("luggage",         "noun"),
            ("platform",        "noun"),
            ("departure",       "noun"),
            ("arrival",         "noun"),
            ("booking",         "noun"),
            ("check-in",        "noun"),
            ("room",            "noun"),
            ("key",             "noun"),
            ("reception",       "noun"),
            ("reservation",     "noun"),
            ("journey",         "noun"),
            ("tourist",         "noun"),
            ("map",             "noun"),
            ("guide",           "noun"),
            ("border",          "noun"),
            ("customs",         "noun"),
            ("delay",           "noun"),
            ("schedule",        "noun"),
            ("seat",            "noun"),
            ("return",          "noun"),
            ("one-way",         "adjective"),
            ("direct",          "adjective"),
            ("suitcase",        "noun"),
        ],
    },

    "food_drink": {
        "name": "Food & drink",
        "emoji": "🍽️",
        "words": [
            ("bread",       "noun"),
            ("rice",        "noun"),
            ("pasta",       "noun"),
            ("egg",         "noun"),
            ("cheese",      "noun"),
            ("butter",      "noun"),
            ("oil",         "noun"),
            ("salt",        "noun"),
            ("pepper",      "noun"),
            ("sugar",       "noun"),
            ("chicken",     "noun"),
            ("beef",        "noun"),
            ("pork",        "noun"),
            ("lamb",        "noun"),
            ("fish",        "noun"),
            ("seafood",     "noun"),
            ("potato",      "noun"),
            ("tomato",      "noun"),
            ("onion",       "noun"),
            ("garlic",      "noun"),
            ("carrot",      "noun"),
            ("salad",       "noun"),
            ("apple",       "noun"),
            ("banana",      "noun"),
            ("lemon",       "noun"),
            ("strawberry",  "noun"),
            ("grape",       "noun"),
            ("water",       "noun"),
            ("juice",       "noun"),
            ("coffee",      "noun"),
            ("tea",         "noun"),
            ("wine",        "noun"),
            ("beer",        "noun"),
            ("milk",        "noun"),
            ("vegetarian",  "adjective"),
            ("vegan",       "adjective"),
            ("spicy",       "adjective"),
            ("sweet",       "adjective"),
            ("sour",        "adjective"),
            ("salty",       "adjective"),
            ("fresh",       "adjective"),
            ("frozen",      "adjective"),
            ("meal",        "noun"),
        ],
    },

    "emotions": {
        "name": "Emotions",
        "emoji": "😊",
        "words": [
            ("happy",           "adjective"),
            ("sad",             "adjective"),
            ("angry",           "adjective"),
            ("afraid",          "adjective"),
            ("surprised",       "adjective"),
            ("nervous",         "adjective"),
            ("excited",         "adjective"),
            ("tired",           "adjective"),
            ("bored",           "adjective"),
            ("confused",        "adjective"),
            ("proud",           "adjective"),
            ("ashamed",         "adjective"),
            ("jealous",         "adjective"),
            ("lonely",          "adjective"),
            ("calm",            "adjective"),
            ("stressed",        "adjective"),
            ("relaxed",         "adjective"),
            ("curious",         "adjective"),
            ("hopeful",         "adjective"),
            ("disappointed",    "adjective"),
            ("grateful",        "adjective"),
            ("content",         "adjective"),
            ("love",            "noun"),
            ("hate",            "noun"),
            ("fear",            "noun"),
            ("joy",             "noun"),
            ("to feel",         "verb"),
            ("mood",            "noun"),
        ],
    },

    "home": {
        "name": "My home",
        "emoji": "🏠",
        "words": [
            ("bedroom",     "noun"),
            ("living room", "noun"),
            ("kitchen",     "noun"),
            ("bathroom",    "noun"),
            ("toilet",      "noun"),
            ("hall",        "noun"),
            ("balcony",     "noun"),
            ("garden",      "noun"),
            ("garage",      "noun"),
            ("roof",        "noun"),
            ("stairs",      "noun"),
            ("bed",         "noun"),
            ("sofa",        "noun"),
            ("table",       "noun"),
            ("chair",       "noun"),
            ("wardrobe",    "noun"),
            ("shelf",       "noun"),
            ("desk",        "noun"),
            ("lamp",        "noun"),
            ("mirror",      "noun"),
            ("curtain",     "noun"),
            ("fridge",      "noun"),
            ("oven",        "noun"),
            ("microwave",   "noun"),
            ("dishwasher",  "noun"),
            ("sink",        "noun"),
            ("cup",         "noun"),
            ("glass",       "noun"),
            ("plate",       "noun"),
            ("fork",        "noun"),
            ("knife",       "noun"),
            ("spoon",       "noun"),
            ("pot",         "noun"),
            ("pan",         "noun"),
            ("window",      "noun"),
            ("door",        "noun"),
            ("floor",       "noun"),
            ("ceiling",     "noun"),
            ("wall",        "noun"),
        ],
    },

    "jobs_work": {
        "name": "Jobs & work",
        "emoji": "💼",
        "words": [
            ("teacher",         "noun"),
            ("engineer",        "noun"),
            ("lawyer",          "noun"),
            ("journalist",      "noun"),
            ("chef",            "noun"),
            ("architect",       "noun"),
            ("police officer",  "noun"),
            ("firefighter",     "noun"),
            ("pilot",           "noun"),
            ("mechanic",        "noun"),
            ("programmer",      "noun"),
            ("artist",          "noun"),
            ("musician",        "noun"),
            ("actor",           "noun"),
            ("farmer",          "noun"),
            ("waiter",          "noun"),
            ("builder",         "noun"),
            ("accountant",      "noun"),
            ("job",             "noun"),
            ("work",            "noun"),
            ("salary",          "noun"),
            ("office",          "noun"),
            ("factory",         "noun"),
            ("meeting",         "noun"),
            ("boss",            "noun"),
            ("deadline",        "noun"),
            ("career",          "noun"),
            ("interview",       "noun"),
            ("to hire",         "verb"),
            ("to retire",       "verb"),
            ("contract",        "noun"),
            ("employee",        "noun"),
            ("employer",        "noun"),
            ("project",         "noun"),
            ("client",          "noun"),
            ("report",          "noun"),
        ],
    },

    "clothing": {
        "name": "Clothing & fashion",
        "emoji": "👗",
        "words": [
            ("shirt",       "noun"),
            ("t-shirt",     "noun"),
            ("trousers",    "noun"),
            ("jeans",       "noun"),
            ("dress",       "noun"),
            ("skirt",       "noun"),
            ("jacket",      "noun"),
            ("coat",        "noun"),
            ("suit",        "noun"),
            ("underwear",   "noun"),
            ("socks",       "noun"),
            ("shoes",       "noun"),
            ("boots",       "noun"),
            ("hat",         "noun"),
            ("scarf",       "noun"),
            ("gloves",      "noun"),
            ("belt",        "noun"),
            ("tie",         "noun"),
            ("bag",         "noun"),
            ("glasses",     "noun"),
            ("ring",        "noun"),
            ("necklace",    "noun"),
            ("size",        "noun"),
            ("to wear",     "verb"),
            ("to try on",   "verb"),
            ("to fit",      "verb"),
            ("tight",       "adjective"),
            ("loose",       "adjective"),
            ("striped",     "adjective"),
            ("plain",       "adjective"),
            ("patterned",   "adjective"),
            ("cotton",      "noun"),
            ("wool",        "noun"),
        ],
    },

    "weather_seasons": {
        "name": "Weather & seasons",
        "emoji": "⛅",
        "words": [
            ("spring",      "noun"),
            ("summer",      "noun"),
            ("autumn",      "noun"),
            ("winter",      "noun"),
            ("sun",         "noun"),
            ("rain",        "noun"),
            ("snow",        "noun"),
            ("wind",        "noun"),
            ("cloud",       "noun"),
            ("fog",         "noun"),
            ("storm",       "noun"),
            ("lightning",   "noun"),
            ("thunder",     "noun"),
            ("ice",         "noun"),
            ("hail",        "noun"),
            ("hot",         "adjective"),
            ("cold",        "adjective"),
            ("warm",        "adjective"),
            ("cool",        "adjective"),
            ("temperature", "noun"),
            ("degree",      "noun"),
            ("forecast",    "noun"),
            ("umbrella",    "noun"),
            ("sunny",       "adjective"),
            ("rainy",       "adjective"),
            ("snowy",       "adjective"),
            ("windy",       "adjective"),
            ("cloudy",      "adjective"),
            ("freezing",    "adjective"),
            ("humid",       "adjective"),
        ],
    },

    "nature_animals": {
        "name": "Nature & animals",
        "emoji": "🌿",
        "words": [
            ("dog",         "noun"),
            ("cat",         "noun"),
            ("horse",       "noun"),
            ("cow",         "noun"),
            ("pig",         "noun"),
            ("sheep",       "noun"),
            ("bird",        "noun"),
            ("eagle",       "noun"),
            ("snake",       "noun"),
            ("lion",        "noun"),
            ("tiger",       "noun"),
            ("elephant",    "noun"),
            ("bear",        "noun"),
            ("wolf",        "noun"),
            ("rabbit",      "noun"),
            ("mouse",       "noun"),
            ("bee",         "noun"),
            ("butterfly",   "noun"),
            ("tree",        "noun"),
            ("flower",      "noun"),
            ("grass",       "noun"),
            ("forest",      "noun"),
            ("mountain",    "noun"),
            ("river",       "noun"),
            ("lake",        "noun"),
            ("sea",         "noun"),
            ("ocean",       "noun"),
            ("beach",       "noun"),
            ("desert",      "noun"),
            ("island",      "noun"),
            ("rock",        "noun"),
            ("sand",        "noun"),
            ("sky",         "noun"),
            ("moon",        "noun"),
            ("star",        "noun"),
            ("earth",       "noun"),
            ("air",         "noun"),
            ("fire",        "noun"),
            ("plant",       "noun"),
        ],
    },

    "shopping_money": {
        "name": "Shopping & money",
        "emoji": "🛒",
        "words": [
            ("shop",            "noun"),
            ("supermarket",     "noun"),
            ("price",           "noun"),
            ("discount",        "noun"),
            ("sale",            "noun"),
            ("receipt",         "noun"),
            ("money",           "noun"),
            ("coin",            "noun"),
            ("banknote",        "noun"),
            ("credit card",     "noun"),
            ("ATM",             "noun"),
            ("cheap",           "adjective"),
            ("expensive",       "adjective"),
            ("free",            "adjective"),
            ("to pay",          "verb"),
            ("to buy",          "verb"),
            ("to sell",         "verb"),
            ("cost",            "noun"),
            ("wallet",          "noun"),
            ("budget",          "noun"),
            ("tip",             "noun"),
            ("change",          "noun"),
            ("queue",           "noun"),
            ("opening hours",   "noun"),
            ("closed",          "adjective"),
            ("open",            "adjective"),
            ("customer",        "noun"),
            ("refund",          "noun"),
        ],
    },

    "school_education": {
        "name": "School & education",
        "emoji": "📚",
        "words": [
            ("university",      "noun"),
            ("classroom",       "noun"),
            ("student",         "noun"),
            ("lesson",          "noun"),
            ("subject",         "noun"),
            ("homework",        "noun"),
            ("exam",            "noun"),
            ("grade",           "noun"),
            ("mathematics",     "noun"),
            ("science",         "noun"),
            ("history",         "noun"),
            ("geography",       "noun"),
            ("language",        "noun"),
            ("art",             "noun"),
            ("music",           "noun"),
            ("sport",           "noun"),
            ("book",            "noun"),
            ("notebook",        "noun"),
            ("pen",             "noun"),
            ("pencil",          "noun"),
            ("ruler",           "noun"),
            ("board",           "noun"),
            ("to learn",        "verb"),
            ("to study",        "verb"),
            ("to read",         "verb"),
            ("to write",        "verb"),
            ("to understand",   "verb"),
            ("to explain",      "verb"),
            ("to ask",          "verb"),
            ("to answer",       "verb"),
            ("to pass",         "verb"),
            ("to fail",         "verb"),
        ],
    },

    "sports_hobbies": {
        "name": "Sports & hobbies",
        "emoji": "⚽",
        "words": [
            ("football",    "noun"),
            ("tennis",      "noun"),
            ("swimming",    "noun"),
            ("running",     "noun"),
            ("cycling",     "noun"),
            ("basketball",  "noun"),
            ("volleyball",  "noun"),
            ("skiing",      "noun"),
            ("boxing",      "noun"),
            ("yoga",        "noun"),
            ("gym",         "noun"),
            ("hiking",      "noun"),
            ("reading",     "noun"),
            ("cooking",     "noun"),
            ("drawing",     "noun"),
            ("painting",    "noun"),
            ("photography", "noun"),
            ("dancing",     "noun"),
            ("gardening",   "noun"),
            ("gaming",      "noun"),
            ("film",        "noun"),
            ("team",        "noun"),
            ("player",      "noun"),
            ("match",       "noun"),
            ("goal",        "noun"),
            ("score",       "noun"),
            ("to play",     "verb"),
            ("to practice", "verb"),
            ("to train",    "verb"),
            ("to win",      "verb"),
            ("to lose",     "verb"),
            ("champion",    "noun"),
            ("referee",     "noun"),
            ("stadium",     "noun"),
            ("coach",       "noun"),
            ("fan",         "noun"),
        ],
    },

    "restaurant": {
        "name": "Restaurants & ordering",
        "emoji": "🍴",
        "words": [
            ("menu",            "noun"),
            ("bill",            "noun"),
            ("starter",         "noun"),
            ("main course",     "noun"),
            ("dessert",         "noun"),
            ("drink",           "noun"),
            ("to order",        "verb"),
            ("to recommend",    "verb"),
            ("to serve",        "verb"),
            ("mild",            "adjective"),
            ("delicious",       "adjective"),
            ("take away",       "phrase"),
            ("delivery",        "noun"),
            ("portion",         "noun"),
            ("bottle",          "noun"),
            ("to taste",        "verb"),
            ("well done",       "phrase"),
            ("enjoy your meal", "phrase"),
            ("the bill please", "phrase"),
        ],
    },

    "technology": {
        "name": "Technology & media",
        "emoji": "💻",
        "words": [
            ("phone",           "noun"),
            ("laptop",          "noun"),
            ("computer",        "noun"),
            ("tablet",          "noun"),
            ("TV",              "noun"),
            ("camera",          "noun"),
            ("screen",          "noun"),
            ("keyboard",        "noun"),
            ("headphones",      "noun"),
            ("internet",        "noun"),
            ("website",         "noun"),
            ("email",           "noun"),
            ("social media",    "noun"),
            ("app",             "noun"),
            ("to download",     "verb"),
            ("to upload",       "verb"),
            ("password",        "noun"),
            ("account",         "noun"),
            ("notification",    "noun"),
            ("news",            "noun"),
            ("newspaper",       "noun"),
            ("magazine",        "noun"),
            ("series",          "noun"),
            ("podcast",         "noun"),
            ("to send",         "verb"),
            ("to call",         "verb"),
            ("to text",         "verb"),
            ("to search",       "verb"),
            ("to save",         "verb"),
            ("to share",        "verb"),
            ("battery",         "noun"),
            ("charger",         "noun"),
        ],
    },
}
