"""
nl_vocab_data.py — Dutch vocabulary preset cards.

Grammar label reference (use these EXACTLY):
  Noun:        Article / Gender | Plural | Diminutive
  Verb:        Past tense (sg.) | Past participle | Auxiliary |
               Present (ik / jij / hij / wij / jullie / zij)
  Adjective:   Inflected form | Comparative | Superlative
  Adverb:      (no grammar fields required)
  Preposition: Pronominal adverb | Fixed combinations
  Conjunction: Type | Word-order effect
  Particle:    Function / meaning nuance | Typical usage example
"""

CARDS = [
    {
        "id": "nl-weemoed",
        "word": "weemoed",
        "translation": "melancholy, wistfulness",
        "type": "noun",
        "group": "🧀 Curated",
        "pronunciation": "/ˈʋeːmut/",
        "etymology": 'From Middle Dutch, related to "wee" (pain) and "moed" (state of mind).',
        "note": "Often poetic or reflective in tone.",
        "tags": ["⭐ common", "🧠 emotion", "📚 literary"],
        "priority": True,
        "grammar": [
            {"label": "Article / Gender", "value": "de"},
            {"label": "Plural", "value": "weemoeden"},
            {"label": "Diminutive", "value": "het weemoedje"},
        ],
        "example": {"nl": "Soms voelt hij een vreemde weemoed wanneer het regent.", "en": "Sometimes he feels a strange melancholy when it rains."},
    },
    {
        "id": "nl-slenteren",
        "word": "slenteren",
        "translation": "to stroll, to wander",
        "type": "verb",
        "group": "🧀 Curated",
        "pronunciation": "/ˈslɛntərə(n)/",
        "etymology": "Possibly related to Germanic roots meaning to drag slowly.",
        "note": "Suggests relaxed, aimless walking.",
        "tags": ["🚶 movement", "⭐ common", "🌆 daily"],
        "priority": True,
        "grammar": [
            {"label": "Past tense (sg.)", "value": "slenterde"},
            {"label": "Past participle", "value": "geslenterd"},
            {"label": "Auxiliary", "value": "hebben"},
            {"label": "Present (ik / jij / hij / wij / jullie / zij)", "value": "slenter / slentert / slentert / slenteren / slenteren / slenteren"},
        ],
        "example": {"nl": "We slenterden urenlang door de oude straatjes.", "en": "We strolled through the old streets for hours."},
    },
    {
        "id": "nl-eigenwijs",
        "word": "eigenwijs",
        "translation": "stubborn, headstrong",
        "type": "adjective",
        "group": "🧀 Curated",
        "pronunciation": "/ˌɛiɣənˈʋɛis/",
        "note": "Often mildly affectionate rather than harsh.",
        "tags": ["🧠 personality", "⭐ common", "🎭 adjective"],
        "priority": True,
        "grammar": [
            {"label": "Inflected form", "value": "eigenwijze"},
            {"label": "Comparative", "value": "eigenwijzer"},
            {"label": "Superlative", "value": "eigenwijsst"},
        ],
        "example": {"nl": "Dat kind is slim maar ontzettend eigenwijs.", "en": "That child is smart but incredibly stubborn."},
    },
    {
        "id": "nl-blijkbaar",
        "word": "blijkbaar",
        "translation": "apparently, evidently",
        "type": "adverb",
        "group": "🧀 Curated",
        "pronunciation": "/ˈblɛikbaːr/",
        "tags": ["💬 communication", "⭐ common", "🕰️ time"],
        "priority": True,
        "example": {"nl": "Hij wist blijkbaar niets van de afspraak.", "en": "Apparently he knew nothing about the appointment."},
    },
    {
        "id": "nl-ondanks",
        "word": "ondanks",
        "translation": "despite, in spite of",
        "type": "preposition",
        "group": "🧀 Curated",
        "pronunciation": "/ɔnˈdɑŋks/",
        "tags": ["💬 communication", "⭐ common", "📚 grammar"],
        "priority": True,
        "grammar": [
            {"label": "Pronominal adverb", "value": "ondanks → ondanks dat"},
            {"label": "Fixed combinations", "value": "ondanks alles, ondanks het feit dat"},
        ],
        "example": {"nl": "Ondanks de regen gingen ze wandelen.", "en": "Despite the rain, they went for a walk."},
    },
    {
        "id": "nl-terwijl",
        "word": "terwijl",
        "translation": "while, whereas",
        "type": "conjunction",
        "group": "🧀 Curated",
        "pronunciation": "/tɛrˈʋɛil/",
        "tags": ["💬 communication", "⭐ common", "📚 grammar"],
        "priority": True,
        "grammar": [
            {"label": "Type", "value": "subordinating"},
            {"label": "Word-order effect", "value": "verb to end of clause (SOV)"},
        ],
        "example": {"nl": "Zij las een boek terwijl hij kookte.", "en": "She read a book while he cooked."},
    },
    {
        "id": "nl-hoor",
        "word": "hoor",
        "translation": "you know, really",
        "type": "particle",
        "group": "🧀 Curated",
        "pronunciation": "/hoːr/",
        "note": "Adds reassurance, emphasis, or friendliness.",
        "tags": ["💬 communication", "🇳🇱 dutchness", "⭐ common"],
        "priority": True,
        "grammar": [
            {"label": "Function / meaning nuance", "value": "emphasis, reassurance, softening"},
            {"label": "Typical usage example", "value": "Het valt wel mee hoor. · Dank je hoor!"},
        ],
        "example": {"nl": "Dat meen ik hoor!", "en": "I really mean that, you know!"},
    },
    {
        "id": "nl-schemering",
        "word": "schemering",
        "translation": "twilight, dusk",
        "type": "noun",
        "group": "🧀 Curated",
        "pronunciation": "/ˈsxeːmərɪŋ/",
        "tags": ["🌙 nature", "📚 literary", "🕰️ time"],
        "priority": True,
        "grammar": [
            {"label": "Article / Gender", "value": "de"},
            {"label": "Plural", "value": "schemeringen"},
            {"label": "Diminutive", "value": "het schemerinkje"},
        ],
        "example": {"nl": "In de schemering zagen de bomen er mysterieus uit.", "en": "In the twilight the trees looked mysterious."},
    },
    {
        "id": "nl-verdwalen",
        "word": "verdwalen",
        "translation": "to get lost",
        "type": "verb",
        "group": "🧀 Curated",
        "pronunciation": "/vərˈdʋaːlə(n)/",
        "tags": ["🚶 movement", "🌍 travel", "⭐ common"],
        "priority": True,
        "grammar": [
            {"label": "Past tense (sg.)", "value": "verdwaalde"},
            {"label": "Past participle", "value": "verdwaald"},
            {"label": "Auxiliary", "value": "zijn"},
            {"label": "Present (ik / jij / hij / wij / jullie / zij)", "value": "verdwaal / verdwaalt / verdwaalt / verdwalen / verdwalen / verdwalen"},
        ],
        "example": {"nl": "We verdwaalden in het bos.", "en": "We got lost in the forest."},
    },
    {
        "id": "nl-knus",
        "word": "knus",
        "translation": "cozy, snug",
        "type": "adjective",
        "group": "🧀 Curated",
        "pronunciation": "/knʏs/",
        "tags": ["🏠 home", "⭐ common", "🎭 adjective"],
        "priority": True,
        "grammar": [
            {"label": "Inflected form", "value": "knusse"},
            {"label": "Comparative", "value": "knusser"},
            {"label": "Superlative", "value": "knust"},
        ],
        "example": {"nl": "Het café was klein maar erg knus.", "en": "The café was small but very cozy."},
    },
    {
        "id": "nl-ineens",
        "word": "ineens",
        "translation": "suddenly, all at once",
        "type": "adverb",
        "group": "🧀 Curated",
        "pronunciation": "/ɪnˈeːns/",
        "tags": ["🕰️ time", "⭐ common", "💬 communication"],
        "priority": True,
        "example": {"nl": "Ineens begon iedereen te lachen.", "en": "Suddenly everyone started laughing."},
    },
    {
        "id": "nl-wegens",
        "word": "wegens",
        "translation": "because of, due to",
        "type": "preposition",
        "group": "🧀 Curated",
        "pronunciation": "/ˈʋeːɣəns/",
        "tags": ["🚆 travel", "📚 grammar", "⭐ common"],
        "priority": True,
        "grammar": [
            {"label": "Pronominal adverb", "value": "wegens → wegens het feit"},
            {"label": "Fixed combinations", "value": "wegens omstandigheden, wegens ziekte"},
        ],
        "example": {"nl": "De trein had vertraging wegens werkzaamheden.", "en": "The train was delayed due to construction work."},
    },
    {
        "id": "nl-zodra",
        "word": "zodra",
        "translation": "as soon as",
        "type": "conjunction",
        "group": "🧀 Curated",
        "pronunciation": "/zoˈdra/",
        "tags": ["🕰️ time", "📚 grammar", "⭐ common"],
        "priority": True,
        "grammar": [
            {"label": "Type", "value": "subordinating"},
            {"label": "Word-order effect", "value": "verb to end of clause (SOV)"},
        ],
        "example": {"nl": "Zodra hij thuiskwam, ging hij slapen.", "en": "As soon as he came home, he went to sleep."},
    },
    {
        "id": "nl-nou",
        "word": "nou",
        "translation": "well, now",
        "type": "particle",
        "group": "🧀 Curated",
        "pronunciation": "/nʌu/",
        "tags": ["💬 communication", "🇳🇱 dutchness", "⭐ common"],
        "priority": True,
        "grammar": [
            {"label": "Function / meaning nuance", "value": "hesitation, emphasis, surprise"},
            {"label": "Typical usage example", "value": "Nou zeg! · Nou en?"},
        ],
        "example": {"nl": "Nou, dat was onverwacht.", "en": "Well, that was unexpected."},
    },
    {
        "id": "nl-rommelmarkt",
        "word": "rommelmarkt",
        "translation": "flea market",
        "type": "noun",
        "group": "🧀 Curated",
        "pronunciation": "/ˈrɔməlmɑrkt/",
        "tags": ["🛍️ shopping", "🌆 daily", "⭐ common"],
        "priority": True,
        "grammar": [
            {"label": "Article / Gender", "value": "de"},
            {"label": "Plural", "value": "rommelmarkten"},
            {"label": "Diminutive", "value": "het rommelmarktje"},
        ],
        "example": {"nl": "Op de rommelmarkt vonden we oude platen.", "en": "At the flea market we found old records."},
    },
    {
        "id": "nl-peinzen",
        "word": "peinzen",
        "translation": "to ponder, to muse",
        "type": "verb",
        "group": "🧀 Curated",
        "pronunciation": "/ˈpɛinzə(n)/",
        "tags": ["🧠 thinking", "📚 literary", "🎭 emotion"],
        "priority": True,
        "grammar": [
            {"label": "Past tense (sg.)", "value": "peinsde"},
            {"label": "Past participle", "value": "gepeinsd"},
            {"label": "Auxiliary", "value": "hebben"},
            {"label": "Present (ik / jij / hij / wij / jullie / zij)", "value": "peins / peinst / peinst / peinzen / peinzen / peinzen"},
        ],
        "example": {"nl": "Hij peinsde urenlang over die vraag.", "en": "He pondered that question for hours."},
    },
    {
        "id": "nl-morsig",
        "word": "morsig",
        "translation": "messy, grubby",
        "type": "adjective",
        "group": "🧀 Curated",
        "pronunciation": "/ˈmɔrsəx/",
        "tags": ["🏠 home", "🎭 adjective", "🌆 daily"],
        "priority": True,
        "grammar": [
            {"label": "Inflected form", "value": "morsige"},
            {"label": "Comparative", "value": "morsiger"},
            {"label": "Superlative", "value": "morsigst"},
        ],
        "example": {"nl": "Hij droeg een morsige jas.", "en": "He wore a grubby coat."},
    },
    {
        "id": "nl-wellicht",
        "word": "wellicht",
        "translation": "perhaps, possibly",
        "type": "adverb",
        "group": "🧀 Curated",
        "pronunciation": "/ʋɛlˈlɪxt/",
        "note": "Slightly formal or literary.",
        "tags": ["💬 communication", "📚 literary", "⭐ common"],
        "priority": True,
        "example": {"nl": "Wellicht komen ze morgen langs.", "en": "Perhaps they will stop by tomorrow."},
    },
    {
        "id": "nl-tegenover",
        "word": "tegenover",
        "translation": "opposite, across from",
        "type": "preposition",
        "group": "🧀 Curated",
        "pronunciation": "/tɛɣəˈnoːvər/",
        "tags": ["🚶 movement", "🌍 travel", "📚 grammar"],
        "priority": True,
        "grammar": [
            {"label": "Pronominal adverb", "value": "tegenover → daartegenover"},
            {"label": "Fixed combinations", "value": "tegenover elkaar, staan tegenover"},
        ],
        "example": {"nl": "Hij woont tegenover het station.", "en": "He lives opposite the station."},
    },
    {
        "id": "nl-tenzij",
        "word": "tenzij",
        "translation": "unless",
        "type": "conjunction",
        "group": "🧀 Curated",
        "pronunciation": "/tɛnˈzɛi/",
        "tags": ["💬 communication", "📚 grammar", "⭐ common"],
        "priority": True,
        "grammar": [
            {"label": "Type", "value": "subordinating"},
            {"label": "Word-order effect", "value": "verb to end of clause (SOV)"},
        ],
        "example": {"nl": "Ik ga mee tenzij het regent.", "en": "I'll come along unless it rains."},
    },
    {
        "id": "nl-toch",
        "word": "toch",
        "translation": "anyway, after all",
        "type": "particle",
        "group": "🧀 Curated",
        "pronunciation": "/tɔx/",
        "tags": ["💬 communication", "🇳🇱 dutchness", "⭐ common"],
        "priority": True,
        "grammar": [
            {"label": "Function / meaning nuance", "value": "reassurance, contradiction, insistence"},
            {"label": "Typical usage example", "value": "Dat wist je toch? · Kom toch mee."},
        ],
        "example": {"nl": "Je komt toch mee?", "en": "You are coming along, right?"},
    },
    {
        "id": "nl-mijmering",
        "word": "mijmering",
        "translation": "daydream, reverie",
        "type": "noun",
        "group": "🧀 Curated",
        "pronunciation": "/ˈmɛimərɪŋ/",
        "tags": ["🧠 thinking", "📚 literary", "🌙 emotion"],
        "priority": True,
        "grammar": [
            {"label": "Article / Gender", "value": "de"},
            {"label": "Plural", "value": "mijmeringen"},
            {"label": "Diminutive", "value": "het mijmerinkje"},
        ],
        "example": {"nl": "Ze verzonk in een stille mijmering.", "en": "She sank into a quiet reverie."},
    },
    {
        "id": "nl-struinen",
        "word": "struinen",
        "translation": "to roam, to rummage around",
        "type": "verb",
        "group": "🧀 Curated",
        "pronunciation": "/ˈstrœynə(n)/",
        "tags": ["🚶 movement", "🛍️ shopping", "🌆 daily"],
        "priority": True,
        "grammar": [
            {"label": "Past tense (sg.)", "value": "struinde"},
            {"label": "Past participle", "value": "gestruind"},
            {"label": "Auxiliary", "value": "hebben"},
            {"label": "Present (ik / jij / hij / wij / jullie / zij)", "value": "struin / struint / struint / struinen / struinen / struinen"},
        ],
        "example": {"nl": "We struinden door kleine boekwinkels.", "en": "We roamed through little bookshops."},
    },
    {
        "id": "nl-guur",
        "word": "guur",
        "translation": "bleak, harsh",
        "type": "adjective",
        "group": "🧀 Curated",
        "pronunciation": "/ɣyːr/",
        "tags": ["🌧️ weather", "🎭 adjective", "⭐ common"],
        "priority": True,
        "grammar": [
            {"label": "Inflected form", "value": "gure"},
            {"label": "Comparative", "value": "guurder"},
            {"label": "Superlative", "value": "guurst"},
        ],
        "example": {"nl": "Het was een gure herfstdag.", "en": "It was a bleak autumn day."},
    },
    {
        "id": "nl-nauwelijks",
        "word": "nauwelijks",
        "translation": "hardly, barely",
        "type": "adverb",
        "group": "🧀 Curated",
        "pronunciation": "/ˈnʌu̯əlɪks/",
        "tags": ["🕰️ time", "⭐ common", "💬 communication"],
        "priority": True,
        "example": {"nl": "Ik had nauwelijks tijd om te eten.", "en": "I barely had time to eat."},
    },
    {
        "id": "nl-dankzij",
        "word": "dankzij",
        "translation": "thanks to",
        "type": "preposition",
        "group": "🧀 Curated",
        "pronunciation": "/ˈdɑŋkzɛi/",
        "tags": ["💬 communication", "⭐ common", "📚 grammar"],
        "priority": True,
        "grammar": [
            {"label": "Pronominal adverb", "value": "dankzij → dankzij dat"},
            {"label": "Fixed combinations", "value": "dankzij jou, dankzij zijn inzet"},
        ],
        "example": {"nl": "Dankzij jouw hulp lukte het.", "en": "Thanks to your help, it worked."},
    },
    {
        "id": "nl-hoewel",
        "word": "hoewel",
        "translation": "although",
        "type": "conjunction",
        "group": "🧀 Curated",
        "pronunciation": "/ɦuˈʋeːl/",
        "tags": ["💬 communication", "📚 grammar", "⭐ common"],
        "priority": True,
        "grammar": [
            {"label": "Type", "value": "subordinating"},
            {"label": "Word-order effect", "value": "verb to end of clause (SOV)"},
        ],
        "example": {"nl": "Hoewel ze moe was, bleef ze werken.", "en": "Although she was tired, she kept working."},
    },
    {
        "id": "nl-maar",
        "word": "maar",
        "translation": "just, simply",
        "type": "particle",
        "group": "🧀 Curated",
        "pronunciation": "/maːr/",
        "tags": ["💬 communication", "🇳🇱 dutchness", "⭐ common"],
        "priority": True,
        "grammar": [
            {"label": "Function / meaning nuance", "value": "softener, encouragement"},
            {"label": "Typical usage example", "value": "Kom maar binnen. · Zeg maar wat je denkt."},
        ],
        "example": {"nl": "Doe maar rustig aan.", "en": "Just take it easy."},
    },
    {
        "id": "nl-verwondering",
        "word": "verwondering",
        "translation": "amazement, wonder",
        "type": "noun",
        "group": "🧀 Curated",
        "pronunciation": "/vərˈʋɔndərɪŋ/",
        "tags": ["🌌 nature", "🎭 emotion", "📚 literary"],
        "priority": True,
        "grammar": [
            {"label": "Article / Gender", "value": "de"},
            {"label": "Plural", "value": "verwonderingen"},
            {"label": "Diminutive", "value": "het verwonderinkje"},
        ],
        "example": {"nl": "Ze keek met verwondering naar de sterren.", "en": "She looked at the stars in amazement."},
    },
    {
        "id": "nl-fluisteren",
        "word": "fluisteren",
        "translation": "to whisper",
        "type": "verb",
        "group": "🧀 Curated",
        "pronunciation": "/ˈflystərə(n)/",
        "tags": ["💬 communication", "⭐ common", "🌆 daily"],
        "priority": True,
        "grammar": [
            {"label": "Past tense (sg.)", "value": "fluisterde"},
            {"label": "Past participle", "value": "gefluisterd"},
            {"label": "Auxiliary", "value": "hebben"},
            {"label": "Present (ik / jij / hij / wij / jullie / zij)", "value": "fluister / fluistert / fluistert / fluisteren / fluisteren / fluisteren"},
        ],
        "example": {"nl": "Ze fluisterde iets in mijn oor.", "en": "She whispered something in my ear."},
    },
    {
        "id": "nl-broeierig",
        "word": "broeierig",
        "translation": "sultry, oppressive",
        "type": "adjective",
        "group": "🧀 Curated",
        "pronunciation": "/ˈbru.jərɪx/",
        "tags": ["🌧️ weather", "🎭 adjective", "🌆 daily"],
        "priority": True,
        "grammar": [
            {"label": "Inflected form", "value": "broeierige"},
            {"label": "Comparative", "value": "broeieriger"},
            {"label": "Superlative", "value": "broeierigst"},
        ],
        "example": {"nl": "Het was een broeierige zomeravond.", "en": "It was a sultry summer evening."},
    },
    {
        "id": "nl-inmiddels",
        "word": "inmiddels",
        "translation": "by now, meanwhile",
        "type": "adverb",
        "group": "🧀 Curated",
        "pronunciation": "/ɪnˈmɪdɛls/",
        "tags": ["🕰️ time", "⭐ common", "💬 communication"],
        "priority": True,
        "example": {"nl": "Inmiddels was iedereen vertrokken.", "en": "By now everyone had left."},
    },
    {
        "id": "nl-volgens",
        "word": "volgens",
        "translation": "according to",
        "type": "preposition",
        "group": "🧀 Curated",
        "pronunciation": "/ˈvɔlxəns/",
        "tags": ["💬 communication", "📚 grammar", "⭐ common"],
        "priority": True,
        "grammar": [
            {"label": "Pronominal adverb", "value": "volgens → volgens mij"},
            {"label": "Fixed combinations", "value": "volgens plan, volgens afspraak"},
        ],
        "example": {"nl": "Volgens de krant wordt het morgen warmer.", "en": "According to the newspaper it will be warmer tomorrow."},
    },
    {
        "id": "nl-even",
        "word": "even",
        "translation": "just, briefly",
        "type": "particle",
        "group": "🧀 Curated",
        "pronunciation": "/ˈeːvə(n)/",
        "tags": ["💬 communication", "🇳🇱 dutchness", "⭐ common"],
        "priority": True,
        "grammar": [
            {"label": "Function / meaning nuance", "value": "softening, brevity"},
            {"label": "Typical usage example", "value": "Kom even hier. · Ik kijk even."},
        ],
        "example": {"nl": "Wacht even!", "en": "Wait a second!"},
    },
    {
        "id": "nl-stilte",
        "word": "stilte",
        "translation": "silence, quiet",
        "type": "noun",
        "group": "🧀 Curated",
        "pronunciation": "/ˈstɪltə/",
        "tags": ["🌙 nature", "🎭 emotion", "⭐ common"],
        "priority": True,
        "grammar": [
            {"label": "Article / Gender", "value": "de"},
            {"label": "Plural", "value": "stiltes"},
            {"label": "Diminutive", "value": "het stilletje"},
        ],
        "example": {"nl": "De stilte in het bos voelde bijna magisch.", "en": "The silence in the forest felt almost magical."},
    },
    {
        "id": "nl-huiveren",
        "word": "huiveren",
        "translation": "to shiver, to recoil",
        "type": "verb",
        "group": "🧀 Curated",
        "pronunciation": "/ˈɦœyvərə(n)/",
        "tags": ["🎭 emotion", "🌧️ weather", "⭐ common"],
        "priority": True,
        "grammar": [
            {"label": "Past tense (sg.)", "value": "huiverde"},
            {"label": "Past participle", "value": "gehuiverd"},
            {"label": "Auxiliary", "value": "hebben"},
            {"label": "Present (ik / jij / hij / wij / jullie / zij)", "value": "huiver / huivert / huivert / huiveren / huiveren / huiveren"},
        ],
        "example": {"nl": "Ze huiverde van de kou.", "en": "She shivered from the cold."},
    },
    {
        "id": "nl-loom",
        "word": "loom",
        "translation": "sluggish, languid",
        "type": "adjective",
        "group": "🧀 Curated",
        "pronunciation": "/loːm/",
        "tags": ["🎭 emotion", "🏠 home", "🎭 adjective"],
        "priority": True,
        "grammar": [
            {"label": "Inflected form", "value": "loome"},
            {"label": "Comparative", "value": "lomer"},
            {"label": "Superlative", "value": "loomst"},
        ],
        "example": {"nl": "Na het eten voelde ik me loom.", "en": "After dinner I felt sluggish."},
    },
    {
        "id": "nl-weldra",
        "word": "weldra",
        "translation": "soon, shortly",
        "type": "adverb",
        "group": "🧀 Curated",
        "pronunciation": "/ʋɛlˈdra/",
        "note": "Literary or old-fashioned.",
        "tags": ["🕰️ time", "📚 literary", "🎭 adjective"],
        "priority": True,
        "example": {"nl": "Weldra begon de voorstelling.", "en": "Shortly the performance began."},
    },
    {
        "id": "nl-omtrent",
        "word": "omtrent",
        "translation": "concerning, regarding",
        "type": "preposition",
        "group": "🧀 Curated",
        "pronunciation": "/ɔmˈtrɛnt/",
        "tags": ["💬 communication", "📚 grammar", "📚 literary"],
        "priority": True,
        "grammar": [
            {"label": "Pronominal adverb", "value": "omtrent → daaromtrent"},
            {"label": "Fixed combinations", "value": "informatie omtrent, vragen omtrent"},
        ],
        "example": {"nl": "Ze spraken omtrent de nieuwe regels.", "en": "They spoke regarding the new rules."},
    },
    {
        "id": "nl-ofschoon",
        "word": "ofschoon",
        "translation": "although, though",
        "type": "conjunction",
        "group": "🧀 Curated",
        "pronunciation": "/ɔfˈsxoːn/",
        "note": "Formal or literary.",
        "tags": ["📚 literary", "💬 communication", "📚 grammar"],
        "priority": True,
        "grammar": [
            {"label": "Type", "value": "subordinating"},
            {"label": "Word-order effect", "value": "verb to end of clause (SOV)"},
        ],
        "example": {"nl": "Ofschoon hij moe was, werkte hij verder.", "en": "Although he was tired, he continued working."},
    },
    {
        "id": "nl-eens",
        "word": "eens",
        "translation": "once, just",
        "type": "particle",
        "group": "🧀 Curated",
        "pronunciation": "/eːns/",
        "tags": ["💬 communication", "🇳🇱 dutchness", "⭐ common"],
        "priority": True,
        "grammar": [
            {"label": "Function / meaning nuance", "value": "friendliness, encouragement, surprise"},
            {"label": "Typical usage example", "value": "Kom eens hier. · Luister eens."},
        ],
        "example": {"nl": "Kijk eens aan!", "en": "Well, look at that!"},
    },
    {
        "id": "nl-schaduw",
        "word": "schaduw",
        "translation": "shadow, shade",
        "type": "noun",
        "group": "🧀 Curated",
        "pronunciation": "/ˈsxaːdu/",
        "tags": ["🌌 nature", "⭐ common", "🌞 weather"],
        "priority": True,
        "grammar": [
            {"label": "Article / Gender", "value": "de"},
            {"label": "Plural", "value": "schaduwen"},
            {"label": "Diminutive", "value": "het schaduwtje"},
        ],
        "example": {"nl": "We zaten in de schaduw van een boom.", "en": "We sat in the shade of a tree."},
    },
    {
        "id": "nl-aarzelen",
        "word": "aarzelen",
        "translation": "to hesitate",
        "type": "verb",
        "group": "🧀 Curated",
        "pronunciation": "/ˈaːrzələ(n)/",
        "tags": ["💬 communication", "🎭 emotion", "⭐ common"],
        "priority": True,
        "grammar": [
            {"label": "Past tense (sg.)", "value": "aarzelde"},
            {"label": "Past participle", "value": "geaarzeld"},
            {"label": "Auxiliary", "value": "hebben"},
            {"label": "Present (ik / jij / hij / wij / jullie / zij)", "value": "aarzel / aarzelt / aarzelt / aarzelen / aarzelen / aarzelen"},
        ],
        "example": {"nl": "Ze aarzelde voordat ze antwoord gaf.", "en": "She hesitated before answering."},
    },
    {
        "id": "nl-onstuimig",
        "word": "onstuimig",
        "translation": "turbulent, boisterous",
        "type": "adjective",
        "group": "🧀 Curated",
        "pronunciation": "/ɔnˈstœyməx/",
        "tags": ["🌊 nature", "🎭 adjective", "🌧️ weather"],
        "priority": True,
        "grammar": [
            {"label": "Inflected form", "value": "onstuimige"},
            {"label": "Comparative", "value": "onstuimiger"},
            {"label": "Superlative", "value": "onstuimigst"},
        ],
        "example": {"nl": "De zee was onstuimig die avond.", "en": "The sea was turbulent that evening."},
    },
    {
        "id": "nl-voortaan",
        "word": "voortaan",
        "translation": "from now on",
        "type": "adverb",
        "group": "🧀 Curated",
        "pronunciation": "/ˌvoːrtˈaːn/",
        "tags": ["🕰️ time", "🚆 travel", "⭐ common"],
        "priority": True,
        "example": {"nl": "Voortaan neem ik de trein.", "en": "From now on I'll take the train."},
    },
    {
        "id": "nl-jegens",
        "word": "jegens",
        "translation": "toward, towards",
        "type": "preposition",
        "group": "🧀 Curated",
        "pronunciation": "/ˈjeːɣəns/",
        "tags": ["💬 communication", "📚 literary", "📚 grammar"],
        "priority": True,
        "grammar": [
            {"label": "Pronominal adverb", "value": "jegens → nergens gebruikelijk"},
            {"label": "Fixed combinations", "value": "vijandig jegens, respect jegens"},
        ],
        "example": {"nl": "Hij gedroeg zich vriendelijk jegens iedereen.", "en": "He behaved kindly toward everyone."},
    },
    {
        "id": "nl-doordat",
        "word": "doordat",
        "translation": "because, due to the fact that",
        "type": "conjunction",
        "group": "🧀 Curated",
        "pronunciation": "/ˈdoːrdɑt/",
        "tags": ["🚆 travel", "📚 grammar", "⭐ common"],
        "priority": True,
        "grammar": [
            {"label": "Type", "value": "subordinating"},
            {"label": "Word-order effect", "value": "verb to end of clause (SOV)"},
        ],
        "example": {"nl": "Doordat het sneeuwde, reden de treinen niet.", "en": "Because it snowed, the trains did not run."},
    },
    {
        "id": "nl-wel",
        "word": "wel",
        "translation": "indeed, actually",
        "type": "particle",
        "group": "🧀 Curated",
        "pronunciation": "/ʋɛl/",
        "tags": ["💬 communication", "🇳🇱 dutchness", "⭐ common"],
        "priority": True,
        "grammar": [
            {"label": "Function / meaning nuance", "value": "contradiction, reassurance, emphasis"},
            {"label": "Typical usage example", "value": "Jawel hoor. · Dat zal wel."},
        ],
        "example": {"nl": "Dat weet ik wel.", "en": "I do know that."},
    },
    {
        "id": "nl-vergezicht",
        "word": "vergezicht",
        "translation": "panorama, far-reaching view",
        "type": "noun",
        "group": "🧀 Curated",
        "pronunciation": "/ˈvɛrɣəzɪxt/",
        "tags": ["🌄 nature", "📚 literary", "🌍 travel"],
        "priority": True,
        "grammar": [
            {"label": "Article / Gender", "value": "het"},
            {"label": "Plural", "value": "vergezichten"},
            {"label": "Diminutive", "value": "het vergezichtje"},
        ],
        "example": {"nl": "Vanaf de heuvel hadden we een prachtig vergezicht.", "en": "From the hill we had a beautiful panorama."},
    },
    {
        "id": "nl-grinniken",
        "word": "grinniken",
        "translation": "to giggle, to snicker",
        "type": "verb",
        "group": "🧀 Curated",
        "pronunciation": "/ˈɣrɪnəkə(n)/",
        "tags": ["💬 communication", "🌆 daily", "⭐ common"],
        "priority": True,
        "grammar": [
            {"label": "Past tense (sg.)", "value": "grinnikte"},
            {"label": "Past participle", "value": "gegrinnikt"},
            {"label": "Auxiliary", "value": "hebben"},
            {"label": "Present (ik / jij / hij / wij / jullie / zij)", "value": "grinnik / grinnikt / grinnikt / grinniken / grinniken / grinniken"},
        ],
        "example": {"nl": "De kinderen grinnikten achterin de klas.", "en": "The children giggled at the back of the classroom."},
    },
    {
        "id": "nl-broos",
        "word": "broos",
        "translation": "fragile, delicate",
        "type": "adjective",
        "group": "🧀 Curated",
        "pronunciation": "/broːs/",
        "tags": ["🌌 nature", "🎭 adjective", "⭐ common"],
        "priority": True,
        "grammar": [
            {"label": "Inflected form", "value": "broze"},
            {"label": "Comparative", "value": "brozer"},
            {"label": "Superlative", "value": "broost"},
        ],
        "example": {"nl": "Het ijs was nog te broos om op te lopen.", "en": "The ice was still too fragile to walk on."},
    },
    {
        "id": "nl-ternauwernood",
        "word": "ternauwernood",
        "translation": "barely, by the skin of one's teeth",
        "type": "adverb",
        "group": "🧀 Curated",
        "pronunciation": "/tɛrˌnʌu̯ərˈnoːt/",
        "tags": ["🎭 emotion", "📚 literary", "⭐ common"],
        "priority": True,
        "example": {"nl": "Hij ontsnapte ternauwernood aan het ongeluk.", "en": "He narrowly escaped the accident."},
    },
]

try:
    from nl_de_vocab_data import CARDS as _DE_CARDS
    CARDS = CARDS + _DE_CARDS
except ImportError:
    pass

try:
    from nl_el_vocab_data import CARDS as _EL_CARDS
    CARDS = CARDS + _EL_CARDS
except ImportError:
    pass
