"""
fr_de_vocab_data.py — French vocabulary cards for German speakers (departure_lang='de').

Mirrors fr_vocab_data.py — same 50 words, translations and notes in German.
Imported automatically by fr_vocab_data.py and appended to CARDS.
"""

CARDS = [
    {
        "id": "fr-de-flaner",
        "word": "flâner",
        "translation": "schlendern, bummeln",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/flɑ.ne/",
        "etymology": 'Aus dem Altnordischen „flana" (umhereilen).',
        "note": "Vermittelt eine poetische, gemächliche Stimmung — das Gegenteil von Eile.",
        "tags": ["⭐ common", "🔤 verb", "🚶 daily"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "flâné"},
            {"label": "Présent (all 6 forms)", "value": "flâne / flânes / flâne / flânons / flânez / flânent"},
        ],
        "example": {
            "fr": "Le dimanche, elle aime flâner dans les rues du vieux quartier.",
            "de": "Sonntags schlendert sie gerne durch die Gassen des alten Viertels.",
        },
    },
    {
        "id": "fr-de-pourtant",
        "word": "pourtant",
        "translation": "jedoch, dennoch, trotzdem",
        "type": "adverb",
        "group": "🥖 Curated",
        "pronunciation": "/puʁ.tɑ̃/",
        "etymology": 'Aus „pour tant" (für so viel).',
        "note": "Häufiges Verbindungswort in Sprache und Schrift — entspricht etwa dem deutschen 'und doch'.",
        "tags": ["⭐ common", "📘 connector", "🚶 daily"],
        "priority": True,
        "departure_lang": "de",
        "example": {
            "fr": "Il était fatigué, pourtant il a continué à travailler.",
            "de": "Er war müde, und doch arbeitete er weiter.",
        },
    },
    {
        "id": "fr-de-luciole",
        "word": "luciole",
        "translation": "Glühwürmchen",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/ly.sjɔl/",
        "note": "Ein sehr poetisches und literarisches Wort.",
        "tags": ["✨ nature", "📚 noun"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "lucioles"},
        ],
        "example": {
            "fr": "Les lucioles brillaient au bord du lac.",
            "de": "Die Glühwürmchen leuchteten am Ufer des Sees.",
        },
    },
    {
        "id": "fr-de-apprivoiser",
        "word": "apprivoiser",
        "translation": "zähmen, vertraut machen",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/a.pʁi.vwa.ze/",
        "etymology": 'Verwandt mit „privé" und lateinisch „privatus".',
        "note": 'Bekannt aus „Der kleine Prinz" — Le Petit Prince.',
        "tags": ["📚 literature", "🔤 verb", "🐾 animals"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "apprivoisé"},
            {"label": "Présent (all 6 forms)", "value": "apprivoise / apprivoises / apprivoise / apprivoisons / apprivoisez / apprivoisent"},
        ],
        "example": {
            "fr": "Il faut du temps pour apprivoiser un chat méfiant.",
            "de": "Es braucht Zeit, eine scheue Katze zu zähmen.",
        },
    },
    {
        "id": "fr-de-bouleverse",
        "word": "bouleversé",
        "translation": "erschüttert, tief bewegt, überwältigt",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/bul.vɛʁ.se/",
        "note": 'Starkes Gefühlsadjektiv — mehr als nur "betroffen".',
        "tags": ["💭 emotions", "🎨 adjective"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Feminine form", "value": "bouleversée"},
            {"label": "Plural (masc.)", "value": "bouleversés"},
            {"label": "Plural (fem.)", "value": "bouleversées"},
        ],
        "example": {
            "fr": "Elle semblait bouleversée après la nouvelle.",
            "de": "Sie wirkte tief erschüttert nach der Nachricht.",
        },
    },
    {
        "id": "fr-de-bidule",
        "word": "bidule",
        "translation": "Dingsbums, Ding da",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/bi.dyl/",
        "note": "Umgangssprachlich und verspielt — wenn man das richtige Wort nicht kennt oder nicht findet.",
        "tags": ["😂 informal", "📚 noun", "🏠 home"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "bidules"},
        ],
        "example": {
            "fr": "Passe-moi le bidule sur la table.",
            "de": "Reich mir mal das Dingsbums auf dem Tisch.",
        },
    },
    {
        "id": "fr-de-avoir-le-cafard",
        "word": "avoir le cafard",
        "translation": "niedergeschlagen sein, deprimiert sein",
        "type": "phrase",
        "group": "🥖 Curated",
        "pronunciation": "/a.vwaʁ lə ka.faʁ/",
        "note": 'Wörtlich: „die Kakerlake haben" — ein bildhafter Ausdruck für Schwermut.',
        "tags": ["💭 emotions", "🗣️ phrase", "🚶 daily"],
        "priority": True,
        "departure_lang": "de",
        "example": {
            "fr": "Depuis l'hiver, il a souvent le cafard.",
            "de": "Seit dem Winter ist er oft niedergeschlagen.",
        },
    },
    {
        "id": "fr-de-eblouissant",
        "word": "éblouissant",
        "translation": "blendend, strahlend, atemberaubend",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/e.blu.i.sɑ̃/",
        "note": "Kann Licht, Schönheit oder Talent beschreiben.",
        "tags": ["✨ descriptive", "🎨 adjective"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Feminine form", "value": "éblouissante"},
            {"label": "Plural (masc.)", "value": "éblouissants"},
            {"label": "Plural (fem.)", "value": "éblouissantes"},
        ],
        "example": {
            "fr": "Le coucher du soleil était éblouissant.",
            "de": "Der Sonnenuntergang war einfach atemberaubend.",
        },
    },
    {
        "id": "fr-de-fouiller",
        "word": "fouiller",
        "translation": "durchsuchen, durchwühlen",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/fu.je/",
        "note": "Wird auch für Polizeidurchsuchungen verwendet.",
        "tags": ["🔤 verb", "🚶 daily"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "fouillé"},
            {"label": "Présent (all 6 forms)", "value": "fouille / fouilles / fouille / fouillons / fouillez / fouillent"},
        ],
        "example": {
            "fr": "Elle a fouillé son sac pendant plusieurs minutes.",
            "de": "Sie durchwühlte mehrere Minuten lang ihre Tasche.",
        },
    },
    {
        "id": "fr-de-chouette",
        "word": "chouette",
        "translation": "toll, prima, klasse",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/ʃwɛt/",
        "note": 'Umgangssprachliches Lob; bedeutet als Substantiv auch „Eule".',
        "tags": ["⭐ common", "🎨 adjective", "😂 informal"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Feminine form", "value": "chouette"},
            {"label": "Plural (masc.)", "value": "chouettes"},
            {"label": "Plural (fem.)", "value": "chouettes"},
        ],
        "example": {
            "fr": "C'est une idée vraiment chouette.",
            "de": "Das ist wirklich eine tolle Idee.",
        },
    },
    {
        "id": "fr-de-grenier",
        "word": "grenier",
        "translation": "Dachboden, Speicher",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/gʁə.nje/",
        "tags": ["🏠 home", "📚 noun"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "greniers"},
        ],
        "example": {
            "fr": "Ils ont trouvé de vieux albums dans le grenier.",
            "de": "Sie fanden alte Fotoalben auf dem Dachboden.",
        },
    },
    {
        "id": "fr-de-epanouir",
        "word": "s'épanouir",
        "translation": "aufblühen, sich entfalten",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/se.pa.nwiʁ/",
        "note": "Oft im emotionalen oder persönlichen Sinne verwendet.",
        "tags": ["💭 emotions", "🔤 verb"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Verb group", "value": "3e"},
            {"label": "Auxiliary", "value": "être"},
            {"label": "Past participle", "value": "épanoui"},
            {"label": "Présent (all 6 forms)", "value": "m'épanouis / t'épanouis / s'épanouit / nous épanouissons / vous épanouissez / s'épanouissent"},
        ],
        "example": {
            "fr": "Elle s'épanouit dans son nouveau travail.",
            "de": "Sie blüht richtig auf in ihrer neuen Stelle.",
        },
    },
    {
        "id": "fr-de-frisson",
        "word": "frisson",
        "translation": "Schauer, Kribbeln, Schauder",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/fʁi.sɔ̃/",
        "tags": ["💭 emotions", "📚 noun"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "frissons"},
        ],
        "example": {
            "fr": "Un frisson lui a traversé le dos.",
            "de": "Ein Schauer lief ihm den Rücken hinunter.",
        },
    },
    {
        "id": "fr-de-tant-pis",
        "word": "tant pis",
        "translation": "schade, macht nichts, egal",
        "type": "phrase",
        "group": "🥖 Curated",
        "pronunciation": "/tɑ̃ pi/",
        "note": "Äußerst geläufige Konversationsphrase — resigniert, aber gelassen.",
        "tags": ["⭐ common", "🗣️ phrase", "🚶 daily"],
        "priority": True,
        "departure_lang": "de",
        "example": {
            "fr": "Il pleut ? Tant pis, on sort quand même.",
            "de": "Es regnet? Schade, wir gehen trotzdem raus.",
        },
    },
    {
        "id": "fr-de-malin",
        "word": "malin",
        "translation": "schlau, gerissen, durchtrieben",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/ma.lɛ̃/",
        "note": "Je nach Kontext bewundernd oder misstrauisch gemeint.",
        "tags": ["🎨 adjective", "🚶 daily"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Feminine form", "value": "maligne"},
            {"label": "Plural (masc.)", "value": "malins"},
            {"label": "Plural (fem.)", "value": "malignes"},
        ],
        "example": {
            "fr": "Ce renard est très malin.",
            "de": "Dieser Fuchs ist sehr schlau.",
        },
    },
    {
        "id": "fr-de-brouhaha",
        "word": "brouhaha",
        "translation": "Lärm, Stimmengewirr, Tumult",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/bʁu.a.a/",
        "note": "Onomatopoetisches Wort — klingt wie das, was es beschreibt.",
        "tags": ["🔊 sound", "📚 noun"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "brouhahas"},
        ],
        "example": {
            "fr": "Un brouhaha remplissait le café.",
            "de": "Ein Stimmengewirr füllte das Café.",
        },
    },
    {
        "id": "fr-de-raler",
        "word": "râler",
        "translation": "meckern, maulen, schimpfen",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/ʁa.le/",
        "note": "Sehr umgangssprachlich und typisch französisch.",
        "tags": ["😂 informal", "🔤 verb", "🚶 daily"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "râlé"},
            {"label": "Présent (all 6 forms)", "value": "râle / râles / râle / râlons / râlez / râlent"},
        ],
        "example": {
            "fr": "Il râle toujours dans les embouteillages.",
            "de": "Er meckert immer im Stau.",
        },
    },
    {
        "id": "fr-de-velours",
        "word": "velours",
        "translation": "Samt",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/və.luʁ/",
        "tags": ["✨ texture", "📚 noun"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "velours"},
        ],
        "example": {
            "fr": "Le fauteuil en velours était incroyablement doux.",
            "de": "Der Samtsessel war unglaublich weich.",
        },
    },
    {
        "id": "fr-de-debrouillard",
        "word": "débrouillard",
        "translation": "einfallsreich, findig, clever",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/de.bʁu.jaʁ/",
        "tags": ["🎨 adjective", "🚶 daily"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Feminine form", "value": "débrouillarde"},
            {"label": "Plural (masc.)", "value": "débrouillards"},
            {"label": "Plural (fem.)", "value": "débrouillardes"},
        ],
        "example": {
            "fr": "Elle est très débrouillarde pour résoudre les problèmes.",
            "de": "Sie ist sehr einfallsreich, wenn es darum geht, Probleme zu lösen.",
        },
    },
    {
        "id": "fr-de-avoir-beau",
        "word": "avoir beau",
        "translation": "etw. vergebens tun",
        "type": "phrase",
        "group": "🥖 Curated",
        "pronunciation": "/a.vwaʁ bo/",
        "note": "Steht vor einem Infinitiv — z.B. 'J\\'ai beau essayer' bedeutet: Wie sehr ich es auch versuche.",
        "tags": ["🗣️ phrase", "📘 grammar"],
        "priority": True,
        "departure_lang": "de",
        "example": {
            "fr": "J'ai beau essayer, je n'y arrive pas.",
            "de": "Wie sehr ich es auch versuche — ich schaffe es einfach nicht.",
        },
    },
    {
        "id": "fr-de-papoter",
        "word": "papoter",
        "translation": "plaudern, klönen, quatschen",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/pa.pɔ.te/",
        "note": "Klingt schon beim Aussprechen locker und freundlich.",
        "tags": ["🗣️ social", "🔤 verb"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "papoté"},
            {"label": "Présent (all 6 forms)", "value": "papote / papotes / papote / papotons / papotez / papotent"},
        ],
        "example": {
            "fr": "Elles ont papoté pendant des heures.",
            "de": "Sie haben stundenlang geplaudert.",
        },
    },
    {
        "id": "fr-de-poussiere",
        "word": "poussière",
        "translation": "Staub",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/pu.sjɛʁ/",
        "tags": ["🏠 home", "📚 noun"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "poussières"},
        ],
        "example": {
            "fr": "La poussière dansait dans la lumière.",
            "de": "Der Staub tanzte im Licht.",
        },
    },
    {
        "id": "fr-de-egare",
        "word": "égaré",
        "translation": "verloren, verirrt",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/e.ɡa.ʁe/",
        "tags": ["🚶 daily", "🎨 adjective"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Feminine form", "value": "égarée"},
            {"label": "Plural (masc.)", "value": "égarés"},
            {"label": "Plural (fem.)", "value": "égarées"},
        ],
        "example": {
            "fr": "Un chien égaré attendait devant la gare.",
            "de": "Ein verirrter Hund wartete vor dem Bahnhof.",
        },
    },
    {
        "id": "fr-de-renverser",
        "word": "renverser",
        "translation": "umwerfen, umstürzen, verschütten",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/ʁɑ̃.vɛʁ.se/",
        "tags": ["🔤 verb", "🚶 daily"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "renversé"},
            {"label": "Présent (all 6 forms)", "value": "renverse / renverses / renverse / renversons / renversez / renversent"},
        ],
        "example": {
            "fr": "Il a renversé son café sur le clavier.",
            "de": "Er hat seinen Kaffee auf die Tastatur geschüttet.",
        },
    },
    {
        "id": "fr-de-fou-rire",
        "word": "fou rire",
        "translation": "Lachanfall",
        "type": "phrase",
        "group": "🥖 Curated",
        "pronunciation": "/fu ʁiʁ/",
        "tags": ["😂 humor", "🗣️ phrase"],
        "priority": True,
        "departure_lang": "de",
        "example": {
            "fr": "Ils ont eu un fou rire au milieu du cours.",
            "de": "Sie bekamen mitten im Unterricht einen Lachanfall.",
        },
    },
    {
        "id": "fr-de-murmure",
        "word": "murmure",
        "translation": "Flüstern, Raunen, Murmeln",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/myʁ.myʁ/",
        "tags": ["🔊 sound", "📚 noun"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "murmures"},
        ],
        "example": {
            "fr": "Un murmure parcourait la foule.",
            "de": "Ein Raunen ging durch die Menge.",
        },
    },
    {
        "id": "fr-de-epanoui",
        "word": "épanoui",
        "translation": "aufgeblüht, erfüllt",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/e.pa.nwi/",
        "tags": ["💭 emotions", "🎨 adjective"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Feminine form", "value": "épanouie"},
            {"label": "Plural (masc.)", "value": "épanouis"},
            {"label": "Plural (fem.)", "value": "épanouies"},
        ],
        "example": {
            "fr": "Il semble plus épanoui depuis son déménagement.",
            "de": "Er wirkt seit seinem Umzug viel erfüllter.",
        },
    },
    {
        "id": "fr-de-bidonner",
        "word": "bidonner",
        "translation": "fälschen, vortäuschen, faken",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/bi.dɔ.ne/",
        "note": "Umgangssprachliche Verwendung.",
        "tags": ["😂 informal", "🔤 verb"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "bidonné"},
            {"label": "Présent (all 6 forms)", "value": "bidonne / bidonnes / bidonne / bidonnons / bidonnez / bidonnent"},
        ],
        "example": {
            "fr": "Certains ont bidonné les résultats.",
            "de": "Manche haben die Ergebnisse gefälscht.",
        },
    },
    {
        "id": "fr-de-etincelle",
        "word": "étincelle",
        "translation": "Funke",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/e.tɛ̃.sɛl/",
        "tags": ["✨ nature", "📚 noun"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "étincelles"},
        ],
        "example": {
            "fr": "Une étincelle a jailli du feu.",
            "de": "Ein Funke sprang aus dem Feuer.",
        },
    },
    {
        "id": "fr-de-zut",
        "word": "zut",
        "translation": "Mist!, Mist!, Ach du Mist!",
        "type": "phrase",
        "group": "🥖 Curated",
        "pronunciation": "/zyt/",
        "note": 'Milde Ausrufe — ungefähr wie "Mist!" oder "Verdammt!".',
        "tags": ["😂 informal", "🗣️ phrase"],
        "priority": True,
        "departure_lang": "de",
        "example": {
            "fr": "Zut, j'ai oublié mes clés.",
            "de": "Mist, ich habe meine Schlüssel vergessen.",
        },
    },
    {
        "id": "fr-de-savoureux",
        "word": "savoureux",
        "translation": "köstlich, lecker, geschmackvoll",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/sa.vu.ʁø/",
        "tags": ["🍕 food", "🎨 adjective"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Feminine form", "value": "savoureuse"},
            {"label": "Plural (masc.)", "value": "savoureux"},
            {"label": "Plural (fem.)", "value": "savoureuses"},
        ],
        "example": {
            "fr": "Ce plat est particulièrement savoureux.",
            "de": "Dieses Gericht ist besonders köstlich.",
        },
    },
    {
        "id": "fr-de-grignoter",
        "word": "grignoter",
        "translation": "knabbern, naschen, snacken",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/gʁi.ɲɔ.te/",
        "tags": ["🍕 food", "🔤 verb"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "grignoté"},
            {"label": "Présent (all 6 forms)", "value": "grignote / grignotes / grignote / grignotons / grignotez / grignotent"},
        ],
        "example": {
            "fr": "Il aime grignoter devant les films.",
            "de": "Er knabbert gerne beim Fernsehen.",
        },
    },
    {
        "id": "fr-de-brume",
        "word": "brume",
        "translation": "Nebel, Dunst",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/bʁym/",
        "tags": ["🌦️ weather", "📚 noun"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "brumes"},
        ],
        "example": {
            "fr": "La brume recouvrait les collines au matin.",
            "de": "Morgendlicher Dunst lag über den Hügeln.",
        },
    },
    {
        "id": "fr-de-dingue",
        "word": "dingue",
        "translation": "verrückt, wahnsinnig, durchgeknallt",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/dɛ̃ɡ/",
        "tags": ["😂 informal", "🎨 adjective"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Feminine form", "value": "dingue"},
            {"label": "Plural (masc.)", "value": "dingues"},
            {"label": "Plural (fem.)", "value": "dingues"},
        ],
        "example": {
            "fr": "Cette histoire est complètement dingue.",
            "de": "Diese Geschichte ist völlig verrückt.",
        },
    },
    {
        "id": "fr-de-trainer",
        "word": "traîner",
        "translation": "herumlungern, schleppen, trödeln",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/tʁɛ.ne/",
        "tags": ["🚶 daily", "🔤 verb"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "traîné"},
            {"label": "Présent (all 6 forms)", "value": "traîne / traînes / traîne / traînons / traînez / traînent"},
        ],
        "example": {
            "fr": "Ils traînaient au parc après les cours.",
            "de": "Sie lungerten nach dem Unterricht im Park herum.",
        },
    },
    {
        "id": "fr-de-ricochet",
        "word": "ricochet",
        "translation": "Abpraller, Steinspringen",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/ʁi.kɔ.ʃɛ/",
        "tags": ["🌊 nature", "📚 noun"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "ricochets"},
        ],
        "example": {
            "fr": "La pierre a fait plusieurs ricochets sur l'eau.",
            "de": "Der Stein prallte mehrmals über das Wasser.",
        },
    },
    {
        "id": "fr-de-a-peine",
        "word": "à peine",
        "translation": "kaum, knapp, gerade so",
        "type": "phrase",
        "group": "🥖 Curated",
        "pronunciation": "/a pɛn/",
        "tags": ["⭐ common", "🗣️ phrase"],
        "priority": True,
        "departure_lang": "de",
        "example": {
            "fr": "J'ai à peine dormi cette nuit.",
            "de": "Ich habe heute Nacht kaum geschlafen.",
        },
    },
    {
        "id": "fr-de-chaleureux",
        "word": "chaleureux",
        "translation": "herzlich, warmherzig",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/ʃa.lœ.ʁø/",
        "tags": ["🗣️ social", "🎨 adjective"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Feminine form", "value": "chaleureuse"},
            {"label": "Plural (masc.)", "value": "chaleureux"},
            {"label": "Plural (fem.)", "value": "chaleureuses"},
        ],
        "example": {
            "fr": "Ils nous ont réservé un accueil chaleureux.",
            "de": "Sie haben uns sehr herzlich empfangen.",
        },
    },
    {
        "id": "fr-de-bouquiner",
        "word": "bouquiner",
        "translation": "schmökern, lesen (gemütlich)",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/bu.ki.ne/",
        "note": "Klingt gemütlich und entspannt — kein pflichtbewusstes Lesen.",
        "tags": ["📚 literature", "🔤 verb"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "bouquiné"},
            {"label": "Présent (all 6 forms)", "value": "bouquine / bouquines / bouquine / bouquinons / bouquinez / bouquinent"},
        ],
        "example": {
            "fr": "Elle bouquine dans le train chaque matin.",
            "de": "Sie schmökert jeden Morgen im Zug.",
        },
    },
    {
        "id": "fr-de-brindille",
        "word": "brindille",
        "translation": "Zweig, Ästchen",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/bʁɛ̃.dij/",
        "tags": ["🌿 nature", "📚 noun"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "brindilles"},
        ],
        "example": {
            "fr": "L'oiseau portait une brindille dans son bec.",
            "de": "Der Vogel trug ein Ästchen im Schnabel.",
        },
    },
    {
        "id": "fr-de-gene",
        "word": "gêné",
        "translation": "verlegen, peinlich berührt",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/ʒe.ne/",
        "tags": ["💭 emotions", "🎨 adjective"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Feminine form", "value": "gênée"},
            {"label": "Plural (masc.)", "value": "gênés"},
            {"label": "Plural (fem.)", "value": "gênées"},
        ],
        "example": {
            "fr": "Il avait l'air gêné après sa remarque.",
            "de": "Er wirkte nach seiner Bemerkung verlegen.",
        },
    },
    {
        "id": "fr-de-chipoter",
        "word": "chipoter",
        "translation": "herumnörgeln, kleinlich sein, pingelig sein",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/ʃi.pɔ.te/",
        "tags": ["😂 informal", "🔤 verb"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "chipoté"},
            {"label": "Présent (all 6 forms)", "value": "chipote / chipotes / chipote / chipotons / chipotez / chipotent"},
        ],
        "example": {
            "fr": "Arrête de chipoter pour des détails.",
            "de": "Hör auf, wegen Kleinigkeiten zu nörgeln.",
        },
    },
    {
        "id": "fr-de-refuge",
        "word": "refuge",
        "translation": "Zuflucht, Zufluchtsort",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/ʁə.fyʒ/",
        "tags": ["🏠 home", "📚 noun"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "refuges"},
        ],
        "example": {
            "fr": "Cette bibliothèque était son refuge préféré.",
            "de": "Diese Bibliothek war sein liebster Zufluchtsort.",
        },
    },
    {
        "id": "fr-de-tomber-dans-les-pommes",
        "word": "tomber dans les pommes",
        "translation": "ohnmächtig werden, in Ohnmacht fallen",
        "type": "phrase",
        "group": "🥖 Curated",
        "pronunciation": "/tɔ̃.be dɑ̃ le pɔm/",
        "note": 'Wörtlich: „in die Äpfel fallen" — ein rein idiomatischer Ausdruck.',
        "tags": ["😂 idiom", "🗣️ phrase"],
        "priority": True,
        "departure_lang": "de",
        "example": {
            "fr": "Il est tombé dans les pommes pendant le concert.",
            "de": "Er wurde beim Konzert ohnmächtig.",
        },
    },
    {
        "id": "fr-de-ebouriffe",
        "word": "ébouriffé",
        "translation": "zerzaust, ungekämmt",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/e.bu.ʁi.fe/",
        "tags": ["👕 appearance", "🎨 adjective"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Feminine form", "value": "ébouriffée"},
            {"label": "Plural (masc.)", "value": "ébouriffés"},
            {"label": "Plural (fem.)", "value": "ébouriffées"},
        ],
        "example": {
            "fr": "Il est arrivé complètement ébouriffé.",
            "de": "Er kam völlig zerzaust an.",
        },
    },
    {
        "id": "fr-de-bidonville",
        "word": "bidonville",
        "translation": "Slum, Elendsviertel",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/bi.dɔ̃.vil/",
        "etymology": 'Von „bidon" (Kanister) und „ville" (Stadt).',
        "tags": ["🌍 society", "📚 noun"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "bidonvilles"},
        ],
        "example": {
            "fr": "Des familles vivent encore dans ce bidonville.",
            "de": "Familien leben noch immer in diesem Elendsviertel.",
        },
    },
    {
        "id": "fr-de-fredonner",
        "word": "fredonner",
        "translation": "summen, trällern",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/fʁə.dɔ.ne/",
        "tags": ["🎵 music", "🔤 verb"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "fredonné"},
            {"label": "Présent (all 6 forms)", "value": "fredonne / fredonnes / fredonne / fredonnons / fredonnez / fredonnent"},
        ],
        "example": {
            "fr": "Elle fredonnait une vieille chanson en cuisinant.",
            "de": "Sie summte beim Kochen ein altes Lied.",
        },
    },
    {
        "id": "fr-de-veloute",
        "word": "velouté",
        "translation": "samtig; Cremesuppe",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/və.lu.te/",
        "note": "Als Adjektiv: samtig weich. Als Substantiv: sämige Cremesuppe.",
        "tags": ["🍕 food", "📚 noun"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "veloutés"},
        ],
        "example": {
            "fr": "Ce velouté de champignons est délicieux.",
            "de": "Diese Champignoncremesuppe ist köstlich.",
        },
    },
    {
        "id": "fr-de-farfelu",
        "word": "farfelu",
        "translation": "verschroben, skurril, schräg",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/faʁ.fə.ly/",
        "tags": ["😂 humor", "🎨 adjective"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Feminine form", "value": "farfelue"},
            {"label": "Plural (masc.)", "value": "farfelus"},
            {"label": "Plural (fem.)", "value": "farfelues"},
        ],
        "example": {
            "fr": "Il propose toujours des idées farfelues.",
            "de": "Er schlägt immer skurrile Ideen vor.",
        },
    },
    {
        "id": "fr-de-se-debrouiller",
        "word": "se débrouiller",
        "translation": "sich durchschlagen, zurechtkommen",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/sə de.bʁu.je/",
        "tags": ["🚶 daily", "🔤 verb"],
        "priority": True,
        "departure_lang": "de",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "être"},
            {"label": "Past participle", "value": "débrouillé"},
            {"label": "Présent (all 6 forms)", "value": "me débrouille / te débrouilles / se débrouille / nous débrouillons / vous débrouillez / se débrouillent"},
        ],
        "example": {
            "fr": "Même sans carte, elle s'est débrouillée.",
            "de": "Sogar ohne Karte hat sie sich durchgeschlagen.",
        },
    },
]
