"""
fr_el_vocab_data.py — French vocabulary cards for Greek speakers (departure_lang='el').
Mirrors fr_vocab_data.py — same 50 words, translations and notes in Greek.
Imported automatically by fr_vocab_data.py and appended to CARDS.
"""

CARDS = [
    {
        "id": "fr-el-flaner",
        "word": "flâner",
        "translation": "να περιφέρομαι, να αργοπεριπατώ",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/flɑ.ne/",
        "etymology": 'Από το παλαιονορβηγικό "flana" (τρέχω εδώ κι εκεί).',
        "note": "Συχνά έχει ποιητικό ή ανέμελο χαρακτήρα — το αντίθετο της βιασύνης.",
        "tags": ["⭐ common", "🔤 verb", "🚶 daily"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "flâné"},
            {"label": "Présent (all 6 forms)", "value": "flâne / flânes / flâne / flânons / flânez / flânent"},
        ],
        "example": {
            "fr": "Le dimanche, elle aime flâner dans les rues du vieux quartier.",
            "el": "Τις Κυριακές, της αρέσει να αργοπεριπατά στους δρόμους της παλιάς συνοικίας.",
        },
    },
    {
        "id": "fr-el-pourtant",
        "word": "pourtant",
        "translation": "ωστόσο, παρ' όλα αυτά, εν τούτοις",
        "type": "adverb",
        "group": "🥖 Curated",
        "pronunciation": "/puʁ.tɑ̃/",
        "etymology": 'Από το "pour tant" (για τόσο πολύ).',
        "note": "Συχνός σύνδεσμος τόσο στον προφορικό όσο και στον γραπτό λόγο.",
        "tags": ["⭐ common", "📘 connector", "🚶 daily"],
        "priority": True,
        "departure_lang": "el",
        "example": {
            "fr": "Il était fatigué, pourtant il a continué à travailler.",
            "el": "Ήταν κουρασμένος, ωστόσο συνέχισε να εργάζεται.",
        },
    },
    {
        "id": "fr-el-luciole",
        "word": "luciole",
        "translation": "πυγολαμπίδα",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/ly.sjɔl/",
        "note": "Πολύ ποιητική και λογοτεχνική λέξη.",
        "tags": ["✨ nature", "📚 noun"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "lucioles"},
        ],
        "example": {
            "fr": "Les lucioles brillaient au bord du lac.",
            "el": "Οι πυγολαμπίδες άστραφταν στην άκρη της λίμνης.",
        },
    },
    {
        "id": "fr-el-apprivoiser",
        "word": "apprivoiser",
        "translation": "να εξημερώσω, να κάνω φίλο",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/a.pʁi.vwa.ze/",
        "etymology": 'Σχετίζεται με το "privé" και το λατινικό "privatus".',
        "note": 'Γνωστό από τον "Μικρό Πρίγκιπα".',
        "tags": ["📚 literature", "🔤 verb", "🐾 animals"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "apprivoisé"},
            {"label": "Présent (all 6 forms)", "value": "apprivoise / apprivoises / apprivoise / apprivoisons / apprivoisez / apprivoisent"},
        ],
        "example": {
            "fr": "Il faut du temps pour apprivoiser un chat méfiant.",
            "el": "Χρειάζεται χρόνος για να εξημερώσεις μια καχύποπτη γάτα.",
        },
    },
    {
        "id": "fr-el-bouleverse",
        "word": "bouleversé",
        "translation": "συγκλονισμένος, συντετριμμένος, βαθιά συγκινημένος",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/bul.vɛʁ.se/",
        "note": "Ισχυρό συναισθηματικό επίθετο — περισσότερο από απλή στεναχώρια.",
        "tags": ["💭 emotions", "🎨 adjective"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Feminine form", "value": "bouleversée"},
            {"label": "Plural (masc.)", "value": "bouleversés"},
            {"label": "Plural (fem.)", "value": "bouleversées"},
        ],
        "example": {
            "fr": "Elle semblait bouleversée après la nouvelle.",
            "el": "Φαινόταν συγκλονισμένη μετά τα νέα.",
        },
    },
    {
        "id": "fr-el-bidule",
        "word": "bidule",
        "translation": "πράγμα, αντικείμενο (όταν δεν ξέρεις το όνομα)",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/bi.dyl/",
        "note": "Ανεπίσημη και παιχνιδιάρικη λέξη-αντικατάστατο για οτιδήποτε.",
        "tags": ["😂 informal", "📚 noun", "🏠 home"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "bidules"},
        ],
        "example": {
            "fr": "Passe-moi le bidule sur la table.",
            "el": "Δώσε μου αυτό το πράγμα που είναι στο τραπέζι.",
        },
    },
    {
        "id": "fr-el-avoir-le-cafard",
        "word": "avoir le cafard",
        "translation": "να νιώθω μελαγχολία, να είμαι καταθλιπτικός",
        "type": "phrase",
        "group": "🥖 Curated",
        "pronunciation": "/a.vwaʁ lə ka.faʁ/",
        "note": 'Κυριολεκτικά σημαίνει "έχω την κατσαρίδα" — εικονιστική έκφραση για βαριά διάθεση.',
        "tags": ["💭 emotions", "🗣️ phrase", "🚶 daily"],
        "priority": True,
        "departure_lang": "el",
        "example": {
            "fr": "Depuis l'hiver, il a souvent le cafard.",
            "el": "Από τον χειμώνα, είναι συχνά μελαγχολικός.",
        },
    },
    {
        "id": "fr-el-eblouissant",
        "word": "éblouissant",
        "translation": "εκθαμβωτικός, λαμπερός, εντυπωσιακός",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/e.blu.i.sɑ̃/",
        "note": "Μπορεί να περιγράψει φως, ομορφιά ή ταλέντο.",
        "tags": ["✨ descriptive", "🎨 adjective"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Feminine form", "value": "éblouissante"},
            {"label": "Plural (masc.)", "value": "éblouissants"},
            {"label": "Plural (fem.)", "value": "éblouissantes"},
        ],
        "example": {
            "fr": "Le coucher du soleil était éblouissant.",
            "el": "Το ηλιοβασίλεμα ήταν εκθαμβωτικό.",
        },
    },
    {
        "id": "fr-el-fouiller",
        "word": "fouiller",
        "translation": "να ψάχνω, να ανακατεύω, να κάνω έρευνα",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/fu.je/",
        "note": "Χρησιμοποιείται και για αστυνομικές έρευνες.",
        "tags": ["🔤 verb", "🚶 daily"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "fouillé"},
            {"label": "Présent (all 6 forms)", "value": "fouille / fouilles / fouille / fouillons / fouillez / fouillent"},
        ],
        "example": {
            "fr": "Elle a fouillé son sac pendant plusieurs minutes.",
            "el": "Έψαχνε στην τσάντα της για αρκετά λεπτά.",
        },
    },
    {
        "id": "fr-el-chouette",
        "word": "chouette",
        "translation": "γλαύκα· ωραίος, τέλειος (ανεπίσημο)",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/ʃwɛt/",
        "note": 'Ανεπίσημο θετικό επίθετο· ως ουσιαστικό σημαίνει επίσης "κουκουβάγια".',
        "tags": ["⭐ common", "🎨 adjective", "😂 informal"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Feminine form", "value": "chouette"},
            {"label": "Plural (masc.)", "value": "chouettes"},
            {"label": "Plural (fem.)", "value": "chouettes"},
        ],
        "example": {
            "fr": "C'est une idée vraiment chouette.",
            "el": "Αυτή είναι μια πραγματικά ωραία ιδέα.",
        },
    },
    {
        "id": "fr-el-grenier",
        "word": "grenier",
        "translation": "σοφίτα, αποθήκη σκεπής",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/gʁə.nje/",
        "tags": ["🏠 home", "📚 noun"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "greniers"},
        ],
        "example": {
            "fr": "Ils ont trouvé de vieux albums dans le grenier.",
            "el": "Βρήκαν παλιά φωτογραφικά άλμπουμ στη σοφίτα.",
        },
    },
    {
        "id": "fr-el-epanouir",
        "word": "s'épanouir",
        "translation": "να ανθίζω, να αναπτύσσομαι, να ευδοκιμώ",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/se.pa.nwiʁ/",
        "note": "Συχνά χρησιμοποιείται με συναισθηματική ή προσωπική έννοια.",
        "tags": ["💭 emotions", "🔤 verb"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "3e"},
            {"label": "Auxiliary", "value": "être"},
            {"label": "Past participle", "value": "épanoui"},
            {"label": "Présent (all 6 forms)", "value": "m'épanouis / t'épanouis / s'épanouit / nous épanouissons / vous épanouissez / s'épanouissent"},
        ],
        "example": {
            "fr": "Elle s'épanouit dans son nouveau travail.",
            "el": "Ανθίζει στη νέα της δουλειά.",
        },
    },
    {
        "id": "fr-el-frisson",
        "word": "frisson",
        "translation": "ρίγος, φρίκη, αναλαμπή συγκίνησης",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/fʁi.sɔ̃/",
        "tags": ["💭 emotions", "📚 noun"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "frissons"},
        ],
        "example": {
            "fr": "Un frisson lui a traversé le dos.",
            "el": "Ένα ρίγος του διαπέρασε τη ράχη.",
        },
    },
    {
        "id": "fr-el-tant-pis",
        "word": "tant pis",
        "translation": "τόσο το χειρότερο, δεν πειράζει, αδιάφορο",
        "type": "phrase",
        "group": "🥖 Curated",
        "pronunciation": "/tɑ̃ pi/",
        "note": "Εξαιρετικά συνηθισμένη συνομιλιακή έκφραση — παραιτητική αλλά ήρεμη.",
        "tags": ["⭐ common", "🗣️ phrase", "🚶 daily"],
        "priority": True,
        "departure_lang": "el",
        "example": {
            "fr": "Il pleut ? Tant pis, on sort quand même.",
            "el": "Βρέχει; Δεν πειράζει, βγαίνουμε έτσι κι αλλιώς.",
        },
    },
    {
        "id": "fr-el-malin",
        "word": "malin",
        "translation": "έξυπνος, πονηρός, πανούργος",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/ma.lɛ̃/",
        "note": "Ανάλογα με το πλαίσιο, μπορεί να εκφράζει θαυμασμό ή καχυποψία.",
        "tags": ["🎨 adjective", "🚶 daily"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Feminine form", "value": "maligne"},
            {"label": "Plural (masc.)", "value": "malins"},
            {"label": "Plural (fem.)", "value": "malignes"},
        ],
        "example": {
            "fr": "Ce renard est très malin.",
            "el": "Αυτή η αλεπού είναι πολύ έξυπνη.",
        },
    },
    {
        "id": "fr-el-brouhaha",
        "word": "brouhaha",
        "translation": "φασαρία, θόρυβος, ντόρος",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/bʁu.a.a/",
        "note": "Ηχομιμητική λέξη — ακούγεται σαν αυτό που περιγράφει.",
        "tags": ["🔊 sound", "📚 noun"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "brouhahas"},
        ],
        "example": {
            "fr": "Un brouhaha remplissait le café.",
            "el": "Μια φασαρία γέμιζε το καφέ.",
        },
    },
    {
        "id": "fr-el-raler",
        "word": "râler",
        "translation": "να γκρινιάζω, να παραπονιέμαι",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/ʁa.le/",
        "note": "Πολύ καθομιλουμένη λέξη — και πολύ γαλλική.",
        "tags": ["😂 informal", "🔤 verb", "🚶 daily"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "râlé"},
            {"label": "Présent (all 6 forms)", "value": "râle / râles / râle / râlons / râlez / râlent"},
        ],
        "example": {
            "fr": "Il râle toujours dans les embouteillages.",
            "el": "Γκρινιάζει πάντα στις κυκλοφοριακές συμφορήσεις.",
        },
    },
    {
        "id": "fr-el-velours",
        "word": "velours",
        "translation": "βελούδο",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/və.luʁ/",
        "tags": ["✨ texture", "📚 noun"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "velours"},
        ],
        "example": {
            "fr": "Le fauteuil en velours était incroyablement doux.",
            "el": "Η βελούδινη πολυθρόνα ήταν απίστευτα μαλακή.",
        },
    },
    {
        "id": "fr-el-debrouillard",
        "word": "débrouillard",
        "translation": "εφευρετικός, πολυμήχανος",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/de.bʁu.jaʁ/",
        "tags": ["🎨 adjective", "🚶 daily"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Feminine form", "value": "débrouillarde"},
            {"label": "Plural (masc.)", "value": "débrouillards"},
            {"label": "Plural (fem.)", "value": "débrouillardes"},
        ],
        "example": {
            "fr": "Elle est très débrouillarde pour résoudre les problèmes.",
            "el": "Είναι πολύ εφευρετική όταν πρόκειται να λύσει προβλήματα.",
        },
    },
    {
        "id": "fr-el-avoir-beau",
        "word": "avoir beau",
        "translation": "κάνω κάτι μάταια",
        "type": "phrase",
        "group": "🥖 Curated",
        "pronunciation": "/a.vwaʁ bo/",
        "note": "Ακολουθείται από απαρέμφατο — π.χ. 'J'ai beau essayer' σημαίνει: όσο κι αν προσπαθώ.",
        "tags": ["🗣️ phrase", "📘 grammar"],
        "priority": True,
        "departure_lang": "el",
        "example": {
            "fr": "J'ai beau essayer, je n'y arrive pas.",
            "el": "Όσο κι αν προσπαθώ, δεν τα καταφέρνω.",
        },
    },
    {
        "id": "fr-el-papoter",
        "word": "papoter",
        "translation": "να κουβεντιάζω, να κουτσομπολεύω",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/pa.pɔ.te/",
        "note": "Ανεπίσημος και φιλικός τόνος.",
        "tags": ["🗣️ social", "🔤 verb"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "papoté"},
            {"label": "Présent (all 6 forms)", "value": "papote / papotes / papote / papotons / papotez / papotent"},
        ],
        "example": {
            "fr": "Elles ont papoté pendant des heures.",
            "el": "Κουβέντιαζαν για ώρες.",
        },
    },
    {
        "id": "fr-el-poussiere",
        "word": "poussière",
        "translation": "σκόνη",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/pu.sjɛʁ/",
        "tags": ["🏠 home", "📚 noun"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "poussières"},
        ],
        "example": {
            "fr": "La poussière dansait dans la lumière.",
            "el": "Η σκόνη χόρευε στο φως.",
        },
    },
    {
        "id": "fr-el-egare",
        "word": "égaré",
        "translation": "χαμένος, αποπροσανατολισμένος",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/e.ɡa.ʁe/",
        "tags": ["🚶 daily", "🎨 adjective"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Feminine form", "value": "égarée"},
            {"label": "Plural (masc.)", "value": "égarés"},
            {"label": "Plural (fem.)", "value": "égarées"},
        ],
        "example": {
            "fr": "Un chien égaré attendait devant la gare.",
            "el": "Ένας χαμένος σκύλος περίμενε μπροστά στον σταθμό.",
        },
    },
    {
        "id": "fr-el-renverser",
        "word": "renverser",
        "translation": "να ανατρέψω, να χύσω, να αναποδογυρίσω",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/ʁɑ̃.vɛʁ.se/",
        "tags": ["🔤 verb", "🚶 daily"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "renversé"},
            {"label": "Présent (all 6 forms)", "value": "renverse / renverses / renverse / renversons / renversez / renversent"},
        ],
        "example": {
            "fr": "Il a renversé son café sur le clavier.",
            "el": "Έχυσε τον καφέ του πάνω στο πληκτρολόγιο.",
        },
    },
    {
        "id": "fr-el-fou-rire",
        "word": "fou rire",
        "translation": "κρίση γέλιου, ασταμάτητο γέλιο",
        "type": "phrase",
        "group": "🥖 Curated",
        "pronunciation": "/fu ʁiʁ/",
        "tags": ["😂 humor", "🗣️ phrase"],
        "priority": True,
        "departure_lang": "el",
        "example": {
            "fr": "Ils ont eu un fou rire au milieu du cours.",
            "el": "Τους έπιασε κρίση γέλιου στη μέση του μαθήματος.",
        },
    },
    {
        "id": "fr-el-murmure",
        "word": "murmure",
        "translation": "ψίθυρος, μουρμουρητό",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/myʁ.myʁ/",
        "tags": ["🔊 sound", "📚 noun"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "murmures"},
        ],
        "example": {
            "fr": "Un murmure parcourait la foule.",
            "el": "Ένας ψίθυρος διατρέχε το πλήθος.",
        },
    },
    {
        "id": "fr-el-epanoui",
        "word": "épanoui",
        "translation": "ολοκληρωμένος, ανθισμένος",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/e.pa.nwi/",
        "tags": ["💭 emotions", "🎨 adjective"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Feminine form", "value": "épanouie"},
            {"label": "Plural (masc.)", "value": "épanouis"},
            {"label": "Plural (fem.)", "value": "épanouies"},
        ],
        "example": {
            "fr": "Il semble plus épanoui depuis son déménagement.",
            "el": "Φαίνεται πιο ολοκληρωμένος από τότε που μετακόμισε.",
        },
    },
    {
        "id": "fr-el-bidonner",
        "word": "bidonner",
        "translation": "να πλαστογραφώ, να στήνω, να κάνω νοθεία",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/bi.dɔ.ne/",
        "note": "Ανεπίσημη χρήση.",
        "tags": ["😂 informal", "🔤 verb"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "bidonné"},
            {"label": "Présent (all 6 forms)", "value": "bidonne / bidonnes / bidonne / bidonnons / bidonnez / bidonnent"},
        ],
        "example": {
            "fr": "Certains ont bidonné les résultats.",
            "el": "Κάποιοι νόθευσαν τα αποτελέσματα.",
        },
    },
    {
        "id": "fr-el-etincelle",
        "word": "étincelle",
        "translation": "σπίθα",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/e.tɛ̃.sɛl/",
        "tags": ["✨ nature", "📚 noun"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "étincelles"},
        ],
        "example": {
            "fr": "Une étincelle a jailli du feu.",
            "el": "Μια σπίθα πετάχτηκε από τη φωτιά.",
        },
    },
    {
        "id": "fr-el-zut",
        "word": "zut",
        "translation": "άντε, συ!, διάολε! (ήπιο επιφώνημα)",
        "type": "phrase",
        "group": "🥖 Curated",
        "pronunciation": "/zyt/",
        "note": "Ήπιο επιφώνημα δυσαρέσκειας.",
        "tags": ["😂 informal", "🗣️ phrase"],
        "priority": True,
        "departure_lang": "el",
        "example": {
            "fr": "Zut, j'ai oublié mes clés.",
            "el": "Διάολε, ξέχασα τα κλειδιά μου.",
        },
    },
    {
        "id": "fr-el-savoureux",
        "word": "savoureux",
        "translation": "νόστιμος, γευστικός",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/sa.vu.ʁø/",
        "tags": ["🍕 food", "🎨 adjective"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Feminine form", "value": "savoureuse"},
            {"label": "Plural (masc.)", "value": "savoureux"},
            {"label": "Plural (fem.)", "value": "savoureuses"},
        ],
        "example": {
            "fr": "Ce plat est particulièrement savoureux.",
            "el": "Αυτό το πιάτο είναι ιδιαίτερα νόστιμο.",
        },
    },
    {
        "id": "fr-el-grignoter",
        "word": "grignoter",
        "translation": "να τσιμπολογώ, να ροκανίζω",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/gʁi.ɲɔ.te/",
        "tags": ["🍕 food", "🔤 verb"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "grignoté"},
            {"label": "Présent (all 6 forms)", "value": "grignote / grignotes / grignote / grignotons / grignotez / grignotent"},
        ],
        "example": {
            "fr": "Il aime grignoter devant les films.",
            "el": "Του αρέσει να τσιμπολογά μπροστά στις ταινίες.",
        },
    },
    {
        "id": "fr-el-brume",
        "word": "brume",
        "translation": "ομίχλη, καταχνιά",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/bʁym/",
        "tags": ["🌦️ weather", "📚 noun"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "brumes"},
        ],
        "example": {
            "fr": "La brume recouvrait les collines au matin.",
            "el": "Η καταχνιά κάλυπτε τους λόφους το πρωί.",
        },
    },
    {
        "id": "fr-el-dingue",
        "word": "dingue",
        "translation": "τρελός, παλαβός",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/dɛ̃ɡ/",
        "tags": ["😂 informal", "🎨 adjective"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Feminine form", "value": "dingue"},
            {"label": "Plural (masc.)", "value": "dingues"},
            {"label": "Plural (fem.)", "value": "dingues"},
        ],
        "example": {
            "fr": "Cette histoire est complètement dingue.",
            "el": "Αυτή η ιστορία είναι τελείως τρελή.",
        },
    },
    {
        "id": "fr-el-trainer",
        "word": "traîner",
        "translation": "να τριγυρνώ, να σέρνω, να χρονοτριβώ",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/tʁɛ.ne/",
        "tags": ["🚶 daily", "🔤 verb"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "traîné"},
            {"label": "Présent (all 6 forms)", "value": "traîne / traînes / traîne / traînons / traînez / traînent"},
        ],
        "example": {
            "fr": "Ils traînaient au parc après les cours.",
            "el": "Τριγυρνούσαν στο πάρκο μετά το σχολείο.",
        },
    },
    {
        "id": "fr-el-ricochet",
        "word": "ricochet",
        "translation": "αναπήδηση, παραπέτασμα πέτρας στο νερό",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/ʁi.kɔ.ʃɛ/",
        "tags": ["🌊 nature", "📚 noun"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "ricochets"},
        ],
        "example": {
            "fr": "La pierre a fait plusieurs ricochets sur l'eau.",
            "el": "Η πέτρα έκανε αρκετές αναπηδήσεις στο νερό.",
        },
    },
    {
        "id": "fr-el-a-peine",
        "word": "à peine",
        "translation": "μόλις και μετά βίας, μόλις",
        "type": "phrase",
        "group": "🥖 Curated",
        "pronunciation": "/a pɛn/",
        "tags": ["⭐ common", "🗣️ phrase"],
        "priority": True,
        "departure_lang": "el",
        "example": {
            "fr": "J'ai à peine dormi cette nuit.",
            "el": "Μόλις και μετά βίας κοιμήθηκα απόψε.",
        },
    },
    {
        "id": "fr-el-chaleureux",
        "word": "chaleureux",
        "translation": "θερμός, φιλόξενος",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/ʃa.lœ.ʁø/",
        "tags": ["🗣️ social", "🎨 adjective"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Feminine form", "value": "chaleureuse"},
            {"label": "Plural (masc.)", "value": "chaleureux"},
            {"label": "Plural (fem.)", "value": "chaleureuses"},
        ],
        "example": {
            "fr": "Ils nous ont réservé un accueil chaleureux.",
            "el": "Μας επιφύλαξαν μια θερμή υποδοχή.",
        },
    },
    {
        "id": "fr-el-bouquiner",
        "word": "bouquiner",
        "translation": "να διαβάζω ξεκούραστα, να ξεφυλλίζω βιβλία",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/bu.ki.ne/",
        "note": "Ανεπίσημη λέξη με άνετο, ζεστό τόνο.",
        "tags": ["📚 literature", "🔤 verb"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "bouquiné"},
            {"label": "Présent (all 6 forms)", "value": "bouquine / bouquines / bouquine / bouquinons / bouquinez / bouquinent"},
        ],
        "example": {
            "fr": "Elle bouquine dans le train chaque matin.",
            "el": "Διαβάζει ξεκούραστα στο τρένο κάθε πρωί.",
        },
    },
    {
        "id": "fr-el-brindille",
        "word": "brindille",
        "translation": "κλαδάκι",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/bʁɛ̃.dij/",
        "tags": ["🌿 nature", "📚 noun"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "brindilles"},
        ],
        "example": {
            "fr": "L'oiseau portait une brindille dans son bec.",
            "el": "Το πουλί κρατούσε ένα κλαδάκι στο ράμφος του.",
        },
    },
    {
        "id": "fr-el-gene",
        "word": "gêné",
        "translation": "αμήχανος, ντροπιασμένος",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/ʒe.ne/",
        "tags": ["💭 emotions", "🎨 adjective"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Feminine form", "value": "gênée"},
            {"label": "Plural (masc.)", "value": "gênés"},
            {"label": "Plural (fem.)", "value": "gênées"},
        ],
        "example": {
            "fr": "Il avait l'air gêné après sa remarque.",
            "el": "Φαινόταν αμήχανος μετά το σχόλιό του.",
        },
    },
    {
        "id": "fr-el-chipoter",
        "word": "chipoter",
        "translation": "να μικρολογώ, να ψειρίζω, να κάνω τον δύσκολο",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/ʃi.pɔ.te/",
        "tags": ["😂 informal", "🔤 verb"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "chipoté"},
            {"label": "Présent (all 6 forms)", "value": "chipote / chipotes / chipote / chipotons / chipotez / chipotent"},
        ],
        "example": {
            "fr": "Arrête de chipoter pour des détails.",
            "el": "Σταμάτα να ψειρίζεις για λεπτομέρειες.",
        },
    },
    {
        "id": "fr-el-refuge",
        "word": "refuge",
        "translation": "καταφύγιο, άσυλο",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/ʁə.fyʒ/",
        "tags": ["🏠 home", "📚 noun"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "refuges"},
        ],
        "example": {
            "fr": "Cette bibliothèque était son refuge préféré.",
            "el": "Αυτή η βιβλιοθήκη ήταν το αγαπημένο του καταφύγιο.",
        },
    },
    {
        "id": "fr-el-tomber-dans-les-pommes",
        "word": "tomber dans les pommes",
        "translation": "να λιποθυμώ",
        "type": "phrase",
        "group": "🥖 Curated",
        "pronunciation": "/tɔ̃.be dɑ̃ le pɔm/",
        "note": 'Κυριολεκτικά "να πέσω στα μήλα" — καθαρά ιδιωματική έκφραση.',
        "tags": ["😂 idiom", "🗣️ phrase"],
        "priority": True,
        "departure_lang": "el",
        "example": {
            "fr": "Il est tombé dans les pommes pendant le concert.",
            "el": "Λιποθύμησε κατά τη διάρκεια της συναυλίας.",
        },
    },
    {
        "id": "fr-el-ebouriffe",
        "word": "ébouriffé",
        "translation": "ανακατωμένα μαλλιά, αναμαλλιασμένος",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/e.bu.ʁi.fe/",
        "tags": ["👕 appearance", "🎨 adjective"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Feminine form", "value": "ébouriffée"},
            {"label": "Plural (masc.)", "value": "ébouriffés"},
            {"label": "Plural (fem.)", "value": "ébouriffées"},
        ],
        "example": {
            "fr": "Il est arrivé complètement ébouriffé.",
            "el": "Έφτασε εντελώς αναμαλλιασμένος.",
        },
    },
    {
        "id": "fr-el-bidonville",
        "word": "bidonville",
        "translation": "παραγκούπολη",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/bi.dɔ̃.vil/",
        "etymology": 'Από το "bidon" (δοχείο) και "ville" (πόλη).',
        "tags": ["🌍 society", "📚 noun"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "bidonvilles"},
        ],
        "example": {
            "fr": "Des familles vivent encore dans ce bidonville.",
            "el": "Οικογένειες ζουν ακόμα σε αυτήν την παραγκούπολη.",
        },
    },
    {
        "id": "fr-el-fredonner",
        "word": "fredonner",
        "translation": "να μουρμουρίζω, να τραγουδώ σιγανά",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/fʁə.dɔ.ne/",
        "tags": ["🎵 music", "🔤 verb"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "fredonné"},
            {"label": "Présent (all 6 forms)", "value": "fredonne / fredonnes / fredonne / fredonnons / fredonnez / fredonnent"},
        ],
        "example": {
            "fr": "Elle fredonnait une vieille chanson en cuisinant.",
            "el": "Μουρμουρούσε ένα παλιό τραγούδι ενώ μαγείρευε.",
        },
    },
    {
        "id": "fr-el-veloute",
        "word": "velouté",
        "translation": "βελούδινος· κρεμώδης σούπα",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/və.lu.te/",
        "tags": ["🍕 food", "📚 noun"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "veloutés"},
        ],
        "example": {
            "fr": "Ce velouté de champignons est délicieux.",
            "el": "Αυτή η κρεμώδης σούπα μανιταριών είναι υπέροχη.",
        },
    },
    {
        "id": "fr-el-farfelu",
        "word": "farfelu",
        "translation": "παράξενος, εκκεντρικός, τρελοκαμένος",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/faʁ.fə.ly/",
        "tags": ["😂 humor", "🎨 adjective"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Feminine form", "value": "farfelue"},
            {"label": "Plural (masc.)", "value": "farfelus"},
            {"label": "Plural (fem.)", "value": "farfelues"},
        ],
        "example": {
            "fr": "Il propose toujours des idées farfelues.",
            "el": "Προτείνει πάντα παράξενες ιδέες.",
        },
    },
    {
        "id": "fr-el-se-debrouiller",
        "word": "se débrouiller",
        "translation": "να τα βγάλω πέρα, να καταφέρω",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/sə de.bʁu.je/",
        "tags": ["🚶 daily", "🔤 verb"],
        "priority": True,
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "être"},
            {"label": "Past participle", "value": "débrouillé"},
            {"label": "Présent (all 6 forms)", "value": "me débrouille / te débrouilles / se débrouille / nous débrouillons / vous débrouillez / se débrouillent"},
        ],
        "example": {
            "fr": "Même sans carte, elle s'est débrouillée.",
            "el": "Ακόμα και χωρίς χάρτη, τα κατάφερε.",
        },
    },
]
