"""
fr_vocab_data.py — French vocabulary preset cards.

Grammar label reference (use these EXACTLY):
  Verb:      Verb group | Auxiliary | Past participle | Présent (all 6 forms)
  Noun:      Gender | Plural | Feminine form
  Adjective: Feminine form | Plural (masc.) | Plural (fem.)
  Phrase:    (no grammar fields required)
"""

CARDS = [
    {
        "id": "fr-flaner",
        "word": "flâner",
        "translation": "to stroll, wander aimlessly",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/flɑ.ne/",
        "etymology": 'From Old Norse "flana" meaning to rush about.',
        "note": "Often carries a poetic or leisurely feeling.",
        "tags": ["⭐ common", "🔤 verb", "🚶 daily"],
        "priority": True,
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "flâné"},
            {"label": "Présent (all 6 forms)", "value": "flâne / flânes / flâne / flânons / flânez / flânent"},
        ],
        "example": {"fr": "Le dimanche, elle aime flâner dans les rues du vieux quartier.", "en": "On Sundays, she likes to stroll through the streets of the old district."},
    },
    {
        "id": "fr-pourtant",
        "word": "pourtant",
        "translation": "however, yet, nevertheless",
        "type": "adverb",
        "group": "🥖 Curated",
        "pronunciation": "/puʁ.tɑ̃/",
        "etymology": 'From "pour tant".',
        "note": "Common connector in both speech and writing.",
        "tags": ["⭐ common", "📘 connector", "🚶 daily"],
        "priority": True,
        "example": {"fr": "Il était fatigué, pourtant il a continué à travailler.", "en": "He was tired, yet he continued working."},
    },
    {
        "id": "fr-luciole",
        "word": "luciole",
        "translation": "firefly",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/ly.sjɔl/",
        "note": "A very evocative and literary word.",
        "tags": ["✨ nature", "📚 noun"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "lucioles"},
        ],
        "example": {"fr": "Les lucioles brillaient au bord du lac.", "en": "Fireflies were glowing by the lake."},
    },
    {
        "id": "fr-apprivoiser",
        "word": "apprivoiser",
        "translation": "to tame, befriend",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/a.pʁi.vwa.ze/",
        "etymology": 'Related to "privé" and Latin "privatus".',
        "note": 'Famous from "Le Petit Prince".',
        "tags": ["📚 literature", "🔤 verb", "🐾 animals"],
        "priority": True,
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "apprivoisé"},
            {"label": "Présent (all 6 forms)", "value": "apprivoise / apprivoises / apprivoise / apprivoisons / apprivoisez / apprivoisent"},
        ],
        "example": {"fr": "Il faut du temps pour apprivoiser un chat méfiant.", "en": "It takes time to tame a wary cat."},
    },
    {
        "id": "fr-bouleverse",
        "word": "bouleversé",
        "translation": "shaken, overwhelmed, deeply moved",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/bul.vɛʁ.se/",
        "note": "Strong emotional adjective.",
        "tags": ["💭 emotions", "🎨 adjective"],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "bouleversée"},
            {"label": "Plural (masc.)", "value": "bouleversés"},
            {"label": "Plural (fem.)", "value": "bouleversées"},
        ],
        "example": {"fr": "Elle semblait bouleversée après la nouvelle.", "en": "She seemed deeply shaken after the news."},
    },
    {
        "id": "fr-bidule",
        "word": "bidule",
        "translation": "thingamajig, gadget, thingy",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/bi.dyl/",
        "note": "Informal and playful placeholder word.",
        "tags": ["😂 informal", "📚 noun", "🏠 home"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "bidules"},
        ],
        "example": {"fr": "Passe-moi le bidule sur la table.", "en": "Pass me the thingy on the table."},
    },
    {
        "id": "fr-avoir-le-cafard",
        "word": "avoir le cafard",
        "translation": "to feel down, be depressed",
        "type": "phrase",
        "group": "🥖 Curated",
        "pronunciation": "/a.vwaʁ lə ka.faʁ/",
        "note": 'Literally "to have the cockroach".',
        "tags": ["💭 emotions", "🗣️ phrase", "🚶 daily"],
        "priority": True,
        "example": {"fr": "Depuis l'hiver, il a souvent le cafard.", "en": "Since winter, he's often been feeling down."},
    },
    {
        "id": "fr-eblouissant",
        "word": "éblouissant",
        "translation": "dazzling, brilliant",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/e.blu.i.sɑ̃/",
        "note": "Can describe light, beauty, or talent.",
        "tags": ["✨ descriptive", "🎨 adjective"],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "éblouissante"},
            {"label": "Plural (masc.)", "value": "éblouissants"},
            {"label": "Plural (fem.)", "value": "éblouissantes"},
        ],
        "example": {"fr": "Le coucher du soleil était éblouissant.", "en": "The sunset was dazzling."},
    },
    {
        "id": "fr-fouiller",
        "word": "fouiller",
        "translation": "to search, rummage",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/fu.je/",
        "note": "Also used for police searches.",
        "tags": ["🔤 verb", "🚶 daily"],
        "priority": True,
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "fouillé"},
            {"label": "Présent (all 6 forms)", "value": "fouille / fouilles / fouille / fouillons / fouillez / fouillent"},
        ],
        "example": {"fr": "Elle a fouillé son sac pendant plusieurs minutes.", "en": "She rummaged through her bag for several minutes."},
    },
    {
        "id": "fr-chouette",
        "word": "chouette",
        "translation": "owl, great, nice",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/ʃwɛt/",
        "note": 'Informal positive adjective; also means "owl" as a noun.',
        "tags": ["⭐ common", "🎨 adjective", "😂 informal"],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "chouette"},
            {"label": "Plural (masc.)", "value": "chouettes"},
            {"label": "Plural (fem.)", "value": "chouettes"},
        ],
        "example": {"fr": "C'est une idée vraiment chouette.", "en": "That's a really nice idea."},
    },
    {
        "id": "fr-grenier",
        "word": "grenier",
        "translation": "attic",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/gʁə.nje/",
        "tags": ["🏠 home", "📚 noun"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "greniers"},
        ],
        "example": {"fr": "Ils ont trouvé de vieux albums dans le grenier.", "en": "They found old photo albums in the attic."},
    },
    {
        "id": "fr-epanouir",
        "word": "s'épanouir",
        "translation": "to blossom, thrive",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/se.pa.nwiʁ/",
        "note": "Often used emotionally or personally.",
        "tags": ["💭 emotions", "🔤 verb"],
        "priority": True,
        "grammar": [
            {"label": "Verb group", "value": "3e"},
            {"label": "Auxiliary", "value": "être"},
            {"label": "Past participle", "value": "épanoui"},
            {"label": "Présent (all 6 forms)", "value": "m'épanouis / t'épanouis / s'épanouit / nous épanouissons / vous épanouissez / s'épanouissent"},
        ],
        "example": {"fr": "Elle s'épanouit dans son nouveau travail.", "en": "She is thriving in her new job."},
    },
    {
        "id": "fr-frisson",
        "word": "frisson",
        "translation": "shiver, thrill",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/fʁi.sɔ̃/",
        "tags": ["💭 emotions", "📚 noun"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "frissons"},
        ],
        "example": {"fr": "Un frisson lui a traversé le dos.", "en": "A shiver ran down his back."},
    },
    {
        "id": "fr-tant-pis",
        "word": "tant pis",
        "translation": "too bad, never mind",
        "type": "phrase",
        "group": "🥖 Curated",
        "pronunciation": "/tɑ̃ pi/",
        "note": "Extremely common conversational phrase.",
        "tags": ["⭐ common", "🗣️ phrase", "🚶 daily"],
        "priority": True,
        "example": {"fr": "Il pleut ? Tant pis, on sort quand même.", "en": "It's raining? Too bad, we're going out anyway."},
    },
    {
        "id": "fr-malin",
        "word": "malin",
        "translation": "clever, sly",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/ma.lɛ̃/",
        "note": "Depending on context, can be admiring or suspicious.",
        "tags": ["🎨 adjective", "🚶 daily"],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "maligne"},
            {"label": "Plural (masc.)", "value": "malins"},
            {"label": "Plural (fem.)", "value": "malignes"},
        ],
        "example": {"fr": "Ce renard est très malin.", "en": "That fox is very clever."},
    },
    {
        "id": "fr-brouhaha",
        "word": "brouhaha",
        "translation": "commotion, hubbub",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/bʁu.a.a/",
        "note": "Fun onomatopoeic word.",
        "tags": ["🔊 sound", "📚 noun"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "brouhahas"},
        ],
        "example": {"fr": "Un brouhaha remplissait le café.", "en": "A hubbub filled the café."},
    },
    {
        "id": "fr-raler",
        "word": "râler",
        "translation": "to complain, grumble",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/ʁa.le/",
        "note": "Very colloquial and very French.",
        "tags": ["😂 informal", "🔤 verb", "🚶 daily"],
        "priority": True,
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "râlé"},
            {"label": "Présent (all 6 forms)", "value": "râle / râles / râle / râlons / râlez / râlent"},
        ],
        "example": {"fr": "Il râle toujours dans les embouteillages.", "en": "He always grumbles in traffic jams."},
    },
    {
        "id": "fr-velours",
        "word": "velours",
        "translation": "velvet",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/və.luʁ/",
        "tags": ["✨ texture", "📚 noun"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "velours"},
        ],
        "example": {"fr": "Le fauteuil en velours était incroyablement doux.", "en": "The velvet armchair was incredibly soft."},
    },
    {
        "id": "fr-debrouillard",
        "word": "débrouillard",
        "translation": "resourceful",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/de.bʁu.jaʁ/",
        "tags": ["🎨 adjective", "🚶 daily"],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "débrouillarde"},
            {"label": "Plural (masc.)", "value": "débrouillards"},
            {"label": "Plural (fem.)", "value": "débrouillardes"},
        ],
        "example": {"fr": "Elle est très débrouillarde pour résoudre les problèmes.", "en": "She is very resourceful when solving problems."},
    },
    {
        "id": "fr-avoir-beau",
        "word": "avoir beau",
        "translation": "to do something in vain",
        "type": "phrase",
        "group": "🥖 Curated",
        "pronunciation": "/a.vwaʁ bo/",
        "note": "Followed by an infinitive.",
        "tags": ["🗣️ phrase", "📘 grammar"],
        "priority": True,
        "example": {"fr": "J'ai beau essayer, je n'y arrive pas.", "en": "No matter how much I try, I can't do it."},
    },
    {
        "id": "fr-papoter",
        "word": "papoter",
        "translation": "to chat",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/pa.pɔ.te/",
        "note": "Casual and friendly tone.",
        "tags": ["🗣️ social", "🔤 verb"],
        "priority": True,
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "papoté"},
            {"label": "Présent (all 6 forms)", "value": "papote / papotes / papote / papotons / papotez / papotent"},
        ],
        "example": {"fr": "Elles ont papoté pendant des heures.", "en": "They chatted for hours."},
    },
    {
        "id": "fr-poussiere",
        "word": "poussière",
        "translation": "dust",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/pu.sjɛʁ/",
        "tags": ["🏠 home", "📚 noun"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "poussières"},
        ],
        "example": {"fr": "La poussière dansait dans la lumière.", "en": "Dust danced in the light."},
    },
    {
        "id": "fr-egare",
        "word": "égaré",
        "translation": "lost, misplaced",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/e.ɡa.ʁe/",
        "tags": ["🚶 daily", "🎨 adjective"],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "égarée"},
            {"label": "Plural (masc.)", "value": "égarés"},
            {"label": "Plural (fem.)", "value": "égarées"},
        ],
        "example": {"fr": "Un chien égaré attendait devant la gare.", "en": "A lost dog was waiting in front of the station."},
    },
    {
        "id": "fr-renverser",
        "word": "renverser",
        "translation": "to knock over, overturn",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/ʁɑ̃.vɛʁ.se/",
        "tags": ["🔤 verb", "🚶 daily"],
        "priority": True,
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "renversé"},
            {"label": "Présent (all 6 forms)", "value": "renverse / renverses / renverse / renversons / renversez / renversent"},
        ],
        "example": {"fr": "Il a renversé son café sur le clavier.", "en": "He spilled his coffee on the keyboard."},
    },
    {
        "id": "fr-fou-rire",
        "word": "fou rire",
        "translation": "laughing fit",
        "type": "phrase",
        "group": "🥖 Curated",
        "pronunciation": "/fu ʁiʁ/",
        "tags": ["😂 humor", "🗣️ phrase"],
        "priority": True,
        "example": {"fr": "Ils ont eu un fou rire au milieu du cours.", "en": "They had a laughing fit in the middle of class."},
    },
    {
        "id": "fr-murmure",
        "word": "murmure",
        "translation": "whisper, murmur",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/myʁ.myʁ/",
        "tags": ["🔊 sound", "📚 noun"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "murmures"},
        ],
        "example": {"fr": "Un murmure parcourait la foule.", "en": "A murmur ran through the crowd."},
    },
    {
        "id": "fr-epanoui",
        "word": "épanoui",
        "translation": "fulfilled, blossoming",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/e.pa.nwi/",
        "tags": ["💭 emotions", "🎨 adjective"],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "épanouie"},
            {"label": "Plural (masc.)", "value": "épanouis"},
            {"label": "Plural (fem.)", "value": "épanouies"},
        ],
        "example": {"fr": "Il semble plus épanoui depuis son déménagement.", "en": "He seems more fulfilled since moving."},
    },
    {
        "id": "fr-bidonner",
        "word": "bidonner",
        "translation": "to fake, rig",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/bi.dɔ.ne/",
        "note": "Informal usage.",
        "tags": ["😂 informal", "🔤 verb"],
        "priority": True,
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "bidonné"},
            {"label": "Présent (all 6 forms)", "value": "bidonne / bidonnes / bidonne / bidonnons / bidonnez / bidonnent"},
        ],
        "example": {"fr": "Certains ont bidonné les résultats.", "en": "Some people rigged the results."},
    },
    {
        "id": "fr-etincelle",
        "word": "étincelle",
        "translation": "spark",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/e.tɛ̃.sɛl/",
        "tags": ["✨ nature", "📚 noun"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "étincelles"},
        ],
        "example": {"fr": "Une étincelle a jailli du feu.", "en": "A spark flew from the fire."},
    },
    {
        "id": "fr-zut",
        "word": "zut",
        "translation": "darn, shoot",
        "type": "phrase",
        "group": "🥖 Curated",
        "pronunciation": "/zyt/",
        "note": "Mild exclamation.",
        "tags": ["😂 informal", "🗣️ phrase"],
        "priority": True,
        "example": {"fr": "Zut, j'ai oublié mes clés.", "en": "Darn, I forgot my keys."},
    },
    {
        "id": "fr-savoureux",
        "word": "savoureux",
        "translation": "tasty, flavorful",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/sa.vu.ʁø/",
        "tags": ["🍕 food", "🎨 adjective"],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "savoureuse"},
            {"label": "Plural (masc.)", "value": "savoureux"},
            {"label": "Plural (fem.)", "value": "savoureuses"},
        ],
        "example": {"fr": "Ce plat est particulièrement savoureux.", "en": "This dish is especially flavorful."},
    },
    {
        "id": "fr-grignoter",
        "word": "grignoter",
        "translation": "to snack, nibble",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/gʁi.ɲɔ.te/",
        "tags": ["🍕 food", "🔤 verb"],
        "priority": True,
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "grignoté"},
            {"label": "Présent (all 6 forms)", "value": "grignote / grignotes / grignote / grignotons / grignotez / grignotent"},
        ],
        "example": {"fr": "Il aime grignoter devant les films.", "en": "He likes snacking during movies."},
    },
    {
        "id": "fr-brume",
        "word": "brume",
        "translation": "mist, haze",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/bʁym/",
        "tags": ["🌦️ weather", "📚 noun"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "brumes"},
        ],
        "example": {"fr": "La brume recouvrait les collines au matin.", "en": "Mist covered the hills in the morning."},
    },
    {
        "id": "fr-dingue",
        "word": "dingue",
        "translation": "crazy, insane",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/dɛ̃ɡ/",
        "tags": ["😂 informal", "🎨 adjective"],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "dingue"},
            {"label": "Plural (masc.)", "value": "dingues"},
            {"label": "Plural (fem.)", "value": "dingues"},
        ],
        "example": {"fr": "Cette histoire est complètement dingue.", "en": "This story is completely crazy."},
    },
    {
        "id": "fr-trainer",
        "word": "traîner",
        "translation": "to hang around, drag",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/tʁɛ.ne/",
        "tags": ["🚶 daily", "🔤 verb"],
        "priority": True,
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "traîné"},
            {"label": "Présent (all 6 forms)", "value": "traîne / traînes / traîne / traînons / traînez / traînent"},
        ],
        "example": {"fr": "Ils traînaient au parc après les cours.", "en": "They were hanging around the park after class."},
    },
    {
        "id": "fr-ricochet",
        "word": "ricochet",
        "translation": "ricochet, skipping stone bounce",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/ʁi.kɔ.ʃɛ/",
        "tags": ["🌊 nature", "📚 noun"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "ricochets"},
        ],
        "example": {"fr": "La pierre a fait plusieurs ricochets sur l'eau.", "en": "The stone skipped several times across the water."},
    },
    {
        "id": "fr-a-peine",
        "word": "à peine",
        "translation": "barely, hardly",
        "type": "phrase",
        "group": "🥖 Curated",
        "pronunciation": "/a pɛn/",
        "tags": ["⭐ common", "🗣️ phrase"],
        "priority": True,
        "example": {"fr": "J'ai à peine dormi cette nuit.", "en": "I barely slept last night."},
    },
    {
        "id": "fr-chaleureux",
        "word": "chaleureux",
        "translation": "warm, welcoming",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/ʃa.lœ.ʁø/",
        "tags": ["🗣️ social", "🎨 adjective"],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "chaleureuse"},
            {"label": "Plural (masc.)", "value": "chaleureux"},
            {"label": "Plural (fem.)", "value": "chaleureuses"},
        ],
        "example": {"fr": "Ils nous ont réservé un accueil chaleureux.", "en": "They gave us a warm welcome."},
    },
    {
        "id": "fr-bouquiner",
        "word": "bouquiner",
        "translation": "to read casually",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/bu.ki.ne/",
        "note": "Informal and cozy feeling.",
        "tags": ["📚 literature", "🔤 verb"],
        "priority": True,
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "bouquiné"},
            {"label": "Présent (all 6 forms)", "value": "bouquine / bouquines / bouquine / bouquinons / bouquinez / bouquinent"},
        ],
        "example": {"fr": "Elle bouquine dans le train chaque matin.", "en": "She reads casually on the train every morning."},
    },
    {
        "id": "fr-brindille",
        "word": "brindille",
        "translation": "twig",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/bʁɛ̃.dij/",
        "tags": ["🌿 nature", "📚 noun"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "brindilles"},
        ],
        "example": {"fr": "L'oiseau portait une brindille dans son bec.", "en": "The bird carried a twig in its beak."},
    },
    {
        "id": "fr-gene",
        "word": "gêné",
        "translation": "embarrassed, awkward",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/ʒe.ne/",
        "tags": ["💭 emotions", "🎨 adjective"],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "gênée"},
            {"label": "Plural (masc.)", "value": "gênés"},
            {"label": "Plural (fem.)", "value": "gênées"},
        ],
        "example": {"fr": "Il avait l'air gêné après sa remarque.", "en": "He looked embarrassed after his comment."},
    },
    {
        "id": "fr-chipoter",
        "word": "chipoter",
        "translation": "to nitpick, fuss",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/ʃi.pɔ.te/",
        "tags": ["😂 informal", "🔤 verb"],
        "priority": True,
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "chipoté"},
            {"label": "Présent (all 6 forms)", "value": "chipote / chipotes / chipote / chipotons / chipotez / chipotent"},
        ],
        "example": {"fr": "Arrête de chipoter pour des détails.", "en": "Stop nitpicking over details."},
    },
    {
        "id": "fr-refuge",
        "word": "refuge",
        "translation": "refuge, shelter",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/ʁə.fyʒ/",
        "tags": ["🏠 home", "📚 noun"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "refuges"},
        ],
        "example": {"fr": "Cette bibliothèque était son refuge préféré.", "en": "That library was his favorite refuge."},
    },
    {
        "id": "fr-tomber-dans-les-pommes",
        "word": "tomber dans les pommes",
        "translation": "to faint",
        "type": "phrase",
        "group": "🥖 Curated",
        "pronunciation": "/tɔ̃.be dɑ̃ le pɔm/",
        "note": 'Literally "to fall into the apples".',
        "tags": ["😂 idiom", "🗣️ phrase"],
        "priority": True,
        "example": {"fr": "Il est tombé dans les pommes pendant le concert.", "en": "He fainted during the concert."},
    },
    {
        "id": "fr-ebouriffe",
        "word": "ébouriffé",
        "translation": "messy-haired, tousled",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/e.bu.ʁi.fe/",
        "tags": ["👕 appearance", "🎨 adjective"],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "ébouriffée"},
            {"label": "Plural (masc.)", "value": "ébouriffés"},
            {"label": "Plural (fem.)", "value": "ébouriffées"},
        ],
        "example": {"fr": "Il est arrivé complètement ébouriffé.", "en": "He arrived completely tousled."},
    },
    {
        "id": "fr-bidonville",
        "word": "bidonville",
        "translation": "shantytown",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/bi.dɔ̃.vil/",
        "etymology": 'From "bidon" and "ville".',
        "tags": ["🌍 society", "📚 noun"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "bidonvilles"},
        ],
        "example": {"fr": "Des familles vivent encore dans ce bidonville.", "en": "Families still live in that shantytown."},
    },
    {
        "id": "fr-fredonner",
        "word": "fredonner",
        "translation": "to hum",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/fʁə.dɔ.ne/",
        "tags": ["🎵 music", "🔤 verb"],
        "priority": True,
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "avoir"},
            {"label": "Past participle", "value": "fredonné"},
            {"label": "Présent (all 6 forms)", "value": "fredonne / fredonnes / fredonne / fredonnons / fredonnez / fredonnent"},
        ],
        "example": {"fr": "Elle fredonnait une vieille chanson en cuisinant.", "en": "She was humming an old song while cooking."},
    },
    {
        "id": "fr-veloute",
        "word": "velouté",
        "translation": "velvety, creamy soup",
        "type": "noun",
        "group": "🥖 Curated",
        "pronunciation": "/və.lu.te/",
        "tags": ["🍕 food", "📚 noun"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "veloutés"},
        ],
        "example": {"fr": "Ce velouté de champignons est délicieux.", "en": "This creamy mushroom soup is delicious."},
    },
    {
        "id": "fr-farfelu",
        "word": "farfelu",
        "translation": "eccentric, wacky",
        "type": "adjective",
        "group": "🥖 Curated",
        "pronunciation": "/faʁ.fə.ly/",
        "tags": ["😂 humor", "🎨 adjective"],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "farfelue"},
            {"label": "Plural (masc.)", "value": "farfelus"},
            {"label": "Plural (fem.)", "value": "farfelues"},
        ],
        "example": {"fr": "Il propose toujours des idées farfelues.", "en": "He always suggests wacky ideas."},
    },
    {
        "id": "fr-se-debrouiller",
        "word": "se débrouiller",
        "translation": "to manage, cope",
        "type": "verb",
        "group": "🥖 Curated",
        "pronunciation": "/sə de.bʁu.je/",
        "tags": ["🚶 daily", "🔤 verb"],
        "priority": True,
        "grammar": [
            {"label": "Verb group", "value": "1er"},
            {"label": "Auxiliary", "value": "être"},
            {"label": "Past participle", "value": "débrouillé"},
            {"label": "Présent (all 6 forms)", "value": "me débrouille / te débrouilles / se débrouille / nous débrouillons / vous débrouillez / se débrouillent"},
        ],
        "example": {"fr": "Même sans carte, elle s'est débrouillée.", "en": "Even without a map, she managed."},
    },
]
