"""
es_de_vocab_data.py — Spanish vocabulary cards for German speakers (departure_lang='de').
Imported automatically by es_vocab_data.py.
"""

CARDS = [
    {
        "id": "es-de-sobremesa",
        "spanish": "sobremesa",
        "translation": "Nachtischschwatz, gemütliches Beisammensein nach dem Essen",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/so.βɾeˈme.sa/",
        "etymology": 'Von sobre („über") + mesa („Tisch").',
        "note": "Eng verbunden mit der spanischsprachigen Gesellschaftskultur.",
        "tags": [
            "⭐ common",
            "🍽️ food",
            "🗣️ culture",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "sobremesas"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Disfrutamos de una larga sobremesa después de la cena.",
            "de": "Wir genossen ein langes Beisammensein nach dem Abendessen.",
        },
    },
    {
        "id": "es-de-desvelarse",
        "spanish": "desvelarse",
        "translation": "wach liegen, nicht schlafen können",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/des.βeˈlaɾ.se/",
        "note": "Impliziert oft unfreiwillige Schlaflosigkeit.",
        "tags": [
            "⭐ common",
            "🌙 night",
            "🧠 emotions",
        ],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "yes"},
            {"label": "Participio pasado", "value": "desvelado"},
            {"label": "Pretérito indefinido (yo)", "value": "desvelé"},
            {"label": "Pretérito imperfecto (yo)", "value": "desvelaba"},
            {"label": "Gerundio", "value": "desvelando"},
            {
                "label": "Presente (all 6 forms)",
                "value": "me desvelo / te desvelas / se desvela / nos desvelamos / os desveláis / se desvelan",
            },
        ],
        "departure_lang": "de",
        "example": {
            "es": "Me desvelé pensando en el examen.",
            "de": "Ich lag wach und dachte an die Prüfung.",
        },
    },
    {
        "id": "es-de-relampago",
        "spanish": "relámpago",
        "translation": "Blitz, Blitzschlag",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/reˈlam.pa.ɣo/",
        "etymology": "Möglicherweise von relampaguear.",
        "tags": [
            "⭐ common",
            "⛈️ weather",
            "🌿 nature",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "relámpagos"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Un relámpago iluminó toda la montaña.",
            "de": "Ein Blitz erhellte den ganzen Berg.",
        },
    },
    {
        "id": "es-de-entrañable",
        "spanish": "entrañable",
        "translation": "herzlich, liebenswert, teuer",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/en.tɾaˈɲa.βle/",
        "etymology": 'Von entraña („innerstes Wesen").',
        "note": "Oft für emotional warme Menschen oder Erinnerungen verwendet.",
        "tags": [
            "⭐ common",
            "❤️ emotions",
            "👥 people",
        ],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "entrañable"},
            {"label": "Plural (masc.)", "value": "entrañables"},
            {"label": "Plural (fem.)", "value": "entrañables"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Fue una conversación entrañable entre amigos.",
            "de": "Es war ein herzliches Gespräch unter Freunden.",
        },
    },
    {
        "id": "es-de-a-duras-penas",
        "spanish": "a duras penas",
        "translation": "kaum, mit großer Mühe",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/a ˈdu.ɾas ˈpe.nas/",
        "note": "Gebräuchlicher idiomatischer Ausdruck.",
        "tags": [
            "⭐ common",
            "💬 idiom",
            "🏃 effort",
        ],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "neutral"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Llegó a duras penas al final de la carrera.",
            "de": "Er schaffte es kaum bis zum Ende des Rennens.",
        },
    },
    {
        "id": "es-de-madrugar",
        "spanish": "madrugar",
        "translation": "früh aufstehen",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/ma.dɾuˈɣaɾ/",
        "tags": [
            "⭐ common",
            "⏰ daily life",
        ],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "no"},
            {"label": "Participio pasado", "value": "madrugado"},
            {"label": "Pretérito indefinido (yo)", "value": "madrugué"},
            {"label": "Pretérito imperfecto (yo)", "value": "madrugaba"},
            {"label": "Gerundio", "value": "madrugando"},
            {
                "label": "Presente (all 6 forms)",
                "value": "madrugo / madrugas / madruga / madrugamos / madrugáis / madrugan",
            },
        ],
        "departure_lang": "de",
        "example": {
            "es": "No me gusta madrugar los domingos.",
            "de": "Ich mag es nicht, sonntags früh aufzustehen.",
        },
    },
    {
        "id": "es-de-rincon",
        "spanish": "rincón",
        "translation": "Ecke, Winkel",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/rinˈkon/",
        "tags": [
            "⭐ common",
            "🏠 places",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "rincones"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Encontramos un rincón tranquilo en la biblioteca.",
            "de": "Wir fanden einen ruhigen Winkel in der Bibliothek.",
        },
    },
    {
        "id": "es-de-ojala",
        "spanish": "ojalá",
        "translation": "hoffentlich, wenn doch nur",
        "type": "adverb",
        "scene_id": "💃 Curated",
        "pronunciation": "/o.xaˈla/",
        'etymology': 'Vom Arabischen law šá lláh („so Gott will").',
        "note": "Oft gefolgt von Verben im Konjunktiv.",
        "tags": [
            "⭐ common",
            "💭 wishes",
            "🗣️ culture",
        ],
        "priority": True,
        "departure_lang": "de",
        "example": {
            "es": "Ojalá llueva mañana.",
            "de": "Hoffentlich regnet es morgen.",
        },
    },
    {
        "id": "es-de-aguacero",
        "spanish": "aguacero",
        "translation": "Regenguss, Platzregen",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/a.ɣwaˈθe.ɾo/",
        "tags": [
            "⛈️ weather",
            "🌿 nature",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "aguaceros"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Nos sorprendió un aguacero en mitad del paseo.",
            "de": "Mitten beim Spaziergang überraschte uns ein Platzregen.",
        },
    },
    {
        "id": "es-de-despistado",
        "spanish": "despistado",
        "translation": "zerstreut, unaufmerksam",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/des.pisˈta.ðo/",
        "tags": [
            "⭐ common",
            "🧠 personality",
        ],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "despistada"},
            {"label": "Plural (masc.)", "value": "despistados"},
            {"label": "Plural (fem.)", "value": "despistadas"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Soy tan despistado que olvidé las llaves otra vez.",
            "de": "Ich bin so zerstreut, dass ich schon wieder die Schlüssel vergessen habe.",
        },
    },
    {
        "id": "es-de-echar-de-menos",
        "spanish": "echar de menos",
        "translation": "vermissen, sich sehnen nach",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/eˈtʃaɾ ðe ˈme.nos/",
        'note': 'Der gängige Ausdruck für „jemanden vermissen".',
        "tags": [
            "⭐ common",
            "❤️ emotions",
            "✈️ travel",
        ],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "neutral"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Echo de menos a mi familia cuando viajo.",
            "de": "Wenn ich reise, vermisse ich meine Familie.",
        },
    },
    {
        "id": "es-de-curiosear",
        "spanish": "curiosear",
        "translation": "neugierig stöbern, herumschnüffeln",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/ku.ɾjo.seˈaɾ/",
        "tags": [
            "📚 learning",
            "👀 curiosity",
        ],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "no"},
            {"label": "Participio pasado", "value": "curioseado"},
            {"label": "Pretérito indefinido (yo)", "value": "curioseé"},
            {"label": "Pretérito imperfecto (yo)", "value": "curioseaba"},
            {"label": "Gerundio", "value": "curioseando"},
            {
                "label": "Presente (all 6 forms)",
                "value": "curioseo / curioseas / curiosea / curioseamos / curioseáis / curiosean",
            },
        ],
        "departure_lang": "de",
        "example": {
            "es": "Le gusta curiosear en las librerías antiguas.",
            "de": "Sie stöbert gerne in alten Buchhandlungen.",
        },
    },
    {
        "id": "es-de-brillo",
        "spanish": "brillo",
        "translation": "Glanz, Schimmer, Funkeln",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/ˈbɾi.ʎo/",
        "tags": [
            "✨ appearance",
            "🎨 art",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "brillos"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Sus ojos tenían un brillo especial.",
            "de": "Ihre Augen hatten ein besonderes Leuchten.",
        },
    },
    {
        "id": "es-de-fugaz",
        "spanish": "fugaz",
        "translation": "flüchtig, kurzlebig",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/fuˈɣaθ/",
        "tags": [
            "⏳ time",
            "❤️ emotions",
        ],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "fugaz"},
            {"label": "Plural (masc.)", "value": "fugaces"},
            {"label": "Plural (fem.)", "value": "fugaces"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Tuvieron un encuentro fugaz en la estación.",
            "de": "Sie hatten eine flüchtige Begegnung am Bahnhof.",
        },
    },
    {
        "id": "es-de-de-golpe",
        "spanish": "de golpe",
        "translation": "plötzlich, auf einmal",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/de ˈɣol.pe/",
        "tags": [
            "💬 idiom",
            "⚡ intensity",
        ],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "neutral"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Todo cambió de golpe.",
            "de": "Alles änderte sich plötzlich.",
        },
    },
    {
        "id": "es-de-merienda",
        "spanish": "merienda",
        "translation": "Nachmittagssnack, kleine Zwischenmahlzeit",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/meˈɾjen.da/",
        "tags": [
            "🍽️ food",
            "☀️ daily life",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "meriendas"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Tomamos una merienda en la terraza.",
            "de": "Wir hatten einen Nachmittagssnack auf der Terrasse.",
        },
    },
    {
        "id": "es-de-brindar",
        "spanish": "brindar",
        "translation": "anstoßen, einen Toast ausbringen",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/bɾinˈdaɾ/",
        "tags": [
            "🍷 social",
            "🎉 celebration",
        ],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "no"},
            {"label": "Participio pasado", "value": "brindado"},
            {"label": "Pretérito indefinido (yo)", "value": "brindé"},
            {"label": "Pretérito imperfecto (yo)", "value": "brindaba"},
            {"label": "Gerundio", "value": "brindando"},
            {
                "label": "Presente (all 6 forms)",
                "value": "brindo / brindas / brinda / brindamos / brindáis / brindan",
            },
        ],
        "departure_lang": "de",
        "example": {
            "es": "Brindamos por el nuevo año.",
            "de": "Wir stießen auf das neue Jahr an.",
        },
    },
    {
        "id": "es-de-ternura",
        "spanish": "ternura",
        "translation": "Zärtlichkeit, Herzlichkeit",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/teɾˈnu.ɾa/",
        "tags": [
            "❤️ emotions",
            "👥 people",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "ternuras"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Habló con mucha ternura.",
            "de": "Sie sprach mit großer Zärtlichkeit.",
        },
    },
    {
        "id": "es-de-inquieto",
        "spanish": "inquieto",
        "translation": "unruhig, beunruhigt",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/iŋˈkje.to/",
        "tags": [
            "🧠 emotions",
            "👥 people",
        ],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "inquieta"},
            {"label": "Plural (masc.)", "value": "inquietos"},
            {"label": "Plural (fem.)", "value": "inquietas"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "El niño estaba inquieto toda la tarde.",
            "de": "Das Kind war den ganzen Nachmittag unruhig.",
        },
    },
    {
        "id": "es-de-ni-de-broma",
        "spanish": "ni de broma",
        "translation": "auf keinen Fall, niemals im Leben",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/ni ðe ˈbɾo.ma/",
        "tags": [
            "💬 idiom",
            "😄 colloquial",
        ],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "colloquial"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Ni de broma voy a saltar desde ahí.",
            "de": "Auf keinen Fall springe ich da runter.",
        },
    },
    {
        "id": "es-de-asomarse",
        "spanish": "asomarse",
        "translation": "herausschauen, sich hinauslehnen",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/a.soˈmaɾ.se/",
        "tags": [
            "👀 movement",
            "🏠 daily life",
        ],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "yes"},
            {"label": "Participio pasado", "value": "asomado"},
            {"label": "Pretérito indefinido (yo)", "value": "asomé"},
            {"label": "Pretérito imperfecto (yo)", "value": "asomaba"},
            {"label": "Gerundio", "value": "asomando"},
            {
                "label": "Presente (all 6 forms)",
                "value": "me asomo / te asomas / se asoma / nos asomamos / os asomáis / se asoman",
            },
        ],
        "departure_lang": "de",
        "example": {
            "es": "Se asomó por la ventana para mirar la lluvia.",
            "de": "Sie lehnte sich zum Fenster hinaus, um den Regen zu beobachten.",
        },
    },
    {
        "id": "es-de-vaiven",
        "spanish": "vaivén",
        "translation": "Schaukeln, Hin-und-her-Bewegung",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/bai̯ˈβen/",
        "tags": [
            "🚆 travel",
            "🌊 movement",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "vaivenes"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "El vaivén del tren me dio sueño.",
            "de": "Das Schaukeln des Zuges machte mich schläfrig.",
        },
    },
    {
        "id": "es-de-acogedor",
        "spanish": "acogedor",
        "translation": "gemütlich, einladend",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/a.ko.xeˈðoɾ/",
        "tags": [
            "🏠 places",
            "☕ social",
        ],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "acogedora"},
            {"label": "Plural (masc.)", "value": "acogedores"},
            {"label": "Plural (fem.)", "value": "acogedoras"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Es un café pequeño y acogedor.",
            "de": "Es ist ein kleines und gemütliches Café.",
        },
    },
    {
        "id": "es-de-por-si-acaso",
        "spanish": "por si acaso",
        "translation": "nur für den Fall, für alle Fälle",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/poɾ si aˈka.so/",
        "tags": [
            "💬 idiom",
            "⛈️ weather",
        ],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "neutral"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Lleva un paraguas por si acaso.",
            "de": "Nimm einen Regenschirm mit, für alle Fälle.",
        },
    },
    {
        "id": "es-de-deslumbrar",
        "spanish": "deslumbrar",
        "translation": "blenden, verblüffen, beeindrucken",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/des.lumˈbɾaɾ/",
        "tags": [
            "✨ art",
            "🎭 performance",
        ],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "no"},
            {"label": "Participio pasado", "value": "deslumbrado"},
            {"label": "Pretérito indefinido (yo)", "value": "deslumbré"},
            {"label": "Pretérito imperfecto (yo)", "value": "deslumbraba"},
            {"label": "Gerundio", "value": "deslumbrando"},
            {
                "label": "Presente (all 6 forms)",
                "value": "deslumbro / deslumbras / deslumbra / deslumbramos / deslumbráis / deslumbran",
            },
        ],
        "departure_lang": "de",
        "example": {
            "es": "La actuación deslumbró al público.",
            "de": "Die Darbietung begeisterte das Publikum.",
        },
    },
    {
        "id": "es-de-murmullo",
        "spanish": "murmullo",
        "translation": "Murmeln, Geflüster",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/muɾˈmu.ʎo/",
        "tags": [
            "🔊 sound",
            "👥 people",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "murmullos"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Se escuchaba un murmullo en la sala.",
            "de": "Im Saal war ein Murmeln zu hören.",
        },
    },
    {
        "id": "es-de-torpe",
        "spanish": "torpe",
        "translation": "ungeschickt, tolpatschig",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/ˈtoɾ.pe/",
        "tags": [
            "👥 personality",
            "💃 movement",
        ],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "torpe"},
            {"label": "Plural (masc.)", "value": "torpes"},
            {"label": "Plural (fem.)", "value": "torpes"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Soy demasiado torpe para bailar tango.",
            "de": "Ich bin zu ungeschickt, um Tango zu tanzen.",
        },
    },
    {
        "id": "es-de-dar-en-el-clavo",
        "spanish": "dar en el clavo",
        "translation": "den Nagel auf den Kopf treffen",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/daɾ en el ˈkla.βo/",
        "tags": [
            "💬 idiom",
            "🗣️ communication",
        ],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "neutral"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Diste en el clavo con tu comentario.",
            "de": "Mit deinem Kommentar hast du den Nagel auf den Kopf getroffen.",
        },
    },
    {
        "id": "es-de-susurrar",
        "spanish": "susurrar",
        "translation": "flüstern, raunen",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/su.suˈraɾ/",
        "tags": [
            "🔊 sound",
            "❤️ emotions",
        ],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "no"},
            {"label": "Participio pasado", "value": "susurrado"},
            {"label": "Pretérito indefinido (yo)", "value": "susurré"},
            {"label": "Pretérito imperfecto (yo)", "value": "susurraba"},
            {"label": "Gerundio", "value": "susurrando"},
            {
                "label": "Presente (all 6 forms)",
                "value": "susurro / susurras / susurra / susurramos / susurráis / susurran",
            },
        ],
        "departure_lang": "de",
        "example": {
            "es": "Me susurró un secreto al oído.",
            "de": "Sie flüsterte mir ein Geheimnis ins Ohr.",
        },
    },
    {
        "id": "es-de-chispa",
        "spanish": "chispa",
        "translation": "Funken, Witz, Esprit",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/ˈtʃis.pa/",
        "tags": [
            "✨ personality",
            "🔥 energy",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "chispas"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Tiene mucha chispa cuando cuenta historias.",
            "de": "Er hat viel Witz, wenn er Geschichten erzählt.",
        },
    },
    {
        "id": "es-de-bochornoso",
        "spanish": "bochornoso",
        "translation": "peinlich, beschämend",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/bo.tʃoɾˈno.so/",
        "tags": [
            "😳 emotions",
            "👥 social",
        ],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "bochornosa"},
            {"label": "Plural (masc.)", "value": "bochornosos"},
            {"label": "Plural (fem.)", "value": "bochornosas"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Fue un momento bastante bochornoso.",
            "de": "Es war ein ziemlich peinlicher Moment.",
        },
    },
    {
        "id": "es-de-estar-en-las-nubes",
        "spanish": "estar en las nubes",
        "translation": "in den Wolken schweben, mit den Gedanken woanders sein",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/esˈtaɾ en las ˈnu.βes/",
        "tags": [
            "💬 idiom",
            "🧠 mind",
        ],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "colloquial"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Siempre está en las nubes durante las reuniones.",
            "de": "Er ist in Besprechungen immer mit den Gedanken woanders.",
        },
    },
    {
        "id": "es-de-acariciar",
        "spanish": "acariciar",
        "translation": "streicheln, liebkosen",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/a.ka.ɾiˈθjaɾ/",
        "tags": [
            "❤️ emotions",
            "🐈 animals",
        ],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "no"},
            {"label": "Participio pasado", "value": "acariciado"},
            {"label": "Pretérito indefinido (yo)", "value": "acaricié"},
            {"label": "Pretérito imperfecto (yo)", "value": "acariciaba"},
            {"label": "Gerundio", "value": "acariciando"},
            {
                "label": "Presente (all 6 forms)",
                "value": "acaricio / acaricias / acaricia / acariciamos / acariciáis / acarician",
            },
        ],
        "departure_lang": "de",
        "example": {
            "es": "Acarició al gato mientras leía.",
            "de": "Sie streichelte die Katze, während sie las.",
        },
    },
    {
        "id": "es-de-amanecer",
        "spanish": "amanecer",
        "translation": "Morgendämmerung, Sonnenaufgang",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/a.ma.neˈθeɾ/",
        "tags": [
            "🌅 nature",
            "⏳ time",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "amaneceres"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Salimos a caminar al amanecer.",
            "de": "Wir gingen bei Sonnenaufgang spazieren.",
        },
    },
    {
        "id": "es-de-nostalgico",
        "spanish": "nostálgico",
        "translation": "nostalgisch",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/nosˈtal.xi.ko/",
        "tags": [
            "❤️ emotions",
            "🎵 music",
        ],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "nostálgica"},
            {"label": "Plural (masc.)", "value": "nostálgicos"},
            {"label": "Plural (fem.)", "value": "nostálgicas"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Esa canción me pone nostálgico.",
            "de": "Dieses Lied macht mich nostalgisch.",
        },
    },
    {
        "id": "es-de-sin-rumbo",
        "spanish": "sin rumbo",
        "translation": "ziellos, ohne Richtung",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/sin ˈrum.bo/",
        "tags": [
            "🚶 movement",
            "🌆 travel",
        ],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "neutral"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Caminamos sin rumbo por la ciudad.",
            "de": "Wir schlenderten ziellos durch die Stadt.",
        },
    },
    {
        "id": "es-de-desahogarse",
        "spanish": "desahogarse",
        "translation": "sich Luft machen, sein Herz ausschütten",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/de.sa.oˈɣaɾ.se/",
        "tags": [
            "❤️ emotions",
            "🧠 mental",
        ],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "yes"},
            {"label": "Participio pasado", "value": "desahogado"},
            {"label": "Pretérito indefinido (yo)", "value": "desahogué"},
            {"label": "Pretérito imperfecto (yo)", "value": "desahogaba"},
            {"label": "Gerundio", "value": "desahogando"},
            {
                "label": "Presente (all 6 forms)",
                "value": "me desahogo / te desahogas / se desahoga / nos desahogamos / os desahogáis / se desahogan",
            },
        ],
        "departure_lang": "de",
        "example": {
            "es": "Necesitaba desahogarse después del trabajo.",
            "de": "Sie musste sich nach der Arbeit Luft machen.",
        },
    },
    {
        "id": "es-de-remolino",
        "spanish": "remolino",
        "translation": "Wirbel, Strudel",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/re.moˈli.no/",
        "tags": [
            "🌪️ weather",
            "🌿 nature",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "remolinos"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "El viento levantó un remolino de hojas.",
            "de": "Der Wind wirbelte einen Strudel aus Blättern auf.",
        },
    },
    {
        "id": "es-de-peculiar",
        "spanish": "peculiar",
        "translation": "eigenartig, eigentümlich",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/pe.kuˈljaɾ/",
        "tags": [
            "👥 personality",
            "🗣️ communication",
        ],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "peculiar"},
            {"label": "Plural (masc.)", "value": "peculiares"},
            {"label": "Plural (fem.)", "value": "peculiares"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Tiene una forma peculiar de hablar.",
            "de": "Er hat eine eigenartige Art zu sprechen.",
        },
    },
    {
        "id": "es-de-de-vez-en-cuando",
        "spanish": "de vez en cuando",
        "translation": "von Zeit zu Zeit, gelegentlich",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/de βeθ en ˈkwan.do/",
        "tags": [
            "💬 idiom",
            "⏳ time",
        ],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "neutral"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "De vez en cuando me gusta desconectar del móvil.",
            "de": "Von Zeit zu Zeit mag ich es, das Handy auszuschalten.",
        },
    },
    {
        "id": "es-de-tropezar",
        "spanish": "tropezar",
        "translation": "stolpern, straucheln",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/tɾo.peˈθaɾ/",
        "tags": [
            "🚶 movement",
            "🌿 nature",
        ],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "no"},
            {"label": "Participio pasado", "value": "tropezado"},
            {"label": "Pretérito indefinido (yo)", "value": "tropecé"},
            {"label": "Pretérito imperfecto (yo)", "value": "tropezaba"},
            {"label": "Gerundio", "value": "tropezando"},
            {
                "label": "Presente (all 6 forms)",
                "value": "tropiezo / tropiezas / tropieza / tropezamos / tropezáis / tropiezan",
            },
        ],
        "departure_lang": "de",
        "example": {
            "es": "Tropecé con una piedra en el camino.",
            "de": "Ich stolperte über einen Stein auf dem Weg.",
        },
    },
    {
        "id": "es-de-latido",
        "spanish": "latido",
        "translation": "Herzschlag, Puls",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/laˈti.ðo/",
        "tags": [
            "❤️ body",
            "🎵 rhythm",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "latidos"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Escuchó el latido de su corazón.",
            "de": "Sie hörte den Schlag ihres Herzens.",
        },
    },
    {
        "id": "es-de-desbordante",
        "spanish": "desbordante",
        "translation": "übersprudelnd, überwältigend",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/des.boɾˈðan.te/",
        "tags": [
            "🔥 energy",
            "👥 personality",
        ],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "desbordante"},
            {"label": "Plural (masc.)", "value": "desbordantes"},
            {"label": "Plural (fem.)", "value": "desbordantes"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Tiene una energía desbordante.",
            "de": "Sie hat eine übersprudelnde Energie.",
        },
    },
    {
        "id": "es-de-costar-un-ojo",
        "spanish": "costar un ojo de la cara",
        "translation": "ein Vermögen kosten",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/kosˈtaɾ un ˈo.xo ðe la ˈka.ɾa/",
        "tags": [
            "💬 idiom",
            "💰 money",
        ],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "colloquial"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Ese apartamento cuesta un ojo de la cara.",
            "de": "Diese Wohnung kostet ein Vermögen.",
        },
    },
    {
        "id": "es-de-hojear",
        "spanish": "hojear",
        "translation": "durchblättern, überfliegen",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/o.xeˈaɾ/",
        "tags": [
            "📚 learning",
            "⏳ daily life",
        ],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "no"},
            {"label": "Participio pasado", "value": "hojeado"},
            {"label": "Pretérito indefinido (yo)", "value": "hojeé"},
            {"label": "Pretérito imperfecto (yo)", "value": "hojeaba"},
            {"label": "Gerundio", "value": "hojeando"},
            {
                "label": "Presente (all 6 forms)",
                "value": "hojeo / hojeas / hojea / hojeamos / hojeáis / hojean",
            },
        ],
        "departure_lang": "de",
        "example": {
            "es": "Hojeé una revista mientras esperaba.",
            "de": "Ich blätterte eine Zeitschrift durch, während ich wartete.",
        },
    },
    {
        "id": "es-de-anhelo",
        "spanish": "anhelo",
        "translation": "Sehnsucht, tiefer Wunsch",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/aˈne.lo/",
        "tags": [
            "❤️ emotions",
            "🌊 nature",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "anhelos"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Sintió un anhelo profundo de volver al mar.",
            "de": "Sie spürte eine tiefe Sehnsucht, ans Meer zurückzukehren.",
        },
    },
    {
        "id": "es-de-efimero",
        "spanish": "efímero",
        "translation": "vergänglich, kurzlebig",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/eˈfi.me.ɾo/",
        "tags": [
            "⏳ time",
            "🎨 art",
        ],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "efímera"},
            {"label": "Plural (masc.)", "value": "efímeros"},
            {"label": "Plural (fem.)", "value": "efímeras"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "La belleza del momento era efímera.",
            "de": "Die Schönheit des Augenblicks war vergänglich.",
        },
    },
    {
        "id": "es-de-meter-la-pata",
        "spanish": "meter la pata",
        "translation": "ins Fettnäpfchen treten, einen Bock schießen",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/meˈteɾ la ˈpa.ta/",
        "tags": [
            "💬 idiom",
            "😳 mistakes",
        ],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "colloquial"},
        ],
        "departure_lang": "de",
        "example": {
            "es": "Metí la pata durante la entrevista.",
            "de": "Ich habe während des Vorstellungsgesprächs ins Fettnäpfchen getreten.",
        },
    },
    {
        "id": "es-de-tambalearse",
        "spanish": "tambalearse",
        "translation": "taumeln, wackeln",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/tam.ba.leˈaɾ.se/",
        "tags": [
            "🚶 movement",
            "⚡ intensity",
        ],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "yes"},
            {"label": "Participio pasado", "value": "tambaleado"},
            {"label": "Pretérito indefinido (yo)", "value": "tambaleé"},
            {"label": "Pretérito imperfecto (yo)", "value": "tambaleaba"},
            {"label": "Gerundio", "value": "tambaleando"},
            {
                "label": "Presente (all 6 forms)",
                "value": "me tambaleo / te tambaleas / se tambalea / nos tambaleamos / os tambaleáis / se tambalean",
            },
        ],
        "departure_lang": "de",
        "example": {
            "es": "El ciclista empezó a tambalearse.",
            "de": "Der Radfahrer begann zu taumeln.",
        },
    },
]
