"""
es_el_vocab_data.py — Spanish vocabulary cards for Greek speakers (departure_lang='el').
Imported automatically by es_vocab_data.py.
"""

CARDS = [
    {
        "id": "es-el-sobremesa",
        "spanish": "sobremesa",
        "translation": "συζήτηση μετά το φαγητό, κουβέντα στο τραπέζι",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/so.βɾeˈme.sa/",
        'etymology': 'Από το sobre («πάνω») + mesa («τραπέζι»).',
        "note": "Συνδέεται στενά με την κοινωνική κουλτούρα των ισπανόφωνων χωρών.",
        "tags": [
            "⭐ common",
            "🍽️ food",
            "🗣️ culture",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "sobremesas"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Disfrutamos de una larga sobremesa después de la cena.",
            "el": "Απολαύσαμε μια μακρά συζήτηση μετά το δείπνο.",
        },
    },
    {
        "id": "es-el-desvelarse",
        "spanish": "desvelarse",
        "translation": "να μένεις ξύπνιος, να χάνεις τον ύπνο",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/des.βeˈlaɾ.se/",
        "note": "Συχνά υπονοεί ακούσια αϋπνία.",
        "tags": [
            "⭐ common",
            "🌙 night",
            "🧠 emotions",
        ],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "yes"},
            {"label": "Participio pasado", "value": "desvelado"},
            {"label": "Pretérito indefinido (yo)", "value": "desvelé"},
            {"label": "Pretérito imperfecto (yo)", "value": "desvelaba"},
            {"label": "Gerundio", "value": "desvelando"},
            {
                "label": "Presente (all 6 forms)",
                "value": "me desvelo / te desvelas / se desvela / nos desvelamos / os desveláis / se desvelan",
            },
        ],
        "departure_lang": "el",
        "example": {
            "es": "Me desvelé pensando en el examen.",
            "el": "Έμεινα ξύπνιος σκεφτόμενος τις εξετάσεις.",
        },
    },
    {
        "id": "es-el-relampago",
        "spanish": "relámpago",
        "translation": "κεραυνός, αστραπή",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/reˈlam.pa.ɣo/",
        "etymology": "Πιθανώς από το relampaguear.",
        "tags": [
            "⭐ common",
            "⛈️ weather",
            "🌿 nature",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "relámpagos"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Un relámpago iluminó toda la montaña.",
            "el": "Μια αστραπή φώτισε ολόκληρο το βουνό.",
        },
    },
    {
        "id": "es-el-entrañable",
        "spanish": "entrañable",
        "translation": "αγαπητός, εγκάρδιος, αξιαγάπητος",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/en.tɾaˈɲa.βle/",
        'etymology': 'Από το entraña («το βαθύτερο μέρος, τα σωθικά»).',
        "note": "Χρησιμοποιείται συχνά για ζεστούς ανθρώπους ή συναισθηματικές αναμνήσεις.",
        "tags": [
            "⭐ common",
            "❤️ emotions",
            "👥 people",
        ],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "entrañable"},
            {"label": "Plural (masc.)", "value": "entrañables"},
            {"label": "Plural (fem.)", "value": "entrañables"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Fue una conversación entrañable entre amigos.",
            "el": "Ήταν μια εγκάρδια συζήτηση μεταξύ φίλων.",
        },
    },
    {
        "id": "es-el-a-duras-penas",
        "spanish": "a duras penas",
        "translation": "μόλις και μετά βίας, με μεγάλη δυσκολία",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/a ˈdu.ɾas ˈpe.nas/",
        "note": "Κοινή ιδιωματική έκφραση.",
        "tags": [
            "⭐ common",
            "💬 idiom",
            "🏃 effort",
        ],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "neutral"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Llegó a duras penas al final de la carrera.",
            "el": "Έφτασε μόλις και μετά βίας στο τέλος της κούρσας.",
        },
    },
    {
        "id": "es-el-madrugar",
        "spanish": "madrugar",
        "translation": "να ξυπνάς νωρίς",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/ma.dɾuˈɣaɾ/",
        "tags": [
            "⭐ common",
            "⏰ daily life",
        ],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "no"},
            {"label": "Participio pasado", "value": "madrugado"},
            {"label": "Pretérito indefinido (yo)", "value": "madrugué"},
            {"label": "Pretérito imperfecto (yo)", "value": "madrugaba"},
            {"label": "Gerundio", "value": "madrugando"},
            {
                "label": "Presente (all 6 forms)",
                "value": "madrugo / madrugas / madruga / madrugamos / madrugáis / madrugan",
            },
        ],
        "departure_lang": "el",
        "example": {
            "es": "No me gusta madrugar los domingos.",
            "el": "Δεν μου αρέσει να ξυπνάω νωρίς τις Κυριακές.",
        },
    },
    {
        "id": "es-el-rincon",
        "spanish": "rincón",
        "translation": "γωνία, γωνιά",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/rinˈkon/",
        "tags": [
            "⭐ common",
            "🏠 places",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "rincones"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Encontramos un rincón tranquilo en la biblioteca.",
            "el": "Βρήκαμε μια ήσυχη γωνιά στη βιβλιοθήκη.",
        },
    },
    {
        "id": "es-el-ojala",
        "spanish": "ojalá",
        "translation": "μακάρι, ελπίζω",
        "type": "adverb",
        "scene_id": "💃 Curated",
        "pronunciation": "/o.xaˈla/",
        'etymology': 'Από τα αραβικά law šá lláh («αν θέλει ο Θεός»).',
        "note": "Συχνά ακολουθείται από ρήματα σε υποτακτική έγκλιση.",
        "tags": [
            "⭐ common",
            "💭 wishes",
            "🗣️ culture",
        ],
        "priority": True,
        "departure_lang": "el",
        "example": {
            "es": "Ojalá llueva mañana.",
            "el": "Μακάρι να βρέξει αύριο.",
        },
    },
    {
        "id": "es-el-aguacero",
        "spanish": "aguacero",
        "translation": "καταρρακτώδης βροχή, μπόρα",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/a.ɣwaˈθe.ɾo/",
        "tags": [
            "⛈️ weather",
            "🌿 nature",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "aguaceros"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Nos sorprendió un aguacero en mitad del paseo.",
            "el": "Μια μπόρα μας έπιασε στη μέση της βόλτας.",
        },
    },
    {
        "id": "es-el-despistado",
        "spanish": "despistado",
        "translation": "αφηρημένος, απρόσεκτος",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/des.pisˈta.ðo/",
        "tags": [
            "⭐ common",
            "🧠 personality",
        ],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "despistada"},
            {"label": "Plural (masc.)", "value": "despistados"},
            {"label": "Plural (fem.)", "value": "despistadas"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Soy tan despistado que olvidé las llaves otra vez.",
            "el": "Είμαι τόσο αφηρημένος που ξέχασα ξανά τα κλειδιά.",
        },
    },
    {
        "id": "es-el-echar-de-menos",
        "spanish": "echar de menos",
        "translation": "να μου λείπει κάποιος, να νοσταλγώ",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/eˈtʃaɾ ðe ˈme.nos/",
        'note': 'Ο κανονικός τρόπος να εκφράσεις ότι σου λείπει κάποιος.',
        "tags": [
            "⭐ common",
            "❤️ emotions",
            "✈️ travel",
        ],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "neutral"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Echo de menos a mi familia cuando viajo.",
            "el": "Μου λείπει η οικογένειά μου όταν ταξιδεύω.",
        },
    },
    {
        "id": "es-el-curiosear",
        "spanish": "curiosear",
        "translation": "να κοιτάζεις με περιέργεια, να ψάχνεις",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/ku.ɾjo.seˈaɾ/",
        "tags": [
            "📚 learning",
            "👀 curiosity",
        ],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "no"},
            {"label": "Participio pasado", "value": "curioseado"},
            {"label": "Pretérito indefinido (yo)", "value": "curioseé"},
            {"label": "Pretérito imperfecto (yo)", "value": "curioseaba"},
            {"label": "Gerundio", "value": "curioseando"},
            {
                "label": "Presente (all 6 forms)",
                "value": "curioseo / curioseas / curiosea / curioseamos / curioseáis / curiosean",
            },
        ],
        "departure_lang": "el",
        "example": {
            "es": "Le gusta curiosear en las librerías antiguas.",
            "el": "Της αρέσει να ψάχνει σε παλαιοβιβλιοπωλεία.",
        },
    },
    {
        "id": "es-el-brillo",
        "spanish": "brillo",
        "translation": "λάμψη, αστραφτερό φως, λαμπρότητα",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/ˈbɾi.ʎo/",
        "tags": [
            "✨ appearance",
            "🎨 art",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "brillos"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Sus ojos tenían un brillo especial.",
            "el": "Τα μάτια της είχαν μια ξεχωριστή λάμψη.",
        },
    },
    {
        "id": "es-el-fugaz",
        "spanish": "fugaz",
        "translation": "παροδικός, εφήμερος",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/fuˈɣaθ/",
        "tags": [
            "⏳ time",
            "❤️ emotions",
        ],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "fugaz"},
            {"label": "Plural (masc.)", "value": "fugaces"},
            {"label": "Plural (fem.)", "value": "fugaces"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Tuvieron un encuentro fugaz en la estación.",
            "el": "Είχαν μια σύντομη συνάντηση στον σταθμό.",
        },
    },
    {
        "id": "es-el-de-golpe",
        "spanish": "de golpe",
        "translation": "ξαφνικά, μονομιάς",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/de ˈɣol.pe/",
        "tags": [
            "💬 idiom",
            "⚡ intensity",
        ],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "neutral"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Todo cambió de golpe.",
            "el": "Όλα άλλαξαν ξαφνικά.",
        },
    },
    {
        "id": "es-el-merienda",
        "spanish": "merienda",
        "translation": "απογευματινό σνακ, ελαφρύ γεύμα",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/meˈɾjen.da/",
        "tags": [
            "🍽️ food",
            "☀️ daily life",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "meriendas"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Tomamos una merienda en la terraza.",
            "el": "Φάγαμε ένα απογευματινό σνακ στη βεράντα.",
        },
    },
    {
        "id": "es-el-brindar",
        "spanish": "brindar",
        "translation": "να κάνεις πρόποση, να πίνεις στην υγεία",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/bɾinˈdaɾ/",
        "tags": [
            "🍷 social",
            "🎉 celebration",
        ],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "no"},
            {"label": "Participio pasado", "value": "brindado"},
            {"label": "Pretérito indefinido (yo)", "value": "brindé"},
            {"label": "Pretérito imperfecto (yo)", "value": "brindaba"},
            {"label": "Gerundio", "value": "brindando"},
            {
                "label": "Presente (all 6 forms)",
                "value": "brindo / brindas / brinda / brindamos / brindáis / brindan",
            },
        ],
        "departure_lang": "el",
        "example": {
            "es": "Brindamos por el nuevo año.",
            "el": "Κάναμε πρόποση για το νέο έτος.",
        },
    },
    {
        "id": "es-el-ternura",
        "spanish": "ternura",
        "translation": "τρυφερότητα, στοργή",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/teɾˈnu.ɾa/",
        "tags": [
            "❤️ emotions",
            "👥 people",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "ternuras"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Habló con mucha ternura.",
            "el": "Μίλησε με πολλή τρυφερότητα.",
        },
    },
    {
        "id": "es-el-inquieto",
        "spanish": "inquieto",
        "translation": "ανήσυχος, αναστατωμένος",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/iŋˈkje.to/",
        "tags": [
            "🧠 emotions",
            "👥 people",
        ],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "inquieta"},
            {"label": "Plural (masc.)", "value": "inquietos"},
            {"label": "Plural (fem.)", "value": "inquietas"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "El niño estaba inquieto toda la tarde.",
            "el": "Το παιδί ήταν ανήσυχο όλο το απόγευμα.",
        },
    },
    {
        "id": "es-el-ni-de-broma",
        "spanish": "ni de broma",
        "translation": "σε καμία περίπτωση, ούτε στο όνειρό μου",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/ni ðe ˈbɾo.ma/",
        "tags": [
            "💬 idiom",
            "😄 colloquial",
        ],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "colloquial"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Ni de broma voy a saltar desde ahí.",
            "el": "Σε καμία περίπτωση δεν θα πηδήξω από εκεί.",
        },
    },
    {
        "id": "es-el-asomarse",
        "spanish": "asomarse",
        "translation": "να κοιτάζεις έξω, να σκύβεις έξω",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/a.soˈmaɾ.se/",
        "tags": [
            "👀 movement",
            "🏠 daily life",
        ],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "yes"},
            {"label": "Participio pasado", "value": "asomado"},
            {"label": "Pretérito indefinido (yo)", "value": "asomé"},
            {"label": "Pretérito imperfecto (yo)", "value": "asomaba"},
            {"label": "Gerundio", "value": "asomando"},
            {
                "label": "Presente (all 6 forms)",
                "value": "me asomo / te asomas / se asoma / nos asomamos / os asomáis / se asoman",
            },
        ],
        "departure_lang": "el",
        "example": {
            "es": "Se asomó por la ventana para mirar la lluvia.",
            "el": "Έσκυψε έξω από το παράθυρο για να κοιτάξει τη βροχή.",
        },
    },
    {
        "id": "es-el-vaiven",
        "spanish": "vaivén",
        "translation": "αιώρηση, κίνηση πέρα-δώθε",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/bai̯ˈβen/",
        "tags": [
            "🚆 travel",
            "🌊 movement",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "vaivenes"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "El vaivén del tren me dio sueño.",
            "el": "Η αιώρηση του τρένου με νύσταξε.",
        },
    },
    {
        "id": "es-el-acogedor",
        "spanish": "acogedor",
        "translation": "άνετος, φιλόξενος",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/a.ko.xeˈðoɾ/",
        "tags": [
            "🏠 places",
            "☕ social",
        ],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "acogedora"},
            {"label": "Plural (masc.)", "value": "acogedores"},
            {"label": "Plural (fem.)", "value": "acogedoras"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Es un café pequeño y acogedor.",
            "el": "Είναι ένα μικρό και άνετο καφέ.",
        },
    },
    {
        "id": "es-el-por-si-acaso",
        "spanish": "por si acaso",
        "translation": "για κάθε ενδεχόμενο, μήπως και",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/poɾ si aˈka.so/",
        "tags": [
            "💬 idiom",
            "⛈️ weather",
        ],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "neutral"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Lleva un paraguas por si acaso.",
            "el": "Πάρε μια ομπρέλα για κάθε ενδεχόμενο.",
        },
    },
    {
        "id": "es-el-deslumbrar",
        "spanish": "deslumbrar",
        "translation": "να εντυπωσιάζεις, να εκθαμβώνεις",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/des.lumˈbɾaɾ/",
        "tags": [
            "✨ art",
            "🎭 performance",
        ],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "no"},
            {"label": "Participio pasado", "value": "deslumbrado"},
            {"label": "Pretérito indefinido (yo)", "value": "deslumbré"},
            {"label": "Pretérito imperfecto (yo)", "value": "deslumbraba"},
            {"label": "Gerundio", "value": "deslumbrando"},
            {
                "label": "Presente (all 6 forms)",
                "value": "deslumbro / deslumbras / deslumbra / deslumbramos / deslumbráis / deslumbran",
            },
        ],
        "departure_lang": "el",
        "example": {
            "es": "La actuación deslumbró al público.",
            "el": "Η παράσταση εξέθαμβε το κοινό.",
        },
    },
    {
        "id": "es-el-murmullo",
        "spanish": "murmullo",
        "translation": "μουρμουρητό, ψίθυρος",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/muɾˈmu.ʎo/",
        "tags": [
            "🔊 sound",
            "👥 people",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "murmullos"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Se escuchaba un murmullo en la sala.",
            "el": "Ακουγόταν ένα μουρμουρητό στην αίθουσα.",
        },
    },
    {
        "id": "es-el-torpe",
        "spanish": "torpe",
        "translation": "αδέξιος, αδέξιος στις κινήσεις",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/ˈtoɾ.pe/",
        "tags": [
            "👥 personality",
            "💃 movement",
        ],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "torpe"},
            {"label": "Plural (masc.)", "value": "torpes"},
            {"label": "Plural (fem.)", "value": "torpes"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Soy demasiado torpe para bailar tango.",
            "el": "Είμαι πολύ αδέξιος για να χορέψω τανγκό.",
        },
    },
    {
        "id": "es-el-dar-en-el-clavo",
        "spanish": "dar en el clavo",
        "translation": "να χτυπάς το καρφί στο κεφάλι, να βρίσκεις ακριβώς",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/daɾ en el ˈkla.βo/",
        "tags": [
            "💬 idiom",
            "🗣️ communication",
        ],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "neutral"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Diste en el clavo con tu comentario.",
            "el": "Με το σχόλιό σου το είπες ακριβώς.",
        },
    },
    {
        "id": "es-el-susurrar",
        "spanish": "susurrar",
        "translation": "να ψιθυρίζεις",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/su.suˈraɾ/",
        "tags": [
            "🔊 sound",
            "❤️ emotions",
        ],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "no"},
            {"label": "Participio pasado", "value": "susurrado"},
            {"label": "Pretérito indefinido (yo)", "value": "susurré"},
            {"label": "Pretérito imperfecto (yo)", "value": "susurraba"},
            {"label": "Gerundio", "value": "susurrando"},
            {
                "label": "Presente (all 6 forms)",
                "value": "susurro / susurras / susurra / susurramos / susurráis / susurran",
            },
        ],
        "departure_lang": "el",
        "example": {
            "es": "Me susurró un secreto al oído.",
            "el": "Μου ψιθύρισε ένα μυστικό στο αυτί.",
        },
    },
    {
        "id": "es-el-chispa",
        "spanish": "chispa",
        "translation": "σπίθα, εξυπνάδα, σβελτάδα",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/ˈtʃis.pa/",
        "tags": [
            "✨ personality",
            "🔥 energy",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "chispas"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Tiene mucha chispa cuando cuenta historias.",
            "el": "Έχει πολλή σβελτάδα όταν διηγείται ιστορίες.",
        },
    },
    {
        "id": "es-el-bochornoso",
        "spanish": "bochornoso",
        "translation": "αμήχανος, ντροπιαστικός",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/bo.tʃoɾˈno.so/",
        "tags": [
            "😳 emotions",
            "👥 social",
        ],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "bochornosa"},
            {"label": "Plural (masc.)", "value": "bochornosos"},
            {"label": "Plural (fem.)", "value": "bochornosas"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Fue un momento bastante bochornoso.",
            "el": "Ήταν μια αρκετά αμήχανη στιγμή.",
        },
    },
    {
        "id": "es-el-estar-en-las-nubes",
        "spanish": "estar en las nubes",
        "translation": "να ονειροπολείς, να είσαι αφηρημένος",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/esˈtaɾ en las ˈnu.βes/",
        "tags": [
            "💬 idiom",
            "🧠 mind",
        ],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "colloquial"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Siempre está en las nubes durante las reuniones.",
            "el": "Πάντα ονειροπολεί κατά τη διάρκεια των συναντήσεων.",
        },
    },
    {
        "id": "es-el-acariciar",
        "spanish": "acariciar",
        "translation": "να χαϊδεύεις, να χαϊδολογείς",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/a.ka.ɾiˈθjaɾ/",
        "tags": [
            "❤️ emotions",
            "🐈 animals",
        ],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "no"},
            {"label": "Participio pasado", "value": "acariciado"},
            {"label": "Pretérito indefinido (yo)", "value": "acaricié"},
            {"label": "Pretérito imperfecto (yo)", "value": "acariciaba"},
            {"label": "Gerundio", "value": "acariciando"},
            {
                "label": "Presente (all 6 forms)",
                "value": "acaricio / acaricias / acaricia / acariciamos / acariciáis / acarician",
            },
        ],
        "departure_lang": "el",
        "example": {
            "es": "Acarició al gato mientras leía.",
            "el": "Χάιδευε τη γάτα ενώ διάβαζε.",
        },
    },
    {
        "id": "es-el-amanecer",
        "spanish": "amanecer",
        "translation": "αυγή, ανατολή του ηλίου",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/a.ma.neˈθeɾ/",
        "tags": [
            "🌅 nature",
            "⏳ time",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "amaneceres"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Salimos a caminar al amanecer.",
            "el": "Βγήκαμε για περίπατο στην αυγή.",
        },
    },
    {
        "id": "es-el-nostalgico",
        "spanish": "nostálgico",
        "translation": "νοσταλγικός",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/nosˈtal.xi.ko/",
        "tags": [
            "❤️ emotions",
            "🎵 music",
        ],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "nostálgica"},
            {"label": "Plural (masc.)", "value": "nostálgicos"},
            {"label": "Plural (fem.)", "value": "nostálgicas"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Esa canción me pone nostálgico.",
            "el": "Αυτό το τραγούδι με κάνει νοσταλγικό.",
        },
    },
    {
        "id": "es-el-sin-rumbo",
        "spanish": "sin rumbo",
        "translation": "άσκοπα, χωρίς κατεύθυνση",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/sin ˈrum.bo/",
        "tags": [
            "🚶 movement",
            "🌆 travel",
        ],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "neutral"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Caminamos sin rumbo por la ciudad.",
            "el": "Περπατήσαμε άσκοπα μέσα στην πόλη.",
        },
    },
    {
        "id": "es-el-desahogarse",
        "spanish": "desahogarse",
        "translation": "να ξεσπάς, να αδειάζεις τον εαυτό σου",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/de.sa.oˈɣaɾ.se/",
        "tags": [
            "❤️ emotions",
            "🧠 mental",
        ],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "yes"},
            {"label": "Participio pasado", "value": "desahogado"},
            {"label": "Pretérito indefinido (yo)", "value": "desahogué"},
            {"label": "Pretérito imperfecto (yo)", "value": "desahogaba"},
            {"label": "Gerundio", "value": "desahogando"},
            {
                "label": "Presente (all 6 forms)",
                "value": "me desahogo / te desahogas / se desahoga / nos desahogamos / os desahogáis / se desahogan",
            },
        ],
        "departure_lang": "el",
        "example": {
            "es": "Necesitaba desahogarse después del trabajo.",
            "el": "Έπρεπε να ξεσπάσει μετά τη δουλειά.",
        },
    },
    {
        "id": "es-el-remolino",
        "spanish": "remolino",
        "translation": "δίνη, στρόβιλος",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/re.moˈli.no/",
        "tags": [
            "🌪️ weather",
            "🌿 nature",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "remolinos"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "El viento levantó un remolino de hojas.",
            "el": "Ο άνεμος σήκωσε ένα στρόβιλο από φύλλα.",
        },
    },
    {
        "id": "es-el-peculiar",
        "spanish": "peculiar",
        "translation": "ιδιαίτερος, χαρακτηριστικός",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/pe.kuˈljaɾ/",
        "tags": [
            "👥 personality",
            "🗣️ communication",
        ],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "peculiar"},
            {"label": "Plural (masc.)", "value": "peculiares"},
            {"label": "Plural (fem.)", "value": "peculiares"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Tiene una forma peculiar de hablar.",
            "el": "Έχει έναν ιδιαίτερο τρόπο ομιλίας.",
        },
    },
    {
        "id": "es-el-de-vez-en-cuando",
        "spanish": "de vez en cuando",
        "translation": "κατά καιρούς, περιστασιακά",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/de βeθ en ˈkwan.do/",
        "tags": [
            "💬 idiom",
            "⏳ time",
        ],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "neutral"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "De vez en cuando me gusta desconectar del móvil.",
            "el": "Κατά καιρούς μου αρέσει να αποσυνδέομαι από το κινητό.",
        },
    },
    {
        "id": "es-el-tropezar",
        "spanish": "tropezar",
        "translation": "να σκοντάφτεις, να παραπατάς",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/tɾo.peˈθaɾ/",
        "tags": [
            "🚶 movement",
            "🌿 nature",
        ],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "no"},
            {"label": "Participio pasado", "value": "tropezado"},
            {"label": "Pretérito indefinido (yo)", "value": "tropecé"},
            {"label": "Pretérito imperfecto (yo)", "value": "tropezaba"},
            {"label": "Gerundio", "value": "tropezando"},
            {
                "label": "Presente (all 6 forms)",
                "value": "tropiezo / tropiezas / tropieza / tropezamos / tropezáis / tropiezan",
            },
        ],
        "departure_lang": "el",
        "example": {
            "es": "Tropecé con una piedra en el camino.",
            "el": "Σκόνταψα σε μια πέτρα στο δρόμο.",
        },
    },
    {
        "id": "es-el-latido",
        "spanish": "latido",
        "translation": "καρδιοχτύπι, παλμός",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/laˈti.ðo/",
        "tags": [
            "❤️ body",
            "🎵 rhythm",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "latidos"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Escuchó el latido de su corazón.",
            "el": "Άκουσε τον χτύπο της καρδιάς της.",
        },
    },
    {
        "id": "es-el-desbordante",
        "spanish": "desbordante",
        "translation": "ξεχειλιστός, ακατάσχετος",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/des.boɾˈðan.te/",
        "tags": [
            "🔥 energy",
            "👥 personality",
        ],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "desbordante"},
            {"label": "Plural (masc.)", "value": "desbordantes"},
            {"label": "Plural (fem.)", "value": "desbordantes"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Tiene una energía desbordante.",
            "el": "Έχει μια ξεχειλιστή ενέργεια.",
        },
    },
    {
        "id": "es-el-costar-un-ojo",
        "spanish": "costar un ojo de la cara",
        "translation": "να κοστίζει μια περιουσία",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/kosˈtaɾ un ˈo.xo ðe la ˈka.ɾa/",
        "tags": [
            "💬 idiom",
            "💰 money",
        ],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "colloquial"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Ese apartamento cuesta un ojo de la cara.",
            "el": "Αυτό το διαμέρισμα κοστίζει μια περιουσία.",
        },
    },
    {
        "id": "es-el-hojear",
        "spanish": "hojear",
        "translation": "να ξεφυλλίζεις, να ξεφυλλώνεις",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/o.xeˈaɾ/",
        "tags": [
            "📚 learning",
            "⏳ daily life",
        ],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "no"},
            {"label": "Participio pasado", "value": "hojeado"},
            {"label": "Pretérito indefinido (yo)", "value": "hojeé"},
            {"label": "Pretérito imperfecto (yo)", "value": "hojeaba"},
            {"label": "Gerundio", "value": "hojeando"},
            {
                "label": "Presente (all 6 forms)",
                "value": "hojeo / hojeas / hojea / hojeamos / hojeáis / hojean",
            },
        ],
        "departure_lang": "el",
        "example": {
            "es": "Hojeé una revista mientras esperaba.",
            "el": "Ξεφύλλισα ένα περιοδικό ενώ περίμενα.",
        },
    },
    {
        "id": "es-el-anhelo",
        "spanish": "anhelo",
        "translation": "νοσταλγία, λαχτάρα",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/aˈne.lo/",
        "tags": [
            "❤️ emotions",
            "🌊 nature",
        ],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "anhelos"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Sintió un anhelo profundo de volver al mar.",
            "el": "Ένιωσε βαθιά λαχτάρα να επιστρέψει στη θάλασσα.",
        },
    },
    {
        "id": "es-el-efimero",
        "spanish": "efímero",
        "translation": "εφήμερος, βραχύβιος",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/eˈfi.me.ɾo/",
        "tags": [
            "⏳ time",
            "🎨 art",
        ],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "efímera"},
            {"label": "Plural (masc.)", "value": "efímeros"},
            {"label": "Plural (fem.)", "value": "efímeras"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "La belleza del momento era efímera.",
            "el": "Η ομορφιά της στιγμής ήταν εφήμερη.",
        },
    },
    {
        "id": "es-el-meter-la-pata",
        "spanish": "meter la pata",
        "translation": "να τη σκαλώνεις, να κάνεις γκάφα",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/meˈteɾ la ˈpa.ta/",
        "tags": [
            "💬 idiom",
            "😳 mistakes",
        ],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "colloquial"},
        ],
        "departure_lang": "el",
        "example": {
            "es": "Metí la pata durante la entrevista.",
            "el": "Την έσκαλα κατά τη διάρκεια της συνέντευξης.",
        },
    },
    {
        "id": "es-el-tambalearse",
        "spanish": "tambalearse",
        "translation": "να ζαλίζεσαι, να τρικλίζεις",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/tam.ba.leˈaɾ.se/",
        "tags": [
            "🚶 movement",
            "⚡ intensity",
        ],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "yes"},
            {"label": "Participio pasado", "value": "tambaleado"},
            {"label": "Pretérito indefinido (yo)", "value": "tambaleé"},
            {"label": "Pretérito imperfecto (yo)", "value": "tambaleaba"},
            {"label": "Gerundio", "value": "tambaleando"},
            {
                "label": "Presente (all 6 forms)",
                "value": "me tambaleo / te tambaleas / se tambalea / nos tambaleamos / os tambaleáis / se tambalean",
            },
        ],
        "departure_lang": "el",
        "example": {
            "es": "El ciclista empezó a tambalearse.",
            "el": "Ο ποδηλάτης άρχισε να τρικλίζει.",
        },
    },
]
