"""
es_vocab_data.py — Spanish vocabulary preset cards.

Grammar label reference (use these EXACTLY):
  Noun:      Gender | Plural
  Verb:      Verb type | Reflexive | Participio pasado | Pretérito indefinido (yo) | Pretérito imperfecto (yo) | Gerundio | Presente (all 6 forms)
  Adjective: Feminine form | Plural (masc.) | Plural (fem.)
  Phrase:    Register
"""

CARDS = [
    {
        "id": "es-sobremesa",
        "spanish": "sobremesa",
        "translation": "after-dinner conversation, table talk",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/so.βɾeˈme.sa/",
        "etymology": 'From sobre ("over") + mesa ("table").',
        "note": "Strongly associated with Spanish-speaking social culture.",
        "tags": ["⭐ common", "🍽️ food", "🗣️ culture"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "sobremesas"},
        ],
        "example": {"es": "Disfrutamos de una larga sobremesa después de la cena.", "en": "We enjoyed a long after-dinner conversation after dinner."},
    },
    {
        "id": "es-desvelarse",
        "spanish": "desvelarse",
        "translation": "to stay up late, to lose sleep",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/des.βeˈlaɾ.se/",
        "note": "Often implies involuntary sleeplessness.",
        "tags": ["⭐ common", "🌙 night", "🧠 emotions"],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "yes"},
            {"label": "Participio pasado", "value": "desvelado"},
            {"label": "Pretérito indefinido (yo)", "value": "desvelé"},
            {"label": "Pretérito imperfecto (yo)", "value": "desvelaba"},
            {"label": "Gerundio", "value": "desvelando"},
            {"label": "Presente (all 6 forms)", "value": "me desvelo / te desvelas / se desvela / nos desvelamos / os desveláis / se desvelan"},
        ],
        "example": {"es": "Me desvelé pensando en el examen.", "en": "I stayed awake thinking about the exam."},
    },
    {
        "id": "es-relampago",
        "spanish": "relámpago",
        "translation": "lightning bolt, flash",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/reˈlam.pa.ɣo/",
        "etymology": "Possibly from relampaguear.",
        "tags": ["⭐ common", "⛈️ weather", "🌿 nature"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "relámpagos"},
        ],
        "example": {"es": "Un relámpago iluminó toda la montaña.", "en": "A lightning bolt lit up the whole mountain."},
    },
    {
        "id": "es-entrañable",
        "spanish": "entrañable",
        "translation": "endearing, heartfelt, dear",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/en.tɾaˈɲa.βle/",
        "etymology": 'From entraña ("innermost part").',
        "note": "Often used for emotionally warm people or memories.",
        "tags": ["⭐ common", "❤️ emotions", "👥 people"],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "entrañable"},
            {"label": "Plural (masc.)", "value": "entrañables"},
            {"label": "Plural (fem.)", "value": "entrañables"},
        ],
        "example": {"es": "Fue una conversación entrañable entre amigos.", "en": "It was a heartfelt conversation between friends."},
    },
    {
        "id": "es-a-duras-penas",
        "spanish": "a duras penas",
        "translation": "barely, with great difficulty",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/a ˈdu.ɾas ˈpe.nas/",
        "note": "Common idiomatic expression.",
        "tags": ["⭐ common", "💬 idiom", "🏃 effort"],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "neutral"},
        ],
        "example": {"es": "Llegó a duras penas al final de la carrera.", "en": "He barely made it to the end of the race."},
    },
    {
        "id": "es-madrugar",
        "spanish": "madrugar",
        "translation": "to wake up early",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/ma.dɾuˈɣaɾ/",
        "tags": ["⭐ common", "⏰ daily life"],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "no"},
            {"label": "Participio pasado", "value": "madrugado"},
            {"label": "Pretérito indefinido (yo)", "value": "madrugué"},
            {"label": "Pretérito imperfecto (yo)", "value": "madrugaba"},
            {"label": "Gerundio", "value": "madrugando"},
            {"label": "Presente (all 6 forms)", "value": "madrugo / madrugas / madruga / madrugamos / madrugáis / madrugan"},
        ],
        "example": {"es": "No me gusta madrugar los domingos.", "en": "I don't like waking up early on Sundays."},
    },
    {
        "id": "es-rincon",
        "spanish": "rincón",
        "translation": "corner, nook",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/rinˈkon/",
        "tags": ["⭐ common", "🏠 places"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "rincones"},
        ],
        "example": {"es": "Encontramos un rincón tranquilo en la biblioteca.", "en": "We found a quiet corner in the library."},
    },
    {
        "id": "es-ojala",
        "spanish": "ojalá",
        "translation": "hopefully, if only",
        "type": "adverb",
        "scene_id": "💃 Curated",
        "pronunciation": "/o.xaˈla/",
        "etymology": 'From Arabic law šá lláh ("if God wills").',
        "note": "Often followed by subjunctive verbs.",
        "tags": ["⭐ common", "💭 wishes", "🗣️ culture"],
        "priority": True,
        "example": {"es": "Ojalá llueva mañana.", "en": "Hopefully it rains tomorrow."},
    },
    {
        "id": "es-aguacero",
        "spanish": "aguacero",
        "translation": "downpour, heavy rain",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/a.ɣwaˈθe.ɾo/",
        "tags": ["⛈️ weather", "🌿 nature"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "aguaceros"},
        ],
        "example": {"es": "Nos sorprendió un aguacero en mitad del paseo.", "en": "A downpour surprised us in the middle of the walk."},
    },
    {
        "id": "es-despistado",
        "spanish": "despistado",
        "translation": "absent-minded, distracted",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/des.pisˈta.ðo/",
        "tags": ["⭐ common", "🧠 personality"],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "despistada"},
            {"label": "Plural (masc.)", "value": "despistados"},
            {"label": "Plural (fem.)", "value": "despistadas"},
        ],
        "example": {"es": "Soy tan despistado que olvidé las llaves otra vez.", "en": "I'm so absent-minded that I forgot the keys again."},
    },
    {
        "id": "es-echar-de-menos",
        "spanish": "echar de menos",
        "translation": "to miss, to long for",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/eˈtʃaɾ ðe ˈme.nos/",
        "note": 'The standard way to express "to miss someone."',
        "tags": ["⭐ common", "❤️ emotions", "✈️ travel"],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "neutral"},
        ],
        "example": {"es": "Echo de menos a mi familia cuando viajo.", "en": "I miss my family when I travel."},
    },
    {
        "id": "es-curiosear",
        "spanish": "curiosear",
        "translation": "to snoop, to browse curiously",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/ku.ɾjo.seˈaɾ/",
        "tags": ["📚 learning", "👀 curiosity"],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "no"},
            {"label": "Participio pasado", "value": "curioseado"},
            {"label": "Pretérito indefinido (yo)", "value": "curioseé"},
            {"label": "Pretérito imperfecto (yo)", "value": "curioseaba"},
            {"label": "Gerundio", "value": "curioseando"},
            {"label": "Presente (all 6 forms)", "value": "curioseo / curioseas / curiosea / curioseamos / curioseáis / curiosean"},
        ],
        "example": {"es": "Le gusta curiosear en las librerías antiguas.", "en": "She likes browsing around old bookstores."},
    },
    {
        "id": "es-brillo",
        "spanish": "brillo",
        "translation": "shine, glow, sparkle",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/ˈbɾi.ʎo/",
        "tags": ["✨ appearance", "🎨 art"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "brillos"},
        ],
        "example": {"es": "Sus ojos tenían un brillo especial.", "en": "Her eyes had a special sparkle."},
    },
    {
        "id": "es-fugaz",
        "spanish": "fugaz",
        "translation": "fleeting, brief",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/fuˈɣaθ/",
        "tags": ["⏳ time", "❤️ emotions"],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "fugaz"},
            {"label": "Plural (masc.)", "value": "fugaces"},
            {"label": "Plural (fem.)", "value": "fugaces"},
        ],
        "example": {"es": "Tuvieron un encuentro fugaz en la estación.", "en": "They had a brief encounter at the station."},
    },
    {
        "id": "es-de-golpe",
        "spanish": "de golpe",
        "translation": "suddenly, all at once",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/de ˈɣol.pe/",
        "tags": ["💬 idiom", "⚡ intensity"],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "neutral"},
        ],
        "example": {"es": "Todo cambió de golpe.", "en": "Everything changed suddenly."},
    },
    {
        "id": "es-merienda",
        "spanish": "merienda",
        "translation": "afternoon snack, light meal",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/meˈɾjen.da/",
        "tags": ["🍽️ food", "☀️ daily life"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "meriendas"},
        ],
        "example": {"es": "Tomamos una merienda en la terraza.", "en": "We had an afternoon snack on the terrace."},
    },
    {
        "id": "es-brindar",
        "spanish": "brindar",
        "translation": "to toast, to celebrate with drinks",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/bɾinˈdaɾ/",
        "tags": ["🍷 social", "🎉 celebration"],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "no"},
            {"label": "Participio pasado", "value": "brindado"},
            {"label": "Pretérito indefinido (yo)", "value": "brindé"},
            {"label": "Pretérito imperfecto (yo)", "value": "brindaba"},
            {"label": "Gerundio", "value": "brindando"},
            {"label": "Presente (all 6 forms)", "value": "brindo / brindas / brinda / brindamos / brindáis / brindan"},
        ],
        "example": {"es": "Brindamos por el nuevo año.", "en": "We toasted to the new year."},
    },
    {
        "id": "es-ternura",
        "spanish": "ternura",
        "translation": "tenderness, affection",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/teɾˈnu.ɾa/",
        "tags": ["❤️ emotions", "👥 people"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "ternuras"},
        ],
        "example": {"es": "Habló con mucha ternura.", "en": "She spoke with great tenderness."},
    },
    {
        "id": "es-inquieto",
        "spanish": "inquieto",
        "translation": "restless, uneasy",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/iŋˈkje.to/",
        "tags": ["🧠 emotions", "👥 people"],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "inquieta"},
            {"label": "Plural (masc.)", "value": "inquietos"},
            {"label": "Plural (fem.)", "value": "inquietas"},
        ],
        "example": {"es": "El niño estaba inquieto toda la tarde.", "en": "The child was restless all afternoon."},
    },
    {
        "id": "es-ni-de-broma",
        "spanish": "ni de broma",
        "translation": "no way, not a chance",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/ni ðe ˈbɾo.ma/",
        "tags": ["💬 idiom", "😄 colloquial"],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "colloquial"},
        ],
        "example": {"es": "Ni de broma voy a saltar desde ahí.", "en": "No way am I jumping from there."},
    },
    {
        "id": "es-asomarse",
        "spanish": "asomarse",
        "translation": "to peek out, to lean out",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/a.soˈmaɾ.se/",
        "tags": ["👀 movement", "🏠 daily life"],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "yes"},
            {"label": "Participio pasado", "value": "asomado"},
            {"label": "Pretérito indefinido (yo)", "value": "asomé"},
            {"label": "Pretérito imperfecto (yo)", "value": "asomaba"},
            {"label": "Gerundio", "value": "asomando"},
            {"label": "Presente (all 6 forms)", "value": "me asomo / te asomas / se asoma / nos asomamos / os asomáis / se asoman"},
        ],
        "example": {"es": "Se asomó por la ventana para mirar la lluvia.", "en": "She leaned out the window to watch the rain."},
    },
    {
        "id": "es-vaiven",
        "spanish": "vaivén",
        "translation": "sway, back-and-forth motion",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/bai̯ˈβen/",
        "tags": ["🚆 travel", "🌊 movement"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "vaivenes"},
        ],
        "example": {"es": "El vaivén del tren me dio sueño.", "en": "The train's swaying made me sleepy."},
    },
    {
        "id": "es-acogedor",
        "spanish": "acogedor",
        "translation": "cozy, welcoming",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/a.ko.xeˈðoɾ/",
        "tags": ["🏠 places", "☕ social"],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "acogedora"},
            {"label": "Plural (masc.)", "value": "acogedores"},
            {"label": "Plural (fem.)", "value": "acogedoras"},
        ],
        "example": {"es": "Es un café pequeño y acogedor.", "en": "It's a small and cozy café."},
    },
    {
        "id": "es-por-si-acaso",
        "spanish": "por si acaso",
        "translation": "just in case",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/poɾ si aˈka.so/",
        "tags": ["💬 idiom", "⛈️ weather"],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "neutral"},
        ],
        "example": {"es": "Lleva un paraguas por si acaso.", "en": "Take an umbrella just in case."},
    },
    {
        "id": "es-deslumbrar",
        "spanish": "deslumbrar",
        "translation": "to dazzle, to amaze",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/des.lumˈbɾaɾ/",
        "tags": ["✨ art", "🎭 performance"],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "no"},
            {"label": "Participio pasado", "value": "deslumbrado"},
            {"label": "Pretérito indefinido (yo)", "value": "deslumbré"},
            {"label": "Pretérito imperfecto (yo)", "value": "deslumbraba"},
            {"label": "Gerundio", "value": "deslumbrando"},
            {"label": "Presente (all 6 forms)", "value": "deslumbro / deslumbras / deslumbra / deslumbramos / deslumbráis / deslumbran"},
        ],
        "example": {"es": "La actuación deslumbró al público.", "en": "The performance dazzled the audience."},
    },
    {
        "id": "es-murmullo",
        "spanish": "murmullo",
        "translation": "murmur, whispering sound",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/muɾˈmu.ʎo/",
        "tags": ["🔊 sound", "👥 people"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "murmullos"},
        ],
        "example": {"es": "Se escuchaba un murmullo en la sala.", "en": "A murmur could be heard in the room."},
    },
    {
        "id": "es-torpe",
        "spanish": "torpe",
        "translation": "clumsy, awkward",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/ˈtoɾ.pe/",
        "tags": ["👥 personality", "💃 movement"],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "torpe"},
            {"label": "Plural (masc.)", "value": "torpes"},
            {"label": "Plural (fem.)", "value": "torpes"},
        ],
        "example": {"es": "Soy demasiado torpe para bailar tango.", "en": "I'm too clumsy to dance tango."},
    },
    {
        "id": "es-dar-en-el-clavo",
        "spanish": "dar en el clavo",
        "translation": "to hit the nail on the head",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/daɾ en el ˈkla.βo/",
        "tags": ["💬 idiom", "🗣️ communication"],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "neutral"},
        ],
        "example": {"es": "Diste en el clavo con tu comentario.", "en": "You hit the nail on the head with your comment."},
    },
    {
        "id": "es-susurrar",
        "spanish": "susurrar",
        "translation": "to whisper",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/su.suˈraɾ/",
        "tags": ["🔊 sound", "❤️ emotions"],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "no"},
            {"label": "Participio pasado", "value": "susurrado"},
            {"label": "Pretérito indefinido (yo)", "value": "susurré"},
            {"label": "Pretérito imperfecto (yo)", "value": "susurraba"},
            {"label": "Gerundio", "value": "susurrando"},
            {"label": "Presente (all 6 forms)", "value": "susurro / susurras / susurra / susurramos / susurráis / susurran"},
        ],
        "example": {"es": "Me susurró un secreto al oído.", "en": "She whispered a secret in my ear."},
    },
    {
        "id": "es-chispa",
        "spanish": "chispa",
        "translation": "spark, wit",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/ˈtʃis.pa/",
        "tags": ["✨ personality", "🔥 energy"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "chispas"},
        ],
        "example": {"es": "Tiene mucha chispa cuando cuenta historias.", "en": "He has a lot of wit when telling stories."},
    },
    {
        "id": "es-bochornoso",
        "spanish": "bochornoso",
        "translation": "embarrassing, shameful",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/bo.tʃoɾˈno.so/",
        "tags": ["😳 emotions", "👥 social"],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "bochornosa"},
            {"label": "Plural (masc.)", "value": "bochornosos"},
            {"label": "Plural (fem.)", "value": "bochornosas"},
        ],
        "example": {"es": "Fue un momento bastante bochornoso.", "en": "It was quite an embarrassing moment."},
    },
    {
        "id": "es-estar-en-las-nubes",
        "spanish": "estar en las nubes",
        "translation": "to daydream, to be absent-minded",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/esˈtaɾ en las ˈnu.βes/",
        "tags": ["💬 idiom", "🧠 mind"],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "colloquial"},
        ],
        "example": {"es": "Siempre está en las nubes durante las reuniones.", "en": "He's always daydreaming during meetings."},
    },
    {
        "id": "es-acariciar",
        "spanish": "acariciar",
        "translation": "to caress, to stroke",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/a.ka.ɾiˈθjaɾ/",
        "tags": ["❤️ emotions", "🐈 animals"],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "no"},
            {"label": "Participio pasado", "value": "acariciado"},
            {"label": "Pretérito indefinido (yo)", "value": "acaricié"},
            {"label": "Pretérito imperfecto (yo)", "value": "acariciaba"},
            {"label": "Gerundio", "value": "acariciando"},
            {"label": "Presente (all 6 forms)", "value": "acaricio / acaricias / acaricia / acariciamos / acariciáis / acarician"},
        ],
        "example": {"es": "Acarició al gato mientras leía.", "en": "She stroked the cat while reading."},
    },
    {
        "id": "es-amanecer",
        "spanish": "amanecer",
        "translation": "dawn, sunrise",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/a.ma.neˈθeɾ/",
        "tags": ["🌅 nature", "⏳ time"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "amaneceres"},
        ],
        "example": {"es": "Salimos a caminar al amanecer.", "en": "We went for a walk at dawn."},
    },
    {
        "id": "es-nostalgico",
        "spanish": "nostálgico",
        "translation": "nostalgic",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/nosˈtal.xi.ko/",
        "tags": ["❤️ emotions", "🎵 music"],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "nostálgica"},
            {"label": "Plural (masc.)", "value": "nostálgicos"},
            {"label": "Plural (fem.)", "value": "nostálgicas"},
        ],
        "example": {"es": "Esa canción me pone nostálgico.", "en": "That song makes me nostalgic."},
    },
    {
        "id": "es-sin-rumbo",
        "spanish": "sin rumbo",
        "translation": "aimlessly, without direction",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/sin ˈrum.bo/",
        "tags": ["🚶 movement", "🌆 travel"],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "neutral"},
        ],
        "example": {"es": "Caminamos sin rumbo por la ciudad.", "en": "We wandered aimlessly through the city."},
    },
    {
        "id": "es-desahogarse",
        "spanish": "desahogarse",
        "translation": "to vent, to unburden oneself",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/de.sa.oˈɣaɾ.se/",
        "tags": ["❤️ emotions", "🧠 mental"],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "yes"},
            {"label": "Participio pasado", "value": "desahogado"},
            {"label": "Pretérito indefinido (yo)", "value": "desahogué"},
            {"label": "Pretérito imperfecto (yo)", "value": "desahogaba"},
            {"label": "Gerundio", "value": "desahogando"},
            {"label": "Presente (all 6 forms)", "value": "me desahogo / te desahogas / se desahoga / nos desahogamos / os desahogáis / se desahogan"},
        ],
        "example": {"es": "Necesitaba desahogarse después del trabajo.", "en": "She needed to vent after work."},
    },
    {
        "id": "es-remolino",
        "spanish": "remolino",
        "translation": "whirlpool, swirl",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/re.moˈli.no/",
        "tags": ["🌪️ weather", "🌿 nature"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "remolinos"},
        ],
        "example": {"es": "El viento levantó un remolino de hojas.", "en": "The wind lifted a swirl of leaves."},
    },
    {
        "id": "es-peculiar",
        "spanish": "peculiar",
        "translation": "peculiar, distinctive",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/pe.kuˈljaɾ/",
        "tags": ["👥 personality", "🗣️ communication"],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "peculiar"},
            {"label": "Plural (masc.)", "value": "peculiares"},
            {"label": "Plural (fem.)", "value": "peculiares"},
        ],
        "example": {"es": "Tiene una forma peculiar de hablar.", "en": "He has a distinctive way of speaking."},
    },
    {
        "id": "es-de-vez-en-cuando",
        "spanish": "de vez en cuando",
        "translation": "from time to time, occasionally",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/de βeθ en ˈkwan.do/",
        "tags": ["💬 idiom", "⏳ time"],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "neutral"},
        ],
        "example": {"es": "De vez en cuando me gusta desconectar del móvil.", "en": "From time to time I like to disconnect from my phone."},
    },
    {
        "id": "es-tropezar",
        "spanish": "tropezar",
        "translation": "to stumble, to trip",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/tɾo.peˈθaɾ/",
        "tags": ["🚶 movement", "🌿 nature"],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "no"},
            {"label": "Participio pasado", "value": "tropezado"},
            {"label": "Pretérito indefinido (yo)", "value": "tropecé"},
            {"label": "Pretérito imperfecto (yo)", "value": "tropezaba"},
            {"label": "Gerundio", "value": "tropezando"},
            {"label": "Presente (all 6 forms)", "value": "tropiezo / tropiezas / tropieza / tropezamos / tropezáis / tropiezan"},
        ],
        "example": {"es": "Tropecé con una piedra en el camino.", "en": "I tripped over a stone on the path."},
    },
    {
        "id": "es-latido",
        "spanish": "latido",
        "translation": "heartbeat, pulse",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/laˈti.ðo/",
        "tags": ["❤️ body", "🎵 rhythm"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "latidos"},
        ],
        "example": {"es": "Escuchó el latido de su corazón.", "en": "She heard the beat of her heart."},
    },
    {
        "id": "es-desbordante",
        "spanish": "desbordante",
        "translation": "overflowing, exuberant",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/des.boɾˈðan.te/",
        "tags": ["🔥 energy", "👥 personality"],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "desbordante"},
            {"label": "Plural (masc.)", "value": "desbordantes"},
            {"label": "Plural (fem.)", "value": "desbordantes"},
        ],
        "example": {"es": "Tiene una energía desbordante.", "en": "She has overflowing energy."},
    },
    {
        "id": "es-costar-un-ojo",
        "spanish": "costar un ojo de la cara",
        "translation": "to cost a fortune",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/kosˈtaɾ un ˈo.xo ðe la ˈka.ɾa/",
        "tags": ["💬 idiom", "💰 money"],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "colloquial"},
        ],
        "example": {"es": "Ese apartamento cuesta un ojo de la cara.", "en": "That apartment costs a fortune."},
    },
    {
        "id": "es-hojear",
        "spanish": "hojear",
        "translation": "to flip through, to leaf through",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/o.xeˈaɾ/",
        "tags": ["📚 learning", "⏳ daily life"],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "no"},
            {"label": "Participio pasado", "value": "hojeado"},
            {"label": "Pretérito indefinido (yo)", "value": "hojeé"},
            {"label": "Pretérito imperfecto (yo)", "value": "hojeaba"},
            {"label": "Gerundio", "value": "hojeando"},
            {"label": "Presente (all 6 forms)", "value": "hojeo / hojeas / hojea / hojeamos / hojeáis / hojean"},
        ],
        "example": {"es": "Hojeé una revista mientras esperaba.", "en": "I flipped through a magazine while waiting."},
    },
    {
        "id": "es-anhelo",
        "spanish": "anhelo",
        "translation": "longing, yearning",
        "type": "noun",
        "scene_id": "💃 Curated",
        "pronunciation": "/aˈne.lo/",
        "tags": ["❤️ emotions", "🌊 nature"],
        "priority": True,
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "anhelos"},
        ],
        "example": {"es": "Sintió un anhelo profundo de volver al mar.", "en": "She felt a deep longing to return to the sea."},
    },
    {
        "id": "es-efimero",
        "spanish": "efímero",
        "translation": "ephemeral, short-lived",
        "type": "adjective",
        "scene_id": "💃 Curated",
        "pronunciation": "/eˈfi.me.ɾo/",
        "tags": ["⏳ time", "🎨 art"],
        "priority": True,
        "grammar": [
            {"label": "Feminine form", "value": "efímera"},
            {"label": "Plural (masc.)", "value": "efímeros"},
            {"label": "Plural (fem.)", "value": "efímeras"},
        ],
        "example": {"es": "La belleza del momento era efímera.", "en": "The beauty of the moment was ephemeral."},
    },
    {
        "id": "es-meter-la-pata",
        "spanish": "meter la pata",
        "translation": "to screw up, to put one's foot in it",
        "type": "phrase",
        "scene_id": "💃 Curated",
        "pronunciation": "/meˈteɾ la ˈpa.ta/",
        "tags": ["💬 idiom", "😳 mistakes"],
        "priority": True,
        "grammar": [
            {"label": "Register", "value": "colloquial"},
        ],
        "example": {"es": "Metí la pata durante la entrevista.", "en": "I screwed up during the interview."},
    },
    {
        "id": "es-tambalearse",
        "spanish": "tambalearse",
        "translation": "to stagger, to wobble",
        "type": "verb",
        "scene_id": "💃 Curated",
        "pronunciation": "/tam.ba.leˈaɾ.se/",
        "tags": ["🚶 movement", "⚡ intensity"],
        "priority": True,
        "grammar": [
            {"label": "Verb type", "value": "-ar"},
            {"label": "Reflexive", "value": "yes"},
            {"label": "Participio pasado", "value": "tambaleado"},
            {"label": "Pretérito indefinido (yo)", "value": "tambaleé"},
            {"label": "Pretérito imperfecto (yo)", "value": "tambaleaba"},
            {"label": "Gerundio", "value": "tambaleando"},
            {"label": "Presente (all 6 forms)", "value": "me tambaleo / te tambaleas / se tambalea / nos tambaleamos / os tambaleáis / se tambalean"},
        ],
        "example": {"es": "El ciclista empezó a tambalearse.", "en": "The cyclist started to wobble."},
    },
]

try:
    from es_de_vocab_data import CARDS as _DE_CARDS
    CARDS = CARDS + _DE_CARDS
except ImportError:
    pass

try:
    from es_el_vocab_data import CARDS as _EL_CARDS
    CARDS = CARDS + _EL_CARDS
except ImportError:
    pass
