"""
de_el_vocab_data.py — German vocabulary cards for Greek speakers (departure_lang='el').
Imported automatically by de_vocab_data.py.
"""

CARDS = [

    # ── Ουσιαστικά ────────────────────────────────────────────────────────────

    {
        "id": "de-el-fernweh",
        "word": "Fernweh",
        "departure_lang": "el",
        "translation": "λαχτάρα για μακρινά μέρη, νοσταλγία του ταξιδιού",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "FEHRN-veh",
        "gender": "n",
        "grammar": [
            {"label": "Gender", "value": "n"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "des Fernwehs"},
        ],
        "example": {
            "de": "Jedes Mal, wenn ich Flugzeuge sehe, packt mich das Fernweh.",
            "el": "Κάθε φορά που βλέπω αεροπλάνα, με κυριεύει η λαχτάρα για ταξίδι.",
        },
        "etymology": "fern (μακριά) + Weh (πόνος/αίσθημα) — κυριολεκτικά «αρρώστια για το μακρινό», αντίθετο του Heimweh",
        "note": "Μη μετρήσιμο, χωρίς πληθυντικό· χρησιμοποιείται με «Fernweh haben» ή «das Fernweh packt mich»",
        "tags": ["common", "emotions"],
        "priority": 1,
    },

    {
        "id": "de-el-zeitgeist",
        "word": "Zeitgeist",
        "departure_lang": "el",
        "translation": "πνεύμα της εποχής, Ζάιτγκαϊστ",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "TSAIT-gaist",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "die Zeitgeister (rare)"},
            {"label": "Genitive singular", "value": "des Zeitgeists"},
        ],
        "example": {
            "de": "Der Roman fängt den Zeitgeist der 1920er Jahre perfekt ein.",
            "el": "Το μυθιστόρημα αποτυπώνει τέλεια το πνεύμα της εποχής της δεκαετίας του 1920.",
        },
        "etymology": "Zeit (χρόνος) + Geist (πνεύμα)",
        "note": "Δανείστηκε αυτούσιο στα αγγλικά· συνήθως ενικός, χωρίς πληθυντικό χωρίς άρθρο στη συνηθισμένη χρήση",
        "tags": ["common", "culture"],
        "priority": 1,
    },

    {
        "id": "de-el-backpfeifengesicht",
        "word": "Backpfeifengesicht",
        "departure_lang": "el",
        "translation": "πρόσωπο που ζητάει χαστούκι",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "BACK-pfai-fen-ge-zicht",
        "gender": "n",
        "grammar": [
            {"label": "Gender", "value": "n"},
            {"label": "Plural (with article)", "value": "die Backpfeifengesichter"},
            {"label": "Genitive singular", "value": "des Backpfeifengesichts"},
        ],
        "example": {
            "de": "Er hat wirklich ein Backpfeifengesicht, findest du nicht?",
            "el": "Έχει πραγματικά ένα πρόσωπο που ζητάει χαστούκι, δεν το βλέπεις;",
        },
        "etymology": "Backpfeife (χαστούκι) + Gesicht (πρόσωπο)",
        "note": "Χοντροκομμένη/χιουμοριστική αργκό, όχι για καλή παρέα",
        "tags": ["slang", "humor"],
        "priority": 0,
    },

    {
        "id": "de-el-kummerspeck",
        "word": "Kummerspeck",
        "departure_lang": "el",
        "translation": 'παχυσαρκία από θλίψη («μπέικον της λύπης»)',
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "KOO-mer-shpeck",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "des Kummerspecks"},
        ],
        "example": {
            "de": "Nach der Trennung habe ich ein bisschen Kummerspeck angesetzt.",
            "el": "Μετά τον χωρισμό πήρα λίγα κιλά από θλίψη.",
        },
        "etymology": "Kummer (θλίψη/λύπη) + Speck (μπέικον/λίπος)",
        "note": "Ανεπίσημο, αυτοσαρκαστικός ή τρυφερός τόνος",
        "tags": ["common", "humor"],
        "priority": 1,
    },

    {
        "id": "de-el-weltschmerz",
        "word": "Weltschmerz",
        "departure_lang": "el",
        "translation": "κοσμική μελαγχολία, υπαρξιακή κούραση από τον κόσμο",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "VELT-shmerts",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "des Weltschmerzes"},
        ],
        "example": {
            "de": "Manchmal überkommt mich ein tiefer Weltschmerz.",
            "el": "Μερικές φορές με κυριεύει μια βαθιά κοσμική μελαγχολία.",
        },
        "etymology": "Welt (κόσμος) + Schmerz (πόνος), επινοήθηκε στη Ρομαντική λογοτεχνία",
        "note": "Πιο λογοτεχνικό/φιλοσοφικό παρά καθημερινό",
        "tags": ["common", "emotions"],
        "priority": 1,
    },

    {
        "id": "de-el-schadenfreude",
        "word": "Schadenfreude",
        "departure_lang": "el",
        "translation": "χαρά για την ατυχία άλλου",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "SHAH-den-froy-de",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "der Schadenfreude"},
        ],
        "example": {
            "de": "Seine Schadenfreude war ihm deutlich anzusehen.",
            "el": "Η χαρά του για την ατυχία του άλλου ήταν ολοφάνερη.",
        },
        "etymology": "Schaden (βλάβη/ζημιά) + Freude (χαρά)",
        "note": "Δανείστηκε ουσιαστικά αναλλοίωτο και στα αγγλικά",
        "tags": ["common", "emotions"],
        "priority": 1,
    },

    {
        "id": "de-el-torschlusspanik",
        "word": "Torschlusspanik",
        "departure_lang": "el",
        "translation": "πανικός ότι ο χρόνος τελειώνει (κυρίως για ορόσημα της ζωής)",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "TOR-shluss-pah-nik",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "der Torschlusspanik"},
        ],
        "example": {
            "de": "Mit vierzig bekam sie plötzlich Torschlusspanik.",
            "el": "Στα σαράντα την κυρίευσε ξαφνικά πανικός ότι ο χρόνος της τελειώνει.",
        },
        "etymology": "Torschluss (κλείσιμο πύλης) + Panik (πανικός) — μεσαιωνική εικόνα των πυλών της πόλης που κλείνουν τη νύχτα",
        "note": "Χρησιμοποιείται συχνά για καριέρα, γάμο, απόκτηση παιδιών",
        "tags": ["emotions", "idiom"],
        "priority": 0,
    },

    {
        "id": "de-el-fingerspitzengefuehl",
        "word": "Fingerspitzengefühl",
        "departure_lang": "el",
        "translation": "διαίσθητη διακριτικότητα, ευαισθησία, επιδέξιο άγγιγμα",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "FIN-ger-shpit-sen-ge-fühl",
        "gender": "n",
        "grammar": [
            {"label": "Gender", "value": "n"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "des Fingerspitzengefühls"},
        ],
        "example": {
            "de": "In dieser Situation braucht man viel Fingerspitzengefühl.",
            "el": "Αυτή η κατάσταση απαιτεί πολλή διακριτικότητα και ευαισθησία.",
        },
        "etymology": "Fingerspitze (άκρο δακτύλου) + Gefühl (αίσθηση)",
        "note": "Θετικό χαρακτηριστικό· συχνά «Fingerspitzengefühl haben/beweisen/brauchen»",
        "tags": ["common", "character-traits"],
        "priority": 1,
    },

    {
        "id": "de-el-ohrwurm",
        "word": "Ohrwurm",
        "departure_lang": "el",
        "translation": "εμμονικό τραγούδι που κολλάει στο μυαλό",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "OR-voorm",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "die Ohrwürmer"},
            {"label": "Genitive singular", "value": "des Ohrwurms"},
        ],
        "example": {
            "de": "Dieses Lied ist ein echter Ohrwurm.",
            "el": "Αυτό το τραγούδι κολλάει αληθινά στο μυαλό.",
        },
        "etymology": "Ohr (αυτί) + Wurm (σκουλήκι) — κυριολεκτικά σημαίνει επίσης «αυτιόσκαρος»",
        "note": "Καθημερινό, πολύ συνηθισμένο στον προφορικό λόγο για τη μουσική",
        "tags": ["common", "music"],
        "priority": 1,
    },

    {
        "id": "de-el-doppelgaenger",
        "word": "Doppelgänger",
        "departure_lang": "el",
        "translation": "σωσίας, άτομο που μοιάζει με κάποιον άλλο",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "DOP-pel-geng-er",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "die Doppelgänger"},
            {"label": "Genitive singular", "value": "des Doppelgängers"},
        ],
        "example": {
            "de": "Sie hat einen Doppelgänger, den man leicht verwechseln könnte.",
            "el": "Έχει έναν σωσία με τον οποίο μπορεί εύκολα να την μπερδέψεις.",
        },
        "etymology": "doppel (διπλό) + Gänger (βαδιστής/αυτός που περπατά)",
        "note": "Δανείστηκε αναλλοίωτο και στα αγγλικά",
        "tags": ["common", "people"],
        "priority": 0,
    },

    {
        "id": "de-el-wanderlust",
        "word": "Wanderlust",
        "departure_lang": "el",
        "translation": "ισχυρή επιθυμία για ταξίδι",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "VAHN-der-loost",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "der Wanderlust"},
        ],
        "example": {
            "de": "Ihre Wanderlust hat sie schon durch zwanzig Länder geführt.",
            "el": "Η λαχτάρα της για ταξίδι την έχει ήδη οδηγήσει σε είκοσι χώρες.",
        },
        "etymology": "wandern (να περπατώ/να περιπλανιέμαι) + Lust (επιθυμία)",
        "note": "Επικαλύπτεται με το Fernweh, αλλά υπονοεί ενεργή επιθυμία κίνησης/εξερεύνησης, όχι απλή νοσταλγία",
        "tags": ["common", "travel"],
        "priority": 1,
    },

    {
        "id": "de-el-geborgenheit",
        "word": "Geborgenheit",
        "departure_lang": "el",
        "translation": "αίσθηση ασφάλειας και ζεστασιάς, προστασία",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "ge-BOR-gen-hait",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "der Geborgenheit"},
        ],
        "example": {
            "de": "Bei ihren Großeltern fühlte sie immer eine tiefe Geborgenheit.",
            "el": "Στους παππούδες της ένιωθε πάντα μια βαθιά αίσθηση ασφάλειας.",
        },
        "etymology": "από το geborgen (προφυλαγμένος, ασφαλής), παρακείμενος μετοχή του bergen (να προφυλάσσω/να διασώζω)",
        "note": "Πιο ζεστό και συναισθηματικό από το «Sicherheit» (ασφάλεια)",
        "tags": ["common", "emotions"],
        "priority": 1,
    },

    {
        "id": "de-el-sehnsucht",
        "word": "Sehnsucht",
        "departure_lang": "el",
        "translation": "λαχτάρα, βαθύς πόθος",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "ZEHN-zookht",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural (with article)", "value": "die Sehnsüchte"},
            {"label": "Genitive singular", "value": "der Sehnsucht"},
        ],
        "example": {
            "de": "Die Sehnsucht nach der Heimat wurde immer stärker.",
            "el": "Η λαχτάρα για την πατρίδα γινόταν όλο και πιο έντονη.",
        },
        "etymology": "sehnen (να λαχταράω) + Sucht (εξάρτηση/λαχτάρα)",
        "note": "Χρησιμοποιείται συχνά με «nach» + αιτιατική· πολύ κοινό στην ποίηση και τους στίχους τραγουδιών",
        "tags": ["common", "emotions"],
        "priority": 1,
    },

    {
        "id": "de-el-erklaerungsnot",
        "word": "Erklärungsnot",
        "departure_lang": "el",
        "translation": "αδυναμία να δώσει κανείς εξήγηση, δύσκολη θέση ανεξήγητης συμπεριφοράς",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "er-KLEH-roongs-note",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "der Erklärungsnot"},
        ],
        "example": {
            "de": "Als die Wahrheit ans Licht kam, war er in großer Erklärungsnot.",
            "el": "Όταν βγήκε η αλήθεια στο φως, δεν είχε τι να πει για δικαιολογία.",
        },
        "etymology": "Erklärung (εξήγηση) + Not (ανάγκη/δυσχέρεια)",
        "note": "Συνήθως «in Erklärungsnot geraten/sein»",
        "tags": ["idiom", "work"],
        "priority": 0,
    },

    {
        "id": "de-el-feierabend",
        "word": "Feierabend",
        "departure_lang": "el",
        "translation": "τέλος εργάσιμης ημέρας, ελεύθερος χρόνος μετά τη δουλειά",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "FAI-er-ah-bent",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "die Feierabende"},
            {"label": "Genitive singular", "value": "des Feierabends"},
        ],
        "example": {
            "de": "Endlich Feierabend — jetzt kann ich mich entspannen!",
            "el": "Επιτέλους τέλος δουλειάς — τώρα μπορώ να χαλαρώσω!",
        },
        "etymology": "Feier (εορτή) + Abend (βράδυ) — αρχικά η παραμονή αργίας",
        "note": "Πολύ κοινό· «Feierabend machen» = να αφήσεις τη δουλειά",
        "tags": ["common", "work"],
        "priority": 1,
    },

    {
        "id": "de-el-gemuetlichkeit",
        "word": "Gemütlichkeit",
        "departure_lang": "el",
        "translation": "άνεση, ζεστασιά, φιλόξενη ατμόσφαιρα",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "ge-MÜT-likh-kait",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "der Gemütlichkeit"},
        ],
        "example": {
            "de": "In dieser kleinen Kneipe herrscht eine besondere Gemütlichkeit.",
            "el": "Αυτό το μικρό παμπ έχει μια ιδιαίτερη ζεστή ατμόσφαιρα.",
        },
        "etymology": "από το gemütlich (άνετος/ζεστός), από το Gemüt (νους/ιδιοσυγκρασία)",
        "note": "Περιγράφει τόσο τη φυσική άνεση όσο και μια χαλαρή, κοινωνική ατμόσφαιρα",
        "tags": ["common", "culture"],
        "priority": 1,
    },

    {
        "id": "de-el-treppenwitz",
        "word": "Treppenwitz",
        "departure_lang": "el",
        "translation": "έξυπνη απάντηση που σκέφτεσαι αργότερα (l'esprit de l'escalier)",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "TREP-pen-vits",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "die Treppenwitze"},
            {"label": "Genitive singular", "value": "des Treppenwitzes"},
        ],
        "example": {
            "de": "Erst im Bus fiel mir der perfekte Treppenwitz ein.",
            "el": "Μόνο στο λεωφορείο μου ήρθε η τέλεια απάντηση.",
        },
        "etymology": "Treppe (σκάλα) + Witz (αστείο) — η ετοιμόλογη απάντηση που σκέφτεσαι καθώς φεύγεις από τη σκάλα",
        "note": "Χρησιμοποιείται επίσης ως «Treppenwitz der Geschichte» (ειρωνεία της ιστορίας)",
        "tags": ["idiom", "humor"],
        "priority": 0,
    },

    {
        "id": "de-el-handschuh",
        "word": "Handschuh",
        "departure_lang": "el",
        "translation": "γάντι",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "HAHNT-shoo",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "die Handschuhe"},
            {"label": "Genitive singular", "value": "des Handschuhs"},
        ],
        "example": {
            "de": "Bei diesem Wetter solltest du Handschuhe tragen.",
            "el": "Με αυτόν τον καιρό πρέπει να φοράς γάντια.",
        },
        "etymology": "Hand (χέρι) + Schuh (παπούτσι) — κυριολεκτικά «παπούτσι του χεριού»",
        "note": "Χρησιμοποιείται σχεδόν πάντα στον πληθυντικό (Handschuhe) στην καθημερινή ομιλία",
        "tags": ["common", "clothing"],
        "priority": 1,
    },

    {
        "id": "de-el-kopfkino",
        "word": "Kopfkino",
        "departure_lang": "el",
        "translation": 'ζωντανές νοητικές εικόνες, «κινηματογράφος στο μυαλό»',
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "KOPF-kee-no",
        "gender": "n",
        "grammar": [
            {"label": "Gender", "value": "n"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "des Kopfkinos"},
        ],
        "example": {
            "de": "Beim Lesen des Buches lief bei mir ständig das Kopfkino.",
            "el": "Διαβάζοντας το βιβλίο, το μυαλό μου έπαιζε συνεχώς τη δική του ταινία.",
        },
        "etymology": "Kopf (κεφάλι) + Kino (σινεμά)",
        "note": "Σύγχρονη, ανεπίσημη δημιουργία· χρησιμοποιείται συχνά για ζωντανή φαντασία ή αγχώδεις σκέψεις",
        "tags": ["modern", "mind"],
        "priority": 0,
    },

    {
        "id": "de-el-naschkatze",
        "word": "Naschkatze",
        "departure_lang": "el",
        "translation": "γλυκατζής/-ού, άτομο που λατρεύει τα γλυκά",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "NAHSH-kaht-se",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural (with article)", "value": "die Naschkatzen"},
            {"label": "Genitive singular", "value": "der Naschkatze"},
        ],
        "example": {
            "de": "Sie ist eine echte Naschkatze und liebt Schokolade.",
            "el": "Είναι αληθινή γλυκατζού και λατρεύει τη σοκολάτα.",
        },
        "etymology": "naschen (να τρώω γλυκά λάθρα) + Katze (γάτα)",
        "note": "Τρυφερό, χρησιμοποιείται για άτομα οποιουδήποτε φύλου παρά τη θηλυκή κατάληξη -katze",
        "tags": ["common", "food"],
        "priority": 1,
    },

    {
        "id": "de-el-purzelbaum",
        "word": "Purzelbaum",
        "departure_lang": "el",
        "translation": "τούμπα, κύλισμα",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "POOR-tsel-baum",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "die Purzelbäume"},
            {"label": "Genitive singular", "value": "des Purzelbaums"},
        ],
        "example": {
            "de": "Die Kinder schlugen im Garten Purzelbäume.",
            "el": "Τα παιδιά έκαναν τούμπες στον κήπο.",
        },
        "etymology": "purzeln (να κυλιέμαι) + Baum (δέντρο, εδώ αρχαϊκό για «δοκάρι/πόλος»)",
        "note": "Σταθερή έκφραση «einen Purzelbaum schlagen» = να κάνω τούμπα",
        "tags": ["common", "kids"],
        "priority": 0,
    },

    {
        "id": "de-el-drachenfutter",
        "word": "Drachenfutter",
        "departure_lang": "el",
        "translation": "δώρο συμφιλίωσης για να κατευναστεί θυμωμένος σύντροφος",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "DRAH-khen-foot-ter",
        "gender": "n",
        "grammar": [
            {"label": "Gender", "value": "n"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "des Drachenfutters"},
        ],
        "example": {
            "de": "Nach dem Streit brachte er ihr Blumen als Drachenfutter mit.",
            "el": "Μετά τον καβγά της έφερε λουλούδια ως δώρο συμφιλίωσης.",
        },
        "etymology": "Drachen (δράκος) + Futter (τροφή) — κυριολεκτικά «φαγητό για το δράκο»",
        "note": "Χιουμοριστική αργκό, υπονοεί κατευνασμό θυμωμένου συζύγου",
        "tags": ["humor", "relationships"],
        "priority": 0,
    },

    {
        "id": "de-el-zwischenraum",
        "word": "Zwischenraum",
        "departure_lang": "el",
        "translation": "κενό, χώρος ανάμεσα",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "TSVI-shen-raum",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "die Zwischenräume"},
            {"label": "Genitive singular", "value": "des Zwischenraums"},
        ],
        "example": {
            "de": "Zwischen den Büchern war kaum ein Zwischenraum.",
            "el": "Ανάμεσα στα βιβλία δεν υπήρχε σχεδόν κανένα κενό.",
        },
        "etymology": "zwischen (ανάμεσα) + Raum (χώρος)",
        "note": "Μπορεί να είναι φυσικό ή μεταφορικό (π.χ. σε σχέσεις, χρόνο)",
        "tags": ["common", "space"],
        "priority": 0,
    },

    {
        "id": "de-el-fremdscham",
        "word": "Fremdscham",
        "departure_lang": "el",
        "translation": "αμηχανία εκ συμπαθείας, ντροπή για λογαριασμό κάποιου άλλου",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "FREMT-shahm",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "der Fremdscham"},
        ],
        "example": {
            "de": "Bei dieser Szene im Film habe ich fast Fremdscham empfunden.",
            "el": "Σε εκείνη τη σκηνή της ταινίας ένιωσα σχεδόν ντροπή για λογαριασμό τους.",
        },
        "etymology": "fremd (ξένος/του άλλου) + Scham (ντροπή)",
        "note": "Σύγχρονη δημιουργία, πολύ κοινή στην καθημερινή/διαδικτυακή γερμανική",
        "tags": ["modern", "emotions"],
        "priority": 1,
    },

    {
        "id": "de-el-herzblut",
        "word": "Herzblut",
        "departure_lang": "el",
        "translation": "ψυχή και καρδιά, πάθος που επενδύεται σε κάτι",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "HERTS-bloot",
        "gender": "n",
        "grammar": [
            {"label": "Gender", "value": "n"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "des Herzbluts"},
        ],
        "example": {
            "de": "Sie hat ihr ganzes Herzblut in dieses Projekt gesteckt.",
            "el": "Έβαλε την ψυχή και την καρδιά της σε αυτό το έργο.",
        },
        "etymology": "Herz (καρδιά) + Blut (αίμα)",
        "note": "Χρησιμοποιείται συνήθως με «sein Herzblut in etwas stecken»",
        "tags": ["idiom", "work"],
        "priority": 0,
    },

    {
        "id": "de-el-lichtblick",
        "word": "Lichtblick",
        "departure_lang": "el",
        "translation": "ακτίνα ελπίδας, θετική στιγμή",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "LIKHT-blick",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "die Lichtblicke"},
            {"label": "Genitive singular", "value": "des Lichtblicks"},
        ],
        "example": {
            "de": "Trotz allem war ihr Anruf ein echter Lichtblick.",
            "el": "Παρ' όλα αυτά, η κλήση της ήταν μια αληθινή ακτίνα ελπίδας.",
        },
        "etymology": "Licht (φως) + Blick (βλέμμα/θέα)",
        "note": "Χρησιμοποιείται για θετική στιγμή μέσα σε δύσκολες συνθήκες",
        "tags": ["common", "emotions"],
        "priority": 1,
    },

    {
        "id": "de-el-augenblick",
        "word": "Augenblick",
        "departure_lang": "el",
        "translation": "στιγμή, δευτερόλεπτο",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "OW-gen-blick",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "die Augenblicke"},
            {"label": "Genitive singular", "value": "des Augenblicks"},
        ],
        "example": {
            "de": "Einen Augenblick bitte, ich bin gleich da!",
            "el": "Μια στιγμή παρακαλώ, έρχομαι αμέσως!",
        },
        "etymology": "Auge (μάτι) + Blick (βλέμμα) — κυριολεκτικά «ένα ανοιγοκλείσιμο του ματιού»",
        "note": "Πολύ κοινό· «im Augenblick» = αυτή τη στιγμή",
        "tags": ["common", "time"],
        "priority": 1,
    },

    {
        "id": "de-el-fruehjahrsmuedigkeit",
        "word": "Frühjahrsmüdigkeit",
        "departure_lang": "el",
        "translation": "ανοιξιάτικη κόπωση (εποχική κούραση)",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "FRÜ-yahrs-mü-dikh-kait",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "der Frühjahrsmüdigkeit"},
        ],
        "example": {
            "de": "Im März leide ich jedes Jahr an Frühjahrsmüdigkeit.",
            "el": "Κάθε Μάρτιο υποφέρω από ανοιξιάτικη κόπωση.",
        },
        "etymology": "Frühjahr (άνοιξη) + Müdigkeit (κόπωση/υπνηλία)",
        "note": "Ένα γνωστό (ημι-ιατρικό) λαϊκό φαινόμενο στις γερμανόφωνες χώρες",
        "tags": ["culture", "health"],
        "priority": 0,
    },

    {
        "id": "de-el-innerer-schweinehund",
        "word": "innerer Schweinehund",
        "departure_lang": "el",
        "translation": "η εσωτερική τεμπελιά/αντίσταση (η παρόρμηση για αναβλητικότητα)",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "IN-er-er SHVAI-ne-hoont",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "(rarely used in plural)"},
            {"label": "Genitive singular", "value": "des inneren Schweinehunds"},
        ],
        "example": {
            "de": "Ich musste meinen inneren Schweinehund überwinden, um joggen zu gehen.",
            "el": "Έπρεπε να νικήσω την εσωτερική μου τεμπελιά για να πάω τζόγκινγκ.",
        },
        "etymology": 'inner (εσωτερικός) + Schweinehund (κυριολεκτικά «χοιροσκύλι», παλιά βρισιά)',
        "note": "Ιδιωματικό και χιουμοριστικό· σχεδόν πάντα με «überwinden» (να νικήσω)",
        "tags": ["idiom", "humor"],
        "priority": 1,
    },

    {
        "id": "de-el-kuddelmuddel",
        "word": "Kuddelmuddel",
        "departure_lang": "el",
        "translation": "μπέρδεμα, χάος, ακαταστασία",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "KOOD-el-mood-el",
        "gender": "n",
        "grammar": [
            {"label": "Gender", "value": "n"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "des Kuddelmuddels"},
        ],
        "example": {
            "de": "In der Küche herrschte ein einziges Kuddelmuddel.",
            "el": "Στην κουζίνα επικρατούσε ένα τεράστιο χάος.",
        },
        "etymology": "Αναδιπλωμένη ανεπίσημη δημιουργία, πιθανώς σχετική με τη χαμηλογερμανική διάλεκτο",
        "note": "Παιχνιδιάρικο και ανεπίσημο, συχνά για χαοτικά έγγραφα ή καταστάσεις",
        "tags": ["humor", "everyday"],
        "priority": 0,
    },

    {
        "id": "de-el-krimskrams",
        "word": "Krimskrams",
        "departure_lang": "el",
        "translation": "μικροπράγματα, διάφορα, αντικείμενα που μπάζουν",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "KRIMS-krahms",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "des Krimskrams"},
        ],
        "example": {
            "de": "In der Schublade liegt nur unnötiger Krimskrams.",
            "el": "Στο συρτάρι υπάρχουν μόνο άχρηστα μικροπράγματα.",
        },
        "etymology": "Αναδιπλωμένη ανεπίσημη λέξη, πιθανώς από το Kram (σκουπίδια/πράγματα)",
        "note": "Καθημερινό, συλλογικός ενικός — δεν χρησιμοποιείται πληθυντικός",
        "tags": ["common", "everyday"],
        "priority": 0,
    },

    {
        "id": "de-el-ruhe",
        "word": "Ruhe",
        "departure_lang": "el",
        "translation": "ηρεμία, σιωπή, γαλήνη",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "ROO-eh",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "der Ruhe"},
        ],
        "example": {
            "de": "Nach dem Streit kehrte endlich wieder Ruhe ein.",
            "el": "Μετά τον καβγά επέστρεψε επιτέλους η ηρεμία.",
        },
        "etymology": "από την Παλαιά Υψηλή Γερμανική ruowa",
        "note": "Εξαιρετικά κοινό· «Ruhe bewahren» = να διατηρώ την ψυχραιμία μου· «lass mich in Ruhe» = άσε με ήσυχο",
        "tags": ["common", "everyday"],
        "priority": 1,
    },

    # ── Ρήματα ────────────────────────────────────────────────────────────────

    {
        "id": "de-el-verschlimmbessern",
        "word": "verschlimmbessern",
        "departure_lang": "el",
        "translation": "να κάνεις κάτι χειρότερο προσπαθώντας να το βελτιώσεις",
        "type": "verb",
        "group": "🍺 Curated",
        "pronunciation": "fer-SHLIM-bess-ern",
        "grammar": [
            {"label": "Verb type", "value": "weak"},
            {"label": "Separable verb?", "value": "no"},
            {"label": "Auxiliary (Perfekt)", "value": "haben"},
            {"label": "Partizip II", "value": "verschlimmbessert"},
            {"label": "Präteritum (ich)", "value": "verschlimmbesserte"},
            {"label": "Präsens (all 6 forms)", "value": "verschlimmbessere / verschlimmbesserst / verschlimmbessert / verschlimmbessern / verschlimmbessert / verschlimmbessern"},
        ],
        "example": {
            "de": "Mit jeder Änderung hat er das Projekt weiter verschlimmbessert.",
            "el": "Με κάθε αλλαγή έκανε το έργο ακόμα χειρότερο ενώ προσπαθούσε να το διορθώσει.",
        },
        "etymology": "verschlimmern (να επιδεινώσω) + verbessern (να βελτιώσω), συνδυασμός των δύο",
        "note": "Παιχνιδιάρικο, ειρωνικό ρήμα· κοινό στον χώρο της τεχνολογίας/λογισμικού",
        "tags": ["humor", "work"],
        "priority": 1,
    },

    {
        "id": "de-el-sich-verlaufen",
        "word": "sich verlaufen",
        "departure_lang": "el",
        "translation": "να χαθείς (με τα πόδια)",
        "type": "verb",
        "group": "🍺 Curated",
        "pronunciation": "zikh fer-LAU-fen",
        "grammar": [
            {"label": "Verb type", "value": "strong"},
            {"label": "Separable verb?", "value": "no"},
            {"label": "Auxiliary (Perfekt)", "value": "haben"},
            {"label": "Partizip II", "value": "verlaufen"},
            {"label": "Präteritum (ich)", "value": "verlief mich"},
            {"label": "Präsens (all 6 forms)", "value": "verlaufe mich / verläufst dich / verläuft sich / verlaufen uns / verlauft euch / verlaufen sich"},
        ],
        "example": {
            "de": "Wir haben uns im Wald völlig verlaufen.",
            "el": "Χαθήκαμε εντελώς στο δάσος.",
        },
        "etymology": "ver- (πρόθεμα που δηλώνει λάθος/παρέκκλιση) + laufen (να περπατώ/να τρέχω)",
        "note": "Αναλογικό ρήμα· χρησιμοποίησε «sich verfahren» για να χαθείς με αυτοκίνητο",
        "tags": ["common", "travel"],
        "priority": 1,
    },

    {
        "id": "de-el-traeumen",
        "word": "träumen",
        "departure_lang": "el",
        "translation": "να ονειρεύομαι",
        "type": "verb",
        "group": "🍺 Curated",
        "pronunciation": "TROY-men",
        "grammar": [
            {"label": "Verb type", "value": "weak"},
            {"label": "Separable verb?", "value": "no"},
            {"label": "Auxiliary (Perfekt)", "value": "haben"},
            {"label": "Partizip II", "value": "geträumt"},
            {"label": "Präteritum (ich)", "value": "träumte"},
            {"label": "Präsens (all 6 forms)", "value": "träume / träumst / träumt / träumen / träumt / träumen"},
        ],
        "example": {
            "de": "Ich habe letzte Nacht von dir geträumt.",
            "el": "Σε ονειρεύτηκα χθες τη νύχτα.",
        },
        "etymology": "από το Traum (όνειρο)",
        "note": "«träumen von» + γενική· χρησιμοποιείται επίσης μεταφορικά για ονειροπόληση/φιλοδοξία",
        "tags": ["common", "mind"],
        "priority": 1,
    },

    {
        "id": "de-el-schmunzeln",
        "word": "schmunzeln",
        "departure_lang": "el",
        "translation": "να χαμογελώ ειρωνικά, να γελώ ήσυχα μέσα μου",
        "type": "verb",
        "group": "🍺 Curated",
        "pronunciation": "SHMOON-tseln",
        "grammar": [
            {"label": "Verb type", "value": "weak"},
            {"label": "Separable verb?", "value": "no"},
            {"label": "Auxiliary (Perfekt)", "value": "haben"},
            {"label": "Partizip II", "value": "geschmunzelt"},
            {"label": "Präteritum (ich)", "value": "schmunzelte"},
            {"label": "Präsens (all 6 forms)", "value": "schmunzle / schmunzelst / schmunzelt / schmunzeln / schmunzelt / schmunzeln"},
        ],
        "example": {
            "de": "Er musste über ihren Kommentar schmunzeln.",
            "el": "Δεν μπόρεσε παρά να χαμογελάσει ειρωνικά με το σχόλιό της.",
        },
        "etymology": "αβέβαιη, σχετική με το schmunzen (διαλεκτικό, «να χαμογελώ πλατιά»)",
        "note": "Πιο ήπιο και πιο ιδιωτικό από το «lachen» (να γελώ)",
        "tags": ["common", "emotions"],
        "priority": 0,
    },

    {
        "id": "de-el-gruebeln",
        "word": "grübeln",
        "departure_lang": "el",
        "translation": "να σκέφτομαι βαθιά, να μαλακώνω πάνω σε κάτι",
        "type": "verb",
        "group": "🍺 Curated",
        "pronunciation": "GRÜ-beln",
        "grammar": [
            {"label": "Verb type", "value": "weak"},
            {"label": "Separable verb?", "value": "no"},
            {"label": "Auxiliary (Perfekt)", "value": "haben"},
            {"label": "Partizip II", "value": "gegrübelt"},
            {"label": "Präteritum (ich)", "value": "grübelte"},
            {"label": "Präsens (all 6 forms)", "value": "grüble / grübelst / grübelt / grübeln / grübelt / grübeln"},
        ],
        "example": {
            "de": "Er grübelte stundenlang über die Entscheidung.",
            "el": "Σκεφτόταν επί ώρες πάνω στην απόφαση.",
        },
        "etymology": "σχετικό με το graben (να σκάβω) — «να σκάβω μέσα στις σκέψεις μου»",
        "note": "Συχνά φέρει ελαφρά αρνητική, αγχώδη χροιά",
        "tags": ["common", "mind"],
        "priority": 1,
    },

    {
        "id": "de-el-anhimmeln",
        "word": "anhimmeln",
        "departure_lang": "el",
        "translation": "να λατρεύω, να αγαλλιάζω μπροστά σε κάποιον",
        "type": "verb",
        "group": "🍺 Curated",
        "pronunciation": "AHN-him-eln",
        "grammar": [
            {"label": "Verb type", "value": "weak"},
            {"label": "Separable verb?", "value": "yes"},
            {"label": "Auxiliary (Perfekt)", "value": "haben"},
            {"label": "Partizip II", "value": "angehimmelt"},
            {"label": "Präteritum (ich)", "value": "himmelte an"},
            {"label": "Präsens (all 6 forms)", "value": "himmle an / himmelst an / himmelt an / himmeln an / himmelt an / himmeln an"},
        ],
        "example": {
            "de": "Die Fans himmelten den Sänger regelrecht an.",
            "el": "Οι θαυμαστές λάτρευαν κυριολεκτικά τον τραγουδιστή.",
        },
        "etymology": "an- + Himmel (ουρανός) — «να ανυψώνω στον ουρανό»",
        "note": "Ελαφρά ειρωνική/μειωτική χροιά όταν χρησιμοποιείται για υπερβολική λατρεία",
        "tags": ["humor", "relationships"],
        "priority": 0,
    },

    # ── Επίθετα ───────────────────────────────────────────────────────────────

    {
        "id": "de-el-lebensmuede",
        "word": "lebensmüde",
        "departure_lang": "el",
        "translation": "κουρασμένος από τη ζωή, απερίσκεπτος (και αστεία «που ψάχνει για μπελάδες»)",
        "type": "adjective",
        "group": "🍺 Curated",
        "pronunciation": "LEH-bens-mü-de",
        "grammar": [
            {"label": "Comparative", "value": "lebensmüder"},
            {"label": "Superlative", "value": "am lebensmüdesten"},
        ],
        "example": {
            "de": "Bist du lebensmüde, bei diesem Verkehr über die Straße zu rennen?",
            "el": "Είσαι τρελός να τρέχεις να διασχίσεις τον δρόμο με αυτή την κίνηση;",
        },
        "etymology": "Leben (ζωή) + müde (κουρασμένος)",
        "note": "Χρησιμοποιείται συχνά υπερβολικά/αστεία παρά κυριολεκτικά",
        "tags": ["humor", "character-traits"],
        "priority": 0,
    },

    {
        "id": "de-el-gemuetlich",
        "word": "gemütlich",
        "departure_lang": "el",
        "translation": "άνετος, ζεστός, χαλαρός",
        "type": "adjective",
        "group": "🍺 Curated",
        "pronunciation": "ge-MÜT-likh",
        "grammar": [
            {"label": "Comparative", "value": "gemütlicher"},
            {"label": "Superlative", "value": "am gemütlichsten"},
        ],
        "example": {
            "de": "Wir hatten einen sehr gemütlichen Abend zusammen.",
            "el": "Περάσαμε ένα πολύ ζεστό βράδυ μαζί.",
        },
        "etymology": "από το Gemüt (νους/ιδιοσυγκρασία)",
        "note": "Μπορεί να περιγράφει μέρη, ατμόσφαιρες ή τον τρόπο συμπεριφοράς ανθρώπων",
        "tags": ["common", "culture"],
        "priority": 1,
    },

    {
        "id": "de-el-verschollen",
        "word": "verschollen",
        "departure_lang": "el",
        "translation": "αγνοούμενος, χαμένος χωρίς ίχνος",
        "type": "adjective",
        "group": "🍺 Curated",
        "pronunciation": "fer-SHOLL-en",
        "grammar": [
            {"label": "Comparative", "value": "verschollener (rare)"},
            {"label": "Superlative", "value": "am verschollensten (rare)"},
        ],
        "example": {
            "de": "Der Seemann gilt seit Jahren als verschollen.",
            "el": "Ο ναύτης θεωρείται αγνοούμενος εδώ και χρόνια.",
        },
        "etymology": "από το schallen (να ηχώ), σχετικό με «να μην ακούγεται»",
        "note": "Χρησιμοποιείται κυρίως κατηγορηματικά· σπανίως συγκρίνεται στην πράξη",
        "tags": ["formal", "news"],
        "priority": 0,
    },

    {
        "id": "de-el-schnippisch",
        "word": "schnippisch",
        "departure_lang": "el",
        "translation": "αγενής, κοφτός, θρασύς",
        "type": "adjective",
        "group": "🍺 Curated",
        "pronunciation": "SHNIP-ish",
        "grammar": [
            {"label": "Comparative", "value": "schnippischer"},
            {"label": "Superlative", "value": "am schnippischsten"},
        ],
        "example": {
            "de": "Sie antwortete ziemlich schnippisch auf seine Frage.",
            "el": "Απάντησε αρκετά κοφτά στην ερώτησή του.",
        },
        "etymology": "από το schnippen (να τσιμπώ/να αναπηδώ)",
        "note": "Ελαφρά αρνητικό, περιγράφει τόνο ομιλίας",
        "tags": ["character-traits"],
        "priority": 0,
    },

    {
        "id": "de-el-wehmutig",
        "word": "wehmütig",
        "departure_lang": "el",
        "translation": "νοσταλγικός, μελαγχολικός",
        "type": "adjective",
        "group": "🍺 Curated",
        "pronunciation": "VEH-mü-tikh",
        "grammar": [
            {"label": "Comparative", "value": "wehmütiger"},
            {"label": "Superlative", "value": "am wehmütigsten"},
        ],
        "example": {
            "de": "Beim Anblick alter Fotos wurde sie ganz wehmütig.",
            "el": "Βλέποντας παλιές φωτογραφίες, την κυρίευσε μια νοσταλγία.",
        },
        "etymology": "Wehmut (νοσταλγία/μελαγχολία) + -ig",
        "note": "Πιο ήπιο και πιο νοσταλγικό από το «traurig» (λυπημένος)",
        "tags": ["emotions"],
        "priority": 0,
    },

    {
        "id": "de-el-durcheinander",
        "word": "durcheinander",
        "departure_lang": "el",
        "translation": "ανακατεμένος, σε αταξία, μπερδεμένος",
        "type": "adjective",
        "group": "🍺 Curated",
        "pronunciation": "durkh-ai-NAN-der",
        "grammar": [
            {"label": "Comparative", "value": "(rarely compared)"},
            {"label": "Superlative", "value": "(rarely compared)"},
        ],
        "example": {
            "de": "Nach dem Umzug war noch alles durcheinander.",
            "el": "Μετά τη μετακόμιση, όλα ήταν ακόμα ανακατεμένα.",
        },
        "etymology": "durch (μέσα από) + einander (ο ένας τον άλλο)",
        "note": "Χρησιμοποιείται μόνο κατηγορηματικά (όχι πριν από ουσιαστικό)· σπανίως συγκρίνεται",
        "tags": ["common", "everyday"],
        "priority": 1,
    },

    # ── Επιρρήματα ────────────────────────────────────────────────────────────

    {
        "id": "de-el-uebermorgen",
        "word": "übermorgen",
        "departure_lang": "el",
        "translation": "μεθαύριο",
        "type": "adverb",
        "group": "🍺 Curated",
        "pronunciation": "Ü-ber-mor-gen",
        "grammar": [],
        "example": {
            "de": "Übermorgen fliege ich nach Berlin.",
            "el": "Μεθαύριο πετώ για Βερολίνο.",
        },
        "etymology": "über (πάνω/πέρα) + Morgen (αύριο/πρωί)",
        "note": "Ταιριάζει με το vorgestern (προχθές)",
        "tags": ["common", "time"],
        "priority": 1,
    },

    {
        "id": "de-el-neulich",
        "word": "neulich",
        "departure_lang": "el",
        "translation": "πρόσφατα, τις προάλλες",
        "type": "adverb",
        "group": "🍺 Curated",
        "pronunciation": "NOY-likh",
        "grammar": [],
        "example": {
            "de": "Neulich habe ich einen alten Freund getroffen.",
            "el": "Τις προάλλες συνάντησα έναν παλιό φίλο.",
        },
        "etymology": "από το neu (νέος)",
        "note": "Αναφέρεται σε αόριστο πρόσφατο σημείο στο παρελθόν, όχι «μόλις τώρα»",
        "tags": ["common", "time"],
        "priority": 1,
    },

    {
        "id": "de-el-jein",
        "word": "jein",
        "departure_lang": "el",
        "translation": '«ναι και όχι», διφορούμενη απάντηση',
        "type": "adverb",
        "group": "🍺 Curated",
        "pronunciation": "YAIN",
        "grammar": [],
        "example": {
            "de": '"Bist du fertig?" — "Jein, fast."',
            "el": '«Τελείωσες;» — «Κάπως, σχεδόν.»',
        },
        "etymology": "σύμμιξη του ja (ναι) και nein (όχι)",
        "note": "Καθημερινό, παιχνιδιάρικο· δεν είναι κατάλληλο σε επίσημα κείμενα",
        "tags": ["slang", "humor"],
        "priority": 0,
    },

    # ── Εκφράσεις ─────────────────────────────────────────────────────────────

    {
        "id": "de-el-auf-wolke-sieben",
        "word": "auf Wolke sieben schweben",
        "departure_lang": "el",
        "translation": "να είμαι στα σύννεφα (από ευτυχία)",
        "type": "phrase",
        "group": "🍺 Curated",
        "pronunciation": "owf VOL-ke ZEE-ben SHVEH-ben",
        "grammar": [
            {"label": "Register", "value": "colloquial"},
        ],
        "example": {
            "de": "Seit dem ersten Date schwebt sie auf Wolke sieben.",
            "el": "Από το πρώτο ραντεβού είναι στα σύννεφα.",
        },
        "etymology": "Wolke sieben (σύννεφο επτά) + schweben (να αιωρούμαι)· γερμανικό αντίστοιχο του αγγλικού «cloud nine»",
        "note": "Χρησιμοποιείται για ερωτικό ενθουσιασμό ή έκσταση",
        "tags": ["idiom", "relationships"],
        "priority": 0,
    },

    {
        "id": "de-el-apfel-stamm",
        "word": "Der Apfel fällt nicht weit vom Stamm",
        "departure_lang": "el",
        "translation": "το μήλο δεν πέφτει μακριά από τη μηλιά / τα παιδιά μοιάζουν τους γονείς τους",
        "type": "phrase",
        "group": "🍺 Curated",
        "pronunciation": "dair AHP-fel felt nikht vait fom shtahm",
        "grammar": [
            {"label": "Register", "value": "neutral"},
        ],
        "example": {
            "de": "Sie ist genauso stur wie ihre Mutter — der Apfel fällt nicht weit vom Stamm.",
            "el": "Είναι εξίσου πεισματάρα με τη μητέρα της — το μήλο δεν πέφτει μακριά από τη μηλιά.",
        },
        "etymology": "Apfel (μήλο) + Stamm (κορμός)· κοινή παροιμία σε πολλές ευρωπαϊκές γλώσσες",
        "note": "Χρησιμοποιείται όταν τα παιδιά μοιάζουν τους γονείς τους στον χαρακτήρα, καλά ή κακά",
        "tags": ["idiom", "family"],
        "priority": 0,
    },

]
