"""
de_vocab_data.py — German vocabulary preset cards.

Grammar label reference (use these EXACTLY):
  Noun:      Gender | Plural (with article) | Genitive singular
  Verb:      Verb type | Separable verb? | Auxiliary (Perfekt) | Partizip II |
             Präteritum (ich) | Präsens (all 6 forms)
  Adjective: Comparative | Superlative
  Phrase:    Register | Usage notes
"""

CARDS = [

    # ── Nouns ─────────────────────────────────────────────────────────────────

    {
        "id": "de-fernweh",
        "word": "Fernweh",
        "translation": "wanderlust, longing for distant places",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "FEHRN-veh",
        "gender": "n",
        "grammar": [
            {"label": "Gender", "value": "n"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "des Fernwehs"},
        ],
        "example": {
            "de": "Jedes Mal, wenn ich Flugzeuge sehe, packt mich das Fernweh.",
            "en": "Every time I see airplanes, I'm gripped by wanderlust.",
        },
        "etymology": "fern (far) + Weh (pain/ache) — literally \"far-sickness\", opposite of Heimweh",
        "note": "Uncountable, no plural; used with \"Fernweh haben\" or \"das Fernweh packt mich\"",
        "tags": ["common", "emotions"],
        "priority": 1,
    },

    {
        "id": "de-zeitgeist",
        "word": "Zeitgeist",
        "translation": "spirit of the times, zeitgeist",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "TSAIT-gaist",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "die Zeitgeister (rare)"},
            {"label": "Genitive singular", "value": "des Zeitgeists"},
        ],
        "example": {
            "de": "Der Roman fängt den Zeitgeist der 1920er Jahre perfekt ein.",
            "en": "The novel perfectly captures the zeitgeist of the 1920s.",
        },
        "etymology": "Zeit (time) + Geist (spirit)",
        "note": "Borrowed directly into English; usually singular, no article-less plural in normal use",
        "tags": ["common", "culture"],
        "priority": 1,
    },

    {
        "id": "de-backpfeifengesicht",
        "word": "Backpfeifengesicht",
        "translation": "a face that's just asking to be slapped",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "BACK-pfai-fen-ge-zicht",
        "gender": "n",
        "grammar": [
            {"label": "Gender", "value": "n"},
            {"label": "Plural (with article)", "value": "die Backpfeifengesichter"},
            {"label": "Genitive singular", "value": "des Backpfeifengesichts"},
        ],
        "example": {
            "de": "Er hat wirklich ein Backpfeifengesicht, findest du nicht?",
            "en": "He really has a punchable face, don't you think?",
        },
        "etymology": "Backpfeife (slap in the face) + Gesicht (face)",
        "note": "Crude/humorous slang, not for polite company",
        "tags": ["slang", "humor"],
        "priority": 0,
    },

    {
        "id": "de-kummerspeck",
        "word": "Kummerspeck",
        "translation": "emotional weight gain (\"grief bacon\")",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "KOO-mer-shpeck",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "des Kummerspecks"},
        ],
        "example": {
            "de": "Nach der Trennung habe ich ein bisschen Kummerspeck angesetzt.",
            "en": "After the breakup I put on a bit of \"grief weight\".",
        },
        "etymology": "Kummer (grief/sorrow) + Speck (bacon/fat)",
        "note": "Informal, affectionate/self-deprecating tone",
        "tags": ["common", "humor"],
        "priority": 1,
    },

    {
        "id": "de-weltschmerz",
        "word": "Weltschmerz",
        "translation": "world-weariness, existential melancholy",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "VELT-shmerts",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "des Weltschmerzes"},
        ],
        "example": {
            "de": "Manchmal überkommt mich ein tiefer Weltschmerz.",
            "en": "Sometimes a deep world-weariness overcomes me.",
        },
        "etymology": "Welt (world) + Schmerz (pain), coined in early Romantic literature",
        "note": "More literary/philosophical than everyday speech",
        "tags": ["common", "emotions"],
        "priority": 1,
    },

    {
        "id": "de-schadenfreude",
        "word": "Schadenfreude",
        "translation": "joy at another's misfortune",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "SHAH-den-froy-de",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "der Schadenfreude"},
        ],
        "example": {
            "de": "Seine Schadenfreude war ihm deutlich anzusehen.",
            "en": "His schadenfreude was clearly visible.",
        },
        "etymology": "Schaden (damage/harm) + Freude (joy)",
        "note": "Also loaned into English essentially unchanged",
        "tags": ["common", "emotions"],
        "priority": 1,
    },

    {
        "id": "de-torschlusspanik",
        "word": "Torschlusspanik",
        "translation": "panic of time running out (esp. life milestones)",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "TOR-shluss-pah-nik",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "der Torschlusspanik"},
        ],
        "example": {
            "de": "Mit vierzig bekam sie plötzlich Torschlusspanik.",
            "en": "At forty she suddenly got panicked that time was running out.",
        },
        "etymology": "Torschluss (gate closing) + Panik (panic) — medieval image of city gates closing at night",
        "note": "Often used re: career, marriage, having children",
        "tags": ["emotions", "idiom"],
        "priority": 0,
    },

    {
        "id": "de-fingerspitzengefuehl",
        "word": "Fingerspitzengefühl",
        "translation": "intuitive tact, sensitivity, a deft touch",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "FIN-ger-shpit-sen-ge-fühl",
        "gender": "n",
        "grammar": [
            {"label": "Gender", "value": "n"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "des Fingerspitzengefühls"},
        ],
        "example": {
            "de": "In dieser Situation braucht man viel Fingerspitzengefühl.",
            "en": "This situation requires a lot of tact and sensitivity.",
        },
        "etymology": "Fingerspitze (fingertip) + Gefühl (feeling)",
        "note": "Positive trait; often \"Fingerspitzengefühl haben/beweisen/brauchen\"",
        "tags": ["common", "character-traits"],
        "priority": 1,
    },

    {
        "id": "de-ohrwurm",
        "word": "Ohrwurm",
        "translation": "earworm, catchy tune stuck in your head",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "OR-voorm",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "die Ohrwürmer"},
            {"label": "Genitive singular", "value": "des Ohrwurms"},
        ],
        "example": {
            "de": "Dieses Lied ist ein echter Ohrwurm.",
            "en": "This song is a real earworm.",
        },
        "etymology": "Ohr (ear) + Wurm (worm) — also literally means \"earwig\"",
        "note": "Casual, very common in everyday speech about music",
        "tags": ["common", "music"],
        "priority": 1,
    },

    {
        "id": "de-doppelgaenger",
        "word": "Doppelgänger",
        "translation": "double, look-alike",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "DOP-pel-geng-er",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "die Doppelgänger"},
            {"label": "Genitive singular", "value": "des Doppelgängers"},
        ],
        "example": {
            "de": "Sie hat einen Doppelgänger, den man leicht verwechseln könnte.",
            "en": "She has a double who could easily be mistaken for her.",
        },
        "etymology": "doppel (double) + Gänger (goer/walker)",
        "note": "Also borrowed into English unchanged",
        "tags": ["common", "people"],
        "priority": 0,
    },

    {
        "id": "de-wanderlust",
        "word": "Wanderlust",
        "translation": "strong desire to travel",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "VAHN-der-loost",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "der Wanderlust"},
        ],
        "example": {
            "de": "Ihre Wanderlust hat sie schon durch zwanzig Länder geführt.",
            "en": "Her wanderlust has already led her through twenty countries.",
        },
        "etymology": "wandern (to hike/wander) + Lust (desire)",
        "note": "Overlaps with Fernweh but implies active desire to move/explore, not just longing",
        "tags": ["common", "travel"],
        "priority": 1,
    },

    {
        "id": "de-geborgenheit",
        "word": "Geborgenheit",
        "translation": "feeling of safety and warmth, security",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "ge-BOR-gen-hait",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "der Geborgenheit"},
        ],
        "example": {
            "de": "Bei ihren Großeltern fühlte sie immer eine tiefe Geborgenheit.",
            "en": "At her grandparents' she always felt a deep sense of security.",
        },
        "etymology": "from geborgen (sheltered, safe), past participle of bergen (to shelter/rescue)",
        "note": "Warmer and more emotional than \"Sicherheit\" (safety)",
        "tags": ["common", "emotions"],
        "priority": 1,
    },

    {
        "id": "de-sehnsucht",
        "word": "Sehnsucht",
        "translation": "yearning, deep longing",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "ZEHN-zookht",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural (with article)", "value": "die Sehnsüchte"},
            {"label": "Genitive singular", "value": "der Sehnsucht"},
        ],
        "example": {
            "de": "Die Sehnsucht nach der Heimat wurde immer stärker.",
            "en": "The longing for home grew ever stronger.",
        },
        "etymology": "sehnen (to yearn) + Sucht (addiction/craving)",
        "note": "Often used with \"nach\" + dative; very common in poetry and song lyrics",
        "tags": ["common", "emotions"],
        "priority": 1,
    },

    {
        "id": "de-erklaerungsnot",
        "word": "Erklärungsnot",
        "translation": "being at a loss for an explanation, having to explain oneself awkwardly",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "er-KLEH-roongs-note",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "der Erklärungsnot"},
        ],
        "example": {
            "de": "Als die Wahrheit ans Licht kam, war er in großer Erklärungsnot.",
            "en": "When the truth came out, he was scrambling for an explanation.",
        },
        "etymology": "Erklärung (explanation) + Not (distress/need)",
        "note": "Usually \"in Erklärungsnot geraten/sein\"",
        "tags": ["idiom", "work"],
        "priority": 0,
    },

    {
        "id": "de-feierabend",
        "word": "Feierabend",
        "translation": "end of the workday, time off after work",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "FAI-er-ah-bent",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "die Feierabende"},
            {"label": "Genitive singular", "value": "des Feierabends"},
        ],
        "example": {
            "de": "Endlich Feierabend — jetzt kann ich mich entspannen!",
            "en": "Finally off work — now I can relax!",
        },
        "etymology": "Feier (celebration) + Abend (evening) — originally the eve before a holiday",
        "note": "Very common; \"Feierabend machen\" = to knock off work",
        "tags": ["common", "work"],
        "priority": 1,
    },

    {
        "id": "de-gemuetlichkeit",
        "word": "Gemütlichkeit",
        "translation": "coziness, warmth, congeniality",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "ge-MÜT-likh-kait",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "der Gemütlichkeit"},
        ],
        "example": {
            "de": "In dieser kleinen Kneipe herrscht eine besondere Gemütlichkeit.",
            "en": "This little pub has a special coziness to it.",
        },
        "etymology": "from gemütlich (cozy), from Gemüt (mind/temperament)",
        "note": "Describes both physical coziness and a relaxed, sociable atmosphere",
        "tags": ["common", "culture"],
        "priority": 1,
    },

    {
        "id": "de-treppenwitz",
        "word": "Treppenwitz",
        "translation": "witty comeback thought of too late (l'esprit de l'escalier)",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "TREP-pen-vits",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "die Treppenwitze"},
            {"label": "Genitive singular", "value": "des Treppenwitzes"},
        ],
        "example": {
            "de": "Erst im Bus fiel mir der perfekte Treppenwitz ein.",
            "en": "Only on the bus did the perfect comeback occur to me.",
        },
        "etymology": "Treppe (staircase) + Witz (joke) — the retort you think of on the stairs leaving",
        "note": "Also used as \"Treppenwitz der Geschichte\" (irony of history)",
        "tags": ["idiom", "humor"],
        "priority": 0,
    },

    {
        "id": "de-handschuh",
        "word": "Handschuh",
        "translation": "glove",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "HAHNT-shoo",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "die Handschuhe"},
            {"label": "Genitive singular", "value": "des Handschuhs"},
        ],
        "example": {
            "de": "Bei diesem Wetter solltest du Handschuhe tragen.",
            "en": "In this weather you should wear gloves.",
        },
        "etymology": "Hand (hand) + Schuh (shoe) — literally \"hand-shoe\"",
        "note": "Almost always used in plural (Handschuhe) in daily speech",
        "tags": ["common", "clothing"],
        "priority": 1,
    },

    {
        "id": "de-kopfkino",
        "word": "Kopfkino",
        "translation": "vivid mental imagery, \"mental cinema\"",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "KOPF-kee-no",
        "gender": "n",
        "grammar": [
            {"label": "Gender", "value": "n"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "des Kopfkinos"},
        ],
        "example": {
            "de": "Beim Lesen des Buches lief bei mir ständig das Kopfkino.",
            "en": "While reading the book, my mind kept running its own movie.",
        },
        "etymology": "Kopf (head) + Kino (cinema)",
        "note": "Modern, informal coinage; often used for vivid imagination or anxious rumination",
        "tags": ["modern", "mind"],
        "priority": 0,
    },

    {
        "id": "de-naschkatze",
        "word": "Naschkatze",
        "translation": "person with a sweet tooth",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "NAHSH-kaht-se",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural (with article)", "value": "die Naschkatzen"},
            {"label": "Genitive singular", "value": "der Naschkatze"},
        ],
        "example": {
            "de": "Sie ist eine echte Naschkatze und liebt Schokolade.",
            "en": "She's a real sweet tooth and loves chocolate.",
        },
        "etymology": "naschen (to nibble sweets) + Katze (cat)",
        "note": "Affectionate, used for people of any gender despite -katze (feminine form)",
        "tags": ["common", "food"],
        "priority": 1,
    },

    {
        "id": "de-purzelbaum",
        "word": "Purzelbaum",
        "translation": "somersault",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "POOR-tsel-baum",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "die Purzelbäume"},
            {"label": "Genitive singular", "value": "des Purzelbaums"},
        ],
        "example": {
            "de": "Die Kinder schlugen im Garten Purzelbäume.",
            "en": "The kids did somersaults in the garden.",
        },
        "etymology": "purzeln (to tumble) + Baum (tree, here archaic for \"beam/pole\")",
        "note": "Fixed phrase \"einen Purzelbaum schlagen\" = to do a somersault",
        "tags": ["common", "kids"],
        "priority": 0,
    },

    {
        "id": "de-drachenfutter",
        "word": "Drachenfutter",
        "translation": "peace-offering gift (to appease an angry partner)",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "DRAH-khen-foot-ter",
        "gender": "n",
        "grammar": [
            {"label": "Gender", "value": "n"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "des Drachenfutters"},
        ],
        "example": {
            "de": "Nach dem Streit brachte er ihr Blumen als Drachenfutter mit.",
            "en": "After the fight, he brought her flowers as a peace offering.",
        },
        "etymology": "Drachen (dragon) + Futter (fodder/feed) — literally \"dragon food\"",
        "note": "Humorous slang, implies placating an angry spouse",
        "tags": ["humor", "relationships"],
        "priority": 0,
    },

    {
        "id": "de-zwischenraum",
        "word": "Zwischenraum",
        "translation": "gap, space in between",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "TSVI-shen-raum",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "die Zwischenräume"},
            {"label": "Genitive singular", "value": "des Zwischenraums"},
        ],
        "example": {
            "de": "Zwischen den Büchern war kaum ein Zwischenraum.",
            "en": "There was barely any gap between the books.",
        },
        "etymology": "zwischen (between) + Raum (space)",
        "note": "Can be physical or figurative (e.g. in relationships, time)",
        "tags": ["common", "space"],
        "priority": 0,
    },

    {
        "id": "de-fremdscham",
        "word": "Fremdscham",
        "translation": "vicarious embarrassment, cringing on someone else's behalf",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "FREMT-shahm",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "der Fremdscham"},
        ],
        "example": {
            "de": "Bei dieser Szene im Film habe ich fast Fremdscham empfunden.",
            "en": "I nearly cringed with secondhand embarrassment at that scene.",
        },
        "etymology": "fremd (foreign/someone else's) + Scham (shame)",
        "note": "Modern coinage, very common in casual/internet German",
        "tags": ["modern", "emotions"],
        "priority": 1,
    },

    {
        "id": "de-herzblut",
        "word": "Herzblut",
        "translation": "heart and soul, life's passion invested into something",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "HERTS-bloot",
        "gender": "n",
        "grammar": [
            {"label": "Gender", "value": "n"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "des Herzbluts"},
        ],
        "example": {
            "de": "Sie hat ihr ganzes Herzblut in dieses Projekt gesteckt.",
            "en": "She poured her heart and soul into this project.",
        },
        "etymology": "Herz (heart) + Blut (blood)",
        "note": "Typically used with \"sein Herzblut in etwas stecken\"",
        "tags": ["idiom", "work"],
        "priority": 0,
    },

    {
        "id": "de-lichtblick",
        "word": "Lichtblick",
        "translation": "ray of hope, bright spot",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "LIKHT-blick",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "die Lichtblicke"},
            {"label": "Genitive singular", "value": "des Lichtblicks"},
        ],
        "example": {
            "de": "Trotz allem war ihr Anruf ein echter Lichtblick.",
            "en": "Despite everything, her call was a real ray of hope.",
        },
        "etymology": "Licht (light) + Blick (glance/view)",
        "note": "Used for a positive moment amid otherwise difficult circumstances",
        "tags": ["common", "emotions"],
        "priority": 1,
    },

    {
        "id": "de-augenblick",
        "word": "Augenblick",
        "translation": "moment, instant",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "OW-gen-blick",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "die Augenblicke"},
            {"label": "Genitive singular", "value": "des Augenblicks"},
        ],
        "example": {
            "de": "Einen Augenblick bitte, ich bin gleich da!",
            "en": "One moment please, I'll be right there!",
        },
        "etymology": "Auge (eye) + Blick (glance) — literally \"the blink of an eye\"",
        "note": "Very common; \"im Augenblick\" = at the moment",
        "tags": ["common", "time"],
        "priority": 1,
    },

    {
        "id": "de-fruehjahrsmuedigkeit",
        "word": "Frühjahrsmüdigkeit",
        "translation": "spring fatigue (seasonal tiredness)",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "FRÜ-yahrs-mü-dikh-kait",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "der Frühjahrsmüdigkeit"},
        ],
        "example": {
            "de": "Im März leide ich jedes Jahr an Frühjahrsmüdigkeit.",
            "en": "Every March I suffer from spring fatigue.",
        },
        "etymology": "Frühjahr (spring) + Müdigkeit (tiredness)",
        "note": "A commonly discussed (semi-medical) folk concept in German-speaking countries",
        "tags": ["culture", "health"],
        "priority": 0,
    },

    {
        "id": "de-innerer-schweinehund",
        "word": "innerer Schweinehund",
        "translation": "one's inner laziness/resistance (the urge to procrastinate)",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "IN-er-er SHVAI-ne-hoont",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "(rarely used in plural)"},
            {"label": "Genitive singular", "value": "des inneren Schweinehunds"},
        ],
        "example": {
            "de": "Ich musste meinen inneren Schweinehund überwinden, um joggen zu gehen.",
            "en": "I had to overcome my inner laziness to go jogging.",
        },
        "etymology": "inner (inner) + Schweinehund (literally \"pig-dog\", an old insult)",
        "note": "Idiomatic and humorous; almost always with \"überwinden\" (to overcome)",
        "tags": ["idiom", "humor"],
        "priority": 1,
    },

    {
        "id": "de-kuddelmuddel",
        "word": "Kuddelmuddel",
        "translation": "mess, muddle, chaos",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "KOOD-el-mood-el",
        "gender": "n",
        "grammar": [
            {"label": "Gender", "value": "n"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "des Kuddelmuddels"},
        ],
        "example": {
            "de": "In der Küche herrschte ein einziges Kuddelmuddel.",
            "en": "The kitchen was a total mess.",
        },
        "etymology": "Reduplicated informal coinage, likely related to Low German dialect",
        "note": "Playful and informal, often used for chaotic paperwork or situations",
        "tags": ["humor", "everyday"],
        "priority": 0,
    },

    {
        "id": "de-krimskrams",
        "word": "Krimskrams",
        "translation": "knick-knacks, odds and ends, clutter",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "KRIMS-krahms",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "des Krimskrams"},
        ],
        "example": {
            "de": "In der Schublade liegt nur unnötiger Krimskrams.",
            "en": "The drawer just has unnecessary odds and ends in it.",
        },
        "etymology": "Reduplicated informal word, possibly from Kram (junk/stuff)",
        "note": "Casual, collective singular — no plural form used",
        "tags": ["common", "everyday"],
        "priority": 0,
    },

    {
        "id": "de-ruhe",
        "word": "Ruhe",
        "translation": "calm, quiet, peace",
        "type": "noun",
        "group": "🍺 Curated",
        "pronunciation": "ROO-eh",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural (with article)", "value": "(no plural)"},
            {"label": "Genitive singular", "value": "der Ruhe"},
        ],
        "example": {
            "de": "Nach dem Streit kehrte endlich wieder Ruhe ein.",
            "en": "After the argument, calm finally returned.",
        },
        "etymology": "from Old High German ruowa",
        "note": "Extremely common; \"Ruhe bewahren\" = to keep calm; \"lass mich in Ruhe\" = leave me alone",
        "tags": ["common", "everyday"],
        "priority": 1,
    },

    # ── Verbs ──────────────────────────────────────────────────────────────────

    {
        "id": "de-verschlimmbessern",
        "word": "verschlimmbessern",
        "translation": "to make something worse by trying to improve it",
        "type": "verb",
        "group": "🍺 Curated",
        "pronunciation": "fer-SHLIM-bess-ern",
        "grammar": [
            {"label": "Verb type", "value": "weak"},
            {"label": "Separable verb?", "value": "no"},
            {"label": "Auxiliary (Perfekt)", "value": "haben"},
            {"label": "Partizip II", "value": "verschlimmbessert"},
            {"label": "Präteritum (ich)", "value": "verschlimmbesserte"},
            {"label": "Präsens (all 6 forms)", "value": "verschlimmbessere / verschlimmbesserst / verschlimmbessert / verschlimmbessern / verschlimmbessert / verschlimmbessern"},
        ],
        "example": {
            "de": "Mit jeder Änderung hat er das Projekt weiter verschlimmbessert.",
            "en": "With every change he made the project worse while trying to fix it.",
        },
        "etymology": "verschlimmern (worsen) blended with verbessern (improve)",
        "note": "Playful, ironic verb; common in tech/software contexts",
        "tags": ["humor", "work"],
        "priority": 1,
    },

    {
        "id": "de-sich-verlaufen",
        "word": "sich verlaufen",
        "translation": "to get lost (on foot)",
        "type": "verb",
        "group": "🍺 Curated",
        "pronunciation": "zikh fer-LAU-fen",
        "grammar": [
            {"label": "Verb type", "value": "strong"},
            {"label": "Separable verb?", "value": "no"},
            {"label": "Auxiliary (Perfekt)", "value": "haben"},
            {"label": "Partizip II", "value": "verlaufen"},
            {"label": "Präteritum (ich)", "value": "verlief mich"},
            {"label": "Präsens (all 6 forms)", "value": "verlaufe mich / verläufst dich / verläuft sich / verlaufen uns / verlauft euch / verlaufen sich"},
        ],
        "example": {
            "de": "Wir haben uns im Wald völlig verlaufen.",
            "en": "We got completely lost in the forest.",
        },
        "etymology": "ver- (prefix indicating error/going astray) + laufen (to walk/run)",
        "note": "Reflexive; use \"sich verfahren\" for getting lost while driving",
        "tags": ["common", "travel"],
        "priority": 1,
    },

    {
        "id": "de-traeumen",
        "word": "träumen",
        "translation": "to dream",
        "type": "verb",
        "group": "🍺 Curated",
        "pronunciation": "TROY-men",
        "grammar": [
            {"label": "Verb type", "value": "weak"},
            {"label": "Separable verb?", "value": "no"},
            {"label": "Auxiliary (Perfekt)", "value": "haben"},
            {"label": "Partizip II", "value": "geträumt"},
            {"label": "Präteritum (ich)", "value": "träumte"},
            {"label": "Präsens (all 6 forms)", "value": "träume / träumst / träumt / träumen / träumt / träumen"},
        ],
        "example": {
            "de": "Ich habe letzte Nacht von dir geträumt.",
            "en": "I dreamed about you last night.",
        },
        "etymology": "from Traum (dream)",
        "note": "\"träumen von\" + dative; also used figuratively for daydreaming/aspiring",
        "tags": ["common", "mind"],
        "priority": 1,
    },

    {
        "id": "de-schmunzeln",
        "word": "schmunzeln",
        "translation": "to smile wryly, to grin quietly to oneself",
        "type": "verb",
        "group": "🍺 Curated",
        "pronunciation": "SHMOON-tseln",
        "grammar": [
            {"label": "Verb type", "value": "weak"},
            {"label": "Separable verb?", "value": "no"},
            {"label": "Auxiliary (Perfekt)", "value": "haben"},
            {"label": "Partizip II", "value": "geschmunzelt"},
            {"label": "Präteritum (ich)", "value": "schmunzelte"},
            {"label": "Präsens (all 6 forms)", "value": "schmunzle / schmunzelst / schmunzelt / schmunzeln / schmunzelt / schmunzeln"},
        ],
        "example": {
            "de": "Er musste über ihren Kommentar schmunzeln.",
            "en": "He couldn't help but smile wryly at her comment.",
        },
        "etymology": "uncertain, related to schmunzen (dialectal, \"to smirk\")",
        "note": "Gentler and more private than \"lachen\" (to laugh)",
        "tags": ["common", "emotions"],
        "priority": 0,
    },

    {
        "id": "de-gruebeln",
        "word": "grübeln",
        "translation": "to brood, to ruminate",
        "type": "verb",
        "group": "🍺 Curated",
        "pronunciation": "GRÜ-beln",
        "grammar": [
            {"label": "Verb type", "value": "weak"},
            {"label": "Separable verb?", "value": "no"},
            {"label": "Auxiliary (Perfekt)", "value": "haben"},
            {"label": "Partizip II", "value": "gegrübelt"},
            {"label": "Präteritum (ich)", "value": "grübelte"},
            {"label": "Präsens (all 6 forms)", "value": "grüble / grübelst / grübelt / grübeln / grübelt / grübeln"},
        ],
        "example": {
            "de": "Er grübelte stundenlang über die Entscheidung.",
            "en": "He brooded over the decision for hours.",
        },
        "etymology": "related to graben (to dig) — \"to dig into one's thoughts\"",
        "note": "Often carries a slightly negative, anxious connotation",
        "tags": ["common", "mind"],
        "priority": 1,
    },

    {
        "id": "de-anhimmeln",
        "word": "anhimmeln",
        "translation": "to idolize, to adore worshipfully",
        "type": "verb",
        "group": "🍺 Curated",
        "pronunciation": "AHN-him-eln",
        "grammar": [
            {"label": "Verb type", "value": "weak"},
            {"label": "Separable verb?", "value": "yes"},
            {"label": "Auxiliary (Perfekt)", "value": "haben"},
            {"label": "Partizip II", "value": "angehimmelt"},
            {"label": "Präteritum (ich)", "value": "himmelte an"},
            {"label": "Präsens (all 6 forms)", "value": "himmle an / himmelst an / himmelt an / himmeln an / himmelt an / himmeln an"},
        ],
        "example": {
            "de": "Die Fans himmelten den Sänger regelrecht an.",
            "en": "The fans practically worshipped the singer.",
        },
        "etymology": "an- + Himmel (heaven/sky) — \"to elevate to heaven\"",
        "note": "Slightly ironic/mocking undertone when used about excessive adoration",
        "tags": ["humor", "relationships"],
        "priority": 0,
    },

    # ── Adjectives ─────────────────────────────────────────────────────────────

    {
        "id": "de-lebensmuede",
        "word": "lebensmüde",
        "translation": "tired of life, reckless/suicidal (also jokingly \"asking for trouble\")",
        "type": "adjective",
        "group": "🍺 Curated",
        "pronunciation": "LEH-bens-mü-de",
        "grammar": [
            {"label": "Comparative", "value": "lebensmüder"},
            {"label": "Superlative", "value": "am lebensmüdesten"},
        ],
        "example": {
            "de": "Bist du lebensmüde, bei diesem Verkehr über die Straße zu rennen?",
            "en": "Are you crazy, running across the street in this traffic?",
        },
        "etymology": "Leben (life) + müde (tired)",
        "note": "Often used hyperbolically/jokingly rather than literally",
        "tags": ["humor", "character-traits"],
        "priority": 0,
    },

    {
        "id": "de-gemuetlich",
        "word": "gemütlich",
        "translation": "cozy, comfortable, easygoing",
        "type": "adjective",
        "group": "🍺 Curated",
        "pronunciation": "ge-MÜT-likh",
        "grammar": [
            {"label": "Comparative", "value": "gemütlicher"},
            {"label": "Superlative", "value": "am gemütlichsten"},
        ],
        "example": {
            "de": "Wir hatten einen sehr gemütlichen Abend zusammen.",
            "en": "We had a very cozy evening together.",
        },
        "etymology": "from Gemüt (mind/temperament)",
        "note": "Can describe places, atmospheres, or people's manner",
        "tags": ["common", "culture"],
        "priority": 1,
    },

    {
        "id": "de-verschollen",
        "word": "verschollen",
        "translation": "missing, lost without a trace",
        "type": "adjective",
        "group": "🍺 Curated",
        "pronunciation": "fer-SHOLL-en",
        "grammar": [
            {"label": "Comparative", "value": "verschollener (rare)"},
            {"label": "Superlative", "value": "am verschollensten (rare)"},
        ],
        "example": {
            "de": "Der Seemann gilt seit Jahren als verschollen.",
            "en": "The sailor has been considered missing for years.",
        },
        "etymology": "from schallen (to sound/resound), related to \"not being heard from\"",
        "note": "Mostly used predicatively; rarely compared in practice",
        "tags": ["formal", "news"],
        "priority": 0,
    },

    {
        "id": "de-schnippisch",
        "word": "schnippisch",
        "translation": "snippy, curt, sassy",
        "type": "adjective",
        "group": "🍺 Curated",
        "pronunciation": "SHNIP-ish",
        "grammar": [
            {"label": "Comparative", "value": "schnippischer"},
            {"label": "Superlative", "value": "am schnippischsten"},
        ],
        "example": {
            "de": "Sie antwortete ziemlich schnippisch auf seine Frage.",
            "en": "She answered his question rather snippily.",
        },
        "etymology": "from schnippen (to snap/flick)",
        "note": "Mildly negative, describes tone of speech",
        "tags": ["character-traits"],
        "priority": 0,
    },

    {
        "id": "de-wehmutig",
        "word": "wehmütig",
        "translation": "wistful, melancholic",
        "type": "adjective",
        "group": "🍺 Curated",
        "pronunciation": "VEH-mü-tikh",
        "grammar": [
            {"label": "Comparative", "value": "wehmütiger"},
            {"label": "Superlative", "value": "am wehmütigsten"},
        ],
        "example": {
            "de": "Beim Anblick alter Fotos wurde sie ganz wehmütig.",
            "en": "Looking at old photos made her quite wistful.",
        },
        "etymology": "Wehmut (wistfulness/melancholy) + -ig",
        "note": "Softer and more nostalgic than \"traurig\" (sad)",
        "tags": ["emotions"],
        "priority": 0,
    },

    {
        "id": "de-durcheinander",
        "word": "durcheinander",
        "translation": "mixed up, in a muddle, confused",
        "type": "adjective",
        "group": "🍺 Curated",
        "pronunciation": "durkh-ai-NAN-der",
        "grammar": [
            {"label": "Comparative", "value": "(rarely compared)"},
            {"label": "Superlative", "value": "(rarely compared)"},
        ],
        "example": {
            "de": "Nach dem Umzug war noch alles durcheinander.",
            "en": "After the move, everything was still a mess.",
        },
        "etymology": "durch (through) + einander (one another)",
        "note": "Used predicatively only (not before a noun); rarely compared",
        "tags": ["common", "everyday"],
        "priority": 1,
    },

    # ── Adverbs ────────────────────────────────────────────────────────────────

    {
        "id": "de-uebermorgen",
        "word": "übermorgen",
        "translation": "the day after tomorrow",
        "type": "adverb",
        "group": "🍺 Curated",
        "pronunciation": "Ü-ber-mor-gen",
        "grammar": [],
        "example": {
            "de": "Übermorgen fliege ich nach Berlin.",
            "en": "The day after tomorrow I'm flying to Berlin.",
        },
        "etymology": "über (over/beyond) + Morgen (tomorrow/morning)",
        "note": "Pairs with vorgestern (the day before yesterday)",
        "tags": ["common", "time"],
        "priority": 1,
    },

    {
        "id": "de-neulich",
        "word": "neulich",
        "translation": "recently, the other day",
        "type": "adverb",
        "group": "🍺 Curated",
        "pronunciation": "NOY-likh",
        "grammar": [],
        "example": {
            "de": "Neulich habe ich einen alten Freund getroffen.",
            "en": "The other day I ran into an old friend.",
        },
        "etymology": "from neu (new)",
        "note": "Refers to a vague recent point in the past, not \"just now\"",
        "tags": ["common", "time"],
        "priority": 1,
    },

    {
        "id": "de-jein",
        "word": "jein",
        "translation": "\"yes and no\", a wishy-washy answer",
        "type": "adverb",
        "group": "🍺 Curated",
        "pronunciation": "YAIN",
        "grammar": [],
        "example": {
            "de": "\"Bist du fertig?\" — \"Jein, fast.\"",
            "en": "\"Are you done?\" — \"Sort of, almost.\"",
        },
        "etymology": "blend of ja (yes) and nein (no)",
        "note": "Colloquial, playful; not appropriate in formal writing",
        "tags": ["slang", "humor"],
        "priority": 0,
    },

    # ── Phrases ────────────────────────────────────────────────────────────────

    {
        "id": "de-auf-wolke-sieben",
        "word": "auf Wolke sieben schweben",
        "translation": "to be on cloud nine",
        "type": "phrase",
        "group": "🍺 Curated",
        "pronunciation": "owf VOL-ke ZEE-ben SHVEH-ben",
        "grammar": [
            {"label": "Register", "value": "colloquial"},
        ],
        "example": {
            "de": "Seit dem ersten Date schwebt sie auf Wolke sieben.",
            "en": "She's been on cloud nine since the first date.",
        },
        "etymology": "Wolke sieben (cloud seven) + schweben (to float/hover); German equivalent of English \"cloud nine\"",
        "note": "Used for romantic infatuation or elation",
        "tags": ["idiom", "relationships"],
        "priority": 0,
    },

    {
        "id": "de-apfel-stamm",
        "word": "Der Apfel fällt nicht weit vom Stamm",
        "translation": "like father like son / the apple doesn't fall far from the tree",
        "type": "phrase",
        "group": "🍺 Curated",
        "pronunciation": "dair AHP-fel felt nikht vait fom shtahm",
        "grammar": [
            {"label": "Register", "value": "neutral"},
        ],
        "example": {
            "de": "Sie ist genauso stur wie ihre Mutter — der Apfel fällt nicht weit vom Stamm.",
            "en": "She's just as stubborn as her mother — the apple doesn't fall far from the tree.",
        },
        "etymology": "Apfel (apple) + Stamm (trunk); a shared proverb across many European languages",
        "note": "Used when children resemble parents in character, for better or worse",
        "tags": ["idiom", "family"],
        "priority": 0,
    },

]
