"""
it_el_vocab_data.py — Italian vocabulary cards for Greek speakers (departure_lang='el').
Imported automatically by it_vocab_data.py.
"""

CARDS = [

    # ── Ουσιαστικά ────────────────────────────────────────────────────────────

    {
        "id": "it-el-nostalgia",
        "italian": "nostalgia",
        "translation": "νοσταλγία, νόστος, καημός",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/nos.taˈldʒi.a/",
        "gender": "f",
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "f"},
        ],
        "example": {
            "it": "Sento una strana nostalgia per la mia città natale.",
            "el": "Νιώθω μια παράξενη νοσταλγία για την πόλη που γεννήθηκα.",
        },
        "etymology": "Από το ελληνικό νόστος (επιστροφή στην πατρίδα) + άλγος (πόνος), επινοήθηκε τον 17ο αιώνα.",
        "note": 'Χρησιμοποιείται συχνά με "di" ή "per"· το avere nostalgia di qualcosa είναι η τυπική κατασκευή.',
        "tags": ["common", "emotions"],
        "priority": 1,
    },

    {
        "id": "it-el-scrivania",
        "italian": "scrivania",
        "translation": "γραφείο, τραπέζι γραψίματος",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/skri.vaˈni.a/",
        "gender": "f",
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "scrivanie"},
        ],
        "example": {
            "it": "Ho lasciato le chiavi sulla scrivania.",
            "el": "Άφησα τα κλειδιά στο γραφείο.",
        },
        "etymology": 'Από το "scrivere" (γράφω).',
        "note": 'Διαφέρει από το "tavolo" (γενικό τραπέζι)· το scrivania υποδηλώνει συγκεκριμένα γραφείο εργασίας/γραψίματος.',
        "tags": ["common", "home", "daily-life"],
        "priority": 0,
    },

    {
        "id": "it-el-sciopero",
        "italian": "sciopero",
        "translation": "απεργία",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/ˈʃɔ.pe.ro/",
        "gender": "m",
        "article": "lo",
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Article override", "value": "lo"},
            {"label": "Plural", "value": "scioperi"},
        ],
        "example": {
            "it": "I treni sono in ritardo per lo sciopero.",
            "el": "Τα τρένα αργούν λόγω της απεργίας.",
        },
        "etymology": 'Αβέβαιη προέλευση — πιθανώς από το "operare" με αποθετικό πρόθεμα "s-", ή από γενοβέζικη διάλεκτο.',
        "note": 'Fare sciopero = "κάνω απεργία". Συνηθισμένο στις ειδήσεις και τα ΜΜΕ.',
        "tags": ["common", "news", "work-society"],
        "priority": 1,
    },

    {
        "id": "it-el-bussola",
        "italian": "bussola",
        "translation": "πυξίδα",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/ˈbus.so.la/",
        "gender": "f",
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "bussole"},
        ],
        "example": {
            "it": "Senza bussola ci siamo persi nel bosco.",
            "el": "Χωρίς πυξίδα χαθήκαμε στο δάσος.",
        },
        "etymology": 'Από το "buxus" (πυξάρι, το υλικό από το οποίο φτιάχνονταν παλαιά οι θήκες πυξίδων).',
        'note': 'Μεταφορικά, "perdere la bussola" σημαίνει να χάσεις τον προσανατολισμό ή την ψυχραιμία σου.',
        "tags": ["travel", "idiom-source"],
        "priority": 0,
    },

    {
        "id": "it-el-tramonto",
        "italian": "tramonto",
        "translation": "ηλιοβασίλεμα",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/traˈmon.to/",
        "gender": "m",
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "tramonti"},
        ],
        "example": {
            "it": "Guardiamo il tramonto dalla spiaggia.",
            "el": "Ας παρακολουθήσουμε το ηλιοβασίλεμα από την παραλία.",
        },
        "etymology": 'Από το "tramontare" (δύω, για τον ήλιο), από το λατινικό "trans" + "montare".',
        "note": "Χρησιμοποιείται και μεταφορικά για την παρακμή κάποιου πράγματος (il tramonto di un'epoca = η δύση μιας εποχής).",
        "tags": ["common", "nature"],
        "priority": 1,
    },

    {
        "id": "it-el-formaggio",
        "italian": "formaggio",
        "translation": "τυρί",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/forˈmad.dʒo/",
        "gender": "m",
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "formaggi"},
        ],
        "example": {
            "it": "Il formaggio stagionato ha un sapore più forte.",
            "el": "Το παλαιωμένο τυρί έχει πιο έντονη γεύση.",
        },
        "etymology": 'Από το υστερολατινικό "formaticum" (φτιαγμένο σε καλούπι), μέσω του "forma".',
        "note": 'Το περιφερειακό συνώνυμο "cacio" είναι κοινό στην κεντρική/νότια Ιταλία.',
        "tags": ["common", "food"],
        "priority": 1,
    },

    {
        "id": "it-el-valigia",
        "italian": "valigia",
        "translation": "βαλίτσα",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/vaˈli.dʒa/",
        "gender": "f",
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "valigie"},
        ],
        "example": {
            "it": "Ho fatto la valigia in dieci minuti.",
            "el": "Έφτιαξα τη βαλίτσα μου σε δέκα λεπτά.",
        },
        "etymology": 'Από το "Valenza", παλαιά ονομασία για δερμάτινα είδη, πιθανώς συνδεδεμένη με την πόλη Βαλένθια.',
        'note': '"Fare la valigia" = ετοιμάζω βαλίτσα. Ο πληθυντικός είναι ανώμαλος για μαθητές: valigie (όχι valige).',
        "tags": ["common", "travel"],
        "priority": 1,
    },

    {
        "id": "it-el-specchio",
        "italian": "specchio",
        "translation": "καθρέφτης",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/ˈspek.kjo/",
        "gender": "m",
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "specchi"},
        ],
        "example": {
            "it": "Mi sono guardato allo specchio prima di uscire.",
            "el": "Κοιτάχτηκα στον καθρέφτη πριν βγω.",
        },
        "etymology": 'Από το λατινικό "speculum".',
        "note": '"Specchietto retrovisore" = καθρέφτης οπισθοπορείας.',
        "tags": ["common", "home", "daily-life"],
        "priority": 0,
    },

    {
        "id": "it-el-fulmine",
        "italian": "fulmine",
        "translation": "κεραυνός",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/ˈful.mi.ne/",
        "gender": "m",
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "fulmini"},
        ],
        "example": {
            "it": "Un fulmine ha colpito l'albero vicino a casa.",
            "el": "Ένας κεραυνός χτύπησε το δέντρο κοντά στο σπίτι.",
        },
        "etymology": 'Από το λατινικό "fulmen", σχετικό με το "fulgere" (λάμπω/αστράφτω).',
        "note": '"Come un fulmine a ciel sereno" = σαν κεραυνός εν αιθρία, χωρίς προειδοποίηση.',
        "tags": ["nature", "idiom-source"],
        "priority": 0,
    },

    {
        "id": "it-el-farfalla",
        "italian": "farfalla",
        "translation": "πεταλούδα",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/farˈfal.la/",
        "gender": "f",
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "farfalle"},
        ],
        "example": {
            "it": "Una farfalla si è posata sul fiore.",
            "el": "Μια πεταλούδα κάθισε στο λουλούδι.",
        },
        "etymology": 'Από το λατινικό "papilio", τροποποιημένο μέσα από τον λαϊκό λόγο, ίσως επηρεασμένο από το "farfallone".',
        "note": "Είναι επίσης το όνομα του σχήματος ζυμαρικών και της κολυμβητικής τεχνικής πεταλούδα.",
        "tags": ["nature", "common"],
        "priority": 0,
    },

    {
        "id": "it-el-malinconia",
        "italian": "malinconia",
        "translation": "μελαγχολία, θλίψη, νοσταλγική λύπη",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/ma.lin.koˈni.a/",
        "gender": "f",
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "f"},
        ],
        "example": {
            "it": "Un velo di malinconia ha coperto la sua voce.",
            "el": "Ένα πέπλο μελαγχολίας σκέπασε τη φωνή της.",
        },
        "etymology": 'Από το ελληνικό "μελαγχολία" (μαύρη χολή), μέρος της αρχαίας θεωρίας των χυμών.',
        'note': 'Πιο ήπιο και ποιητικό από το "tristezza"· χρησιμοποιείται συχνά σε λογοτεχνικά ή στοχαστικά πλαίσια.',
        "tags": ["emotions", "literary"],
        "priority": 0,
    },

    {
        "id": "it-el-capriccio",
        "italian": "capriccio",
        "translation": "ιδιοτροπία, νεύρα, καπρίτσιο",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/kaˈprit.tʃo/",
        "gender": "m",
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "capricci"},
        ],
        "example": {
            "it": "Il bambino ha fatto un capriccio al supermercato.",
            "el": "Το παιδί έκανε νεύρα στο σούπερ μάρκετ.",
        },
        "etymology": 'Πιθανώς από το "capro" (τράγος) ή από το "capo" + "riccio" (τριχωτή που ανατριχιάζει από τρόμο).',
        "note": '"Fare i capricci" = κάνω νεύρα/ιδιοτροπίες (χρησιμοποιείται για παιδιά).',
        "tags": ["emotions", "common"],
        "priority": 0,
    },

    {
        "id": "it-el-rimpianto",
        "italian": "rimpianto",
        "translation": "μεταμέλεια, τύψη",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/rimˈpjan.to/",
        "gender": "m",
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "rimpianti"},
        ],
        "example": {
            "it": "Non ho rimpianti per le scelte che ho fatto.",
            "el": "Δεν έχω τύψεις για τις επιλογές που έκανα.",
        },
        "etymology": 'Από το "rimpiangere" (μετανιώνω), από το "ri-" + "piangere" (κλαίω).',
        "note": 'Ελαφρώς πιο επίσημο/λογοτεχνικό από το "rammarico".',
        "tags": ["emotions"],
        "priority": 0,
    },

    {
        "id": "it-el-quotidianita",
        "italian": "quotidianità",
        "translation": "καθημερινότητα, ρουτίνα",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/kwo.ti.dja.niˈta/",
        "gender": "f",
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "quotidianità (invariable)"},
        ],
        "example": {
            "it": "Mi piace la semplicità della quotidianità.",
            "el": "Μου αρέσει η απλότητα της καθημερινότητας.",
        },
        "etymology": 'Από το "quotidiano" (καθημερινός), από το λατινικό "cotidianus".',
        "note": "Αφηρημένο ουσιαστικό, συνήθως χρησιμοποιείται μόνο στον ενικό.",
        "tags": ["daily-life", "abstract"],
        "priority": 0,
    },

    {
        "id": "it-el-arguzia",
        "italian": "arguzia",
        "translation": "ευφυΐα, πνευματικότητα",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/arˈɡu.tsja/",
        "gender": "f",
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "arguzie"},
        ],
        "example": {
            "it": "Ha risposto con la sua solita arguzia.",
            "el": "Απάντησε με τη συνηθισμένη της ευφυΐα.",
        },
        "etymology": 'Από το λατινικό "argutia", σχετικό με το "argutus" (οξύς, έξυπνος).',
        'note': 'Κάπως επίσημο/λογοτεχνικό· το "spirito" είναι η πιο καθημερινή λέξη για πνευματικότητα.',
        "tags": ["personality", "literary"],
        "priority": 0,
    },

    {
        "id": "it-el-straniero",
        "italian": "straniero",
        "translation": "αλλοδαπός, ξένος",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/straˈnjɛ.ro/",
        "gender": "m",
        "departure_lang": "el",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "stranieri"},
        ],
        "example": {
            "it": "Da straniero, mi sento sempre benvenuto qui.",
            "el": "Ως ξένος, νιώθω πάντα ευπρόσδεκτος εδώ.",
        },
        "etymology": 'Από το παλαιό γαλλικό "estrangier", από το λατινικό "extraneus" (εξωτερικός, ξένος).',
        "note": "Θηλυκός τύπος: straniera. Λειτουργεί επίσης ως επίθετο (paese straniero = ξένη χώρα).",
        "tags": ["travel", "common"],
        "priority": 1,
    },

    # ── Ρήματα ────────────────────────────────────────────────────────────────

    {
        "id": "it-el-chiacchierare",
        "italian": "chiacchierare",
        "translation": "κουβεντιάζω, κουτσομπολεύω",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/kjak.kjeˈra.re/",
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "-are"},
            {"label": "Auxiliary (passato prossimo)", "value": "avere"},
            {"label": "Participio passato", "value": "chiacchierato"},
            {"label": "Passato remoto (io)", "value": "chiacchierai"},
            {"label": "Gerundio", "value": "chiacchierando"},
            {"label": "Presente (all 6 forms)", "value": "chiacchiero / chiacchieri / chiacchiera / chiacchieriamo / chiacchierate / chiacchierano"},
        ],
        "example": {
            "it": "Ci siamo fermati a chiacchierare al bar.",
            "el": "Σταματήσαμε να κουβεντιάσουμε στο μπαρ.",
        },
        "etymology": 'Ονοματοποιητική ρίζα "chiacchiera" (φλυαρία), που μιμείται τον ήχο της συζήτησης.',
        'note': 'Ανεπίσημο, κοινωνικό ύφος — διαφέρει από το "parlare" (ουδέτερο "μιλώ").',
        "tags": ["common", "social", "daily-life"],
        "priority": 1,
    },

    {
        "id": "it-el-sorridere",
        "italian": "sorridere",
        "translation": "χαμογελώ",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/sorˈri.de.re/",
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "irregular"},
            {"label": "Auxiliary (passato prossimo)", "value": "avere"},
            {"label": "Participio passato", "value": "sorriso"},
            {"label": "Passato remoto (io)", "value": "sorrisi"},
            {"label": "Gerundio", "value": "sorridendo"},
            {"label": "Presente (all 6 forms)", "value": "sorrido / sorridi / sorride / sorridiamo / sorridete / sorridono"},
        ],
        "example": {
            "it": "Mi ha sorriso appena mi ha visto.",
            "el": "Μου χαμογέλασε μόλις με είδε.",
        },
        "etymology": 'Από το λατινικό "subridere" (sub- + ridere, "γελώ").',
        'note': 'Ανώμαλο όπως το βασικό του ρήμα "ridere"· προσέξτε το μοτίβο -is- στη μετοχή/παρελθοντικό.',
        "tags": ["common", "emotions"],
        "priority": 1,
    },

    {
        "id": "it-el-svegliarsi",
        "italian": "svegliarsi",
        "translation": "ξυπνώ",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/zveʎˈʎar.si/",
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "-are"},
            {"label": "Auxiliary (passato prossimo)", "value": "essere"},
            {"label": "Participio passato", "value": "svegliato"},
            {"label": "Passato remoto (io)", "value": "mi svegliai"},
            {"label": "Gerundio", "value": "svegliandosi"},
            {"label": "Presente (all 6 forms)", "value": "mi sveglio / ti svegli / si sveglia / ci svegliamo / vi svegliate / si svegliano"},
        ],
        "example": {
            "it": "Mi sveglio sempre presto durante la settimana.",
            "el": "Ξυπνώ πάντα νωρίς τις καθημερινές.",
        },
        "etymology": 'Από το "svegliare" (ξυπνώ κάποιον), από το λατινικό "ex-vigilare".',
        'note': 'Αντανακλαστικό — παίρνει essere στους σύνθετους χρόνους. Αντίθετο: "svegliare" (ξυπνώ κάποιον άλλο).',
        "tags": ["common", "daily-life"],
        "priority": 1,
    },

    {
        "id": "it-el-raggiungere",
        "italian": "raggiungere",
        "translation": "φτάνω, προφτάνω",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/rad.ˈdʒun.dʒe.re/",
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "irregular"},
            {"label": "Auxiliary (passato prossimo)", "value": "avere"},
            {"label": "Participio passato", "value": "raggiunto"},
            {"label": "Passato remoto (io)", "value": "raggiunsi"},
            {"label": "Gerundio", "value": "raggiungendo"},
            {"label": "Presente (all 6 forms)", "value": "raggiungo / raggiungi / raggiunge / raggiungiamo / raggiungete / raggiungono"},
        ],
        "example": {
            "it": "Ti raggiungo tra dieci minuti.",
            "el": "Θα σε προφτάσω σε δέκα λεπτά.",
        },
        "etymology": 'Από το "giungere" (φτάνω), από το λατινικό "jungere" (συνδέω), με το πρόθεμα "ra-".',
        "note": "Χρησιμοποιείται και αφηρημένα: raggiungere un obiettivo = επιτυγχάνω έναν στόχο.",
        "tags": ["common", "travel"],
        "priority": 1,
    },

    {
        "id": "it-el-accorgersi",
        "italian": "accorgersi",
        "translation": "αντιλαμβάνομαι, παρατηρώ",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/akˈkɔr.dʒer.si/",
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "irregular"},
            {"label": "Auxiliary (passato prossimo)", "value": "essere"},
            {"label": "Participio passato", "value": "accorto"},
            {"label": "Passato remoto (io)", "value": "mi accorsi"},
            {"label": "Gerundio", "value": "accorgendosi"},
            {"label": "Presente (all 6 forms)", "value": "mi accorgo / ti accorgi / si accorge / ci accorgiamo / vi accorgete / si accorgono"},
        ],
        "example": {
            "it": "Non mi sono accorto dell'errore subito.",
            "el": "Δεν παρατήρησα αμέσως το λάθος.",
        },
        "etymology": 'Από το λατινικό "ad-" + "corrigere" (διορθώνω), με σημασιολογική αλλαγή με την πάροδο του χρόνου.',
        'note': 'Πάντα αντανακλαστικό· ακολουθείται από "di" + ουσιαστικό/απαρέμφατο (accorgersi di qualcosa).',
        "tags": ["common", "emotions"],
        "priority": 1,
    },

    {
        "id": "it-el-fingere",
        "italian": "fingere",
        "translation": "προσποιούμαι, υποκρίνομαι",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/ˈfin.dʒe.re/",
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "irregular"},
            {"label": "Auxiliary (passato prossimo)", "value": "avere"},
            {"label": "Participio passato", "value": "finto"},
            {"label": "Passato remoto (io)", "value": "finsi"},
            {"label": "Gerundio", "value": "fingendo"},
            {"label": "Presente (all 6 forms)", "value": "fingo / fingi / finge / fingiamo / fingete / fingono"},
        ],
        "example": {
            "it": "Ha finto di non sentire la domanda.",
            "el": "Προσποιήθηκε ότι δεν άκουσε την ερώτηση.",
        },
        "etymology": 'Από το λατινικό "fingere" (πλάθω, σκαρφίζομαι) — ίδια ρίζα με το "finzione" (μυθοπλασία).',
        "note": '"Fingere di + απαρέμφατο" είναι η τυπική κατασκευή.',
        "tags": ["common", "personality"],
        "priority": 0,
    },

    {
        "id": "it-el-affrettarsi",
        "italian": "affrettarsi",
        "translation": "βιάζομαι, σπεύδω",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/af.fretˈtar.si/",
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "-are"},
            {"label": "Auxiliary (passato prossimo)", "value": "essere"},
            {"label": "Participio passato", "value": "affrettato"},
            {"label": "Passato remoto (io)", "value": "mi affrettai"},
            {"label": "Gerundio", "value": "affrettandosi"},
            {"label": "Presente (all 6 forms)", "value": "mi affretto / ti affretti / si affretta / ci affrettiamo / vi affrettate / si affrettano"},
        ],
        "example": {
            "it": "Affrettati, il treno sta per partire!",
            "el": "Βιάσου, το τρένο πρόκειται να φύγει!",
        },
        "etymology": 'Από το "affrettare" (επιταχύνω), από το "a-" + "fretta" (βιάση).',
        "note": "Αντανακλαστικό· χρησιμοποιείται συχνά στην προστακτική, όπως παραπάνω.",
        "tags": ["common", "daily-life"],
        "priority": 0,
    },

    {
        "id": "it-el-annoiarsi",
        "italian": "annoiarsi",
        "translation": "βαριέμαι",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/an.noˈjar.si/",
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "-are"},
            {"label": "Auxiliary (passato prossimo)", "value": "essere"},
            {"label": "Participio passato", "value": "annoiato"},
            {"label": "Passato remoto (io)", "value": "mi annoiai"},
            {"label": "Gerundio", "value": "annoiandosi"},
            {"label": "Presente (all 6 forms)", "value": "mi annoio / ti annoi / si annoia / ci annoiamo / vi annoiate / si annoiano"},
        ],
        "example": {
            "it": "Mi annoio quando piove tutto il giorno.",
            "el": "Βαριέμαι όταν βρέχει όλη μέρα.",
        },
        "etymology": 'Από το "annoiare" (βαριέμαι/ενοχλούμαι), από το παλαιό γαλλικό "enui" — ίδια ρίζα με το αγγλικό "ennui".',
        'note': 'Αντανακλαστικό· το μη αντανακλαστικό "annoiare" σημαίνει "βαριέμαι/ενοχλώ κάποιον άλλο".',
        "tags": ["common", "emotions"],
        "priority": 0,
    },

    {
        "id": "it-el-costruire",
        "italian": "costruire",
        "translation": "χτίζω, κατασκευάζω",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/ko.struˈi.re/",
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "-ire"},
            {"label": "Auxiliary (passato prossimo)", "value": "avere"},
            {"label": "Participio passato", "value": "costruito"},
            {"label": "Passato remoto (io)", "value": "costruii"},
            {"label": "Gerundio", "value": "costruendo"},
            {"label": "Presente (all 6 forms)", "value": "costruisco / costruisci / costruisce / costruiamo / costruite / costruiscono"},
        ],
        "example": {
            "it": "Stanno costruendo un nuovo ponte in centro.",
            "el": "Χτίζουν μια νέα γέφυρα στο κέντρο.",
        },
        "etymology": 'Από το λατινικό "construere" (con- + struere, "συσσωρεύω").',
        'note': 'Ακολουθεί το μοτίβο -isc- στον ενεστώτα (όπως "capire", "finire").',
        "tags": ["common", "work", "work-society"],
        "priority": 0,
    },

    {
        "id": "it-el-tradurre",
        "italian": "tradurre",
        "translation": "μεταφράζω",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/traˈdur.re/",
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "irregular"},
            {"label": "Auxiliary (passato prossimo)", "value": "avere"},
            {"label": "Participio passato", "value": "tradotto"},
            {"label": "Passato remoto (io)", "value": "tradussi"},
            {"label": "Gerundio", "value": "traducendo"},
            {"label": "Presente (all 6 forms)", "value": "traduco / traduci / traduce / traduciamo / traducete / traducono"},
        ],
        "example": {
            "it": "Ho tradotto il documento dall'italiano al tedesco.",
            "el": "Μετέφρασα το έγγραφο από τα ιταλικά στα γερμανικά.",
        },
        "etymology": 'Από το λατινικό "traducere" (οδηγώ απέναντι). Ίδια ρίζα με το αγγλικό "translate".',
        'note': 'Ανώμαλη κλίση που μοιράζεται με τα "produrre", "condurre" κ.λπ. (η οικογένεια -durre).',
        "tags": ["common", "work", "work-society"],
        "priority": 1,
    },

    {
        "id": "it-el-ingannare",
        "italian": "ingannare",
        "translation": "εξαπατώ, ξεγελώ",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/in.ɡanˈna.re/",
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "-are"},
            {"label": "Auxiliary (passato prossimo)", "value": "avere"},
            {"label": "Participio passato", "value": "ingannato"},
            {"label": "Passato remoto (io)", "value": "ingannai"},
            {"label": "Gerundio", "value": "ingannando"},
            {"label": "Presente (all 6 forms)", "value": "inganno / inganni / inganna / inganniamo / ingannate / ingannano"},
        ],
        "example": {
            "it": "Non lasciarti ingannare dalle apparenze.",
            "el": "Μην αφήνεσαι να σε εξαπατούν τα φαινόμενα.",
        },
        "etymology": 'Από το λατινικό "in-" + "gannire" (γαυγίζω/μουγγρίζω), με σημασιολογική μετάβαση στο "εξαπατώ".',
        "note": '"Ingannare il tempo" = σκοτώνω τον χρόνο (ιδιωματικό).',
        "tags": ["personality"],
        "priority": 0,
    },

    {
        "id": "it-el-sospirare",
        "italian": "sospirare",
        "translation": "αναστενάζω",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/sos.piˈra.re/",
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "-are"},
            {"label": "Auxiliary (passato prossimo)", "value": "avere"},
            {"label": "Participio passato", "value": "sospirato"},
            {"label": "Passato remoto (io)", "value": "sospirai"},
            {"label": "Gerundio", "value": "sospirando"},
            {"label": "Presente (all 6 forms)", "value": "sospiro / sospiri / sospira / sospiriamo / sospirate / sospirano"},
        ],
        "example": {
            "it": "Ha sospirato profondamente prima di rispondere.",
            "el": "Αναστέναξε βαθιά πριν απαντήσει.",
        },
        "etymology": 'Από το λατινικό "suspirare" (sub- + spirare, "αναπνέω").',
        'note': 'Σχετικό ουσιαστικό: "sospiro" (ένας αναστεναγμός).',
        "tags": ["emotions"],
        "priority": 0,
    },

    {
        "id": "it-el-vagabondare",
        "italian": "vagabondare",
        "translation": "περιπλανιέμαι, τριγυρίζω",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/va.ɡa.bonˈda.re/",
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "-are"},
            {"label": "Auxiliary (passato prossimo)", "value": "avere"},
            {"label": "Participio passato", "value": "vagabondato"},
            {"label": "Passato remoto (io)", "value": "vagabondai"},
            {"label": "Gerundio", "value": "vagabondando"},
            {"label": "Presente (all 6 forms)", "value": "vagabondo / vagabondi / vagabonda / vagabondiamo / vagabondate / vagabondano"},
        ],
        "example": {
            "it": "Mi piace vagabondare per le vie della città senza meta.",
            "el": "Μου αρέσει να περιπλανιέμαι στους δρόμους της πόλης χωρίς προορισμό.",
        },
        "etymology": 'Από το "vagabondo" (αλήτης), από το λατινικό "vagari" (περιπλανιέμαι).',
        'note': 'Ελαφρώς ποιητικό/λογοτεχνικό ύφος· το "girovagare" είναι στενό συνώνυμο.',
        "tags": ["travel", "literary"],
        "priority": 0,
    },

    {
        "id": "it-el-stupire",
        "italian": "stupire",
        "translation": "εκπλήσσω, καταπλήσσω",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/stuˈpi.re/",
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "-ire"},
            {"label": "Auxiliary (passato prossimo)", "value": "avere"},
            {"label": "Participio passato", "value": "stupito"},
            {"label": "Passato remoto (io)", "value": "stupii"},
            {"label": "Gerundio", "value": "stupendo"},
            {"label": "Presente (all 6 forms)", "value": "stupisco / stupisci / stupisce / stupiamo / stupite / stupiscono"},
        ],
        "example": {
            "it": "Il suo talento continua a stupirmi.",
            "el": "Το ταλέντο της συνεχίζει να με εκπλήσσει.",
        },
        "etymology": 'Από το λατινικό "stupere" (μένω άναυδος/παγωμένος).',
        'note': 'Ακολουθεί το μοτίβο -isc-· το αντανακλαστικό "stupirsi" σημαίνει "εκπλήσσομαι" (παίρνει essere).',
        "tags": ["common", "emotions"],
        "priority": 0,
    },

    {
        "id": "it-el-mancare",
        "italian": "mancare",
        "translation": "λείπω, μου λείπει",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/manˈka.re/",
        "departure_lang": "el",
        "grammar": [
            {"label": "Verb group", "value": "-are"},
            {"label": "Auxiliary (passato prossimo)", "value": "essere"},
            {"label": "Participio passato", "value": "mancato"},
            {"label": "Passato remoto (io)", "value": "mancai"},
            {"label": "Gerundio", "value": "mancando"},
            {"label": "Presente (all 6 forms)", "value": "manco / manchi / manca / manchiamo / mancate / mancano"},
        ],
        "example": {
            "it": "Mi manchi molto quando sei via.",
            "el": "Μου λείπεις πολύ όταν λείπεις.",
        },
        "etymology": 'Από το λατινικό "mancus" (ατελής, αυτός που του λείπει το χέρι).',
        "note": 'Γραμματική παγίδα: "tu mi manchi" = "μου λείπεις" (κυριολεκτικά "εσύ μου λείπεις"). Το βοηθητικό μπορεί να αλλάξει σε avere όταν σημαίνει "παραλείπω να κάνω κάτι".',
        "tags": ["common", "grammar-trap", "emotions"],
        "priority": 1,
    },

    # ── Επίθετα ───────────────────────────────────────────────────────────────

    {
        "id": "it-el-goloso",
        "italian": "goloso",
        "translation": "λαίμαργος, γλυκατζής",
        "type": "adjective",
        "scene_id": "🍕 Curated",
        "pronunciation": "/ɡoˈlo.zo/",
        "departure_lang": "el",
        "grammar": [
            {"label": "Feminine form", "value": "golosa"},
            {"label": "Plural (masc.)", "value": "golosi"},
            {"label": "Plural (fem.)", "value": "golose"},
        ],
        "example": {
            "it": "Sono golosa di cioccolato.",
            "el": "Είμαι γλυκατζού με σοκολάτα.",
        },
        "etymology": 'Από το "gola" (λαιμός/λαιμαργία), από το λατινικό "gula".',
        "note": '"Essere goloso di" + ουσιαστικό = είμαι φανατικός με / λαχταρώ κάτι.',
        "tags": ["personality", "food"],
        "priority": 0,
    },

    {
        "id": "it-el-testardo",
        "italian": "testardo",
        "translation": "πεισματάρης, ισχυρογνώμων",
        "type": "adjective",
        "scene_id": "🍕 Curated",
        "pronunciation": "/tesˈtar.do/",
        "departure_lang": "el",
        "grammar": [
            {"label": "Feminine form", "value": "testarda"},
            {"label": "Plural (masc.)", "value": "testardi"},
            {"label": "Plural (fem.)", "value": "testarde"},
        ],
        "example": {
            "it": "Mio fratello è troppo testardo per ammettere l'errore.",
            "el": "Ο αδερφός μου είναι πολύ πεισματάρης για να παραδεχτεί το λάθος.",
        },
        "etymology": 'Από το "testa" (κεφάλι), υποδηλώνοντας σκληροκεφαλιά.',
        'note': 'Κοινό συνώνυμο: "ostinato" (ελαφρώς πιο επίσημο).',
        "tags": ["personality", "common"],
        "priority": 1,
    },

    {
        "id": "it-el-sfacciato",
        "italian": "sfacciato",
        "translation": "αναιδής, αδιάντροπος, θρασύς",
        "type": "adjective",
        "scene_id": "🍕 Curated",
        "pronunciation": "/sfatˈtʃa.to/",
        "departure_lang": "el",
        "grammar": [
            {"label": "Feminine form", "value": "sfacciata"},
            {"label": "Plural (masc.)", "value": "sfacciati"},
            {"label": "Plural (fem.)", "value": "sfacciate"},
        ],
        "example": {
            "it": "Che risposta sfacciata!",
            "el": "Τι αναιδής απάντηση!",
        },
        "etymology": 'Από το "faccia" (πρόσωπο), με το πρόθεμα "s-" που σημαίνει "χωρίς" (δηλ. "χωρίς πρόσωπο" = αδιάντροπος).',
        "note": "Μπορεί να είναι στοργικό/πειραχτικό ή πραγματικά κριτικό ανάλογα με τον τόνο.",
        "tags": ["personality"],
        "priority": 0,
    },

    {
        "id": "it-el-distratto",
        "italian": "distratto",
        "translation": "αφηρημένος, αποσπασμένος",
        "type": "adjective",
        "scene_id": "🍕 Curated",
        "pronunciation": "/disˈtrat.to/",
        "departure_lang": "el",
        "grammar": [
            {"label": "Feminine form", "value": "distratta"},
            {"label": "Plural (masc.)", "value": "distratti"},
            {"label": "Plural (fem.)", "value": "distratte"},
        ],
        "example": {
            "it": "Ero troppo distratto per notare il cartello.",
            "el": "Ήμουν πολύ αφηρημένος για να παρατηρήσω την πινακίδα.",
        },
        "etymology": 'Μετοχή παρελθόντος του "distrarre" (αποσπώ), από το λατινικό "distrahere".',
        'note': 'Λειτουργεί επίσης ως μετοχή παρελθόντος του ρήματος "distrarre".',
        "tags": ["common", "personality"],
        "priority": 0,
    },

    {
        "id": "it-el-accogliente",
        "italian": "accogliente",
        "translation": "φιλόξενος, ζεστός, άνετος",
        "type": "adjective",
        "scene_id": "🍕 Curated",
        "pronunciation": "/ak.koʎˈʎɛn.te/",
        "departure_lang": "el",
        "grammar": [
            {"label": "Feminine form", "value": "accogliente (invariable)"},
            {"label": "Plural (masc.)", "value": "accoglienti"},
            {"label": "Plural (fem.)", "value": "accoglienti"},
        ],
        "example": {
            "it": "Il loro appartamento è piccolo ma accogliente.",
            "el": "Το διαμέρισμά τους είναι μικρό αλλά άνετο.",
        },
        "etymology": 'Από το "accogliere" (υποδέχομαι/φιλοξενώ), από το λατινικό "ad-" + "colligere".',
        "note": "Αναλλοίωτο ως προς το γένος (ίδια μορφή αρσ./θηλ.)· αλλάζει μόνο ο πληθυντικός.",
        "tags": ["common", "home", "daily-life"],
        "priority": 1,
    },

    {
        "id": "it-el-spettinato",
        "italian": "spettinato",
        "translation": "ατημέλητος, ανακατεμένα μαλλιά",
        "type": "adjective",
        "scene_id": "🍕 Curated",
        "pronunciation": "/spet.tiˈna.to/",
        "departure_lang": "el",
        "grammar": [
            {"label": "Feminine form", "value": "spettinata"},
            {"label": "Plural (masc.)", "value": "spettinati"},
            {"label": "Plural (fem.)", "value": "spettinate"},
        ],
        "example": {
            "it": "Sono uscita di casa tutta spettinata.",
            "el": "Βγήκα από το σπίτι εντελώς ατημέλητη.",
        },
        "etymology": 'Από το "pettinare" (χτενίζω), με αρνητικό πρόθεμα "s-".',
        'note': 'Αναφέρεται ειδικά σε ανακατεμένα μαλλιά· για γενική αταξία χρησιμοποιείται το "disordinato".',
        "tags": ["daily-life"],
        "priority": 0,
    },

    {
        "id": "it-el-sgraziato",
        "italian": "sgraziato",
        "translation": "άχαρος, αδέξιος",
        "type": "adjective",
        "scene_id": "🍕 Curated",
        "pronunciation": "/zɡratˈtsja.to/",
        "departure_lang": "el",
        "grammar": [
            {"label": "Feminine form", "value": "sgraziata"},
            {"label": "Plural (masc.)", "value": "sgraziati"},
            {"label": "Plural (fem.)", "value": "sgraziate"},
        ],
        "example": {
            "it": "I suoi movimenti sono un po' sgraziati.",
            "el": "Οι κινήσεις του είναι λίγο αδέξιες.",
        },
        "etymology": 'Από το "grazia" (χάρη/χαριτωμένο), με αρνητικό πρόθεμα "s-".',
        'note': 'Περιγράφει σωματική αδεξιότητα· το "goffo" είναι στενό συνώνυμο.',
        "tags": ["personality"],
        "priority": 0,
    },

    {
        "id": "it-el-schietto",
        "italian": "schietto",
        "translation": "ειλικρινής, ευθύς, αμεσος",
        "type": "adjective",
        "scene_id": "🍕 Curated",
        "pronunciation": "/ˈskjɛt.to/",
        "departure_lang": "el",
        "grammar": [
            {"label": "Feminine form", "value": "schietta"},
            {"label": "Plural (masc.)", "value": "schietti"},
            {"label": "Plural (fem.)", "value": "schiette"},
        ],
        "example": {
            "it": "Apprezzo il tuo modo schietto di dire le cose.",
            "el": "Εκτιμώ τον άμεσο τρόπο σου να λες τα πράγματα.",
        },
        "etymology": 'Από γερμανική ρίζα σχετική με το "schlicht" (απλός, ανεπιτήδευτος).',
        'note': 'Θετική συνδήλωση, σε αντίθεση με το "brusco" (απότομος), που μπορεί να ακούγεται αγενές.',
        "tags": ["personality"],
        "priority": 1,
    },

    {
        "id": "it-el-impacciato",
        "italian": "impacciato",
        "translation": "αμήχανος, ντροπαλός, αμβαλτσαρισμένος",
        "type": "adjective",
        "scene_id": "🍕 Curated",
        "pronunciation": "/im.patˈtʃa.to/",
        "departure_lang": "el",
        "grammar": [
            {"label": "Feminine form", "value": "impacciata"},
            {"label": "Plural (masc.)", "value": "impacciati"},
            {"label": "Plural (fem.)", "value": "impacciate"},
        ],
        "example": {
            "it": "Mi sono sentito impacciato davanti a tutti quegli sconosciuti.",
            "el": "Ένιωσα αμήχανος μπροστά σε όλους εκείνους τους αγνώστους.",
        },
        "etymology": 'Από το "impacciare" (εμποδίζω/φέρνω σε αμηχανία), πιθανώς σχετικό με το "impacchettare" (τυλίγω/μπλέκω).',
        "note": "Περιγράφει μια προσωρινή κατάσταση κοινωνικής αμηχανίας, όχι μόνιμο χαρακτηριστικό.",
        "tags": ["emotions", "personality"],
        "priority": 0,
    },

    # ── Επιρρήματα ────────────────────────────────────────────────────────────

    {
        "id": "it-el-magari",
        "italian": "magari",
        "translation": "μακάρι, ίσως, αν μόνο",
        "type": "adverb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/maˈɡa.ri/",
        "departure_lang": "el",
        "grammar": [],
        "example": {
            "it": "\"Vieni anche tu alla festa?\" \"Magari!\"",
            "el": '«Έρχεσαι κι εσύ στο πάρτι;» «Μακάρι!»',
        },
        "etymology": 'Από το ελληνικό "μακάρι(ε)" (μακάρι, αν μόνο), μέσω της βυζαντινής ελληνικής.',
        "note": 'Πολύ ευέλικτο — μπορεί να σημαίνει "ίσως", "μακάρι" ή "ακόμα και" ανάλογα με το πλαίσιο και τον τόνο.',
        "tags": ["common", "colloquial", "daily-life"],
        "priority": 1,
    },

    {
        "id": "it-el-purtroppo",
        "italian": "purtroppo",
        "translation": "δυστυχώς",
        "type": "adverb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/purˈtrɔp.po/",
        "departure_lang": "el",
        "grammar": [],
        "example": {
            "it": "Purtroppo non potrò venire alla cena.",
            "el": "Δυστυχώς, δεν θα μπορέσω να έρθω στο δείπνο.",
        },
        "etymology": 'Από το "pur" (ακόμα/επίσης) + "troppo" (πολύ).',
        "note": "Συνηθισμένη αρχή πρότασης για να μαλακώσει άσχημα νέα.",
        "tags": ["common", "daily-life"],
        "priority": 1,
    },

    {
        "id": "it-el-appena",
        "italian": "appena",
        "translation": "μόλις, μόλις και μετά βίας, μόλις που",
        "type": "adverb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/apˈpe.na/",
        "departure_lang": "el",
        "grammar": [],
        "example": {
            "it": "Sono appena arrivato in ufficio.",
            "el": "Μόλις έφτασα στο γραφείο.",
        },
        "etymology": 'Από το λατινικό "ad poenam" (με δυσκολία/τιμωρία), εξελίχθηκε στο "μόλις/μόλις που".',
        'note': 'Λειτουργεί επίσης ως σύνδεσμος που σημαίνει "μόλις" (appena arrivo, ti chiamo = μόλις φτάσω, θα σε πάρω τηλέφωνο).',
        "tags": ["common", "grammar-trap", "daily-life"],
        "priority": 1,
    },

    {
        "id": "it-el-comunque",
        "italian": "comunque",
        "translation": "ούτως ή άλλως, ωστόσο, εν πάση περιπτώσει",
        "type": "adverb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/koˈmun.kwe/",
        "departure_lang": "el",
        "grammar": [],
        "example": {
            "it": "Non sono sicuro, ma vengo comunque.",
            "el": "Δεν είμαι σίγουρος, αλλά έρχομαι ούτως ή άλλως.",
        },
        "etymology": 'Από το "come" (ως/πώς) + "unque" (ποτέ), λατινικό "cumque".',
        "note": "Εξαιρετικά συχνός συνδετικός/πλήρωτικός λόγος στον προφορικό ιταλικό λόγο.",
        "tags": ["common", "colloquial", "daily-life"],
        "priority": 1,
    },

    {
        "id": "it-el-finalmente",
        "italian": "finalmente",
        "translation": "επιτέλους, τέλος πάντων",
        "type": "adverb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/fi.nalˈmen.te/",
        "departure_lang": "el",
        "grammar": [],
        "example": {
            "it": "Finalmente è arrivato il weekend!",
            "el": "Επιτέλους ήρθε το Σαββατοκύριακο!",
        },
        "etymology": 'Από το "finale" (τελικός) + επιρρηματικό επίθημα "-mente" (από το λατινικό "mente", νους).',
        'note': 'Εκφράζει ανακούφιση ή ικανοποίηση, σε αντίθεση με το ουδέτερο "alla fine" (στο τέλος).',
        "tags": ["common", "daily-life"],
        "priority": 0,
    },

    # ── Φράσεις ───────────────────────────────────────────────────────────────

    {
        "id": "it-el-in-bocca-al-lupo",
        "italian": "in bocca al lupo",
        "translation": "καλή επιτυχία",
        "type": "phrase",
        "scene_id": "🍕 Curated",
        "pronunciation": "/im ˈbok.ka al ˈlu.po/",
        "departure_lang": "el",
        "grammar": [],
        "example": {
            "it": "Domani hai l'esame? In bocca al lupo!",
            "el": "Αύριο έχεις εξετάσεις; Καλή επιτυχία!",
        },
        "etymology": 'Κυριολεκτικά "μέσα στο στόμα του λύκου" — πιθανώς από την κυνηγετική παράδοση, εύχεσαι ασφαλή επιστροφή από τον κίνδυνο.',
        'note': 'Η παραδοσιακή απάντηση είναι "crepi" ή "crepi il lupo" (να ψοφήσει ο λύκος) — ποτέ μην λες "grazie" ως απάντηση.',
        "tags": ["common", "idiom", "daily-life"],
        "priority": 1,
    },

    {
        "id": "it-el-che-casino",
        "italian": "che casino",
        "translation": "τι χάος, τι αταξία",
        "type": "phrase",
        "scene_id": "🍕 Curated",
        "pronunciation": "/ke kaˈzi.no/",
        "departure_lang": "el",
        "grammar": [],
        "example": {
            "it": "Che casino in questa stazione oggi!",
            "el": "Τι χάος σε αυτό το σταθμό σήμερα!",
        },
        "etymology": 'Το "casino" σήμαινε αρχικά "μικρό σπίτι" (για τζόγο/πάρτι), αργότερα απέκτησε στην καθομιλουμένη τη σημασία "χάος/αταξία".',
        "note": 'Πολύ ανεπίσημο — αποφύγετε το σε επίσημο γραπτό λόγο. Άσχετο με την αγγλική σημασία (τζόγος).',
        "tags": ["colloquial", "common", "daily-life"],
        "priority": 0,
    },

    {
        "id": "it-el-non-vedo-lora",
        "italian": "non vedo l'ora",
        "translation": "ανυπομονώ",
        "type": "phrase",
        "scene_id": "🍕 Curated",
        "pronunciation": "/non ˈve.do ˈlɔ.ra/",
        "departure_lang": "el",
        "grammar": [],
        "example": {
            "it": "Non vedo l'ora di rivederti.",
            "el": "Ανυπομονώ να σε ξαναδώ.",
        },
        "etymology": 'Κυριολεκτικά "δεν βλέπω την ώρα", δηλ. ο χρόνος δεν μπορεί να περάσει αρκετά γρήγορα.',
        'note': 'Ακολουθείται από "di" + απαρέμφατο (non vedo l\'ora di partire).',
        "tags": ["common", "emotions"],
        "priority": 1,
    },

    {
        "id": "it-el-avercela-con",
        "italian": "avercela con qualcuno",
        "translation": "τα έχω με κάποιον, θυμώνω με κάποιον",
        "type": "phrase",
        "scene_id": "🍕 Curated",
        "pronunciation": "/a.verˈtʃe.la kon kwalˈku.no/",
        "departure_lang": "el",
        "grammar": [],
        "example": {
            "it": "Non so perché ce l'hai con me oggi.",
            "el": "Δεν ξέρω γιατί τα έχεις μαζί μου σήμερα.",
        },
        "etymology": 'Από το "avere" + τη σταθερή αντωνυμική ομάδα "ce la", που ιδιωματικοποιήθηκε με την πάροδο του χρόνου.',
        'note': 'Πολύ ανεπίσημο· κλίνεται όπως το "avere" (ce l\'ho, ce l\'hai, ce l\'ha…) — το "cela" παραμένει αμετάβλητο.',
        "tags": ["colloquial", "grammar-trap", "emotions"],
        "priority": 0,
    },

    {
        "id": "it-el-fare-due-passi",
        "italian": "fare due passi",
        "translation": "κάνω μια βόλτα",
        "type": "phrase",
        "scene_id": "🍕 Curated",
        "pronunciation": "/ˈfa.re ˈdu.e ˈpas.si/",
        "departure_lang": "el",
        "grammar": [],
        "example": {
            "it": "Dopo cena andiamo a fare due passi?",
            "el": "Μετά το δείπνο πάμε για μια βόλτα;",
        },
        "etymology": 'Κυριολεκτικά "κάνω δύο βήματα" — υποτιμητικός/σεμνός τρόπος να πούμε "πηγαίνω για περίπατο".',
        "note": 'Το "due" εδώ δεν σημαίνει κυριολεκτικά δύο — είναι ιδιωματικό για "λίγο/σύντομα".',
        "tags": ["common", "idiom", "daily-life"],
        "priority": 1,
    },

]
