"""
it_vocab_data.py — Italian vocabulary preset cards.

Card format:
    id          unique string
    italian     Italian word/phrase  (mapped → "word" by _normalize_cards)
    translation English translation
    type        noun | verb | adjective | adverb | phrase
    scene_id    group key             (mapped → "group" by _normalize_cards)
    gender      "m" | "f"  top-level field (nouns/adjectives — drives article colour)
    article     article override when il/la rule doesn't apply (lo, l', gli …)
    grammar     list of {"label": "...", "value": "..."} shown on card back
    example     {"it": "...", "en": "..."}
    pronunciation, note, etymology, tags, priority
"""

CARDS = [

    # ── Nouns ─────────────────────────────────────────────────────────────────

    {
        "id": "it-nostalgia",
        "italian": "nostalgia",
        "translation": "nostalgia, homesickness, longing",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/nos.taˈldʒi.a/",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
        ],
        "example": {
            "it": "Sento una strana nostalgia per la mia città natale.",
            "en": "I feel a strange nostalgia for my hometown.",
        },
        "etymology": "From Greek nóstos (return home) + álgos (pain), coined in the 17th century.",
        "note": 'Often used with "di" or "per"; avere nostalgia di qualcosa is the standard construction.',
        "tags": ["common", "emotions"],
        "priority": 1,
    },

    {
        "id": "it-scrivania",
        "italian": "scrivania",
        "translation": "desk, writing table",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/skri.vaˈni.a/",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "scrivanie"},
        ],
        "example": {
            "it": "Ho lasciato le chiavi sulla scrivania.",
            "en": "I left the keys on the desk.",
        },
        "etymology": 'From "scrivere" (to write).',
        "note": 'Distinct from "tavolo" (generic table); scrivania specifically implies a work/writing desk.',
        "tags": ["common", "home", "daily-life"],
        "priority": 0,
    },

    {
        "id": "it-sciopero",
        "italian": "sciopero",
        "translation": "strike, walkout",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/ˈʃɔ.pe.ro/",
        "gender": "m",
        "article": "lo",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Article override", "value": "lo"},
            {"label": "Plural", "value": "scioperi"},
        ],
        "example": {
            "it": "I treni sono in ritardo per lo sciopero.",
            "en": "The trains are late because of the strike.",
        },
        "etymology": 'Uncertain — possibly from "operare" with a pejorative "s-" prefix, or from Genoese dialect.',
        "note": 'Fare sciopero = "to go on strike." Common in news/media Italian.',
        "tags": ["common", "news", "work-society"],
        "priority": 1,
    },

    {
        "id": "it-bussola",
        "italian": "bussola",
        "translation": "compass",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/ˈbus.so.la/",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "bussole"},
        ],
        "example": {
            "it": "Senza bussola ci siamo persi nel bosco.",
            "en": "Without a compass we got lost in the woods.",
        },
        "etymology": 'From "buxus" (boxwood, the material old compass cases were made of).',
        "note": 'Figuratively, "perdere la bussola" means to lose one\'s bearings/composure.',
        "tags": ["travel", "idiom-source"],
        "priority": 0,
    },

    {
        "id": "it-tramonto",
        "italian": "tramonto",
        "translation": "sunset",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/traˈmon.to/",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "tramonti"},
        ],
        "example": {
            "it": "Guardiamo il tramonto dalla spiaggia.",
            "en": "Let's watch the sunset from the beach.",
        },
        "etymology": 'From "tramontare" (to set, of the sun), from Latin "trans" + "montare."',
        "note": "Also used figuratively for the decline of something (il tramonto di un'epoca).",
        "tags": ["common", "nature"],
        "priority": 1,
    },

    {
        "id": "it-formaggio",
        "italian": "formaggio",
        "translation": "cheese",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/forˈmad.dʒo/",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "formaggi"},
        ],
        "example": {
            "it": "Il formaggio stagionato ha un sapore più forte.",
            "en": "Aged cheese has a stronger flavor.",
        },
        "etymology": 'From Late Latin "formaticum" (formed in a mold), via "forma."',
        "note": 'Regional synonym "cacio" is common in central/southern Italy.',
        "tags": ["common", "food"],
        "priority": 1,
    },

    {
        "id": "it-valigia",
        "italian": "valigia",
        "translation": "suitcase",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/vaˈli.dʒa/",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "valigie"},
        ],
        "example": {
            "it": "Ho fatto la valigia in dieci minuti.",
            "en": "I packed my suitcase in ten minutes.",
        },
        "etymology": 'From "Valenza," an old form referring to leather goods, possibly linked to the city Valencia.',
        "note": '"Fare la valigia" = to pack. Plural is irregular-feeling for learners: valigie (not valige).',
        "tags": ["common", "travel"],
        "priority": 1,
    },

    {
        "id": "it-specchio",
        "italian": "specchio",
        "translation": "mirror",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/ˈspek.kjo/",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "specchi"},
        ],
        "example": {
            "it": "Mi sono guardato allo specchio prima di uscire.",
            "en": "I looked at myself in the mirror before going out.",
        },
        "etymology": 'From Latin "speculum."',
        "note": '"Specchietto retrovisore" = rearview mirror.',
        "tags": ["common", "home", "daily-life"],
        "priority": 0,
    },

    {
        "id": "it-fulmine",
        "italian": "fulmine",
        "translation": "lightning bolt",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/ˈful.mi.ne/",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "fulmini"},
        ],
        "example": {
            "it": "Un fulmine ha colpito l'albero vicino a casa.",
            "en": "A lightning bolt struck the tree near the house.",
        },
        "etymology": 'From Latin "fulmen," related to "fulgere" (to shine/flash).',
        "note": '"Come un fulmine a ciel sereno" = out of the blue, unexpectedly.',
        "tags": ["nature", "idiom-source"],
        "priority": 0,
    },

    {
        "id": "it-farfalla",
        "italian": "farfalla",
        "translation": "butterfly",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/farˈfal.la/",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "farfalle"},
        ],
        "example": {
            "it": "Una farfalla si è posata sul fiore.",
            "en": "A butterfly landed on the flower.",
        },
        "etymology": 'From Latin "papilio," altered through popular speech, possibly influenced by "farfallone."',
        "note": "Also the name of the pasta shape and the swimming stroke.",
        "tags": ["nature", "common"],
        "priority": 0,
    },

    {
        "id": "it-malinconia",
        "italian": "malinconia",
        "translation": "melancholy, sadness, wistfulness",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/ma.lin.koˈni.a/",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
        ],
        "example": {
            "it": "Un velo di malinconia ha coperto la sua voce.",
            "en": "A veil of melancholy covered her voice.",
        },
        "etymology": 'From Greek "melankholía" (black bile), part of ancient humoral theory.',
        "note": 'Softer and more poetic than "tristezza"; often used in literary or reflective contexts.',
        "tags": ["emotions", "literary"],
        "priority": 0,
    },

    {
        "id": "it-capriccio",
        "italian": "capriccio",
        "translation": "whim, tantrum, fancy",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/kaˈprit.tʃo/",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "capricci"},
        ],
        "example": {
            "it": "Il bambino ha fatto un capriccio al supermercato.",
            "en": "The kid threw a tantrum at the supermarket.",
        },
        "etymology": 'Possibly from "capro" (goat) or from "capo" + "riccio" (hair standing on end from fright).',
        "note": '"Fare i capricci" = to throw tantrums (used for children).',
        "tags": ["emotions", "common"],
        "priority": 0,
    },

    {
        "id": "it-rimpianto",
        "italian": "rimpianto",
        "translation": "regret",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/rimˈpjan.to/",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "rimpianti"},
        ],
        "example": {
            "it": "Non ho rimpianti per le scelte che ho fatto.",
            "en": "I have no regrets about the choices I've made.",
        },
        "etymology": 'From "rimpiangere" (to regret), from "ri-" + "piangere" (to cry).',
        "note": 'Slightly more formal/literary than "rammarico."',
        "tags": ["emotions"],
        "priority": 0,
    },

    {
        "id": "it-quotidianita",
        "italian": "quotidianità",
        "translation": "everyday life, routine",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/kwo.ti.dja.niˈta/",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "quotidianità (invariable)"},
        ],
        "example": {
            "it": "Mi piace la semplicità della quotidianità.",
            "en": "I like the simplicity of everyday life.",
        },
        "etymology": 'From "quotidiano" (daily), from Latin "cotidianus."',
        "note": "Abstract noun, typically used only in the singular.",
        "tags": ["daily-life", "abstract"],
        "priority": 0,
    },

    {
        "id": "it-arguzia",
        "italian": "arguzia",
        "translation": "wit, cleverness",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/arˈɡu.tsja/",
        "gender": "f",
        "grammar": [
            {"label": "Gender", "value": "f"},
            {"label": "Plural", "value": "arguzie"},
        ],
        "example": {
            "it": "Ha risposto con la sua solita arguzia.",
            "en": "She replied with her usual wit.",
        },
        "etymology": 'From Latin "argutia," related to "argutus" (sharp, clever).',
        "note": 'A bit formal/literary; "spirito" is the more everyday word for wit.',
        "tags": ["personality", "literary"],
        "priority": 0,
    },

    {
        "id": "it-straniero",
        "italian": "straniero",
        "translation": "foreigner, stranger",
        "type": "noun",
        "scene_id": "🍕 Curated",
        "pronunciation": "/straˈnjɛ.ro/",
        "gender": "m",
        "grammar": [
            {"label": "Gender", "value": "m"},
            {"label": "Plural", "value": "stranieri"},
        ],
        "example": {
            "it": "Da straniero, mi sento sempre benvenuto qui.",
            "en": "As a foreigner, I always feel welcome here.",
        },
        "etymology": 'From Old French "estrangier," from Latin "extraneus" (external, foreign).',
        "note": "Feminine form: straniera. Also functions as an adjective (paese straniero = foreign country).",
        "tags": ["travel", "common"],
        "priority": 1,
    },

    # ── Verbs ──────────────────────────────────────────────────────────────────

    {
        "id": "it-chiacchierare",
        "italian": "chiacchierare",
        "translation": "to chat, to gossip",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/kjak.kjeˈra.re/",
        "grammar": [
            {"label": "Verb group", "value": "-are"},
            {"label": "Auxiliary (passato prossimo)", "value": "avere"},
            {"label": "Participio passato", "value": "chiacchierato"},
            {"label": "Passato remoto (io)", "value": "chiacchierai"},
            {"label": "Gerundio", "value": "chiacchierando"},
            {"label": "Presente (all 6 forms)", "value": "chiacchiero / chiacchieri / chiacchiera / chiacchieriamo / chiacchierate / chiacchierano"},
        ],
        "example": {
            "it": "Ci siamo fermati a chiacchierare al bar.",
            "en": "We stopped to chat at the bar.",
        },
        "etymology": 'Onomatopoeic root "chiacchiera" (chatter), imitating the sound of talking.',
        "note": 'Casual, sociable register — different from "parlare" (neutral "to speak").',
        "tags": ["common", "social", "daily-life"],
        "priority": 1,
    },

    {
        "id": "it-sorridere",
        "italian": "sorridere",
        "translation": "to smile",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/sorˈri.de.re/",
        "grammar": [
            {"label": "Verb group", "value": "irregular"},
            {"label": "Auxiliary (passato prossimo)", "value": "avere"},
            {"label": "Participio passato", "value": "sorriso"},
            {"label": "Passato remoto (io)", "value": "sorrisi"},
            {"label": "Gerundio", "value": "sorridendo"},
            {"label": "Presente (all 6 forms)", "value": "sorrido / sorridi / sorride / sorridiamo / sorridete / sorridono"},
        ],
        "example": {
            "it": "Mi ha sorriso appena mi ha visto.",
            "en": "She smiled at me as soon as she saw me.",
        },
        "etymology": 'From Latin "subridere" (sub- + ridere, "to laugh").',
        "note": 'Irregular like its root verb "ridere"; note the -is- participle/remoto pattern.',
        "tags": ["common", "emotions"],
        "priority": 1,
    },

    {
        "id": "it-svegliarsi",
        "italian": "svegliarsi",
        "translation": "to wake up",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/zveʎˈʎar.si/",
        "grammar": [
            {"label": "Verb group", "value": "-are"},
            {"label": "Auxiliary (passato prossimo)", "value": "essere"},
            {"label": "Participio passato", "value": "svegliato"},
            {"label": "Passato remoto (io)", "value": "mi svegliai"},
            {"label": "Gerundio", "value": "svegliandosi"},
            {"label": "Presente (all 6 forms)", "value": "mi sveglio / ti svegli / si sveglia / ci svegliamo / vi svegliate / si svegliano"},
        ],
        "example": {
            "it": "Mi sveglio sempre presto durante la settimana.",
            "en": "I always wake up early during the week.",
        },
        "etymology": 'From "svegliare" (to wake someone), from Latin "ex-vigilare."',
        "note": 'Reflexive — takes essere in compound tenses. Contrast with "svegliare" (to wake someone else).',
        "tags": ["common", "daily-life"],
        "priority": 1,
    },

    {
        "id": "it-raggiungere",
        "italian": "raggiungere",
        "translation": "to reach, to catch up with",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/rad.ˈdʒun.dʒe.re/",
        "grammar": [
            {"label": "Verb group", "value": "irregular"},
            {"label": "Auxiliary (passato prossimo)", "value": "avere"},
            {"label": "Participio passato", "value": "raggiunto"},
            {"label": "Passato remoto (io)", "value": "raggiunsi"},
            {"label": "Gerundio", "value": "raggiungendo"},
            {"label": "Presente (all 6 forms)", "value": "raggiungo / raggiungi / raggiunge / raggiungiamo / raggiungete / raggiungono"},
        ],
        "example": {
            "it": "Ti raggiungo tra dieci minuti.",
            "en": "I'll catch up with you in ten minutes.",
        },
        "etymology": 'From "giungere" (to arrive), from Latin "jungere" (to join), with prefix "ra-."',
        "note": "Also used abstractly: raggiungere un obiettivo = to achieve a goal.",
        "tags": ["common", "travel"],
        "priority": 1,
    },

    {
        "id": "it-accorgersi",
        "italian": "accorgersi",
        "translation": "to realize, to notice",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/akˈkɔr.dʒer.si/",
        "grammar": [
            {"label": "Verb group", "value": "irregular"},
            {"label": "Auxiliary (passato prossimo)", "value": "essere"},
            {"label": "Participio passato", "value": "accorto"},
            {"label": "Passato remoto (io)", "value": "mi accorsi"},
            {"label": "Gerundio", "value": "accorgendosi"},
            {"label": "Presente (all 6 forms)", "value": "mi accorgo / ti accorgi / si accorge / ci accorgiamo / vi accorgete / si accorgono"},
        ],
        "example": {
            "it": "Non mi sono accorto dell'errore subito.",
            "en": "I didn't notice the mistake right away.",
        },
        "etymology": 'From Latin "ad-" + "corrigere" (to correct), shifted in meaning over time.',
        "note": 'Always reflexive; followed by "di" + noun/infinitive (accorgersi di qualcosa).',
        "tags": ["common", "emotions"],
        "priority": 1,
    },

    {
        "id": "it-fingere",
        "italian": "fingere",
        "translation": "to pretend, to feign",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/ˈfin.dʒe.re/",
        "grammar": [
            {"label": "Verb group", "value": "irregular"},
            {"label": "Auxiliary (passato prossimo)", "value": "avere"},
            {"label": "Participio passato", "value": "finto"},
            {"label": "Passato remoto (io)", "value": "finsi"},
            {"label": "Gerundio", "value": "fingendo"},
            {"label": "Presente (all 6 forms)", "value": "fingo / fingi / finge / fingiamo / fingete / fingono"},
        ],
        "example": {
            "it": "Ha finto di non sentire la domanda.",
            "en": "He pretended not to hear the question.",
        },
        "etymology": 'From Latin "fingere" (to shape, mold, feign) — same root as "finzione" (fiction).',
        "note": '"Fingere di + infinitive" is the standard construction.',
        "tags": ["common", "personality"],
        "priority": 0,
    },

    {
        "id": "it-affrettarsi",
        "italian": "affrettarsi",
        "translation": "to hurry, to rush",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/af.fretˈtar.si/",
        "grammar": [
            {"label": "Verb group", "value": "-are"},
            {"label": "Auxiliary (passato prossimo)", "value": "essere"},
            {"label": "Participio passato", "value": "affrettato"},
            {"label": "Passato remoto (io)", "value": "mi affrettai"},
            {"label": "Gerundio", "value": "affrettandosi"},
            {"label": "Presente (all 6 forms)", "value": "mi affretto / ti affretti / si affretta / ci affrettiamo / vi affrettate / si affrettano"},
        ],
        "example": {
            "it": "Affrettati, il treno sta per partire!",
            "en": "Hurry up, the train is about to leave!",
        },
        "etymology": 'From "affrettare" (to hasten), from "a-" + "fretta" (haste).',
        "note": "Reflexive; often used in the imperative, as above.",
        "tags": ["common", "daily-life"],
        "priority": 0,
    },

    {
        "id": "it-annoiarsi",
        "italian": "annoiarsi",
        "translation": "to get bored",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/an.noˈjar.si/",
        "grammar": [
            {"label": "Verb group", "value": "-are"},
            {"label": "Auxiliary (passato prossimo)", "value": "essere"},
            {"label": "Participio passato", "value": "annoiato"},
            {"label": "Passato remoto (io)", "value": "mi annoiai"},
            {"label": "Gerundio", "value": "annoiandosi"},
            {"label": "Presente (all 6 forms)", "value": "mi annoio / ti annoi / si annoia / ci annoiamo / vi annoiate / si annoiano"},
        ],
        "example": {
            "it": "Mi annoio quando piove tutto il giorno.",
            "en": "I get bored when it rains all day.",
        },
        "etymology": 'From "annoiare" (to bore/annoy), from Old French "enui" — same root as English "ennui."',
        "note": 'Reflexive; the non-reflexive "annoiare" means "to bore/annoy someone else."',
        "tags": ["common", "emotions"],
        "priority": 0,
    },

    {
        "id": "it-costruire",
        "italian": "costruire",
        "translation": "to build, to construct",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/ko.struˈi.re/",
        "grammar": [
            {"label": "Verb group", "value": "-ire"},
            {"label": "Auxiliary (passato prossimo)", "value": "avere"},
            {"label": "Participio passato", "value": "costruito"},
            {"label": "Passato remoto (io)", "value": "costruii"},
            {"label": "Gerundio", "value": "costruendo"},
            {"label": "Presente (all 6 forms)", "value": "costruisco / costruisci / costruisce / costruiamo / costruite / costruiscono"},
        ],
        "example": {
            "it": "Stanno costruendo un nuovo ponte in centro.",
            "en": "They are building a new bridge downtown.",
        },
        "etymology": 'From Latin "construere" (con- + struere, "to pile up").',
        "note": 'Follows the -isc- pattern in the present tense (like "capire," "finire").',
        "tags": ["common", "work", "work-society"],
        "priority": 0,
    },

    {
        "id": "it-tradurre",
        "italian": "tradurre",
        "translation": "to translate",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/traˈdur.re/",
        "grammar": [
            {"label": "Verb group", "value": "irregular"},
            {"label": "Auxiliary (passato prossimo)", "value": "avere"},
            {"label": "Participio passato", "value": "tradotto"},
            {"label": "Passato remoto (io)", "value": "tradussi"},
            {"label": "Gerundio", "value": "traducendo"},
            {"label": "Presente (all 6 forms)", "value": "traduco / traduci / traduce / traduciamo / traducete / traducono"},
        ],
        "example": {
            "it": "Ho tradotto il documento dall'italiano al tedesco.",
            "en": "I translated the document from Italian to German.",
        },
        "etymology": 'From Latin "traducere" (to lead across). Same root as English "translate."',
        "note": 'Irregular conjugation shared with "produrre," "condurre," etc. (the -durre family).',
        "tags": ["common", "work", "work-society"],
        "priority": 1,
    },

    {
        "id": "it-ingannare",
        "italian": "ingannare",
        "translation": "to deceive, to trick",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/in.ɡanˈna.re/",
        "grammar": [
            {"label": "Verb group", "value": "-are"},
            {"label": "Auxiliary (passato prossimo)", "value": "avere"},
            {"label": "Participio passato", "value": "ingannato"},
            {"label": "Passato remoto (io)", "value": "ingannai"},
            {"label": "Gerundio", "value": "ingannando"},
            {"label": "Presente (all 6 forms)", "value": "inganno / inganni / inganna / inganniamo / ingannate / ingannano"},
        ],
        "example": {
            "it": "Non lasciarti ingannare dalle apparenze.",
            "en": "Don't be deceived by appearances.",
        },
        "etymology": 'From Latin "in-" + "gannire" (to yelp/snarl), with a semantic shift to "trick."',
        "note": '"Ingannare il tempo" = to pass the time (idiomatic).',
        "tags": ["personality"],
        "priority": 0,
    },

    {
        "id": "it-sospirare",
        "italian": "sospirare",
        "translation": "to sigh",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/sos.piˈra.re/",
        "grammar": [
            {"label": "Verb group", "value": "-are"},
            {"label": "Auxiliary (passato prossimo)", "value": "avere"},
            {"label": "Participio passato", "value": "sospirato"},
            {"label": "Passato remoto (io)", "value": "sospirai"},
            {"label": "Gerundio", "value": "sospirando"},
            {"label": "Presente (all 6 forms)", "value": "sospiro / sospiri / sospira / sospiriamo / sospirate / sospirano"},
        ],
        "example": {
            "it": "Ha sospirato profondamente prima di rispondere.",
            "en": "She sighed deeply before answering.",
        },
        "etymology": 'From Latin "suspirare" (sub- + spirare, "to breathe").',
        "note": 'Related noun: "sospiro" (a sigh).',
        "tags": ["emotions"],
        "priority": 0,
    },

    {
        "id": "it-vagabondare",
        "italian": "vagabondare",
        "translation": "to wander, to roam",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/va.ɡa.bonˈda.re/",
        "grammar": [
            {"label": "Verb group", "value": "-are"},
            {"label": "Auxiliary (passato prossimo)", "value": "avere"},
            {"label": "Participio passato", "value": "vagabondato"},
            {"label": "Passato remoto (io)", "value": "vagabondai"},
            {"label": "Gerundio", "value": "vagabondando"},
            {"label": "Presente (all 6 forms)", "value": "vagabondo / vagabondi / vagabonda / vagabondiamo / vagabondate / vagabondano"},
        ],
        "example": {
            "it": "Mi piace vagabondare per le vie della città senza meta.",
            "en": "I like wandering the city streets without a destination.",
        },
        "etymology": 'From "vagabondo" (vagrant), from Latin "vagari" (to wander).',
        "note": 'Slightly poetic/literary register; "girovagare" is a close synonym.',
        "tags": ["travel", "literary"],
        "priority": 0,
    },

    {
        "id": "it-stupire",
        "italian": "stupire",
        "translation": "to amaze, to astonish",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/stuˈpi.re/",
        "grammar": [
            {"label": "Verb group", "value": "-ire"},
            {"label": "Auxiliary (passato prossimo)", "value": "avere"},
            {"label": "Participio passato", "value": "stupito"},
            {"label": "Passato remoto (io)", "value": "stupii"},
            {"label": "Gerundio", "value": "stupendo"},
            {"label": "Presente (all 6 forms)", "value": "stupisco / stupisci / stupisce / stupiamo / stupite / stupiscono"},
        ],
        "example": {
            "it": "Il suo talento continua a stupirmi.",
            "en": "Her talent keeps amazing me.",
        },
        "etymology": 'From Latin "stupere" (to be stunned/numb).',
        "note": 'Follows the -isc- pattern; reflexive "stupirsi" means "to be amazed" (takes essere).',
        "tags": ["common", "emotions"],
        "priority": 0,
    },

    {
        "id": "it-mancare",
        "italian": "mancare",
        "translation": "to miss, to be lacking",
        "type": "verb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/manˈka.re/",
        "grammar": [
            {"label": "Verb group", "value": "-are"},
            {"label": "Auxiliary (passato prossimo)", "value": "essere"},
            {"label": "Participio passato", "value": "mancato"},
            {"label": "Passato remoto (io)", "value": "mancai"},
            {"label": "Gerundio", "value": "mancando"},
            {"label": "Presente (all 6 forms)", "value": "manco / manchi / manca / manchiamo / mancate / mancano"},
        ],
        "example": {
            "it": "Mi manchi molto quando sei via.",
            "en": "I miss you a lot when you're away.",
        },
        "etymology": 'From Latin "mancus" (defective, lacking a hand).',
        "note": 'Grammar trap: "tu mi manchi" = "I miss you" (literally "you are missing to me"). Auxiliary can shift to avere when meaning "to fail to do something."',
        "tags": ["common", "grammar-trap", "emotions"],
        "priority": 1,
    },

    # ── Adjectives ─────────────────────────────────────────────────────────────

    {
        "id": "it-goloso",
        "italian": "goloso",
        "translation": "gluttonous, having a sweet tooth",
        "type": "adjective",
        "scene_id": "🍕 Curated",
        "pronunciation": "/ɡoˈlo.zo/",
        "grammar": [
            {"label": "Feminine form", "value": "golosa"},
            {"label": "Plural (masc.)", "value": "golosi"},
            {"label": "Plural (fem.)", "value": "golose"},
        ],
        "example": {
            "it": "Sono golosa di cioccolato.",
            "en": "I have a sweet tooth for chocolate.",
        },
        "etymology": 'From "gola" (throat/gluttony), from Latin "gula."',
        "note": '"Essere goloso di" + noun = to be a fan of/crave something.',
        "tags": ["personality", "food"],
        "priority": 0,
    },

    {
        "id": "it-testardo",
        "italian": "testardo",
        "translation": "stubborn, headstrong",
        "type": "adjective",
        "scene_id": "🍕 Curated",
        "pronunciation": "/tesˈtar.do/",
        "grammar": [
            {"label": "Feminine form", "value": "testarda"},
            {"label": "Plural (masc.)", "value": "testardi"},
            {"label": "Plural (fem.)", "value": "testarde"},
        ],
        "example": {
            "it": "Mio fratello è troppo testardo per ammettere l'errore.",
            "en": "My brother is too stubborn to admit the mistake.",
        },
        "etymology": 'From "testa" (head), suggesting hard-headedness.',
        "note": 'Common synonym: "ostinato" (slightly more formal).',
        "tags": ["personality", "common"],
        "priority": 1,
    },

    {
        "id": "it-sfacciato",
        "italian": "sfacciato",
        "translation": "cheeky, shameless, brazen",
        "type": "adjective",
        "scene_id": "🍕 Curated",
        "pronunciation": "/sfatˈtʃa.to/",
        "grammar": [
            {"label": "Feminine form", "value": "sfacciata"},
            {"label": "Plural (masc.)", "value": "sfacciati"},
            {"label": "Plural (fem.)", "value": "sfacciate"},
        ],
        "example": {
            "it": "Che risposta sfacciata!",
            "en": "What a cheeky answer!",
        },
        "etymology": 'From "faccia" (face), with prefix "s-" implying "without" (i.e., "faceless" = shameless).',
        "note": "Can be affectionate/teasing or genuinely critical depending on tone.",
        "tags": ["personality"],
        "priority": 0,
    },

    {
        "id": "it-distratto",
        "italian": "distratto",
        "translation": "distracted, absent-minded",
        "type": "adjective",
        "scene_id": "🍕 Curated",
        "pronunciation": "/disˈtrat.to/",
        "grammar": [
            {"label": "Feminine form", "value": "distratta"},
            {"label": "Plural (masc.)", "value": "distratti"},
            {"label": "Plural (fem.)", "value": "distratte"},
        ],
        "example": {
            "it": "Ero troppo distratto per notare il cartello.",
            "en": "I was too distracted to notice the sign.",
        },
        "etymology": 'Past participle of "distrarre" (to distract), from Latin "distrahere."',
        "note": 'Also functions as the past participle of the verb "distrarre."',
        "tags": ["common", "personality"],
        "priority": 0,
    },

    {
        "id": "it-accogliente",
        "italian": "accogliente",
        "translation": "welcoming, cozy",
        "type": "adjective",
        "scene_id": "🍕 Curated",
        "pronunciation": "/ak.koʎˈʎɛn.te/",
        "grammar": [
            {"label": "Feminine form", "value": "accogliente (invariable)"},
            {"label": "Plural (masc.)", "value": "accoglienti"},
            {"label": "Plural (fem.)", "value": "accoglienti"},
        ],
        "example": {
            "it": "Il loro appartamento è piccolo ma accogliente.",
            "en": "Their apartment is small but cozy.",
        },
        "etymology": 'From "accogliere" (to welcome/receive), from Latin "ad-" + "colligere."',
        "note": "Invariable for gender (same form m/f); only the plural changes.",
        "tags": ["common", "home", "daily-life"],
        "priority": 1,
    },

    {
        "id": "it-spettinato",
        "italian": "spettinato",
        "translation": "disheveled, tousled (hair)",
        "type": "adjective",
        "scene_id": "🍕 Curated",
        "pronunciation": "/spet.tiˈna.to/",
        "grammar": [
            {"label": "Feminine form", "value": "spettinata"},
            {"label": "Plural (masc.)", "value": "spettinati"},
            {"label": "Plural (fem.)", "value": "spettinate"},
        ],
        "example": {
            "it": "Sono uscita di casa tutta spettinata.",
            "en": "I left the house completely disheveled.",
        },
        "etymology": 'From "pettinare" (to comb), with negating prefix "s-."',
        "note": 'Refers specifically to messy hair; for general untidiness use "disordinato."',
        "tags": ["daily-life"],
        "priority": 0,
    },

    {
        "id": "it-sgraziato",
        "italian": "sgraziato",
        "translation": "clumsy, ungraceful",
        "type": "adjective",
        "scene_id": "🍕 Curated",
        "pronunciation": "/zɡratˈtsja.to/",
        "grammar": [
            {"label": "Feminine form", "value": "sgraziata"},
            {"label": "Plural (masc.)", "value": "sgraziati"},
            {"label": "Plural (fem.)", "value": "sgraziate"},
        ],
        "example": {
            "it": "I suoi movimenti sono un po' sgraziati.",
            "en": "His movements are a bit clumsy.",
        },
        "etymology": 'From "grazia" (grace), with negating prefix "s-."',
        "note": 'Describes physical clumsiness; "goffo" is a near-synonym.',
        "tags": ["personality"],
        "priority": 0,
    },

    {
        "id": "it-schietto",
        "italian": "schietto",
        "translation": "frank, straightforward, sincere",
        "type": "adjective",
        "scene_id": "🍕 Curated",
        "pronunciation": "/ˈskjɛt.to/",
        "grammar": [
            {"label": "Feminine form", "value": "schietta"},
            {"label": "Plural (masc.)", "value": "schietti"},
            {"label": "Plural (fem.)", "value": "schiette"},
        ],
        "example": {
            "it": "Apprezzo il tuo modo schietto di dire le cose.",
            "en": "I appreciate your straightforward way of saying things.",
        },
        "etymology": 'From Germanic root related to "schlicht" (plain, simple).',
        "note": 'Positive connotation, unlike "brusco" (blunt/curt), which can sound rude.',
        "tags": ["personality"],
        "priority": 1,
    },

    {
        "id": "it-impacciato",
        "italian": "impacciato",
        "translation": "awkward, embarrassed, self-conscious",
        "type": "adjective",
        "scene_id": "🍕 Curated",
        "pronunciation": "/im.patˈtʃa.to/",
        "grammar": [
            {"label": "Feminine form", "value": "impacciata"},
            {"label": "Plural (masc.)", "value": "impacciati"},
            {"label": "Plural (fem.)", "value": "impacciate"},
        ],
        "example": {
            "it": "Mi sono sentito impacciato davanti a tutti quegli sconosciuti.",
            "en": "I felt awkward in front of all those strangers.",
        },
        "etymology": 'From "impacciare" (to hinder/embarrass), possibly related to "impacchettare" (to wrap/entangle).',
        "note": "Describes a temporary state of social awkwardness, not a permanent trait.",
        "tags": ["emotions", "personality"],
        "priority": 0,
    },

    # ── Adverbs ────────────────────────────────────────────────────────────────

    {
        "id": "it-magari",
        "italian": "magari",
        "translation": "maybe, if only, I wish",
        "type": "adverb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/maˈɡa.ri/",
        "grammar": [],
        "example": {
            "it": "\"Vieni anche tu alla festa?\" \"Magari!\"",
            "en": "\"Are you coming to the party too?\" \"I wish!\"",
        },
        "etymology": 'From Greek "makári(e)" (would that, if only), via Byzantine Greek.',
        "note": 'Very versatile — can mean "maybe," "I wish," or "even" depending on context and intonation.',
        "tags": ["common", "colloquial", "daily-life"],
        "priority": 1,
    },

    {
        "id": "it-purtroppo",
        "italian": "purtroppo",
        "translation": "unfortunately",
        "type": "adverb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/purˈtrɔp.po/",
        "grammar": [],
        "example": {
            "it": "Purtroppo non potrò venire alla cena.",
            "en": "Unfortunately, I won't be able to come to dinner.",
        },
        "etymology": 'From "pur" (even/also) + "troppo" (too much).',
        "note": "Common sentence-opener to soften bad news.",
        "tags": ["common", "daily-life"],
        "priority": 1,
    },

    {
        "id": "it-appena",
        "italian": "appena",
        "translation": "just, as soon as, barely",
        "type": "adverb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/apˈpe.na/",
        "grammar": [],
        "example": {
            "it": "Sono appena arrivato in ufficio.",
            "en": "I just arrived at the office.",
        },
        "etymology": 'From Latin "ad poenam" (with difficulty/punishment), shifted to mean "barely/just."',
        "note": 'Also works as a conjunction meaning "as soon as" (appena arrivo, ti chiamo).',
        "tags": ["common", "grammar-trap", "daily-life"],
        "priority": 1,
    },

    {
        "id": "it-comunque",
        "italian": "comunque",
        "translation": "anyway, however, in any case",
        "type": "adverb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/koˈmun.kwe/",
        "grammar": [],
        "example": {
            "it": "Non sono sicuro, ma vengo comunque.",
            "en": "I'm not sure, but I'm coming anyway.",
        },
        "etymology": 'From "come" (as/how) + "unque" (ever), Latin "cumque."',
        "note": "Extremely frequent filler/connector in spoken Italian.",
        "tags": ["common", "colloquial", "daily-life"],
        "priority": 1,
    },

    {
        "id": "it-finalmente",
        "italian": "finalmente",
        "translation": "finally, at last",
        "type": "adverb",
        "scene_id": "🍕 Curated",
        "pronunciation": "/fi.nalˈmen.te/",
        "grammar": [],
        "example": {
            "it": "Finalmente è arrivato il weekend!",
            "en": "The weekend has finally arrived!",
        },
        "etymology": 'From "finale" (final) + adverbial suffix "-mente" (from Latin "mente," mind).',
        "note": 'Conveys relief or satisfaction, unlike neutral "alla fine" (in the end).',
        "tags": ["common", "daily-life"],
        "priority": 0,
    },

    # ── Phrases ────────────────────────────────────────────────────────────────

    {
        "id": "it-in-bocca-al-lupo",
        "italian": "in bocca al lupo",
        "translation": "good luck",
        "type": "phrase",
        "scene_id": "🍕 Curated",
        "pronunciation": "/im ˈbok.ka al ˈlu.po/",
        "grammar": [],
        "example": {
            "it": "Domani hai l'esame? In bocca al lupo!",
            "en": "You have your exam tomorrow? Good luck!",
        },
        "etymology": 'Literally "into the wolf\'s mouth" — likely from hunting tradition, wishing safe return from danger.',
        "note": 'Traditional reply is "crepi" or "crepi il lupo" (may the wolf die) — never say "grazie" back.',
        "tags": ["common", "idiom", "daily-life"],
        "priority": 1,
    },

    {
        "id": "it-che-casino",
        "italian": "che casino",
        "translation": "what a mess, what chaos",
        "type": "phrase",
        "scene_id": "🍕 Curated",
        "pronunciation": "/ke kaˈzi.no/",
        "grammar": [],
        "example": {
            "it": "Che casino in questa stazione oggi!",
            "en": "What a mess at this station today!",
        },
        "etymology": '"Casino" originally meant "small house" (used for gambling/parties), later shifted colloquially to mean "mess/chaos."',
        "note": 'Very colloquial/informal — avoid in formal writing. Unrelated to the English gambling-establishment sense.',
        "tags": ["colloquial", "common", "daily-life"],
        "priority": 0,
    },

    {
        "id": "it-non-vedo-lora",
        "italian": "non vedo l'ora",
        "translation": "I can't wait",
        "type": "phrase",
        "scene_id": "🍕 Curated",
        "pronunciation": "/non ˈve.do ˈlɔ.ra/",
        "grammar": [],
        "example": {
            "it": "Non vedo l'ora di rivederti.",
            "en": "I can't wait to see you again.",
        },
        "etymology": 'Literally "I don\'t see the hour," i.e., time can\'t pass fast enough.',
        "note": 'Followed by "di" + infinitive (non vedo l\'ora di partire).',
        "tags": ["common", "emotions"],
        "priority": 1,
    },

    {
        "id": "it-avercela-con",
        "italian": "avercela con qualcuno",
        "translation": "to have it in for someone, to be annoyed with someone",
        "type": "phrase",
        "scene_id": "🍕 Curated",
        "pronunciation": "/a.verˈtʃe.la kon kwalˈku.no/",
        "grammar": [],
        "example": {
            "it": "Non so perché ce l'hai con me oggi.",
            "en": "I don't know why you're annoyed with me today.",
        },
        "etymology": 'From "avere" + the fixed pronoun cluster "ce la," idiomatized over time.',
        "note": 'Very colloquial; conjugates like "avere" (ce l\'ho, ce l\'hai, ce l\'ha…) — the "cela" part stays fixed.',
        "tags": ["colloquial", "grammar-trap", "emotions"],
        "priority": 0,
    },

    {
        "id": "it-fare-due-passi",
        "italian": "fare due passi",
        "translation": "to take a short walk",
        "type": "phrase",
        "scene_id": "🍕 Curated",
        "pronunciation": "/ˈfa.re ˈdu.e ˈpas.si/",
        "grammar": [],
        "example": {
            "it": "Dopo cena andiamo a fare due passi?",
            "en": "Shall we go for a short walk after dinner?",
        },
        "etymology": 'Literally "to make two steps" — a diminutive/understated way of saying "go for a walk."',
        "note": '"Due" here doesn\'t mean literally two — it\'s idiomatic for "a little/short."',
        "tags": ["common", "idiom", "daily-life"],
        "priority": 1,
    },

]
