"""
el_de_vocab_data.py — Greek vocabulary cards for German speakers (departure_lang='de').
Imported automatically by vocab_data.py.
"""

CARDS = [
    {
        "id": "el-de-1",
        "greek": "φιλότιμο",
        "translation": "Ehre / Würde / der innere Antrieb, das Richtige zu tun",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "fi-LO-ti-mo",
        "definition": "Das zutiefst griechische Konzept, mit Ehre, Großzügigkeit und Selbstlosigkeit zu handeln – nicht aus Pflicht, sondern aus dem Stolz darauf, wer man ist",
        "note": 'Unübersetzbar. Wenn jemand sagt «έχει φιλότιμο», ist das höchstes Lob. Griechen betrachten es als eine ihrer prägenden Nationaltugenden und reden gerne darüber, wenn man das Thema anspricht.',
        "etymology": "φίλος (liebend, Freund) + τιμή (Ehre) – die Ehre lieben; τιμή ergibt τιμώ (ehren) und τιμή (Preis – der Wert von etwas)",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "formal",
            "figurative",
        ],
        "grammar": [
            {
                "label": "Article",
                "value": "το φιλότιμο",
            },
            {
                "label": "Gender",
                "value": "Neuter",
            },
            {
                "label": "Genitive",
                "value": "του φιλότιμου",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Το φιλότιμο είναι ό,τι πιο ελληνικό υπάρχει.",
            "de": "Das Filotimo ist das Griechischste, was es gibt.",
        },
    },
    {
        "id": "el-de-2",
        "greek": "μεράκι",
        "translation": "leidenschaftliche Hingabe / Herzblut in einem Handwerk",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "me-RA-ki",
        "definition": "Etwas mit ganzem Herzen und ganzer Seele tun – nicht nur mit Geschick, sondern mit Liebe und tiefer persönlicher Anteilnahme",
        "note": "Etwas με μεράκι zu tun ist eines der größten Komplimente für jemandes Arbeit oder Kochkunst. Ein Handwerker, ein Musiker, ein Koch – sie alle können μεράκι haben.",
        "etymology": 'Türkisch merak (Neugier, tiefes Interesse, Besessenheit) – eines der schönsten türkischen Lehnwörter im Griechischen',
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "colloquial",
            "figurative",
            "loanword:turkish",
        ],
        "grammar": [
            {
                "label": "Article",
                "value": "το μεράκι",
            },
            {
                "label": "Gender",
                "value": "Neuter",
            },
            {
                "label": "Genitive",
                "value": "του μερακιού",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Μαγειρεύει με μεράκι.",
            "de": "Sie kocht mit echter Leidenschaft und Herzblut.",
        },
    },
    {
        "id": "el-de-3",
        "greek": "κέφι",
        "translation": "Hochstimmung / Feierlust / Lebensfreude",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "KE-fi",
        "definition": "Die spontane, ansteckende Energie guter Laune – die Stimmung, die eine Nacht unvergesslich macht",
        "note": "Μου κόπηκε το κέφι = etwas hat die Stimmung gekillt. Σήκωσε το κέφι όλων = er hat die Stimmung aller gehoben. Vom türkischen keyif (Vergnügen, Gemütlichkeit).",
        "etymology": "Türkisch keyif (Vergnügen, Behagen, Stimmung) – über den osmanischen Kontakt ins Griechische gelangt",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "colloquial",
            "loanword:turkish",
        ],
        "grammar": [
            {
                "label": "Article",
                "value": "το κέφι",
            },
            {
                "label": "Gender",
                "value": "Neuter",
            },
            {
                "label": "Genitive",
                "value": "του κεφιού",
            },
            {
                "label": "Key phrase",
                "value": "έχω κέφι = ich bin in Hochstimmung · δεν έχω κέφι = ich bin nicht in der Stimmung",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Απόψε έχω κέφι για χορό.",
            "de": "Heute Abend bin ich in Tanzstimmung.",
        },
    },
    {
        "id": "el-de-4",
        "greek": "λεβεντιά",
        "translation": "edle Haltung / Ritterlichkeit / die Würde eines freien Menschen",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "le-ven-DIA",
        "definition": "Die Verbindung von körperlicher Anmut, moralischer Aufrichtigkeit und Furchtlosigkeit – die Haltung von jemandem, der sich vor niemandem verneigt",
        "note": "Ein λεβέντης ist der archetypisch bewundernswerte griechische Mann – tapfer, würdevoll, frei. Zentral in der klephtenischen Volkstradition und im Volkslied.",
        "etymology": "Türkisch levend (ein freier Soldat, ein Matrose) – beschrieb ursprünglich irreguläre Soldaten, die keinem Herrn dienten",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": False,
        "tags": [
            "formal",
            "figurative",
            "loanword:turkish",
        ],
        "grammar": [
            {
                "label": "Article",
                "value": "η λεβεντιά",
            },
            {
                "label": "Gender",
                "value": "Feminine",
            },
            {
                "label": "Genitive",
                "value": "της λεβεντιάς",
            },
            {
                "label": "Related",
                "value": "λεβέντης = ein galanter, aufrechter Mann",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Περπατούσε με λεβεντιά, χωρίς να φοβάται κανέναν.",
            "de": "Er ging mit stolzer Haltung und fürchtete niemanden.",
        },
    },
    {
        "id": "el-de-5",
        "greek": "μαγκιά",
        "translation": "Coolness / Straßen-Swagger / mühelose Gelassenheit",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "mag-GIA",
        "definition": "Die Eigenschaft, alles mit mühelosem Stil und einer gewissen Unbekümmertheit zu meistern – nach seinen eigenen Regeln spielen und es leicht aussehen lassen",
        "note": "Ein μάγκας ist die Person; μαγκιά ist die Eigenschaft selbst. Tief verwurzelt in der Rebetiko-Musikkultur. Nicht kriminell, aber street-smart und unerschütterlich.",
        "etymology": "möglicherweise vom türkischen manga (ein militärischer Trupp harter Männer) – gelangte über die Hafenkultur von Piräus in den griechischen Stadtslang",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": False,
        "tags": [
            "colloquial",
            "figurative",
        ],
        "grammar": [
            {
                "label": "Article",
                "value": "η μαγκιά",
            },
            {
                "label": "Gender",
                "value": "Feminine",
            },
            {
                "label": "Genitive",
                "value": "της μαγκιάς",
            },
            {
                "label": "Related",
                "value": "ο μάγκας = ein cooler, straßenschlauer Mensch",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Το έκανε με μαγκιά — χωρίς να ιδρώσει.",
            "de": "Er zog es mit totaler Coolness durch – ohne ins Schwitzen zu kommen.",
        },
    },
    {
        "id": "el-de-6",
        "greek": "γλέντι",
        "translation": "Fest / Feier mit Musik und Tanz",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "GLEN-di",
        "definition": "Eine richtige Feier mit Musik, Gesang, Tanz, Essen und echter Ausgelassenheit – mehr als nur eine Party",
        "note": "Das Verb γλεντώ bedeutet, sich der Feier hinzugeben. Κάνουμε γλέντι = wir feiern richtig. Verbunden mit Hochzeiten, Namenstagen und Dorffesten.",
        "etymology": "möglicherweise vom albanischen gëzend (Freude, Feier) oder verwandt mit γελώ (lachen) – Ursprung umstritten",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "neutral",
        ],
        "grammar": [
            {
                "label": "Article",
                "value": "το γλέντι",
            },
            {
                "label": "Gender",
                "value": "Neuter",
            },
            {
                "label": "Plural",
                "value": "τα γλέντια",
            },
            {
                "label": "Genitive",
                "value": "του γλεντιού",
            },
            {
                "label": "Related verb",
                "value": "γλεντώ = feiern, ausgelassen sein",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Το γλέντι κράτησε ώς το πρωί.",
            "de": "Die Feier dauerte bis in den Morgen.",
        },
    },
    {
        "id": "el-de-7",
        "greek": "καημός",
        "translation": "tiefe Sehnsucht / nagender Schmerz / bittersüßes Verlangen",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "ka-i-MOS",
        "definition": "Der besondere Schmerz, etwas oder jemanden zu vermissen, oder ein unerfülltes Verlangen, das Teil von einem geworden ist – zwischen Trauer und Sehnsucht",
        "note": "Unverzichtbares Vokabular für das Verständnis griechischer Musik, besonders Rebetiko und Volkslied. Oft mit ξενιτιά verbunden. Eines der emotional aufgeladensten Wörter der Sprache.",
        "etymology": "möglicherweise von καίω (brennen) – ein brennender Schmerz; die Trauer, die schwelt, statt aufzuflammen",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "formal",
            "figurative",
        ],
        "grammar": [
            {
                "label": "Article",
                "value": "ο καημός",
            },
            {
                "label": "Gender",
                "value": "Masculine",
            },
            {
                "label": "Plural",
                "value": "οι καημοί",
            },
            {
                "label": "Genitive",
                "value": "του καημού",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Τραγουδούσε τον καημό της ξενιτιάς.",
            "de": "Sie sang vom nagenden Schmerz des Lebens fern der Heimat.",
        },
    },
    {
        "id": "el-de-8",
        "greek": "ξενιτιά",
        "translation": "Fremde / das Dasein fernab der Heimat",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "kse-ni-TIA",
        "definition": "Der Zustand, weit weg von den eigenen Menschen, dem eigenen Land und der eigenen Sprache zu sein – nicht nur Heimweh, sondern ein ganzer existenzieller Zustand",
        "note": "Von ξένος (Fremder / Ausländer / Gast – dasselbe Wort deckt alle drei ab). Ein zentrales Thema im griechischen Volkslied seit Jahrhunderten, von der osmanischen Periode bis zu den Auswanderungswellen.",
        "etymology": "ξένος (Fremder, Ausländer, Gast) ← Altgriechisch ξένος ← PIE *gʰosti- (Gast, Fremder) – dieselbe Wurzel wie lateinisch hostis (Feind) und hospes (Gastgeber)",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "formal",
            "figurative",
        ],
        "grammar": [
            {
                "label": "Article",
                "value": "η ξενιτιά",
            },
            {
                "label": "Gender",
                "value": "Feminine",
            },
            {
                "label": "Genitive",
                "value": "της ξενιτιάς",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Η ξενιτιά τρώει την καρδιά σου σιγά σιγά.",
            "de": "Das Leben fernab der Heimat frisst dein Herz langsam auf.",
        },
    },
    {
        "id": "el-de-9",
        "greek": "ρεμβασμός",
        "translation": "Tagtraum / Träumerei / das Abschweifen der Gedanken",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "rem-vaz-MOS",
        "definition": "Die besondere Qualität des Gedankenabschweifens, das weder Schlaf noch aktives Denken ist – ein meditatives, zielloses Treiben",
        "note": "Poetischer und spezifischer als bloßes σκέφτομαι (denken). Perfekt für jemanden, der in den Anblick des Meeres versunken ist oder am Nachmittag am Fenster träumt.",
        "etymology": "Altgriechisch ῥέμβομαι (wandern, streifen, sich drehen) – der Geist als etwas, das sich frei bewegt, wenn er nicht verankert ist",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": False,
        "tags": [
            "formal",
            "figurative",
        ],
        "grammar": [
            {
                "label": "Article",
                "value": "ο ρεμβασμός",
            },
            {
                "label": "Gender",
                "value": "Masculine",
            },
            {
                "label": "Genitive",
                "value": "του ρεμβασμού",
            },
            {
                "label": "Related verb",
                "value": "ρεμβάζω = träumen, in Gedanken versunken sein",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Τον έπιασε ρεμβασμός κοιτάζοντας τη θάλασσα.",
            "de": "Er versank in Träumerei, während er aufs Meer blickte.",
        },
    },
    {
        "id": "el-de-10",
        "greek": "κάηκα",
        "translation": "Ich bin verloren / ich bin verbrannt / ich bin hoffnungslos verliebt",
        "type": "Ρήμα · Verb (aorist 1sg)",
        "pronunciation": "KA-i-ka",
        "definition": "Aorist von καίγομαι – von einer Situation, einem Gefühl oder Erschöpfung verzehrt werden; deckt Katastrophe, Erschöpfung und das hoffnungslose Verlieben ab",
        "note": "Ein Wort mit erstaunlicher Bandbreite: Ich bin erwischt worden, ich stecke in der Klemme, ich bin völlig erschöpft, ich habe mich in jemanden verknallt. Και καήκαμε = und wir sind erledigt. Κάηκα μαζί της = ich habe mich schlimm in sie verliebt.",
        "etymology": "καίω (brennen) ← Altgriechisch καίω ← PIE *keh₂u- (brennen) – dieselbe Wurzel wie καύσωνας (Hitzewelle) und Holocaust (ὁλόκαυστος = vollständig verbrannt)",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "colloquial",
            "figurative",
        ],
        "grammar": [
            {
                "label": "Base verb",
                "value": "καίγομαι (Passiv/Deponens) = brennen",
            },
            {
                "label": "Aorist",
                "value": "κάηκα (1sg) / καήκαμε (1pl)",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Κάηκα — ξέχασα τελείως την εξέταση.",
            "de": "Ich bin geliefert – ich habe die Prüfung völlig vergessen.",
        },
    },
    {
        "id": "el-de-11",
        "greek": "με τρώει",
        "translation": "es frisst mich / es lässt mich nicht los / ich kann nicht aufhören, daran zu denken",
        "type": "Φράση · Fixed Expression",
        "pronunciation": "me TRO-i",
        "definition": "Etwas, das einen von innen auffrisst – Schuld, Neugier, Eifersucht, eine unbeantwortete Frage",
        "note": "Με τρώει η περιέργεια = die Neugier frisst mich auf (= ich will es unbedingt wissen). Με τρώει η ζήλια = die Eifersucht frisst mich. Eine wunderschön körperliche Metapher für seelische Beschäftigung.",
        "etymology": "τρώω (essen) ← Altgriechisch τρώγω (nagen, knabbern) – das Bild von etwas, das einen von innen annagt",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "colloquial",
            "figurative",
        ],
        "grammar": [
            {
                "label": "Structure",
                "value": "με τρώει + Substantiv/Nebensatz",
            },
            {
                "label": "Base verb",
                "value": "τρώω = essen – 3sg: τρώει",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Με τρώει που δεν του είπα την αλήθεια.",
            "de": "Es frisst mich, dass ich ihm nicht die Wahrheit gesagt habe.",
        },
    },
    {
        "id": "el-de-12",
        "greek": "κολλητός",
        "translation": "bester Freund / unzertrennlicher Weggefährte",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "ko-li-TOS",
        "definition": "Der engste Freund – so nah, dass man metaphorisch aneinander geklebt ist",
        "note": "Im Umgangssprachlichen inniger und herzlicher als φίλος (Freund). Ο κολλητός μου = mein bester Kumpel. Die feminine Form ist κολλητή.",
        "etymology": "κολλώ (kleben, haften) ← Altgriechisch κόλλα (Leim) – buchstäblich «der Geklebte», jemand, der untrennbar mit einem verbunden ist",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "colloquial",
        ],
        "grammar": [
            {
                "label": "Masculine",
                "value": "ο κολλητός",
            },
            {
                "label": "Feminine",
                "value": "η κολλητή",
            },
            {
                "label": "Root",
                "value": "κολλώ = kleben, haften",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Αυτός είναι ο κολλητός μου από το δημοτικό.",
            "de": "Er ist mein bester Freund seit der Grundschule.",
        },
    },
    {
        "id": "el-de-13",
        "greek": "ψήνομαι",
        "translation": "sich erwärmen für eine Idee / sich überzeugen lassen / in Versuchung geraten",
        "type": "Ρήμα · Verb",
        "pronunciation": "PSI-no-me",
        "definition": "Sich allmählich überzeugen oder zu etwas hinziehen lassen – bearbeitet werden, bis man nachgibt",
        "note": "Wörtlich «Ich werde gegrillt.» Σε ψήνω = ich arbeite an dir / versuche dich zu überzeugen. Auch wörtlich: ψήνομαι στον ήλιο = ich brate in der Sonne. Die Grillmetapher funktioniert für beides perfekt.",
        "etymology": "ψήνω (grillen, braten) ← Altgriechisch ὀπτάω – das passive Bild, erhitzt zu werden, bis man bereit ist",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "colloquial",
            "figurative",
        ],
        "grammar": [
            {
                "label": "Aorist",
                "value": "ψήθηκα (ich habe nachgegeben / wurde überzeugt)",
            },
            {
                "label": "Also literal",
                "value": "ψήνομαι = ich brate (Hitze)",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Αρχίζω να ψήνομαι για εκείνο το ταξίδι.",
            "de": "Ich fange an, mich für diese Reise zu erwärmen.",
        },
    },
    {
        "id": "el-de-14",
        "greek": "έχω πλάκα",
        "translation": "lustig sein / zum Lachen sein / Spaß machen",
        "type": "Φράση · Fixed Expression",
        "pronunciation": "E-ho PLA-ka",
        "definition": "Amüsant oder unterhaltend sein – von einer Person oder einer Situation",
        "note": "Κάνω πλάκα = ich mache Witze / Spaß. Μην κάνεις πλάκες = hör auf, herumzualbern. Τι πλάκα! = wie lustig! Η πλάκα bedeutet wörtlich ein flacher Stein – die Bedeutungsentwicklung hin zu «ein Witz» läuft über das Bild von etwas unverblümt, schlagend Komischem.",
        "etymology": "η πλάκα (flacher Stein, Platte) ← Altgriechisch πλάξ (flache Fläche) – wie es zur Bedeutung «ein Witz» kam, geht auf die Vorstellung von etwas Unverblümt-Komischem zurück",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "colloquial",
        ],
        "grammar": [
            {
                "label": "Structure",
                "value": "έχω πλάκα (ich bin lustig) · έχει πλάκα (es ist lustig/spaßig)",
            },
            {
                "label": "Related",
                "value": "άσχημη πλάκα = ein schlechter Witz / Geschmacklosigkeit",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Έχει πλάκα αυτός ο τύπος.",
            "de": "Dieser Typ ist wirklich witzig.",
        },
    },
    {
        "id": "el-de-15",
        "greek": "αχλύς",
        "translation": "Dunst / Nebel / der Schleier vor den Augen",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "ah-HLIS",
        "definition": "Die Trübung oder der Nebel, der sich über die Augen legt – bei Tränen, in Ohnmacht oder im Tod; ein poetisches Wort für verschleiernde Unschärfe",
        "note": "Homer verwendet αχλύς für den Schleier, der sich über die Augen eines sterbenden Helden legt. Im Alltag so gut wie nie gebraucht, doch in literarischen Kontexten von sofortiger Schönheit. Ein Wort für das gehobene Register.",
        "etymology": "Altgriechisch ἀχλύς (Nebel, Dunkel) – unklare vorgriechische Herkunft; möglicherweise verwandt mit ἄχνη (Schaum, Gischt)",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": False,
        "tags": [
            "formal",
        ],
        "grammar": [
            {
                "label": "Article",
                "value": "η αχλύς",
            },
            {
                "label": "Gender",
                "value": "Feminine",
            },
            {
                "label": "Genitive",
                "value": "της αχλύος (archaische Deklination)",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Μια αχλύς σκέπασε τα μάτια του.",
            "de": "Ein Schleier legte sich über seine Augen.",
        },
    },
    {
        "id": "el-de-16",
        "greek": "δειλινό",
        "translation": "später Nachmittag / die goldene Stunde vor der Dämmerung",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "thei-li-NO",
        "definition": "Die besondere Qualität des spätnachmittäglichen Lichts – warm, schräg einfallend, bevor die Sonne untergeht; nicht nur eine Tageszeit, sondern eine Stimmung",
        "note": "Eines der schönsten Zeitwörter des Griechischen. Erscheint ständig in Volkslied und Lyrik. Nicht dasselbe wie απόγευμα (Nachmittag, neutral/praktisch) – δειλινό ist die goldene, melancholische Stunde.",
        "etymology": "Altgriechisch δείλη (Nachmittag, der absteigende Teil des Tages) ← δείλω (untergehen, sinken) – die Stunde, wenn die Sonne ihren Abstieg beginnt",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "formal",
            "figurative",
        ],
        "grammar": [
            {
                "label": "Article",
                "value": "το δειλινό",
            },
            {
                "label": "Gender",
                "value": "Neuter",
            },
            {
                "label": "Genitive",
                "value": "του δειλινού",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Καθίσαμε στη βεράντα το δειλινό.",
            "de": "Wir saßen im spätnachmittäglichen Licht auf der Veranda.",
        },
    },
    {
        "id": "el-de-17",
        "greek": "ερημιά",
        "translation": "Einsamkeit / Verlassenheit / Leere",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "e-re-MIA",
        "definition": "Die Leere einer verlassenen Landschaft oder eines einsamen Herzens – reicher und poetischer als μοναξιά (Einsamkeit)",
        "note": "Η ερημιά της νύχτας = die Leere der Nacht. Kann schön sein (die Einsamkeit eines Berges) oder verheerend (die Verlassenheit des Verlusts). Vielschichtiger als bloße Einsamkeit.",
        "etymology": "έρημος (verlassen, leer) ← Altgriechisch ἔρημος (öde, unbewohnt) ← PIE *h₁erH- (leer sein, verlassen) – dieselbe Wurzel wie englisch «err» (umherirren)",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": False,
        "tags": [
            "formal",
            "figurative",
        ],
        "grammar": [
            {
                "label": "Article",
                "value": "η ερημιά",
            },
            {
                "label": "Gender",
                "value": "Feminine",
            },
            {
                "label": "Genitive",
                "value": "της ερημιάς",
            },
            {
                "label": "Related",
                "value": "η έρημος = Wüste · ο έρημος = einsam/öde (Adj.)",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Μέσα στην ερημιά του έρωτα, ψάχνει κάποιον να τον καταλάβει.",
            "de": "In der Verlassenheit der Liebe sucht er jemanden, der ihn versteht.",
        },
    },
    {
        "id": "el-de-18",
        "greek": "πελαγώνω",
        "translation": "auf dem offenen Meer treiben / überfordert sein / nicht mehr weiterwissen",
        "type": "Ρήμα · Verb",
        "pronunciation": "pe-la-GO-no",
        "definition": "Sich über die eigenen Kräfte hinaus, orientierungslos, überwältigt vorzufinden – als treibe man auf dem offenen Meer ohne Orientierungspunkte",
        "note": "Πελάγωσα ist der Aorist – «Ich bin auf dem offenen Meer verloren gegangen» – und eines jener Wörter, das Griechen anerkennend nicken lässt, wenn ein Ausländer es richtig benutzt.",
        "etymology": "πέλαγος (das offene Meer, die Tiefe) ← Altgriechisch πέλαγος ← PIE *pleh₂- (flach, offenes Wasser) – auf dem offenen Meer sein, ohne Anhaltspunkt",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "figurative",
            "colloquial",
        ],
        "grammar": [
            {
                "label": "Aorist",
                "value": "πελάγωσα",
            },
            {
                "label": "Base noun",
                "value": "το πέλαγος = das offene Meer",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Πελάγωσα με τόσες επιλογές.",
            "de": "Ich war von so vielen Möglichkeiten völlig überfordert.",
        },
    },
    {
        "id": "el-de-19",
        "greek": "γαλήνη",
        "translation": "Stille / Gelassenheit / innere Ruhe",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "ga-LI-ni",
        "definition": "Die besondere Ruhe nach einem Sturm – vor allem die Stille des Meeres nach einem Unwetter",
        "note": "Trägt jene spezifische Qualität des Friedens, der auf Anspannung folgt. Γαλήνιο πρόσωπο = ein ruhiges, gelassenes Gesicht. Eines jener Wörter, die genau wie das klingen, was sie bedeuten.",
        "etymology": "Altgriechisch γαλήνη (ruhiges Meer, Stille) – möglicherweise verwandt mit γάλα (Milch) über das Bild einer glatten, weißen, ungetrübten Oberfläche",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "formal",
            "figurative",
        ],
        "grammar": [
            {
                "label": "Article",
                "value": "η γαλήνη",
            },
            {
                "label": "Gender",
                "value": "Feminine",
            },
            {
                "label": "Genitive",
                "value": "της γαλήνης",
            },
            {
                "label": "Related adj.",
                "value": "γαλήνιος = ruhig, gelassen, still",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Μετά την καταιγίδα, επικράτησε απόλυτη γαλήνη.",
            "de": "Nach dem Gewitter herrschte absolute Stille.",
        },
    },
    {
        "id": "el-de-20",
        "greek": "λυγμός",
        "translation": "ein Schluchzer / ein würgender Weinkrampf",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "lig-MOS",
        "definition": "Das unwillkürliche Würgen eines vom Schmerz überwältigten Körpers – physischer und spezifischer als κλάμα (Weinen)",
        "note": "Die Wurzel λυγίζω (biegen, einknicken) verrät alles: Ein Schluchzer ist das, was passiert, wenn der Schmerz einen biegt. Dramatischer und spezifischer als κλάμα.",
        "etymology": "λυγίζω (biegen, einknicken, nachgeben) ← Altgriechisch λύγος (eine Pflanze, die sich biegen lässt) – das körperliche Nachgeben unter emotionalem Gewicht",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": False,
        "tags": [
            "formal",
        ],
        "grammar": [
            {
                "label": "Article",
                "value": "ο λυγμός",
            },
            {
                "label": "Gender",
                "value": "Masculine",
            },
            {
                "label": "Plural",
                "value": "οι λυγμοί",
            },
            {
                "label": "Genitive",
                "value": "του λυγμού",
            },
            {
                "label": "Related verb",
                "value": "λυγίζω = biegen, einknicken (unter Emotion)",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Ακούστηκαν λυγμοί από το διπλανό δωμάτιο.",
            "de": "Aus dem Nebenzimmer waren Schluchzer zu hören.",
        },
    },
    {
        "id": "el-de-21",
        "greek": "στραβοπατώ",
        "translation": "einen Fehltritt begehen / im Leben einen falschen Schritt machen",
        "type": "Ρήμα · Verb",
        "pronunciation": "stra-vo-pa-TO",
        "definition": "Falsch auftreten – wörtlich stolpern, übertragen einen falschen Weg im Leben einschlagen oder eine schlechte Entscheidung treffen",
        "note": "Die Zusammensetzung erschließt sich sofort, wenn man die Teile kennt. Στραβοπάτησα = ich habe einen Fehltritt gemacht.",
        "etymology": "στραβός (schief, verdreht, daneben) + πατώ (treten, schreiten) ← Altgriechisch πατέω – ein schiefer Schritt; στραβός möglicherweise von στρέφω (drehen)",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "figurative",
            "colloquial",
        ],
        "grammar": [
            {
                "label": "Aorist",
                "value": "στραβοπάτησα",
            },
            {
                "label": "Components",
                "value": "στραβός (schief) + πατώ (treten)",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Στραβοπάτησε νωρίς στη ζωή του, αλλά τα κατάφερε.",
            "de": "Er machte früh im Leben einen Fehltritt, schaffte es aber trotzdem.",
        },
    },
    {
        "id": "el-de-22",
        "greek": "καρδιοχτύπι",
        "translation": "Herzschlag / Herzflattern / Herzklopfen",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "kar-thio-HTIP-i",
        "definition": "Das Gefühl, wie das Herz vor Aufregung, Angst oder Vorfreude schlägt – ein Flattern, kein gleichmäßiger Schlag",
        "note": "Μου 'ρθε καρδιοχτύπι = mein Herz setzte einen Schlag aus. Eines jener griechischen Komposita, das in einem Wort ausdrückt, wofür Englisch einen ganzen Satz braucht.",
        "etymology": "καρδιά (Herz) ← Altgriechisch καρδία + χτυπώ (schlagen, treffen) ← Altgriechisch κτυπέω – das Herz, das gegen die Brust schlägt",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "figurative",
        ],
        "grammar": [
            {
                "label": "Article",
                "value": "το καρδιοχτύπι",
            },
            {
                "label": "Gender",
                "value": "Neuter",
            },
            {
                "label": "Plural",
                "value": "τα καρδιοχτύπια",
            },
            {
                "label": "Components",
                "value": "καρδιά (Herz) + χτυπώ (schlagen)",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Το καρδιοχτύπι της δυνάμωνε καθώς τον έβλεπε να πλησιάζει.",
            "de": "Ihr Herzklopfen wurde stärker, als sie ihn näher kommen sah.",
        },
    },
    {
        "id": "el-de-23",
        "greek": "φεγγαρόλουστος",
        "translation": "im Mondlicht gebadet / mondlichtdurchflutet",
        "type": "Επίθετο · Adjective",
        "pronunciation": "feg-ga-RO-lus-tos",
        "definition": "Von Mondlicht durchflutet oder übergossen – was im Englischen fünf Wörter braucht",
        "note": "Rein poetisch – im Alltag kaum zu hören, bringt aber jeden Muttersprachler zum Innehalten. Ein Vorzeige-Wort.",
        "etymology": "φεγγάρι (Mond) ← φέγγος (Licht, Glanz) + λούζω (baden, durchfluten) ← Altgriechisch λούω – im Licht des Mondes gebadet sein",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": False,
        "tags": [
            "formal",
        ],
        "grammar": [
            {
                "label": "Masculine",
                "value": "φεγγαρόλουστος",
            },
            {
                "label": "Feminine",
                "value": "φεγγαρόλουστη",
            },
            {
                "label": "Neuter",
                "value": "φεγγαρόλουστο",
            },
            {
                "label": "Components",
                "value": "φεγγάρι (Mond) + λούζομαι (gebadet/durchflutet werden)",
            },
            {
                "label": "Plural",
                "value": "φεγγαρόλουστοι / φεγγαρόλουστες / φεγγαρόλουστα",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Η παραλία ήταν φεγγαρόλουστη εκείνη τη νύχτα.",
            "de": "Der Strand war in jener Nacht vom Mondlicht durchflutet.",
        },
    },
    {
        "id": "el-de-24",
        "greek": "μελαγχολία",
        "translation": "Melancholie / schöne Schwermut",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "me-lag-ho-LI-a",
        "definition": "Eine nachdenkliche, bitterschöne Traurigkeit – keine Depression, sondern die ästhetische Melancholie des Herbstes, der Musik und des Bitterschönen",
        "note": 'Das Griechische hat dieses Wort der Welt geschenkt. Die antike Medizin schrieb sie der schwarzen Galle (μέλας χολή) zu. Griechische μελαγχολία hat eine besondere Schönheit – es ist die Traurigkeit, die man fast genießt.',
        "etymology": "μέλας (schwarz) + χολή (Galle) – in der antiken Medizin das Temperament, das für nachdenkliche, traurige Gemütszustände verantwortlich war; Griechenland gab dieses Wort an alle europäischen Sprachen weiter",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "formal",
            "figurative",
        ],
        "grammar": [
            {
                "label": "Article",
                "value": "η μελαγχολία",
            },
            {
                "label": "Gender",
                "value": "Feminine",
            },
            {
                "label": "Genitive",
                "value": "της μελαγχολίας",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Ένα αίσθημα μελαγχολίας τον κυρίεψε το φθινόπωρο.",
            "de": "Im Herbst ergriff ihn ein Gefühl der Melancholie.",
        },
    },
    {
        "id": "el-de-25",
        "greek": "αναποδογυρίζω",
        "translation": "auf den Kopf stellen / vollständig umwerfen",
        "type": "Ρήμα · Verb",
        "pronunciation": "a-na-po-tho-yi-RI-zo",
        "definition": "Etwas vollständig umdrehen – wörtlich oder übertragen (ein auf den Kopf gestelltes Leben)",
        "note": "Die Bestandteile sind beide schon im Vokabular: ανάποδα (verkehrt herum) + γυρίζω (drehen). Dadurch durch Zerlegung leicht lernbar.",
        "etymology": "ανάποδα (verkehrt herum/rückwärts) + γυρίζω (drehen) ← γύρος (eine Drehung, eine Runde) – in die verkehrte/umgekehrte Position drehen",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "figurative",
            "colloquial",
        ],
        "grammar": [
            {
                "label": "Aorist",
                "value": "αναποδογύρισα",
            },
            {
                "label": "Components",
                "value": "ανάποδα (verkehrt herum) + γυρίζω (drehen)",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Αναποδογύρισε τη ζωή μου.",
            "de": "Er hat mein Leben völlig auf den Kopf gestellt.",
        },
    },
    {
        "id": "el-de-26",
        "greek": "τριγυρνώ",
        "translation": "umherwandern / treiben / ziellos streifen",
        "type": "Ρήμα · Verb",
        "pronunciation": "tri-yi-NO",
        "definition": "Immer wieder im Kreis gehen, ohne Richtung – zielloser und rhythmischer als bloßes περπατώ (gehen)",
        "note": "Das Wort selbst hat in seinem Klang eine wandernde Qualität. Τριγυρνούσε = er trieb herum. Sehr ausdrucksstark für zielloses Stadtbummel.",
        "etymology": "τριγύρω (ringsum, auf allen Seiten) + das Verbsuffix -νώ – in alle Richtungen gehen, ohne irgendwo zu bleiben; τριγύρω aus τρι- (drei/alle) + γύρω (herum)",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "colloquial",
            "figurative",
        ],
        "grammar": [
            {
                "label": "Aorist",
                "value": "τριγύρισα",
            },
            {
                "label": "Related adverb",
                "value": "τριγύρω = ringsum, auf allen Seiten",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Τριγυρνούσε στους δρόμους χωρίς σκοπό.",
            "de": "Er streifte ziellos durch die Straßen.",
        },
    },
    {
        "id": "el-de-27",
        "greek": "ξεδιψώ",
        "translation": "den Durst stillen / ein lang gehegtes Verlangen endlich befriedigen",
        "type": "Ρήμα · Verb",
        "pronunciation": "kse-thip-SO",
        "definition": "Keinen Durst mehr haben – wörtlich oder übertragen, wenn ein lang gehegtes Verlangen endlich erfüllt wird",
        "note": "Funktioniert für wörtlichen Durst wie für jedes langgehegte Verlangen, das endlich gestillt wird. Ξεδίψασα επιτέλους = ich habe endlich bekommen, wonach ich mich gesehnt habe.",
        "etymology": "ξε- (aus/weg, signalisiert Befreiung) + δίψα (Durst) ← Altgriechisch δίψα ← PIE *dhwers- (trocken sein) – sich vom Durst befreien",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "figurative",
            "colloquial",
        ],
        "grammar": [
            {
                "label": "Aorist",
                "value": "ξεδίψασα",
            },
            {
                "label": "Components",
                "value": "ξε- (Befreiungspräfix) + δίψα (Durst)",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Επιτέλους ξεδίψασα — μήνες ήθελα να δω αυτή την ταινία.",
            "de": "Endlich habe ich dieses Verlangen gestillt – monatelang wollte ich diesen Film sehen.",
        },
    },
    {
        "id": "el-de-28",
        "greek": "φαφλατάς",
        "translation": "Schaumschläger / Großmaul / der viel redet und nichts tut",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "fa-fla-TAS",
        "definition": "Jemand, der viel redet, viel verspricht und nichts liefert",
        "note": "Wunderbar lautmalerisch – das Wort selbst klingt wie Prahlerei und hohles Getöse. Das Verb φαφλατίζω (heiße Luft reden) ist ebenso nützlich.",
        "etymology": "lautmalerisch – das Wort ahmt das Geräusch hohlen, aufgeblasenen Geredens nach; die wiederholten φ und die offenen Vokale imitieren die ausgestoßene heiße Luft",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "colloquial",
        ],
        "grammar": [
            {
                "label": "Masculine",
                "value": "ο φαφλατάς",
            },
            {
                "label": "Feminine",
                "value": "η φαφλατού",
            },
            {
                "label": "Related verb",
                "value": "φαφλατίζω = prahlen, heiße Luft reden",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Μην τον ακούς — είναι φαφλατάς, μιλά πολύ και δεν κάνει τίποτα.",
            "de": "Hör nicht auf ihn – er ist ein Schaumschläger, redet viel und tut nichts.",
        },
    },
    {
        "id": "el-de-29",
        "greek": "κουτσομπόλης",
        "translation": "Klatschbase / Tratschmaul / Gerüchteverbreiter",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "kut-som-BO-lis",
        "definition": "Jemand, der Klatsch und Gerüchte über andere sammelt und verbreitet",
        "note": "Κουτσομπολεύω (klatschen) und κουτσομπολιό (Klatsch als gesellschaftliche Beschäftigung) sind beide sehr geläufig. Η γειτονιά είναι γεμάτη κουτσομπόληδες = die Nachbarschaft ist voller Klatschbasen.",
        "etymology": "κουτσός (lahm, hinkend) + μπόλι (ein Pfropfen, etwas, das sich verbreitet) – etwas Lahmes, das von Person zu Person weitergetragen wird; oder möglicherweise Volksetymologie; Ursprung nicht endgültig geklärt",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "colloquial",
        ],
        "grammar": [
            {
                "label": "Masculine",
                "value": "ο κουτσομπόλης",
            },
            {
                "label": "Feminine",
                "value": "η κουτσομπόλα",
            },
            {
                "label": "Related verb",
                "value": "κουτσομπολεύω = klatschen, tratschen",
            },
            {
                "label": "Related noun",
                "value": "το κουτσομπολιό = Klatsch (als Tätigkeit)",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Μη λες τίποτα σε αυτόν — είναι κουτσομπόλης.",
            "de": "Sag ihm nichts – er ist eine Klatschbase.",
        },
    },
    {
        "id": "el-de-30",
        "greek": "κεφάτος",
        "translation": "gut aufgelegt / ausgelassen / voller ansteckender Energie",
        "type": "Επίθετο · Adjective",
        "pronunciation": "ke-FA-tos",
        "definition": "Jemand, der ansteckend gute Energie ausstrahlt – nicht nur glücklich, sondern eine ganze Runde mitreißend",
        "note": "Das Adjektiv zu κέφι. Σήκωσε το κέφι = er hat alle aufgemuntert. Ήρθε κεφάτος = er kam voller Leben an. Wer κεφάτος ist, bringt die Party erst zum Laufen.",
        "etymology": "κέφι (Hochstimmung, s. oben) + das Adjektivsuffix -άτος – voller κέφι; das Suffix signalisiert, mit der genannten Eigenschaft aufgeladen zu sein",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "colloquial",
        ],
        "grammar": [
            {
                "label": "Masculine",
                "value": "κεφάτος",
            },
            {
                "label": "Feminine",
                "value": "κεφάτη",
            },
            {
                "label": "Neuter",
                "value": "κεφάτο",
            },
            {
                "label": "Root",
                "value": "κέφι (Hochstimmung)",
            },
            {
                "label": "Plural",
                "value": "κεφάτοι / κεφάτες / κεφάτα",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Ήρθε κεφάτος στο πάρτι και σήκωσε το κέφι όλων.",
            "de": "Er kam gut aufgelegt zur Party und riss alle mit.",
        },
    },
    {
        "id": "el-de-31",
        "greek": "αλάνης",
        "translation": "Straßenkind / liebenswerter Schlawiner / jemand, der auf der Straße aufgewachsen ist",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "a-LA-nis",
        "definition": "Jemand, der ohne viel Aufsicht auf der Straße aufgewachsen ist – rau, aber mit eigenem Ehrenkodex",
        "note": "Von αλάνα (ein leeres Stadtgrundstück, Brachland) – der Ort, an dem unbeaufsichtigte Kinder spielten. Das Wort trägt Zuneigung neben der Rauheit. Tief verwurzelt in der griechischen Stadtkultur und im Rebetiko.",
        "etymology": "αλάνα (ein leeres Stadtgrundstück, Brachland) – möglicherweise aus dem Albanischen oder einem Balkankontaktwort; das Brachland als Schule der Straßenkultur",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": False,
        "tags": [
            "colloquial",
        ],
        "grammar": [
            {
                "label": "Masculine",
                "value": "ο αλάνης",
            },
            {
                "label": "Feminine",
                "value": "η αλάνα",
            },
            {
                "label": "Related",
                "value": "η αλάνα = Brachland, leeres Stadtgrundstück",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Μεγάλωσε αλάνης, αλλά έγινε καλός άνθρωπος.",
            "de": "Er wuchs als Straßenkind auf, wurde aber ein guter Mensch.",
        },
    },
    {
        "id": "el-de-32",
        "greek": "πονηρός",
        "translation": "gerissen / verschlagen / schlau / nicht naiv",
        "type": "Επίθετο · Adjective",
        "pronunciation": "po-ni-ROS",
        "definition": "Klug und berechnend – nicht unbedingt unehrlich, aber keineswegs unschuldig; kann je nach Kontext bewundernswert oder beunruhigend sein",
        "note": "Nicht dasselbe wie κακός (böse). Η πονηριά kann eine Überlebensstrategie oder ein moralischer Makel sein. Πονηρό βλέμμα = ein wissender, verschlagener Blick. Der Kontext entscheidet, ob es ein Kompliment oder eine Warnung ist.",
        "etymology": "Altgriechisch πονηρός (voller Mühsal, lästig, betrügerisch) ← πόνος (Mühsal, Schmerz) – ursprünglich «einer, der Ärger macht», entwickelte sich zu «einer, der klug genug ist, Ärger zu machen»",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "neutral",
            "figurative",
        ],
        "grammar": [
            {
                "label": "Masculine",
                "value": "πονηρός",
            },
            {
                "label": "Feminine",
                "value": "πονηρή",
            },
            {
                "label": "Neuter",
                "value": "πονηρό",
            },
            {
                "label": "Related noun",
                "value": "η πονηριά = Gerissenheit, Verschlagenheit",
            },
            {
                "label": "Plural",
                "value": "πονηροί / πονηρές / πονηρά",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Είναι πονηρός — πάντα ξέρει πώς να βγαίνει κερδισμένος.",
            "de": "Er ist gerissen – er weiß immer, wie er als Gewinner herauskommt.",
        },
    },
    {
        "id": "el-de-33",
        "greek": "ζωηρός",
        "translation": "lebhaft / energiegeladen / temperamentvoll",
        "type": "Επίθετο · Adjective",
        "pronunciation": "zo-i-ROS",
        "definition": "Voller Leben und Energie – von einem Kind, einer Person, einer Farbe oder einer Diskussion",
        "note": "Von ζωή (Leben). Ζωηρό χρώμα = eine lebhafte/leuchtende Farbe. Ζωηρή συζήτηση = eine lebhafte Diskussion. Die Wurzel ist transparent, und die Wortfamilie ist enorm – ζωή ergibt ζωολογία, ζωγράφος und vieles mehr.",
        "etymology": 'ζωή (Leben) ← Altgriechisch ζωή ← PIE *gʷih₃wó- (lebendig) + das Suffix -ηρός (voll von) – dieselbe Wurzel wie englisch "quick" (ursprünglich: lebendig) und "zoo"',
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "neutral",
        ],
        "grammar": [
            {
                "label": "Masculine",
                "value": "ζωηρός",
            },
            {
                "label": "Feminine",
                "value": "ζωηρή",
            },
            {
                "label": "Neuter",
                "value": "ζωηρό",
            },
            {
                "label": "Root",
                "value": "ζωή (Leben)",
            },
            {
                "label": "Plural",
                "value": "ζωηροί / ζωηρές / ζωηρά",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Είναι πολύ ζωηρό παιδί — δεν ησυχάζει ποτέ.",
            "de": "Es ist ein sehr lebhaftes Kind – es sitzt nie still.",
        },
    },
    {
        "id": "el-de-34",
        "greek": "αψύς",
        "translation": "jähzornig / hitzig / jemand, der schnell aufbraust, aber keinen Groll hegt",
        "type": "Επίθετο · Adjective",
        "pronunciation": "ap-SIS",
        "definition": "Aufbrausend und schnell wütend, aber das Feuer brennt schnell und kurz – kein kalter, anhaltender Groll",
        "note": "Die entscheidende kulturelle Nuance: Ein αψύς Mensch braust sofort auf, verzeiht aber meistens auch schnell wieder. Anders als jemand Kaltes und Berechnendes. Vgl. θυμοσιάρης (jähzornig, umgangssprachlicher).",
        "etymology": "α- (verstärkendes Präfix) + ψύχω (abkühlen) ← Altgriechisch ψύχω (blasen, kühlen) – wörtlich «schwer abzukühlen», jemand, dessen Hitze sich nur schwer verflüchtigt",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": False,
        "tags": [
            "neutral",
        ],
        "grammar": [
            {
                "label": "Masculine",
                "value": "αψύς",
            },
            {
                "label": "Feminine",
                "value": "αψιά",
            },
            {
                "label": "Neuter",
                "value": "αψύ",
            },
            {
                "label": "Related noun",
                "value": "η αψυθυμία = Jähzornigkeit",
            },
            {
                "label": "Plural",
                "value": "αψείς / αψιές / αψιά",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Είναι αψύς, αλλά ξεχνά γρήγορα.",
            "de": "Er ist jähzornig, vergisst es aber auch schnell wieder.",
        },
    },
    {
        "id": "el-de-35",
        "greek": "σβέλτος",
        "translation": "flink / behänd / leichtfüßig",
        "type": "Επίθετο · Adjective",
        "pronunciation": "ZVEL-tos",
        "definition": "Körperlich flink und schnell – leichtfüßig, fix von Hand oder geistig wendig",
        "note": "Aus dem Italienischen svelto. Σβέλτα! als Adverb = schnell! beeil dich! Eines der venezianisch-italienischen Lehnwörter, das sich im Griechischen völlig zu Hause fühlt.",
        "etymology": "Italienisch svelto (flink, schnell) ← svellere (entwurzeln, herausreißen) ← Latein ex- + vellere (ziehen) – das Bild von etwas leicht und schnell Herausgerissenem",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": False,
        "tags": [
            "neutral",
            "loanword:italian",
        ],
        "grammar": [
            {
                "label": "Masculine",
                "value": "σβέλτος",
            },
            {
                "label": "Feminine",
                "value": "σβέλτη",
            },
            {
                "label": "Neuter",
                "value": "σβέλτο",
            },
            {
                "label": "Adverb",
                "value": "σβέλτα = schnell, flink",
            },
            {
                "label": "Plural",
                "value": "σβέλτοι / σβέλτες / σβέλτα",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Σβέλτος σαν γάτα, πέρασε ανάμεσα στο πλήθος.",
            "de": "Flink wie eine Katze, schlüpfte er durch die Menge.",
        },
    },
    {
        "id": "el-de-36",
        "greek": "χαρούμενος",
        "translation": "glücklich / fröhlich / freudig",
        "type": "Επίθετο · Adjective",
        "pronunciation": "ha-RU-me-nos",
        "definition": "Glück und gute Laune ausstrahlend – der Mensch, dem die Freude anzusehen ist",
        "note": "Von χαρά (Freude) – eines der grundlegenden Wörter des griechischen Gefühlswortschatzes. Τι χαρά! = was für eine Freude! / wie wunderbar! Vgl. χαίρομαι (sich freuen/genießen).",
        "etymology": "χαρά (Freude) ← Altgriechisch χαρά ← χαίρω (sich freuen) ← PIE *ǵʰeh₁i- (sich freuen) – gibt über einen anderen Zweig englisch «yearn» (sich sehnen)",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "neutral",
        ],
        "grammar": [
            {
                "label": "Masculine",
                "value": "χαρούμενος",
            },
            {
                "label": "Feminine",
                "value": "χαρούμενη",
            },
            {
                "label": "Neuter",
                "value": "χαρούμενο",
            },
            {
                "label": "Root",
                "value": "η χαρά = Freude",
            },
            {
                "label": "Plural",
                "value": "χαρούμενοι / χαρούμενες / χαρούμενα",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Σε βλέπω χαρούμενο σήμερα — τι έγινε;",
            "de": "Du siehst heute glücklich aus – was ist passiert?",
        },
    },
    {
        "id": "el-de-37",
        "greek": "στριμώχνομαι",
        "translation": "eingequetscht sein / in einem engen Raum zusammengepfercht sein / in die Enge getrieben werden",
        "type": "Ρήμα · Verb",
        "pronunciation": "stri-MOH-no-me",
        "definition": "Von allen Seiten zusammengedrückt werden – in einem überfüllten Fahrzeug, einem vollgestopften Raum oder einer engen Ecke; auch übertragen für eine schwierige Lage",
        "note": "Der Klang des Wortes ist befriedigend kompakt. Στριμώχτηκα σε μια γωνιά = ich wurde in eine Ecke gedrängt. Στριμωχτήκαμε όλοι μέσα = wir haben uns alle hineingezwängt.",
        "etymology": "möglicherweise verwandt mit στρίβω (drehen, quetschen) und στριφογυρίζω (sich eng im Kreis drehen) – das Bild, in einen kleinen Raum hineingepresst zu werden",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "colloquial",
            "figurative",
        ],
        "grammar": [
            {
                "label": "Active",
                "value": "στριμώχνω = jemanden hineinquetschen/hineinpferchen",
            },
            {
                "label": "Aorist passive",
                "value": "στριμώχτηκα = ich wurde eingequetscht",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Στριμωχτήκαμε όλοι στο μικρό αμάξι.",
            "de": "Wir haben uns alle in das winzige Auto gezwängt.",
        },
    },
    {
        "id": "el-de-38",
        "greek": "καλοτυχία",
        "translation": "Glück / Wohlergehen / ein herzlicher Wunsch für jemandes Zukunft",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "ka-lo-ti-HI-a",
        "definition": "Gutes Glück – ein herzlicherer und wärmerer Wunsch als bloßes καλή τύχη (viel Glück)",
        "note": "Das Kompositum καλο- + τύχη verbindet Güte und Schicksal in einem einzigen Wort. Schön zu sagen bei einem Abschied oder einem neuen Anfang.",
        "etymology": "καλός (gut) + τύχη (Glück, Schicksal) ← Altgriechisch τύχη ← τυγχάνω (geschehen, zufällig treffen) – wörtlich «gutes Schicksal», die Zuteilung guter Dinge",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "neutral",
        ],
        "grammar": [
            {
                "label": "Article",
                "value": "η καλοτυχία",
            },
            {
                "label": "Gender",
                "value": "Feminine",
            },
            {
                "label": "Related adj.",
                "value": "καλότυχος = glücklich, vom Glück begünstigt",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Σου εύχομαι καλοτυχία στο νέο σου ξεκίνημα.",
            "de": "Ich wünsche dir viel Glück bei deinem neuen Anfang.",
        },
    },
    {
        "id": "el-de-39",
        "greek": "σιωπή",
        "translation": "Stille / Schweigen",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "si-o-PI",
        "definition": "Schweigen – aber mit Gewicht und Präsenz; eine bedeutungsvolle Stille, nicht bloß die Abwesenheit von Lärm",
        "note": "Η σιωπή είναι χρυσός = Schweigen ist Gold. Σιωπηρή συμφωνία = stillschweigende Vereinbarung. Σιώπα! = sei still! (befehlsartiger als ησύχασε). Das Verb σιωπώ ist ebenso schön.",
        "etymology": "Altgriechisch σιωπή (Schweigen, Stille) ← σιγή (Schweigen) – möglicherweise verwandt mit σιγανός (leise, sanft); die tiefere PIE-Wurzel ist ungewiss",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "formal",
            "figurative",
        ],
        "grammar": [
            {
                "label": "Article",
                "value": "η σιωπή",
            },
            {
                "label": "Gender",
                "value": "Feminine",
            },
            {
                "label": "Genitive",
                "value": "της σιωπής",
            },
            {
                "label": "Related verb",
                "value": "σιωπώ = schweigen",
            },
            {
                "label": "Related adj.",
                "value": "σιωπηλός = still, schweigsam (von einer Person)",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Βασίλεψε απόλυτη σιωπή στο δωμάτιο.",
            "de": "Im Zimmer herrschte absolute Stille.",
        },
    },
    {
        "id": "el-de-40",
        "greek": "αυγή",
        "translation": "Morgengrauen / Tagesanbruch",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "av-YI",
        "definition": "Das Morgengrauen – das erste Licht des Tages; gehobener und poetischer als das umgangssprachliche χαράματα",
        "note": "Auch ein verbreiteter Frauenname. Poetischer als χαράματα (das Umgangswort für Morgengrauen). Verwandt mit αυγό (Ei) über die blassgelbe Farbe beider. Das Wort leuchtet mit dem Licht, das es beschreibt.",
        "etymology": "Altgriechisch αὐγή (Helligkeit, Glanz, Morgenlicht) ← PIE *h₂ewg- (leuchten, wachsen) – dieselbe Wurzel wie lateinisch aurora und englisch «augment» (wachsendes Licht)",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "formal",
        ],
        "grammar": [
            {
                "label": "Article",
                "value": "η αυγή",
            },
            {
                "label": "Gender",
                "value": "Feminine",
            },
            {
                "label": "Genitive",
                "value": "της αυγής",
            },
            {
                "label": "cf.",
                "value": "τα χαράματα = Morgengrauen (umgangssprachlich) · η αυγή = Morgengrauen (poetisch/literarisch)",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Ξύπνησε με την αυγή και βγήκε στη θάλασσα.",
            "de": "Sie erwachte bei Morgengrauen und ging ans Meer.",
        },
    },
    {
        "id": "el-de-41",
        "greek": "αστραπή",
        "translation": "Blitz / Blitzstrahl / alles blendend Schnelle",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "as-tra-PI",
        "definition": "Ein Blitzstrahl – wörtlich oder übertragen für alles von blendender Geschwindigkeit oder Brillanz",
        "note": "Σαν αστραπή (wie ein Blitz) ist ein äußerst geläufiger Vergleich für Geschwindigkeit. Αστραπιαίος = blitzschnell. In der Mythologie der Begleiter von βροντή (Donner) – Zeus schleuderte beide.",
        "etymology": "αστράπτω (aufblitzen, leuchten) ← αστήρ/αστέρι (Stern) ← PIE *h₂stér- (Stern) – Blitz als Sternblitz; dieselbe Wurzel wie αστέρι (Stern) und «Astronomie»",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "neutral",
            "figurative",
        ],
        "grammar": [
            {
                "label": "Article",
                "value": "η αστραπή",
            },
            {
                "label": "Gender",
                "value": "Feminine",
            },
            {
                "label": "Plural",
                "value": "οι αστραπές",
            },
            {
                "label": "Related",
                "value": "αστράφτω = aufblitzen/leuchten · αστραπιαίος = blitzschnell",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Πέρασε σαν αστραπή.",
            "de": "Er raste vorbei wie ein Blitz.",
        },
    },
    {
        "id": "el-de-42",
        "greek": "ανάσα",
        "translation": "Atemzug / ein Moment der Erleichterung / Luft zum Atmen",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "A-na-sa",
        "definition": "Wörtlich ein Atemzug; übertragen ein Moment der Erleichterung, Raum zum Durchatmen oder etwas, das einem den Atem verschlägt",
        "note": "Μου πήρε την ανάσα = es hat mir den Atem verschlagen. Δεν έχω ανάσα = ich bin überwältigt / habe keine Luft mehr. Δώσε μου μια ανάσα = gib mir eine Atempause. Vgl. αναπνέω.",
        "etymology": "ανα- (auf, wieder) + πνοή (Atem) ← Altgriechisch πνέω (atmen, blasen) – ein nach oben genommener Atemzug; dieselbe Wurzel wie αναπνέω",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "neutral",
            "figurative",
        ],
        "grammar": [
            {
                "label": "Article",
                "value": "η ανάσα",
            },
            {
                "label": "Gender",
                "value": "Feminine",
            },
            {
                "label": "Plural",
                "value": "οι ανάσες",
            },
            {
                "label": "Key phrases",
                "value": "μου πήρε την ανάσα = es hat mir den Atem verschlagen · δεν έχω ανάσα = ich habe keine Luft mehr",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Επιτέλους λίγη ανάσα από τη δουλειά.",
            "de": "Endlich ein wenig Luft vom Arbeitsalltag.",
        },
    },
    {
        "id": "el-de-43",
        "greek": "γαμώτο",
        "translation": "Scheiße / verdammt nochmal / Mist",
        "type": "Επιφώνημα · Expletive",
        "pronunciation": "ga-MO-to",
        "definition": "Der griechische Allzweck-Kraftausdruck – je nach Ton und Kontext für Frustration, Überraschung, Schmerz oder sogar Bewunderung",
        "note": "Anders als englische Entsprechungen deckt es ein breites emotionales Spektrum ab: Schmerz, Frustration, Überraschung, sogar Bewunderung (γαμώτο, τι ωραίο! = verdammt, das ist schön!). Der Ton entscheidet über alles.",
        "etymology": "von γαμώ (ein starkes Verb) – das Suffix -τo ist eine diminutive/expressive Endung, die es leicht abschwächt; gelangte aus dem Arbeitermilieu der Städte in die Alltagssprache",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "colloquial",
        ],
        "grammar": [
            {
                "label": "Register",
                "value": "Starker Kraftausdruck – mit Bewusstsein für den Kontext verwenden",
            },
            {
                "label": "Variants",
                "value": "γαμώτο μου (emphatisch) · μα το γαμώτο (um Himmels willen)",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Γαμώτο, ξέχασα το κλειδί μου!",
            "de": "Scheiße, ich habe meinen Schlüssel vergessen!",
        },
    },
    {
        "id": "el-de-44",
        "greek": "μαλακία",
        "translation": "Schwachsinn / eine dumme Handlung / Blödsinn (Schimpfwort)",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "ma-la-KI-a",
        "definition": "Eine dumme Bemerkung, eine sinnlose Handlung oder allgemeiner Unsinn – technisch vulgär, aber im informellen Gespräch allgegenwärtig",
        "note": "Im griechischen Alltag so eingebettet, dass so zu tun, als existiere es nicht, unehrlich wäre. Unter engen Freunden kann μαλάκα sogar liebevoll sein. Erst verstehen, dann benutzen – sicherer, bis man sein Publikum kennt.",
        "etymology": "von μαλακός (weich, schwach) ← Altgriechisch μαλακός ← PIE *ml̥h₂kó- (weich) – das Substantiv entwickelte sich durch medizinische und umgangssprachliche Bedeutungsverschiebung zur heutigen Bedeutung",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "colloquial",
        ],
        "grammar": [
            {
                "label": "Article",
                "value": "η μαλακία",
            },
            {
                "label": "Gender",
                "value": "Feminine",
            },
            {
                "label": "Plural",
                "value": "οι μαλακίες",
            },
            {
                "label": "Register",
                "value": "Vulgär, aber im informellen Gespräch extrem verbreitet",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Μη λες μαλακίες — ξέρεις πολύ καλά τι έγινε.",
            "de": "Erzähl keinen Blödsinn – du weißt genau, was passiert ist.",
        },
    },
    {
        "id": "el-de-45",
        "greek": "ξεκάνω",
        "translation": "erledigen / zerstören / völlig erschöpfen",
        "type": "Ρήμα · Verb",
        "pronunciation": "kse-KA-no",
        "definition": "Etwas vollständig aus der Existenz heraus tun – zerstören, restlos erschöpfen oder entscheidend abschließen",
        "note": "Με ξεκάνεις! kann Verzweiflung sein (du bringst mich um!) oder Bewunderung (du bist unglaublich!). Ξεκάνομαι = sich völlig abrackern. Das Präfix ξε- signalisiert totalen, unumkehrbaren Abschluss.",
        "etymology": "ξε- (aus/weg – signalisiert vollständige Erschöpfung) + κάνω (tun/machen) ← Altgriechisch κάνω – etwas so gründlich tun, dass es nicht mehr existiert",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "colloquial",
            "figurative",
        ],
        "grammar": [
            {
                "label": "Aorist",
                "value": "ξεκανόνισα / ξεκάνεψα",
            },
            {
                "label": "Passive",
                "value": "ξεκάνομαι = erschöpft sein / sich abrackern",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Με ξεκάνει αυτή η δουλειά.",
            "de": "Diese Arbeit macht mich fertig.",
        },
    },
    {
        "id": "el-de-46",
        "greek": "σιγανός",
        "translation": "leise / sanft / langsam / still-melancholisch",
        "type": "Επίθετο · Adjective",
        "pronunciation": "si-ga-NOS",
        "definition": "Weich und leise – vom Regen, einem Lied, der Haltung einer Person; im griechischen Volksgebrauch mit sanfter Melancholie behaftet",
        "note": "Sinnlicher und atmosphärischer als bloßes ήσυχος (ruhig). Σιγά σιγά (langsam langsam) ist einer der griechischsten Sätze überhaupt. Ein σιγανό τραγούδι ist ein leises, melancholisches Lied.",
        "etymology": "σιγή (Schweigen, Stille) ← Altgriechisch σιγή – möglicherweise aus einer vorgriechischen oder lautmalerischen Wurzel; das Suffix -ανός bildet das Adjektiv «von der Beschaffenheit der Stille»",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": [
            "formal",
            "figurative",
        ],
        "grammar": [
            {
                "label": "Masculine",
                "value": "σιγανός",
            },
            {
                "label": "Feminine",
                "value": "σιγανή",
            },
            {
                "label": "Neuter",
                "value": "σιγανό",
            },
            {
                "label": "Related adverb",
                "value": "σιγά = langsam / leise · σιγά σιγά = nach und nach",
            },
            {
                "label": "Plural",
                "value": "σιγανοί / σιγανές / σιγανά",
            },
        ],
        "conjugation": None,
        "departure_lang": "de",
        "example": {
            "gr": "Έπεφτε σιγανή βροχή και ο κόσμος ησύχαζε.",
            "de": "Ein leiser Regen fiel und die Welt wurde stiller.",
        },
    },
]
