# vocab_data.py
# Built-in curated word set — 46 cards, IDs 1-46.
# User cards live in user_cards.json (IDs 1001+).

SCENES_META: list = [
    {"id": "curated", "label": "🧿 Curated", "emoji": "🧿"},
]

CARDS: list = [
    {
        "id": 1,
        "greek": "φιλότιμο",
        "translation": "honour / dignity / the compulsion to do right by others",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "fi-LO-ti-mo",
        "definition": "The deeply Greek concept of acting with honour, generosity, and selflessness — not out of obligation but out of pride in who you are",
        "note": "Untranslatable. If someone says «έχει φιλότιμο» it is high praise. Greeks consider it a defining national virtue and will happily discuss it at length if you bring it up.",
        "etymology": "φίλος (loving, friend) + τιμή (honour) — to love honour; τιμή gives τιμώ (to honour) and τιμή (price — the worth of something)",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["formal", "figurative"],
        "grammar": [{"label": "Article", "value": "το φιλότιμο"}, {"label": "Gender", "value": "Neuter"}, {"label": "Genitive", "value": "του φιλότιμου"}],
        "example": {"gr": "Το φιλότιμο είναι ό,τι πιο ελληνικό υπάρχει.", "en": "Filotimo is the most Greek thing there is."},
        "conjugation": None,
    },
    {
        "id": 2,
        "greek": "μεράκι",
        "translation": "passionate devotion / soul poured into a craft",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "me-RA-ki",
        "definition": "Doing something with your whole heart and soul — not just skill but love and deep personal investment",
        "note": "Doing something με μεράκι is one of the highest compliments you can pay someone's work or cooking. A craftsman, a musician, a cook can all have μεράκι.",
        "etymology": "Turkish merak (curiosity, deep interest, obsession) — one of the most beautiful Turkish loanwords in Greek",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["colloquial", "figurative", "loanword:turkish"],
        "grammar": [{"label": "Article", "value": "το μεράκι"}, {"label": "Gender", "value": "Neuter"}, {"label": "Genitive", "value": "του μερακιού"}],
        "example": {"gr": "Μαγειρεύει με μεράκι.", "en": "She cooks with real soul and passion."},
        "conjugation": None,
    },
    {
        "id": 3,
        "greek": "κέφι",
        "translation": "high spirits / the mood to celebrate / joie de vivre",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "KE-fi",
        "definition": "The spontaneous, contagious energy of high spirits — the mood that makes a night unforgettable",
        "note": "Μου κόπηκε το κέφι = something killed the vibe. Σήκωσε το κέφι όλων = he lifted everyone's spirits. From Turkish keyif (pleasure, comfort).",
        "etymology": "Turkish keyif (pleasure, comfort, mood) — entered Greek via Ottoman contact",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["colloquial", "loanword:turkish"],
        "grammar": [{"label": "Article", "value": "το κέφι"}, {"label": "Gender", "value": "Neuter"}, {"label": "Genitive", "value": "του κεφιού"}, {"label": "Key phrase", "value": "έχω κέφι = I'm in high spirits · δεν έχω κέφι = I'm not feeling it"}],
        "example": {"gr": "Απόψε έχω κέφι για χορό.", "en": "Tonight I'm in the mood to dance."},
        "conjugation": None,
    },
    {
        "id": 4,
        "greek": "λεβεντιά",
        "translation": "noble bearing / gallantry / the dignity of a free person",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "le-ven-DIA",
        "definition": "The quality of physical grace, moral uprightness, and fearlessness combined — the carriage of someone who bows to no one",
        "note": "A λεβέντης is the archetypally admirable Greek man — brave, dignified, free. Central to klephtic folk tradition and folk song.",
        "etymology": "Turkish levend (a free soldier, a sailor) — originally described irregular soldiers who served no master",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": False,
        "tags": ["formal", "figurative", "loanword:turkish"],
        "grammar": [{"label": "Article", "value": "η λεβεντιά"}, {"label": "Gender", "value": "Feminine"}, {"label": "Genitive", "value": "της λεβεντιάς"}, {"label": "Related", "value": "λεβέντης = a gallant, upstanding man"}],
        "example": {"gr": "Περπατούσε με λεβεντιά, χωρίς να φοβάται κανέναν.", "en": "He walked with proud bearing, fearing no one."},
        "conjugation": None,
    },
    {
        "id": 5,
        "greek": "μαγκιά",
        "translation": "coolness / street swagger / effortless composure",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "mag-GIA",
        "definition": "The quality of handling everything with effortless style and a certain irreverence — playing by your own rules and making it look easy",
        "note": "A μάγκας is the person; μαγκιά is the quality itself. Deeply embedded in rebetiko music culture. Not criminal but streetwise and unflappable.",
        "etymology": "possibly from Turkish manga (a military squad of tough men) — entered Greek urban slang via Piraeus port culture",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": False,
        "tags": ["colloquial", "figurative"],
        "grammar": [{"label": "Article", "value": "η μαγκιά"}, {"label": "Gender", "value": "Feminine"}, {"label": "Genitive", "value": "της μαγκιάς"}, {"label": "Related", "value": "ο μάγκας = a cool, street-smart person"}],
        "example": {"gr": "Το έκανε με μαγκιά — χωρίς να ιδρώσει.", "en": "He pulled it off with total cool — without breaking a sweat."},
        "conjugation": None,
    },
    {
        "id": 6,
        "greek": "γλέντι",
        "translation": "feast / celebration with music and dancing",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "GLEN-di",
        "definition": "A proper celebration involving music, singing, dancing, food, and genuine abandon — more than a party",
        "note": "The verb γλεντώ means to give yourself over to celebration. Κάνουμε γλέντι = we're having a proper feast. Associated with weddings, name days, and village festivals.",
        "etymology": "possibly from Albanian gëzend (joy, celebration) or related to γελώ (to laugh) — origin debated",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["neutral"],
        "grammar": [{"label": "Article", "value": "το γλέντι"}, {"label": "Gender", "value": "Neuter"}, {"label": "Plural", "value": "τα γλέντια"}, {"label": "Genitive", "value": "του γλεντιού"}, {"label": "Related verb", "value": "γλεντώ = to celebrate, to make merry"}],
        "example": {"gr": "Το γλέντι κράτησε ώς το πρωί.", "en": "The celebration went on until morning."},
        "conjugation": None,
    },
    {
        "id": 7,
        "greek": "καημός",
        "translation": "deep longing / aching grief / bittersweet yearning",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "ka-i-MOS",
        "definition": "The particular pain of missing something or someone, or of an unfulfilled desire that has become part of you — between grief and longing",
        "note": "Essential vocabulary for understanding Greek music, especially rebetiko and folk song. Often paired with ξενιτιά. One of the most emotionally loaded words in the language.",
        "etymology": "possibly from καίω (to burn) — a burning ache; the grief that smoulders rather than flares",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["formal", "figurative"],
        "grammar": [{"label": "Article", "value": "ο καημός"}, {"label": "Gender", "value": "Masculine"}, {"label": "Plural", "value": "οι καημοί"}, {"label": "Genitive", "value": "του καημού"}],
        "example": {"gr": "Τραγουδούσε τον καημό της ξενιτιάς.", "en": "She sang of the aching grief of living far from home."},
        "conjugation": None,
    },
    {
        "id": 8,
        "greek": "ξενιτιά",
        "translation": "exile / the condition of living far from home",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "kse-ni-TIA",
        "definition": "The condition of being far from your people, your land, and your language — not just homesickness but a whole existential state",
        "note": "From ξένος (stranger/foreigner/guest — the same word covers all three). A central theme in Greek folk song for centuries, from the Ottoman period through waves of emigration.",
        "etymology": "ξένος (stranger, foreigner, guest) ← Ancient Greek ξένος ← PIE *gʰosti- (guest, stranger) — the same root as Latin hostis (enemy) and hospes (host)",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["formal", "figurative"],
        "grammar": [{"label": "Article", "value": "η ξενιτιά"}, {"label": "Gender", "value": "Feminine"}, {"label": "Genitive", "value": "της ξενιτιάς"}],
        "example": {"gr": "Η ξενιτιά τρώει την καρδιά σου σιγά σιγά.", "en": "Living far from home eats away at your heart slowly."},
        "conjugation": None,
    },
    {
        "id": 9,
        "greek": "ρεμβασμός",
        "translation": "daydreaming / reverie / the mind drifting",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "rem-vaz-MOS",
        "definition": "The specific quality of mind-wandering that is neither sleep nor active thought — a meditative, aimless drift",
        "note": "More poetic and specific than just σκέφτομαι (to think). Perfect for describing someone lost in a seaside gaze or an afternoon window reverie.",
        "etymology": "Ancient Greek ῥέμβομαι (to wander, to rove, to spin) — the mind as something that wanders freely when unanchored",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": False,
        "tags": ["formal", "figurative"],
        "grammar": [{"label": "Article", "value": "ο ρεμβασμός"}, {"label": "Gender", "value": "Masculine"}, {"label": "Genitive", "value": "του ρεμβασμού"}, {"label": "Related verb", "value": "ρεμβάζω = to daydream, to be lost in thought"}],
        "example": {"gr": "Τον έπιασε ρεμβασμός κοιτάζοντας τη θάλασσα.", "en": "He fell into a reverie gazing at the sea."},
        "conjugation": None,
    },
    {
        "id": 10,
        "greek": "κάηκα",
        "translation": "I'm done for / I got burned / I fell hard (for someone)",
        "type": "Ρήμα · Verb (aorist 1sg)",
        "pronunciation": "KA-i-ka",
        "definition": "Aorist of καίγομαι — to be consumed by a situation, emotion, or exhaustion; covers disaster, exhaustion, and falling hard for someone",
        "note": "One word that covers a remarkable range: I got caught, I'm in deep trouble, I'm utterly exhausted, I fell hard for someone. Και καήκαμε = and we're done for. Κάηκα μαζί της = I fell for her badly.",
        "etymology": "καίω (to burn) ← Ancient Greek καίω ← PIE *keh₂u- (to burn) — same root as καύσωνας (heatwave) and Holocaust (ὁλόκαυστος = completely burned)",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["colloquial", "figurative"],
        "grammar": [{"label": "Base verb", "value": "καίγομαι (passive/deponent) = to burn"}, {"label": "Aorist", "value": "κάηκα (1sg) / καήκαμε (1pl)"}],
        "example": {"gr": "Κάηκα — ξέχασα τελείως την εξέταση.", "en": "I'm done for — I completely forgot the exam."},
        "conjugation": None,
    },
    {
        "id": 11,
        "greek": "με τρώει",
        "translation": "it's eating me / it's bugging me / I can't stop thinking about it",
        "type": "Φράση · Fixed Expression",
        "pronunciation": "me TRO-i",
        "definition": "Something consuming you from the inside — guilt, curiosity, jealousy, an unanswered question",
        "note": "Με τρώει η περιέργεια = curiosity is eating me alive (= I'm dying to know). Με τρώει η ζήλια = jealousy is eating me. A beautifully physical metaphor for psychological preoccupation.",
        "etymology": "τρώω (to eat) ← Ancient Greek τρώγω (to gnaw, to nibble) — the image of something gnawing at you from within",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["colloquial", "figurative"],
        "grammar": [{"label": "Structure", "value": "με τρώει + noun/clause"}, {"label": "Base verb", "value": "τρώω = to eat — 3sg: τρώει"}],
        "example": {"gr": "Με τρώει που δεν του είπα την αλήθεια.", "en": "It's eating me that I didn't tell him the truth."},
        "conjugation": None,
    },
    {
        "id": 12,
        "greek": "κολλητός",
        "translation": "best friend / inseparable companion",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "ko-li-TOS",
        "definition": "Your closest friend — so close they are metaphorically glued to you",
        "note": "More intimate and warmer than φίλος (friend) in colloquial speech. Ο κολλητός μου = my best mate. The feminine is κολλητή.",
        "etymology": "κολλώ (to glue, to stick) ← Ancient Greek κόλλα (glue) — literally \"the glued one,\" someone inseparably bonded to you",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["colloquial"],
        "grammar": [{"label": "Masculine", "value": "ο κολλητός"}, {"label": "Feminine", "value": "η κολλητή"}, {"label": "Root", "value": "κολλώ = to glue, to stick"}],
        "example": {"gr": "Αυτός είναι ο κολλητός μου από το δημοτικό.", "en": "He's been my best friend since primary school."},
        "conjugation": None,
    },
    {
        "id": 13,
        "greek": "ψήνομαι",
        "translation": "to warm to an idea / to be persuaded / to be tempted",
        "type": "Ρήμα · Verb",
        "pronunciation": "PSI-no-me",
        "definition": "To gradually be convinced or drawn toward something — being worked on until you come around",
        "note": "Literally \"I'm being grilled.\" Σε ψήνω = I'm working on you / trying to convince you. Also literal: ψήνομαι στον ήλιο = I'm roasting in the sun. The grilling metaphor works perfectly for both.",
        "etymology": "ψήνω (to grill, to roast) ← Ancient Greek ὀπτάω — the passive image of being heated up until you're ready",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["colloquial", "figurative"],
        "grammar": [{"label": "Aorist", "value": "ψήθηκα (I came around / was convinced)"}, {"label": "Also literal", "value": "ψήνομαι = I'm roasting (heat)"}],
        "example": {"gr": "Αρχίζω να ψήνομαι για εκείνο το ταξίδι.", "en": "I'm starting to warm to the idea of that trip."},
        "conjugation": None,
    },
    {
        "id": 14,
        "greek": "έχω πλάκα",
        "translation": "to be funny / to be a laugh / to be fun",
        "type": "Φράση · Fixed Expression",
        "pronunciation": "E-ho PLA-ka",
        "definition": "To be amusing or entertaining — of a person or a situation",
        "note": "Κάνω πλάκα = I'm joking / kidding. Μην κάνεις πλάκες = stop messing about. Τι πλάκα! = how funny! Η πλάκα literally means a flat stone — the semantic journey to \"a laugh\" is via striking/flat-out funny.",
        "etymology": "η πλάκα (flat stone, slab) ← Ancient Greek πλάξ (flat surface) — how it came to mean \"a joke\" is via the idea of something flat-out, strikingly funny",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["colloquial"],
        "grammar": [{"label": "Structure", "value": "έχω πλάκα (I'm funny) · έχει πλάκα (it's funny/fun)"}, {"label": "Related", "value": "άσχημη πλάκα = a bad joke / bad taste"}],
        "example": {"gr": "Έχει πλάκα αυτός ο τύπος.", "en": "That guy is really funny."},
        "conjugation": None,
    },
    {
        "id": 15,
        "greek": "αχλύς",
        "translation": "haze / mist / the veil before the eyes",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "ah-HLIS",
        "definition": "The dimness or mist that falls over the eyes — in tears, in a swoon, or at death; a poetic word for obscuring vagueness",
        "note": "Homer uses αχλύς for the veil that falls over a dying hero's eyes. Almost never used in everyday speech but instantly beautiful in literary contexts. One for the advanced register.",
        "etymology": "Ancient Greek ἀχλύς (mist, darkness) — of uncertain pre-Greek origin; possibly related to ἄχνη (foam, spray)",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": False,
        "tags": ["formal"],
        "grammar": [{"label": "Article", "value": "η αχλύς"}, {"label": "Gender", "value": "Feminine"}, {"label": "Genitive", "value": "της αχλύος (archaic declension)"}],
        "example": {"gr": "Μια αχλύς σκέπασε τα μάτια του.", "en": "A haze covered his eyes."},
        "conjugation": None,
    },
    {
        "id": 16,
        "greek": "δειλινό",
        "translation": "late afternoon / the golden hour before dusk",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "thei-li-NO",
        "definition": "The specific quality of late afternoon light — warm, slanting, before the sun sets; not just a time but a mood",
        "note": "One of the most beautiful time-words in Greek. Appears constantly in folk song and poetry. Not the same as απόγευμα (afternoon, neutral/practical) — δειλινό is the golden, melancholic hour.",
        "etymology": "Ancient Greek δείλη (afternoon, the declining part of the day) ← δείλω (to set, to decline) — the hour when the sun begins its descent",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["formal", "figurative"],
        "grammar": [{"label": "Article", "value": "το δειλινό"}, {"label": "Gender", "value": "Neuter"}, {"label": "Genitive", "value": "του δειλινού"}],
        "example": {"gr": "Καθίσαμε στη βεράντα το δειλινό.", "en": "We sat on the veranda in the late afternoon light."},
        "conjugation": None,
    },
    {
        "id": 17,
        "greek": "ερημιά",
        "translation": "solitude / desolation / emptiness",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "e-re-MIA",
        "definition": "The emptiness of a deserted landscape or a lonely heart — richer and more poetic than μοναξιά (loneliness)",
        "note": "Η ερημιά της νύχτας = the emptiness of the night. Can be beautiful (the solitude of a mountain) or devastating (the desolation of loss). More textured than simple loneliness.",
        "etymology": "έρημος (deserted, empty) ← Ancient Greek ἔρημος (desolate, uninhabited) ← PIE *h₁erH- (to be empty, to leave) — same root as English \"err\" (to wander away)",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": False,
        "tags": ["formal", "figurative"],
        "grammar": [{"label": "Article", "value": "η ερημιά"}, {"label": "Gender", "value": "Feminine"}, {"label": "Genitive", "value": "της ερημιάς"}, {"label": "Related", "value": "η έρημος = desert · ο έρημος = lonely/desolate (adj.)"}],
        "example": {"gr": "Μέσα στην ερημιά του έρωτα, ψάχνει κάποιον να τον καταλάβει.", "en": "In the desolation of love, he searches for someone to understand him."},
        "conjugation": None,
    },
    {
        "id": 18,
        "greek": "πελαγώνω",
        "translation": "to be lost at sea / to be overwhelmed / to not know where to turn",
        "type": "Ρήμα · Verb",
        "pronunciation": "pe-la-GO-no",
        "definition": "To find yourself out of your depth, directionless, overwhelmed — as if adrift in the open sea with no landmarks",
        "note": "Πελάγωσα is the aorist — \"I got lost at sea\" — and one of those words that makes Greeks nod with recognition when a foreigner uses it correctly.",
        "etymology": "πέλαγος (the open sea, the deep) ← Ancient Greek πέλαγος ← PIE *pleh₂- (flat, open water) — to be out in the open sea with no reference point",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["figurative", "colloquial"],
        "grammar": [{"label": "Aorist", "value": "πελάγωσα"}, {"label": "Base noun", "value": "το πέλαγος = the open sea"}],
        "example": {"gr": "Πελάγωσα με τόσες επιλογές.", "en": "I was completely overwhelmed by so many options."},
        "conjugation": None,
    },
    {
        "id": 19,
        "greek": "γαλήνη",
        "translation": "calm / serenity / tranquillity",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "ga-LI-ni",
        "definition": "The particular calm that follows turbulence — especially the stillness of the sea after a storm",
        "note": "Carries that specific quality of peace that comes after tension. Γαλήνιο πρόσωπο = a serene face. One of those words that sounds exactly like what it means.",
        "etymology": "Ancient Greek γαλήνη (calm sea, stillness) — possibly related to γάλα (milk) via the image of a smooth, white, untroubled surface",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["formal", "figurative"],
        "grammar": [{"label": "Article", "value": "η γαλήνη"}, {"label": "Gender", "value": "Feminine"}, {"label": "Genitive", "value": "της γαλήνης"}, {"label": "Related adj.", "value": "γαλήνιος = calm, serene, tranquil"}],
        "example": {"gr": "Μετά την καταιγίδα, επικράτησε απόλυτη γαλήνη.", "en": "After the storm, absolute calm prevailed."},
        "conjugation": None,
    },
    {
        "id": 20,
        "greek": "λυγμός",
        "translation": "a sob / a choking cry",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "lig-MOS",
        "definition": "The involuntary choking sound of a body overwhelmed by grief — more physical and specific than κλάμα (crying)",
        "note": "The root λυγίζω (to bend, to buckle) gives it away: a sob is what happens when grief bends you. More dramatic and specific than κλάμα.",
        "etymology": "λυγίζω (to bend, to buckle, to give way) ← Ancient Greek λύγος (a plant supple enough to bend) — the physical giving-way of the body under emotional weight",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": False,
        "tags": ["formal"],
        "grammar": [{"label": "Article", "value": "ο λυγμός"}, {"label": "Gender", "value": "Masculine"}, {"label": "Plural", "value": "οι λυγμοί"}, {"label": "Genitive", "value": "του λυγμού"}, {"label": "Related verb", "value": "λυγίζω = to bend, to buckle (under emotion)"}],
        "example": {"gr": "Ακούστηκαν λυγμοί από το διπλανό δωμάτιο.", "en": "Sobs could be heard from the next room."},
        "conjugation": None,
    },
    {
        "id": 21,
        "greek": "στραβοπατώ",
        "translation": "to take a wrong step / to go wrong in life / to make a misstep",
        "type": "Ρήμα · Verb",
        "pronunciation": "stra-vo-pa-TO",
        "definition": "To step wrongly — literally to stumble, figuratively to make a wrong turn in life or a bad decision",
        "note": "The compound is perfectly transparent once you know the parts. Στραβοπάτησα = I put my foot wrong / I made a misstep.",
        "etymology": "στραβός (crooked, skewed, off) + πατώ (to step, to tread) ← Ancient Greek πατέω — a crooked step; στραβός possibly from στρέφω (to twist)",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["figurative", "colloquial"],
        "grammar": [{"label": "Aorist", "value": "στραβοπάτησα"}, {"label": "Components", "value": "στραβός (crooked) + πατώ (to step)"}],
        "example": {"gr": "Στραβοπάτησε νωρίς στη ζωή του, αλλά τα κατάφερε.", "en": "He went wrong early in life but managed to turn it around."},
        "conjugation": None,
    },
    {
        "id": 22,
        "greek": "καρδιοχτύπι",
        "translation": "heartbeat / flutter of the heart / palpitation",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "kar-thio-HTIP-i",
        "definition": "The sensation of the heart beating with excitement, fear, or anticipation — a flutter rather than a steady beat",
        "note": "Μου 'ρθε καρδιοχτύπι = my heart skipped a beat. One of those Greek compounds that does in one word what English needs a sentence to express.",
        "etymology": "καρδιά (heart) ← Ancient Greek καρδία + χτυπώ (to beat, to strike) ← Ancient Greek κτυπέω — the heart striking against the chest",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["figurative"],
        "grammar": [{"label": "Article", "value": "το καρδιοχτύπι"}, {"label": "Gender", "value": "Neuter"}, {"label": "Plural", "value": "τα καρδιοχτύπια"}, {"label": "Components", "value": "καρδιά (heart) + χτυπώ (to beat)"}],
        "example": {"gr": "Το καρδιοχτύπι της δυνάμωνε καθώς τον έβλεπε να πλησιάζει.", "en": "Her heartbeat quickened as she watched him approach."},
        "conjugation": None,
    },
    {
        "id": 23,
        "greek": "φεγγαρόλουστος",
        "translation": "bathed in moonlight / moon-drenched",
        "type": "Επίθετο · Adjective",
        "pronunciation": "feg-ga-RO-lus-tos",
        "definition": "Drenched or flooded with moonlight — what English requires five words to say",
        "note": "Purely poetic — you won't hear it in everyday speech but it will stop a native speaker in their tracks. A showpiece word.",
        "etymology": "φεγγάρι (moon) ← φέγγος (light, radiance) + λούζω (to bathe, to drench) ← Ancient Greek λούω — to be bathed in the moon's light",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": False,
        "tags": ["formal"],
        "grammar": [{"label": "Masculine", "value": "φεγγαρόλουστος"}, {"label": "Feminine", "value": "φεγγαρόλουστη"}, {"label": "Neuter", "value": "φεγγαρόλουστο"}, {"label": "Components", "value": "φεγγάρι (moon) + λούζομαι (to be bathed/drenched)"}, {"label": "Plural", "value": "φεγγαρόλουστοι / φεγγαρόλουστες / φεγγαρόλουστα"}],
        "example": {"gr": "Η παραλία ήταν φεγγαρόλουστη εκείνη τη νύχτα.", "en": "The beach was bathed in moonlight that night."},
        "conjugation": None,
    },
    {
        "id": 24,
        "greek": "μελαγχολία",
        "translation": "melancholy / beautiful sadness",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "me-lag-ho-LI-a",
        "definition": "A pensive, bittersweet sadness — not depression but the aesthetic melancholy of autumn, music, and the bittersweet",
        "note": "Greek gave this word to the world. Ancient medicine blamed it on black bile (μέλας χολή). Greek μελαγχολία has a particular beauty — it is the sadness you almost enjoy.",
        "etymology": "μέλας (black) + χολή (bile) — in ancient medicine, the humour responsible for a pensive, sad temperament; Greek gave this word to all European languages",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["formal", "figurative"],
        "grammar": [{"label": "Article", "value": "η μελαγχολία"}, {"label": "Gender", "value": "Feminine"}, {"label": "Genitive", "value": "της μελαγχολίας"}],
        "example": {"gr": "Ένα αίσθημα μελαγχολίας τον κυρίεψε το φθινόπωρο.", "en": "A feeling of melancholy took hold of him in autumn."},
        "conjugation": None,
    },
    {
        "id": 25,
        "greek": "αναποδογυρίζω",
        "translation": "to turn upside down / to overturn completely",
        "type": "Ρήμα · Verb",
        "pronunciation": "a-na-po-tho-yi-RI-zo",
        "definition": "To flip something completely — literally or figuratively (a life turned upside down)",
        "note": "The component parts are both already in your vocabulary: ανάποδα (upside down) + γυρίζω (to turn). Makes it very learnable by decomposition.",
        "etymology": "ανάποδα (upside down/backwards) + γυρίζω (to turn) ← γύρος (a turn, a round) — to turn into the backwards/upside-down position",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["figurative", "colloquial"],
        "grammar": [{"label": "Aorist", "value": "αναποδογύρισα"}, {"label": "Components", "value": "ανάποδα (upside down) + γυρίζω (to turn)"}],
        "example": {"gr": "Αναποδογύρισε τη ζωή μου.", "en": "He turned my life completely upside down."},
        "conjugation": None,
    },
    {
        "id": 26,
        "greek": "τριγυρνώ",
        "translation": "to wander / to drift / to roam aimlessly",
        "type": "Ρήμα · Verb",
        "pronunciation": "tri-yi-NO",
        "definition": "To go around and around without direction — more aimless and rhythmic than simply περπατώ (to walk)",
        "note": "The word itself has a wandering quality in its sound. Τριγυρνούσε = he was drifting around. Very evocative for describing aimless urban wandering.",
        "etymology": "τριγύρω (all around, on all sides) + the verb suffix -νώ — to go around in all directions without settling; τριγύρω from τρι- (three/all) + γύρω (around)",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["colloquial", "figurative"],
        "grammar": [{"label": "Aorist", "value": "τριγύρισα"}, {"label": "Related adverb", "value": "τριγύρω = all around, on all sides"}],
        "example": {"gr": "Τριγυρνούσε στους δρόμους χωρίς σκοπό.", "en": "He was wandering the streets aimlessly."},
        "conjugation": None,
    },
    {
        "id": 27,
        "greek": "ξεδιψώ",
        "translation": "to quench one's thirst / to finally satisfy a long craving",
        "type": "Ρήμα · Verb",
        "pronunciation": "kse-thip-SO",
        "definition": "To no longer be thirsty — literally or figuratively, when a long-held craving is finally satisfied",
        "note": "Works for literal thirst and for any long-held desire finally met. Ξεδίψασα επιτέλους = I finally got what I'd been craving.",
        "etymology": "ξε- (out/away, signals release) + δίψα (thirst) ← Ancient Greek δίψα ← PIE *dhwers- (to be dry) — to release oneself from thirst",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["figurative", "colloquial"],
        "grammar": [{"label": "Aorist", "value": "ξεδίψασα"}, {"label": "Components", "value": "ξε- (release prefix) + δίψα (thirst)"}],
        "example": {"gr": "Επιτέλους ξεδίψασα — μήνες ήθελα να δω αυτή την ταινία.", "en": "I finally satisfied that craving — I'd wanted to see that film for months."},
        "conjugation": None,
    },
    {
        "id": 28,
        "greek": "φαφλατάς",
        "translation": "windbag / blowhard / all talk and no action",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "fa-fla-TAS",
        "definition": "Someone who talks a great deal, promises much, and delivers nothing",
        "note": "Wonderfully onomatopoeic — the word itself sounds like bluster and empty noise. The verb φαφλατίζω (to talk hot air) is equally useful.",
        "etymology": "onomatopoeic — the word imitates the sound of empty, blustering talk; the repeated φ and the open vowels enact the hot air being expelled",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["colloquial"],
        "grammar": [{"label": "Masculine", "value": "ο φαφλατάς"}, {"label": "Feminine", "value": "η φαφλατού"}, {"label": "Related verb", "value": "φαφλατίζω = to bluster, to talk hot air"}],
        "example": {"gr": "Μην τον ακούς — είναι φαφλατάς, μιλά πολύ και δεν κάνει τίποτα.", "en": "Don't listen to him — he's all talk and no action."},
        "conjugation": None,
    },
    {
        "id": 29,
        "greek": "κουτσομπόλης",
        "translation": "gossip / busybody / rumour-spreader",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "kut-som-BO-lis",
        "definition": "Someone who collects and spreads gossip and rumours about others",
        "note": "Κουτσομπολεύω (to gossip) and κουτσομπολιό (gossip as a social activity) are both extremely common. Η γειτονιά είναι γεμάτη κουτσομπόληδες = the neighbourhood is full of gossips.",
        "etymology": "κουτσός (lame, limping) + μπόλι (a graft, something that spreads) — something lame that spreads from person to person; or possibly folk etymology; origin not definitively established",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["colloquial"],
        "grammar": [{"label": "Masculine", "value": "ο κουτσομπόλης"}, {"label": "Feminine", "value": "η κουτσομπόλα"}, {"label": "Related verb", "value": "κουτσομπολεύω = to gossip"}, {"label": "Related noun", "value": "το κουτσομπολιό = gossip (the activity)"}],
        "example": {"gr": "Μη λες τίποτα σε αυτόν — είναι κουτσομπόλης.", "en": "Don't tell him anything — he's a gossip."},
        "conjugation": None,
    },
    {
        "id": 30,
        "greek": "κεφάτος",
        "translation": "in high spirits / jolly / radiating good humour",
        "type": "Επίθετο · Adjective",
        "pronunciation": "ke-FA-tos",
        "definition": "Someone who radiates contagious good energy — not just happy but actively lifting the room",
        "note": "The adjective derived from κέφι. Σήκωσε το κέφι = he raised everyone's spirits. Ήρθε κεφάτος = he arrived full of life. A person who is κεφάτος makes the party happen.",
        "etymology": "κέφι (high spirits, see above) + the adjectival suffix -άτος — full of κέφι; the suffix signals being loaded with the quality named",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["colloquial"],
        "grammar": [{"label": "Masculine", "value": "κεφάτος"}, {"label": "Feminine", "value": "κεφάτη"}, {"label": "Neuter", "value": "κεφάτο"}, {"label": "Root", "value": "κέφι (high spirits)"}, {"label": "Plural", "value": "κεφάτοι / κεφάτες / κεφάτα"}],
        "example": {"gr": "Ήρθε κεφάτος στο πάρτι και σήκωσε το κέφι όλων.", "en": "He arrived in high spirits and lifted everyone's mood."},
        "conjugation": None,
    },
    {
        "id": 31,
        "greek": "αλάνης",
        "translation": "street kid / loveable rogue / someone raised on the streets",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "a-LA-nis",
        "definition": "Someone who grew up without much supervision, on the streets — rough around the edges but with their own code",
        "note": "From αλάνα (an empty urban lot, wasteland) — the place where unsupervised kids played. The word carries affection alongside the rough edges. Deeply embedded in urban Greek culture and rebetiko.",
        "etymology": "αλάνα (an empty urban lot, wasteland) — possibly from Albanian or a Balkan contact word; the empty lot as the classroom of street culture",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": False,
        "tags": ["colloquial"],
        "grammar": [{"label": "Masculine", "value": "ο αλάνης"}, {"label": "Feminine", "value": "η αλάνα"}, {"label": "Related", "value": "η αλάνα = a wasteland, an empty urban lot"}],
        "example": {"gr": "Μεγάλωσε αλάνης, αλλά έγινε καλός άνθρωπος.", "en": "He grew up a street kid but became a good person."},
        "conjugation": None,
    },
    {
        "id": 32,
        "greek": "πονηρός",
        "translation": "cunning / crafty / sly / not naive",
        "type": "Επίθετο · Adjective",
        "pronunciation": "po-ni-ROS",
        "definition": "Shrewd and calculating — not necessarily dishonest but definitely not innocent; can be admirable or alarming depending on context",
        "note": "Not the same as κακός (evil). Η πονηριά can be a survival skill or a moral failing. Πονηρό βλέμμα = a knowing, sly look. Context decides whether it's a compliment or a warning.",
        "etymology": "Ancient Greek πονηρός (full of toil, troublesome, knavish) ← πόνος (toil, pain) — originally \"one who causes trouble\" evolved into \"one who is clever enough to be troublesome\"",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["neutral", "figurative"],
        "grammar": [{"label": "Masculine", "value": "πονηρός"}, {"label": "Feminine", "value": "πονηρή"}, {"label": "Neuter", "value": "πονηρό"}, {"label": "Related noun", "value": "η πονηριά = cunning, craftiness"}, {"label": "Plural", "value": "πονηροί / πονηρές / πονηρά"}],
        "example": {"gr": "Είναι πονηρός — πάντα ξέρει πώς να βγαίνει κερδισμένος.", "en": "He's crafty — he always knows how to come out on top."},
        "conjugation": None,
    },
    {
        "id": 33,
        "greek": "ζωηρός",
        "translation": "lively / energetic / vivacious",
        "type": "Επίθετο · Adjective",
        "pronunciation": "zo-i-ROS",
        "definition": "Full of life and energy — of a child, a person, a colour, or a discussion",
        "note": "From ζωή (life). Ζωηρό χρώμα = a vivid/bright colour. Ζωηρή συζήτηση = a lively discussion. The root is transparent and the word family is enormous — ζωή gives ζωολογία, ζωγράφος, and much more.",
        "etymology": "ζωή (life) ← Ancient Greek ζωή ← PIE *gʷih₃wó- (alive) + the -ηρός suffix (full of) — the same root as English \"quick\" (originally meaning alive) and \"zoo\"",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["neutral"],
        "grammar": [{"label": "Masculine", "value": "ζωηρός"}, {"label": "Feminine", "value": "ζωηρή"}, {"label": "Neuter", "value": "ζωηρό"}, {"label": "Root", "value": "ζωή (life)"}, {"label": "Plural", "value": "ζωηροί / ζωηρές / ζωηρά"}],
        "example": {"gr": "Είναι πολύ ζωηρό παιδί — δεν ησυχάζει ποτέ.", "en": "He's a very lively child — he never sits still."},
        "conjugation": None,
    },
    {
        "id": 34,
        "greek": "αψύς",
        "translation": "quick-tempered / fiery / someone who flares up fast but doesn't hold a grudge",
        "type": "Επίθετο · Adjective",
        "pronunciation": "ap-SIS",
        "definition": "Hot-tempered and quick to anger, but the fire burns fast and brief — not a cold or lasting grudge",
        "note": "The key cultural nuance: an αψύς person flares up instantly but usually forgives quickly too. Different from someone cold and calculating. Cross-ref θυμοσιάρης (hot-tempered, more colloquial).",
        "etymology": "α- (intensive prefix) + ψύχω (to cool) ← Ancient Greek ψύχω (to blow, to cool) — literally \"hard to cool down,\" someone whose heat is difficult to dissipate",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": False,
        "tags": ["neutral"],
        "grammar": [{"label": "Masculine", "value": "αψύς"}, {"label": "Feminine", "value": "αψιά"}, {"label": "Neuter", "value": "αψύ"}, {"label": "Related noun", "value": "η αψυθυμία = hot-temperedness"}, {"label": "Plural", "value": "αψείς / αψιές / αψιά"}],
        "example": {"gr": "Είναι αψύς, αλλά ξεχνά γρήγορα.", "en": "He's quick-tempered but quick to forget too."},
        "conjugation": None,
    },
    {
        "id": 35,
        "greek": "σβέλτος",
        "translation": "nimble / quick / light on one's feet",
        "type": "Επίθετο · Adjective",
        "pronunciation": "ZVEL-tos",
        "definition": "Physically nimble and quick — light of foot, quick of hand, or mentally sharp",
        "note": "From Italian svelto. Σβέλτα! as an adverb = quickly! get a move on! One of the Italian/Venetian loanwords that feels completely at home in Greek.",
        "etymology": "Italian svelto (nimble, quick) ← svellere (to uproot, to pluck up) ← Latin ex- + vellere (to pull) — the image of something plucked up lightly and quickly",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": False,
        "tags": ["neutral", "loanword:italian"],
        "grammar": [{"label": "Masculine", "value": "σβέλτος"}, {"label": "Feminine", "value": "σβέλτη"}, {"label": "Neuter", "value": "σβέλτο"}, {"label": "Adverb", "value": "σβέλτα = quickly, nimbly"}, {"label": "Plural", "value": "σβέλτοι / σβέλτες / σβέλτα"}],
        "example": {"gr": "Σβέλτος σαν γάτα, πέρασε ανάμεσα στο πλήθος.", "en": "Nimble as a cat, he slipped through the crowd."},
        "conjugation": None,
    },
    {
        "id": 36,
        "greek": "χαρούμενος",
        "translation": "happy / cheerful / joyful",
        "type": "Επίθετο · Adjective",
        "pronunciation": "ha-RU-me-nos",
        "definition": "Radiating happiness and good cheer — the person wearing joy visibly",
        "note": "From χαρά (joy) — one of the foundational words of Greek emotional vocabulary. Τι χαρά! = what joy! / how wonderful! Cross-ref χαίρομαι (to be glad/enjoy, already in your deck).",
        "etymology": "χαρά (joy) ← Ancient Greek χαρά ← χαίρω (to rejoice) ← PIE *ǵʰeh₁i- (to rejoice) — gives English \"yearn\" via a different branch",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["neutral"],
        "grammar": [{"label": "Masculine", "value": "χαρούμενος"}, {"label": "Feminine", "value": "χαρούμενη"}, {"label": "Neuter", "value": "χαρούμενο"}, {"label": "Root", "value": "η χαρά = joy"}, {"label": "Plural", "value": "χαρούμενοι / χαρούμενες / χαρούμενα"}],
        "example": {"gr": "Σε βλέπω χαρούμενο σήμερα — τι έγινε;", "en": "You look happy today — what happened?"},
        "conjugation": None,
    },
    {
        "id": 37,
        "greek": "στριμώχνομαι",
        "translation": "to be squashed in / to be crammed into a tight space / to be cornered",
        "type": "Ρήμα · Verb",
        "pronunciation": "stri-MOH-no-me",
        "definition": "To be pressed in on all sides — in a crowded vehicle, a packed room, or a tight corner; also figuratively to be put in a difficult position",
        "note": "The sound of the word is satisfyingly compressed. Στριμώχτηκα σε μια γωνιά = I got cornered. Στριμωχτήκαμε όλοι μέσα = we all crammed in.",
        "etymology": "possibly related to στρίβω (to twist, to squeeze) and στριφογυρίζω (to spin tight) — the image of being twisted into a small space",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["colloquial", "figurative"],
        "grammar": [{"label": "Active", "value": "στριμώχνω = to squeeze/cram someone in"}, {"label": "Aorist passive", "value": "στριμώχτηκα = I got squashed in"}],
        "example": {"gr": "Στριμωχτήκαμε όλοι στο μικρό αμάξι.", "en": "We all crammed into the tiny car."},
        "conjugation": None,
    },
    {
        "id": 38,
        "greek": "καλοτυχία",
        "translation": "good fortune / good luck / a warm wish for someone's future",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "ka-lo-ti-HI-a",
        "definition": "Good fortune — a warmer and more heartfelt wish than just καλή τύχη (good luck)",
        "note": "The compound καλο- + τύχη brings together goodness and fate in a single word. A nice thing to say at a departure or new beginning.",
        "etymology": "καλός (good) + τύχη (luck, fate) ← Ancient Greek τύχη ← τυγχάνω (to happen, to chance upon) — literally \"good fate,\" the allotment of good things",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["neutral"],
        "grammar": [{"label": "Article", "value": "η καλοτυχία"}, {"label": "Gender", "value": "Feminine"}, {"label": "Related adj.", "value": "καλότυχος = lucky, fortunate"}],
        "example": {"gr": "Σου εύχομαι καλοτυχία στο νέο σου ξεκίνημα.", "en": "I wish you good fortune in your new beginning."},
        "conjugation": None,
    },
    {
        "id": 39,
        "greek": "σιωπή",
        "translation": "silence",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "si-o-PI",
        "definition": "Silence — but with weight and presence; a meaningful quiet rather than mere absence of noise",
        "note": "Η σιωπή είναι χρυσός = silence is golden. Σιωπηρή συμφωνία = a tacit agreement. Σιώπα! = be silent! (more commanding than ησύχασε). The verb σιωπώ is equally beautiful.",
        "etymology": "Ancient Greek σιωπή (silence, stillness) ← σιγή (silence) — possibly related to σιγανός (quiet, gentle); the deeper PIE root is uncertain",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["formal", "figurative"],
        "grammar": [{"label": "Article", "value": "η σιωπή"}, {"label": "Gender", "value": "Feminine"}, {"label": "Genitive", "value": "της σιωπής"}, {"label": "Related verb", "value": "σιωπώ = to be silent"}, {"label": "Related adj.", "value": "σιωπηλός = silent, quiet (of a person)"}],
        "example": {"gr": "Βασίλεψε απόλυτη σιωπή στο δωμάτιο.", "en": "Absolute silence reigned in the room."},
        "conjugation": None,
    },
    {
        "id": 40,
        "greek": "αυγή",
        "translation": "dawn / daybreak",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "av-YI",
        "definition": "Dawn — the first light of day; more elevated and poetic than the colloquial χαράματα",
        "note": "Also a common woman's name. More poetic than χαράματα (the colloquial word for dawn). Related to αυγό (egg) via the pale golden colour of both. The word glows with the light it describes.",
        "etymology": "Ancient Greek αὐγή (brightness, radiance, dawn light) ← PIE *h₂ewg- (to shine, to increase) — same root as Latin aurora and English \"augment\" (growing light)",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["formal"],
        "grammar": [{"label": "Article", "value": "η αυγή"}, {"label": "Gender", "value": "Feminine"}, {"label": "Genitive", "value": "της αυγής"}, {"label": "cf.", "value": "τα χαράματα = dawn (colloquial) · η αυγή = dawn (poetic/literary)"}],
        "example": {"gr": "Ξύπνησε με την αυγή και βγήκε στη θάλασσα.", "en": "She woke at dawn and went to the sea."},
        "conjugation": None,
    },
    {
        "id": 41,
        "greek": "αστραπή",
        "translation": "lightning / lightning bolt / anything blindingly fast",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "as-tra-PI",
        "definition": "A lightning bolt — literal or figurative for anything of blinding speed or brilliance",
        "note": "Σαν αστραπή (like lightning) is an extremely common simile for speed. Αστραπιαίος = instantaneous. In mythology the companion of βροντή (thunder) — Zeus hurled both.",
        "etymology": "αστράπτω (to flash, to gleam) ← αστήρ/αστέρι (star) ← PIE *h₂stér- (star) — lightning as a star-flash; same root as αστέρι (star) and \"astronomy\"",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["neutral", "figurative"],
        "grammar": [{"label": "Article", "value": "η αστραπή"}, {"label": "Gender", "value": "Feminine"}, {"label": "Plural", "value": "οι αστραπές"}, {"label": "Related", "value": "αστράφτω = to flash/gleam · αστραπιαίος = lightning-fast"}],
        "example": {"gr": "Πέρασε σαν αστραπή.", "en": "He passed like lightning."},
        "conjugation": None,
    },
    {
        "id": 42,
        "greek": "ανάσα",
        "translation": "breath / a moment's relief / breathing room",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "A-na-sa",
        "definition": "Literally a breath; figuratively a moment of relief, breathing room, or something that takes your breath away",
        "note": "Μου πήρε την ανάσα = it took my breath away. Δεν έχω ανάσα = I'm swamped / I have no breathing room. Δώσε μου μια ανάσα = give me a breather. Cross-ref αναπνέω (already in your deck).",
        "etymology": "ανα- (up, again) + πνοή (breath) ← Ancient Greek πνέω (to breathe, to blow) — a breath taken upward; same root as αναπνέω",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["neutral", "figurative"],
        "grammar": [{"label": "Article", "value": "η ανάσα"}, {"label": "Gender", "value": "Feminine"}, {"label": "Plural", "value": "οι ανάσες"}, {"label": "Key phrases", "value": "μου πήρε την ανάσα = it took my breath away · δεν έχω ανάσα = I have no breathing room"}],
        "example": {"gr": "Επιτέλους λίγη ανάσα από τη δουλειά.", "en": "Finally a moment's relief from work."},
        "conjugation": None,
    },
    {
        "id": 43,
        "greek": "γαμώτο",
        "translation": "damn it / bloody hell",
        "type": "Επιφώνημα · Expletive",
        "pronunciation": "ga-MO-to",
        "definition": "The all-purpose Greek expletive — frustration, surprise, pain, or even admiration depending on tone and context",
        "note": "Unlike English equivalents, works across a wide emotional range: pain, frustration, surprise, even admiration (γαμώτο, τι ωραίο! = damn, that's beautiful!). Tone does everything.",
        "etymology": "from γαμώ (a strong verb) — the -τo ending is a diminutive/expressive suffix that softens it slightly; entered everyday speech from working-class urban slang",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["colloquial"],
        "grammar": [{"label": "Register", "value": "Strong expletive — use with awareness of context"}, {"label": "Variants", "value": "γαμώτο μου (emphatic) · μα το γαμώτο (for crying out loud)"}],
        "example": {"gr": "Γαμώτο, ξέχασα το κλειδί μου!", "en": "Damn it, I forgot my key!"},
        "conjugation": None,
    },
    {
        "id": 44,
        "greek": "μαλακία",
        "translation": "nonsense / a stupid act / rubbish (expletive)",
        "type": "Ουσιαστικό · Noun",
        "pronunciation": "ma-la-KI-a",
        "definition": "A stupid remark, a pointless act, or general nonsense — technically vulgar but ubiquitous in informal speech",
        "note": "So embedded in everyday informal Greek that pretending it doesn't exist would be dishonest. Between close friends μαλάκα can even be affectionate. Understand before producing — safer until you know your audience well.",
        "etymology": "from μαλακός (soft, weak) ← Ancient Greek μαλακός ← PIE *ml̥h₂kó- (soft) — the noun evolved via medical and colloquial semantic drift into its current meaning",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["colloquial"],
        "grammar": [{"label": "Article", "value": "η μαλακία"}, {"label": "Gender", "value": "Feminine"}, {"label": "Plural", "value": "οι μαλακίες"}, {"label": "Register", "value": "Vulgar but extremely common in informal speech"}],
        "example": {"gr": "Μη λες μαλακίες — ξέρεις πολύ καλά τι έγινε.", "en": "Don't talk rubbish — you know perfectly well what happened."},
        "conjugation": None,
    },
    {
        "id": 45,
        "greek": "ξεκάνω",
        "translation": "to finish off / to destroy / to exhaust completely",
        "type": "Ρήμα · Verb",
        "pronunciation": "kse-KA-no",
        "definition": "To do something completely out of existence — to destroy, to exhaust utterly, or to finish decisively",
        "note": "Με ξεκάνεις! can be exasperation (you're killing me!) or admiration (you're incredible!). Ξεκάνομαι = to wear yourself out completely. The ξε- prefix signals total, irreversible completion.",
        "etymology": "ξε- (out/away — signals complete depletion) + κάνω (to do/make) ← Ancient Greek κάνω — to do something so thoroughly it no longer exists",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["colloquial", "figurative"],
        "grammar": [{"label": "Aorist", "value": "ξεκανόνισα / ξεκάνεψα"}, {"label": "Passive", "value": "ξεκάνομαι = to be exhausted / to wear oneself out"}],
        "example": {"gr": "Με ξεκάνει αυτή η δουλειά.", "en": "This job is finishing me off."},
        "conjugation": None,
    },
    {
        "id": 46,
        "greek": "σιγανός",
        "translation": "quiet / gentle / slow / softly melancholic",
        "type": "Επίθετο · Adjective",
        "pronunciation": "si-ga-NOS",
        "definition": "Soft and quiet — of rain, a song, a person's manner; carries a gentle melancholy in Greek folk usage",
        "note": "More sensory and atmospheric than simply ήσυχος (quiet). Σιγά σιγά (slowly slowly) is one of the most Greek phrases there is. A σιγανό τραγούδι is a soft, melancholy song.",
        "etymology": "σιγή (silence, stillness) ← Ancient Greek σιγή — possibly from a pre-Greek or onomatopoeic root; the -ανός suffix creates the adjective \"of the quality of silence\"",
        "scene_id": "curated",
        "scene_label": "🧿 Curated",
        "priority": True,
        "tags": ["formal", "figurative"],
        "grammar": [{"label": "Masculine", "value": "σιγανός"}, {"label": "Feminine", "value": "σιγανή"}, {"label": "Neuter", "value": "σιγανό"}, {"label": "Related adverb", "value": "σιγά = slowly / quietly · σιγά σιγά = little by little"}, {"label": "Plural", "value": "σιγανοί / σιγανές / σιγανά"}],
        "example": {"gr": "Έπεφτε σιγανή βροχή και ο κόσμος ησύχαζε.", "en": "A gentle rain was falling and the world was quietening."},
        "conjugation": None,
    },
]

try:
    from el_de_vocab_data import CARDS as _DE_CARDS
    CARDS = CARDS + _DE_CARDS
except ImportError:
    pass

CARDS_BY_ID: dict = {c['id']: c for c in CARDS}
ACCEPTED_ALTS: dict = {}
